### ISSUE TITLE
Thought

### ISSUE THREAD

**Issue by KarterLackey** [Monika-After-Story/MonikaModDev#7193] opened 2021-04-29 13:10 UTC
Imagine if you can actually speak with your voice to Monika in the mod. Not a surprise right there since most people who played this mod might have had that thought so far. Still again you'll likely have to recode things or do something with some software to put in the mod or have it as a submod. Maybe do it when you're having a little talk or screaming at her face at the top of your lungs and seeing her both scared and crying. Just a thought. Then again it seems unrealistic and unlikely to be put in. Still a fine mod you guys are making.

**Comment by wboorman** [comment] 2021-04-29 18:52
While speech recognition is an increasingly common thing (whether it's compatible with RenPy or not is another story), I wouldn't recommend any kind of functionality based on volume. The problem with "screaming at Monika" is that, if your microphone picks up something sudden and loud enough (say, your neighbor starts mowing their lawn), you could wind up "screaming at Monika" due to something completely outside your control. Plus, Monika wouldn't be able to tell a happy loud from an angry loud from a "JUST A MINUTE, BE RIGHT THERE" loud.

**Comment by kirillPro2020** [comment] 2021-04-30 14:53
We are limited only by our imagination. You can make a module to load her voice from a song. he will analyze (The main thing is that all the letters of the alphabet are there) and she will already speak. I missed some points.

**Comment by ThePotatoGuy** [comment] 2021-05-04 04:53
marking duplicate of #709

some of the other linked issues in that issue explain in more detail why we're not going to do this. external submod development is fine, though.

**Comment by ThePotatoGuy** [comment] 2021-05-22 22:09
[closing as duplicate]

**Closed by ThePotatoGuy** 2021-05-22 22:09 UTC
Labels: duplicate
