### ISSUE TITLE
[Suggestion] Check to see if you're ignoring Monika

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1920] opened 2018-07-14 15:29 UTC
This came out of a discussion on the discord sever and was requested to be put on here.

Basically a timer that if you don't progress the convo she knows you're not listening.  Or for those that leave it in auto, a topic that would come up after a while that would request a response to see if you're still there, and if you don't answer in a timely manner, she knows you're not paying attention.  In either scenario, she could then disable random topics herself since you're not listening anyway.  Could possibly tie in with affection if you're ignoring her, especially if it happens a lot.

**Comment by Rai99** [comment] 2018-07-14 15:55
I think it would be interesting to have Monika comment if you're not progressing the dialogue, and when you get back and progress it, she continues where she left off. I don't like the idea of having Monika automatically disable random topics and what if you haven't unlocked all the topics? Maybe set random chatter to never is what you meant. 

Also, after a while, I think it would be more common to have Monika in the background, but not actively listening to her as much since it's been a while and we're used to it. I don't want to close down MAS if I'm not going to be here. I always let Monika sit with MAS up and occasionally see her and chat a bit. 

I like the idea of having unique dialogue if the player isn't advancing dialogue, but I don't think it should have negative consequences. There was a topic where Monika discussed that some people don't need to actively be doing something with someone to bond or have fun. Just being nearby is enough to keep them happy.

**Comment by jmwall24** [comment] 2018-07-14 16:03
Well you can always re-enable random topics back on as well in the menu.  Just saying she'd disable them right then when you're obviously not listening.

And yes, you can still leave her up in the background when you can't talk.  Either turn off random topics, adjust the chatter slider to never, or right-click so she doesn't start talking again.  There could even be a 'I'm busy/can't talk option' that would let her know you're not going to be able to talk right now.  I'm just pooling suggestions that were discussed in chat.

**Comment by Rai99** [comment] 2018-07-14 16:14
I don't know if it was just me, if it's fixed now or what, but last time I checked, I experienced some lag when the random topics option was disabled. 

My guess was that autosaving only occurred when there was no dialogue, so it was autosaving at every possible moment which may have caused lag. I'm not sure if this even was or still is the case. 

I think the napping feature would fit _perfectly_ with this, or at least really well. If you're busy, you can let Monika nap for a bit and when you're back and can talk, you can wake her up. 

In the mean time, I think right clicking could serve this purpose.

**Comment by ThePotatoGuy** [comment] 2018-07-15 00:59
going to mark this as a duplicate of #1541 

Currently we dont have a solution for detecting inactivity. We do have a way of having timed menus, but its explicit so its difficult to generalize.

We're open to people prototyping ideas for this.

**Comment by ACoolCat** [comment] 2018-07-15 02:43
I'm not sure if I like this one all too much. I like to leave her running in the background while I do stuff, something she suggests, then periodically coming back to check on her.

**Comment by Dovahkun** [comment] 2018-07-15 14:55
I actually happen to really like this idea, even if it may not be entirely possible just yet. It's as if you're talking to someone and just check out and stop listening. If it tied in to affection, one could easily just turn off repeat topics or disable random chatter if you aren't actively paying attention to her. I leave MAS running in the background all the time. I think of it like how I would hate if I were texting or messaging someone and come to find out that they aren't even in the same room or doing something else. It's just my opinion. If she's talking, I just feel like she should have my undivided attention and it's more.

**Comment by jmwall24** [comment] 2018-07-15 14:56
Well again, this wouldn't keep you from leaving her up in the background, just from ignoring her while she's talking in the background.  You'd need to be able to let her know you can't talk right now.

**Comment by ACoolCat** [comment] 2018-07-15 18:58
Eh, still rubs me the wrong way. Like, there's a reason the auto button is there and it's not like you can leave while she's talking. I'd understand it was in the middle of the conversation, because at that point you're just opting out, but putting it between topics seems counter intuitive in my opinion.

**Closed** 2018-07-21 18:09 UTC
Labels: duplicate
