### ISSUE TITLE
Broken addon?

### ISSUE THREAD

**Issue by M4R10zM0113R** [Monika-After-Story/MonikaModDev#1325] opened 2018-03-26 05:21 UTC
EDIT: Related to the Chess addon, which crashes because of the way it behaves in the display manager.
(relevant link: https://bbs.archlinux.org/viewtopic.php?id=171095 )

It's a little misleading, but...

I manually updated to 0.7.3

The issue here is that the game prompted me to update to the same recent version, which then brought this up after that:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chess.rpy", line 104, in script
  File "game/chess.rpy", line 173, in <module>
  File "game/chess.rpy", line 134, in is_platform_good_for_chess
IOError: [Errno 10] No child processes

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/steam/Games/DDLC/Monika_After_Story/renpy/bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "/home/steam/Games/DDLC/Monika_After_Story/renpy/main.py", line 419, in main
    game.context().run(node)
  File "game/chess.rpy", line 104, in script
  File "/home/steam/Games/DDLC/Monika_After_Story/renpy/ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/steam/Games/DDLC/Monika_After_Story/renpy/python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 173, in <module>
  File "game/chess.rpy", line 134, in is_platform_good_for_chess
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/platform.py", line 1310, in system
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/platform.py", line 1277, in uname
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/platform.py", line 1012, in _syscmd_uname
IOError: [Errno 10] No child processes
```

System Information:
* OS: Gentoo
Full disclosure: (using Steam's hardware information)
https://paste.pound-python.org/show/wn4py0n1dJRBVjCMoONR/

EDIT:
* Seems reinstalling still brings up the same error
* Original game runs fine in the setup

**Comment by aldoram5** [comment] 2018-03-26 07:14
This issue is caused by `platform.system()` which seems to be crashing for some reason.
Since the relevant link posted by @M4R10zM0113R seems to provide a workaround and we really can't do anything here (`platform.system()` shouldn't crash) I'm closing this.

**Closed by aldoram5** 2018-03-26 07:14 UTC
