### ISSUE TITLE
[Suggestion] Let the Updater run in the background.

### ISSUE THREAD

**Issue by NotShige** [Monika-After-Story/MonikaModDev#595] opened 2017-12-26 02:22 UTC
I was thinking about just letting the Updater run in the background, and when it finds an update the game will prompt the player if he/she wants to update or not. It's getting annoying that I have to click "Cancel" everytime the game launches.

**Comment by therationalpi** [comment] 2017-12-27 15:44
I'll have to think about how this could be implemented. The issue is the engine implements update checks by handing control transferred over to a screen, and then redrawing the screen when an update is found. It might be possible to do this with an invisible screen, but I'll need to do some testing with that, since it's possible that redrawing the screen gets skipped for screens that don't have any currently visible displayables.

**Comment by ThePotatoGuy** [comment] 2018-04-20 13:53
We could probably have the update check run via a separate thread and have the main loop check for a response from the thread and display a banner of some sort. This would be way neater than the current setup.

Since the new update screen uses threading already, this shouldnt be an issue to incorporate.

**Closed** 2018-04-21 06:02 UTC
Labels: suggestion
