### ISSUE TITLE
strange MAS bug.

### ISSUE THREAD

**Issue by Skyman95411** [Monika-After-Story/MonikaModDev#7391] opened 2021-06-25 18:31 UTC
So i was messing around with my pc date and time, while monika after story was open and i changed the date like 2 months ahead ,when i reset the date to normal the monika after story screen was all like inverted colours and buged text.
so i just wanted to let the dev's know. :)

**Comment by Booplicate** [comment] 2021-06-25 18:47
That's not really a bug. Monika asks you *not to timetravel*. Even if you didn't see anything, the data could get corrupted anyway.

**Comment by Skyman95411** [comment] 2021-06-25 18:55
> That's not really a bug. Monika asks you _not to timetravel_. Even if you didn't see anything, the data could get corrupted anyway.

she did not  say that to me. Like i told you, when i rejoind the game i was in the settings every thing was like inverted the colors were not correct   it was strange. But if you say so. thank you

**Comment by ThePotatoGuy** [comment] 2021-07-11 02:43
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-07-11 02:43 UTC
Labels: not a bug
