### ISSUE TITLE
[Suggestion] - Undertale Window Alert

### ISSUE THREAD

**Issue by KidIqbal** [Monika-After-Story/MonikaModDev#7613] opened 2021-08-07 19:30 UTC
Monika tends to react to certain applications when they open (YouTube, Twitter, Minecraft, Rule3-I mean Reddit). She's stated in the past how the best games for us to enjoy together would be open-world adventure games; Undertale perfectly fitting within this category. Would be neat for her to have something to say regarding it.

**Comment by fromulus** [comment] 2021-08-07 20:14
_Undertale is a RPG with Action/Bullet-Hell elements incorporated to the combat system and fairly linear exploration of it's overworld, in no way is it an adventure game and especially not an open-world, what are you talking about_

Generally speaking, we avoid having Monika talking about specific games just for the sake of having her talk about a specific game.

She's not very big into games, and unless she has a good reason to bring it up (like how she mentions Monopoly in the boardgames history topic, not just for the sake of bringing up Monopoly, but because she uses it as a way to illustrate her point about games being used as a way to convey messages and ideas), it really doesn't make sense for her to just randomly start talking about games, nor do we want to make topics/reactions/others about specific games if there isn't a really good reason that's pertinent to Monika's character behind it.

And before you ask, no, Undertale "breaking the fourth wall" (it never actually does break the fourth wall, everything that happens in the game has an in-universe explanation) isn't good enough of a reason to bring it up in MAS.

**Comment by AxelX0** [comment] 2021-08-07 21:29
Monika is in literature and books,this may risk her personality and character
But I admit it's not a bad idea


> And before you ask, no, Undertale "breaking the fourth wall" (it never actually does break the fourth wall, everything that happens in the game has an in-universe explanation) isn't good enough of a reason to bring it up in MAS.

I know this has nothing to do with the topic,but doesnt Flowey and Chara know they're inside a game?

**Comment by fromulus** [comment] 2021-08-07 22:05
They don't.
While the game tries to keep up the illusion of the fourth wall being broken (in Flowey and Chara's case, to make them more creepy), everything is always explained as an in-universe power (resetting, saving, loading, all of that is stuff that Frisk knows how to do) and doesn't actually adresses the player, but their self-insert (Frisk).

When Flowey talks to "you", they're actually talking to Frisk who essentially stole their power.
When Chara makes their appearance, they mention how what "you" have been feeling every time "you" levelled up was caused by them.

We don't know what that feeling Chara is referring to exactly feels like, because it's Frisk who felt it, not us.

Compare to that with DDLC which actually breaks the fourth wall, by implying the Player into the story and giving them a very different role from the one the Main Character is supposed to play, despite being our self-insert.

**Comment by AxelX0** [comment] 2021-08-07 22:11
> They don't.
> While the game tries to keep up the illusion of the fourth wall being broken (in Flowey and Chara's case, to make them more creepy), everything is always explained as an in-universe power (resetting, saving, loading, all of that is stuff that Frisk knows how to do) and doesn't actually adresses the player, but their self-insert (Frisk).
> 
> When Flowey talks to "you", they're actually talking to Frisk who essentially stole their power.
> When Chara makes their appearance, they mention how what "you" have been feeling every time "you" levelled up was caused by them.
> 
> We don't know what that feeling Chara is referring to exactly feels like, because it's Frisk who felt it, not us.
> 
> Compare to that with DDLC which actually breaks the fourth wall, by implying the Player into the story and giving them a very different role from the one the Main Character is supposed to play, despite being our self-insert.

I remembered a video about someone who gave theories seperating Frisk from the player,it really made sense,at least for me
That's why I asked
But at least DDLC does an obvious separation between the player and the MC,giving each their role,unlike undertale
Anyway,thank you for sharing your opinion about it

**Comment by xXMidnight** [comment] 2021-08-10 10:30
whee

**Comment by ThePotatoGuy** [comment] 2021-08-28 20:10
[closing until we look into it]

**Closed by ThePotatoGuy** 2021-08-28 20:10 UTC
Labels: suggestion
