### ISSUE TITLE
another issue to gift monika

### ISSUE THREAD

**Issue by themostunlunckypeoplealive** [Monika-After-Story/MonikaModDev#8473] opened 2021-12-23 03:50 UTC
some things i put on characters  or monika ignore and delete or she can't  read

i see every issue of gifting AND....nothing she always ignore or can't read  (my game is on brazilian portuguese if this change something)

please help me

**Comment by ThePotatoGuy** [comment] 2021-12-25 06:29
since this was 2 days ago, it most likely was because of [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by ThePotatoGuy** [comment] 2021-12-31 05:27
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-31 05:27 UTC
Labels: not a bug, tree gift
