### ISSUE TITLE
Watching a movie with Monika

### ISSUE THREAD

**Issue by InternetAlien97** [Monika-After-Story/MonikaModDev#4089] opened 2019-04-14 23:32 UTC
If you could pull up a movie player in the room or on your computer and then Monika could watch the movie with you would be really cool.

**Comment by Rai99** [comment] 2019-04-14 23:43
#628, #826, #984, #1548, #2102, #2898, #3431 

It's been suggested before a few times, and as far as I know, it's actually a thing, but the problem is there's not enough content in it, so it's disabled for the time being.

**Comment by multimokia** [comment] 2019-04-14 23:48
> but the problem is there's not enough content in it, so it's disabled for the time being.

Allow me to fix that:
but the problem is there's no~~t enough~~ content ~~in~~ for it, so it's disabled for the time being.

**Comment by ThePotatoGuy** [comment] 2019-04-22 18:49
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-04-22 18:49 UTC
Labels: duplicate
