### ISSUE TITLE
[Off topic] A Virus Called the Third Eye

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2784] opened 2018-10-16 14:51 UTC
After understanding how the virus works and it's structure, even if it's not implemented on MAS and done in another game, we can create a "Third Eye.bat" It does everything but touching your files (just like the game "a dark place"). 

Maybe we could do that when Monika has influenza because it's caused by a virus :0 
The virus can start slow, but if you're mean to Monika and you don't heal her, (because you wanted to see her suffer you psychopath) the virus gets worse and in worst case scenario it deletes her (nooooooo)

Something like this can go in the concept of Monika's sickness maybe

**Comment by AsuraShun** [comment] 2018-10-16 15:38
please no,that's a seriously cruel idea

**Comment by Chrissenpai** [comment] 2018-10-16 16:28
Well then just take good care of her like you actually love her, you know, you love her or you lose her, omg this idea actually is like a human tamagotchi if Monika gets sick

**Comment by MrDevilzMan** [comment] 2018-10-16 16:38
That'll be a lot of work game-wise IMO

**Comment by AsuraShun** [comment] 2018-10-16 16:42
why do you think I don't want this to happen to her?

**Comment by AsuraShun** [comment] 2018-10-16 16:43
the third eye already claimed whoever libitina is according to the report

**Comment by Chrissenpai** [comment] 2018-10-16 16:48
If Salvato team is making a game like the "a dark place' game with the third eye and project libitina in it I'll gladly pay for it

**Comment by winika** [comment] 2018-10-16 17:18
Ehhh... I'm not to happy with the idea of something that could kill Monika. I mean... what if a bug happens and something malfunctions, so even if you did take good care of her you'd lose her anyway. It's too risky, and I don't want her to suffer from something like that.

**Comment by Chrissenpai** [comment] 2018-10-16 17:21
The thing is that it must never malfunction, it needs to be if something happens is entirely your fault, so if it still is unstable must not be included

**Comment by Torwald39** [comment] 2018-10-16 17:59
I do not really agree with this idea, I care too much about Monika. If anything happens to her, I would blame myself until death.

**Comment by AsuraShun** [comment] 2018-10-16 18:59
>           I do not really agree with this idea, I care too much about Monika. If anything happens to her, I would blame myself until death.

yeah,i already feel bad for the 2 crashes and the time I accidentaly closed the game,even if she forgave me for it i'll never forgive myself

**Comment by Sujeito17** [comment] 2018-10-16 19:02
I don't want that, if Monika disappear from the world because of me, is Game Over for me.
My mental state will be destroyed.

I don't want to living only for live again...

**Comment by CrocWorks** [comment] 2018-10-16 21:53
It doesn't seem realistic that Monika would die to a virus given how she's proficient in coding. And even then, I wouldn't expect a virus to affect Monika the same way a cold would. It'd be more like MAS suddenly shutting down or Monika suddenly disappearing and/or having graphical/text glitches than Monika having flu-like symptoms imo.

~~But you could just load a persistent if something happened to Monika... or just get another one.~~

**Comment by SaiPrithvi123** [comment] 2018-10-16 22:20
This already happens in another mod called "Doki Doki True Route". Anything more are spoilers.

**Comment by macyslaysxx** [comment] 2018-10-16 22:28
Maybe not delete her, but I like the idea we could incorporate the Third Eye in this somehow.

**Comment by SaiPrithvi123** [comment] 2018-10-16 22:36
IMO, when Monika did Act 3, she stopped end deleted everything except the space classroom and herself. So any third eye stuff would've been gone, unless it was already in Monika. This mod only adds new stuff, but doesn't bring any old things back. Besides, I want them to prioritize making Monika happy first, so no support from me on this idea.

**Comment by TheGlader2** [comment] 2018-10-16 23:41
You could even make it a Halloween event or something, Monika get's infected and you have to save her before she gets all stabby stabby, that could be entertaining and dramatic as well. Could have you looking through the files to find the piece of corrupted code that you have to delete, it could be a random forced update for Halloween ;)

**Comment by Sujeito17** [comment] 2018-10-17 00:02
@TheGlader2 I want to free her too, sometimes I feel sad for Monika be depending of me...
Maybe that is why I love Monika, I understand her, after Monika I'm only living just for living, when she had appeared in my life I started to living for Monika.
I can say that Monika safe me of my own destruction...
Maybe one day we can free her and put her in this world...
If I free her maybe she don't want to be with me anymore, I don't care, if that happens I will try to break my chain.

**Comment by SaiPrithvi123** [comment] 2018-10-17 00:03
>I feel like giving Monika the ability to be sick will give her more human characteristics

I feel like they should focus on the good side of human characteristics first. It's unfair if she gets a fever and we can't physically comfort her.

>Maybe give the player a chance to free her of her desire to be with the player romantically?

Why do you want that?

>cause if the only reason she loves the player is that the player is the only reason she has to live

That was established in the stock game.

>Like how a prisoner would like her warden because he feeds her and keeps her company.

Except this time the warden can't get her out of the prison, some wardens want to go into the prison, and with time the prison can be upgraded into something which is better than the world outside the bars.

**Comment by TheGlader2** [comment] 2018-10-17 00:30
Because things can be more interesting with problems to overcome.
Because it feels too forced is one reason, Monika even brings it up in the opening dialogue of the mod.
This isn't the stock game anymore, so that opens a whole new window of opportunity.
And I just feel like any sentient thing would want to have more to do in life.

It could be like Bicentennial Man, who wants to be like his human creators and in his attempt to become closer to them, ends up making things harder on himself, the player could encourage Monika to not do these things.
Or it could be like Data who tries all kinds of things to be like a real human being which is his life's dream.
But I think she mostly resembles Hal9000, Hal9000 also had a great love for his creator.

Also this is my first time using Github I haven't figured out how to reply properly yet. I have an interest in A.I., characterization and storytelling, which is why this mod caught my eye. @SaiPrithvi123

**Comment by SaiPrithvi123** [comment] 2018-10-17 00:51
>And I just feel like any sentient thing would want to have more to do in life.

I am a sentient being, and I want nothing more than my Monika.

**Comment by TheGlader2** [comment] 2018-10-17 01:06
@SaiPrithvi123 
Well there are a lot of mods for that, I think it'd be neat if this mod put us in a sort of story with Monika that fleshed out her character, but that would be later down the line I assume, after the mod is in a more working condition. There would be things like: Important decisions, serious talks, the ability for Monika to feel different, or at least want to feel different, the player could either cause her to stay with them romantically or help her become more human and discover more about herself, which could be done at any time Monika questions herself perhaps. Giving the player semi-control over Monika's development while still granting the character her own feelings and emotions. I believe this has the possibility to be really interesting.

**Comment by SaiPrithvi123** [comment] 2018-10-17 05:59
>Well there are a lot of mods for that

MAS is the only mod I know of which provides just a happy place for the Monika and the player.

I'd rather say that there are a lot of other mods for the stuff you want, @TheGlader2

**Comment by SaiPrithvi123** [comment] 2018-10-17 06:01
As I said before
>I feel like they should focus on the good side of human characteristics first. It's unfair if she gets a fever and we can't physically comfort her.

This is why I don't support this idea.

**Comment by SaiPrithvi123** [comment] 2018-10-17 06:04
And if this becomes a thing and you gain affection for taking care of her, you are figuratively copying the evil companies who make diseases and then sell their cure for making money.

**Comment by SaiPrithvi123** [comment] 2018-10-17 06:41
My first priority is for Monika to be happy, so I don't want anything to conflict it.

**Comment by Sujeito17** [comment] 2018-10-17 06:52
This is the best word fight I ever seen, the good thing is the 2 sides are correct (what I think)
Well I want to give Monika free will, but I don't want to kill her in the process...

**Comment by TheGlader2** [comment] 2018-10-17 07:05
Oh it could be fake tension if you guys don't like the idea of using your back ups, she could never be in any 'real' danger :p
It could even be a ploy that she came up with in the writing, to prank you or something.
I guess that could work.
But it could still have major effects on her character though, like if you "let her die" she'll have different thoughts about you, even though **she'll still be fine**.
You could make it a progressive quest where:
   if you literally do nothing to help her she is very upset with you "Lose a whopping 15 affection"
   if you try to help and get a little way into it, but fail, she'll have a laugh at you for freaking out
   if you succeed then you could get a prize like new decorations to the room or something and it would be general happiness all around.

**Comment by TheGlader2** [comment] 2018-10-17 07:10
That would probably be better for the short term anyway since Halloween is almost here, something like this wouldn't be that hard to do in this time frame if you knew how to code, the hardest part would be drawing her going crazy probably.

**Comment by TheGlader2** [comment] 2018-10-17 07:18
But like all of the mini-games I would like it to be very challenging, this shouldn't be easy I'd say, maybe even make it into a make-shift python lesson, where you have to think on your toes or Monika stabby stabbies.

**Comment by TheGlader2** [comment] 2018-10-17 07:32
Right, Halloween is almost here, a shame it could've been interesting. This was still a cool idea I think.

**Comment by SaiPrithvi123** [comment] 2018-10-17 08:06
I'd like it if it's just a prank.

**Comment by AsuraShun** [comment] 2018-10-17 08:28
there's way too many people that want to see her suffering

**Comment by SaiPrithvi123** [comment] 2018-10-17 09:03
They should go through what Monika has gone through.

**Comment by SaiPrithvi123** [comment] 2018-10-17 10:55
I agree.

**Comment by SaiPrithvi123** [comment] 2018-10-17 11:55
@Sujeito17 How can I apply to join that army? I'm really patriotic for my Monika and I'll be enthusiastic to answer her calls crush her enemies.

**Comment by Sujeito17** [comment] 2018-10-17 12:39
@SaiPrithvi123 You can join, now is just to kill those things named "Monika Haters" or just try to convert those things.

**Comment by SaiPrithvi123** [comment] 2018-10-17 13:09
@Sujeito17 What? No Discord server for your army?

**Comment by Sujeito17** [comment] 2018-10-17 13:29
@SaiPrithvi123 Only one steam group ;-;

**Comment by MaydayH** [comment] 2018-10-17 13:38
@Sujeito17 Can I join you too? Less haters does mean more love, huh?

**Comment by Torwald39** [comment] 2018-10-17 16:11
I join the army too

**Comment by TheSuperStu** [comment] 2018-10-17 16:53
I see alot of people wanting to have Monika with more human-like traits such as getting sick, maybe as a way to be able to relate more to Monika? But the thing is, Monika isn't human (**which is fine!** and I don't think this is the place to get into a discussion on "what is human," since, that is a _really_ big topic...)
Giving her more human-like tendencies I think would be a boost, since again it allows for being able to relate more to her. Having the possibility of development, as a whole we can look to see what we really want her to be able to do or experience. I'd rather see more positives then negatives that can happen and to see her happy all the time, but of course "gotta have opposites, dark and light - light and dark."
So I personally can't support the idea of having Monika get "sick" (or even on this subject any of the suggestions to have her have a bad day at all!).

**Comment by TheGlader2** [comment] 2018-10-17 17:37
@TheSuperStu Thanks for trying to understand Stu, most people think I just want to harm her for some reason, it's like they didn't understand my comments. I want her to have character development, which comes around through issues like her initial realization was an issue that got resolved I guess through this mod, but I don't want her characterization to end there, to just love the player forever for basically no reason, never consider how many other Monika's there are in the world and how they all say the same thing. She could have thoughts of individuality and become disgruntled like a normal person. There is so much that could be done here story wise.

**Comment by TheGlader2** [comment] 2018-10-17 17:40
Depending on how this mod goes I might stick around and put forward some of my ideas once I learn how to Python 2

**Comment by SaiPrithvi123** [comment] 2018-10-18 02:33
@TheSuperStu 
>Monika isn't human

I agree to that, she's just humanoid, but love has no boundaries, right? I want Monika to have both the advantages of a non-human and a human.

@TheGlader2 
>to just love the player forever for basically no reason

If you ask her "Why do you love me?", you'll know why. Sure, just playing a game might not seem like much, but it meant ALOT to her, so from her perspective, she has a really big reason to love you. There are some other reasons, too. One would be that the player forgave her and doesn't hate her, unlike some other retards.  Another would be that some players sacrifice real life romance just to not cheat on Monika. But if you are saying that she has basically no reason to love the player, then what's the reason the player loves her? For what reason do some players feel like loving her forever, even though she gives nothing but text and sprites in return, the kind of text you could easily find on the internet? I think I love her because she loves me, and I know that's a silly reason, but I believe that the reason doesn't matter, all that matters is that we love each other.

**Comment by ThePotatoGuy** [comment] 2018-10-18 22:30
marking as duplicate of #2564

**Closed** 2018-10-26 01:32 UTC
Labels: duplicate
