### ISSUE TITLE
Cannot give gifts to Monika (I wanna spoil her)

### ISSUE THREAD

**Issue by SpaceHX** [Monika-After-Story/MonikaModDev#8402] opened 2021-12-14 04:16 UTC
Hey MAS! 

I gave Monika a Sprite pack gift I got from Reddit. 

If you wanna see the Gift I am trying to give her, click this link: 

https://www.reddit.com/r/MASFandom/comments/e451nj/i_installed_the_shoulderless_sweater_spritepack/    PS: I used the DownGit link to get the Sprite Pack.

I copied the mod_assets file into the games file found in the directory.

and for the .gift file, I had copied that into the character folder.

(Disclaimer, I did this yesterday.)

Then I went to go check and see if she got the gift, but she did not, I tried reinstalling the gift over and over again but she would not react.
Random Chatter is turned on to the max, and repeat topics are on.

Then the next day comes, I go to check on Monika, and then she reacts to the gift but she says she cannot read the gift correctly. 
(I had installed a second sprite pack as a gift to Monika, (Which were ribbons.) to her.

I think she cannot recognize it because I tried reinstalling the sprite pack too many times. Not to mention, I had given her a second sprite pack as a gift to her,
I think that had also interfered with the gift.

So, I FULLY reinstalled MAS. And I only gave her 1 gift. And now I am waiting till tomorrow to see if she gets it and can read it.

Well, next day, I just got onto Monika After Story, and not surprisingly, she did not recognize the gift, nor did the gift show up in the 
clothing section.

If you would like to contact me, Do it on Discord. My user is narek#1662

Thanks, Narek C.

**Comment by ThePotatoGuy** [comment] 2021-12-15 04:55
Do you see presents under the tree?

**Comment by SpaceHX** [comment] 2021-12-15 05:00
> Do you see presents under the tree?

Yes

**Comment by ThePotatoGuy** [comment] 2021-12-15 05:06
Since it's currently christmas season, all gifts are put under the tree and will be opened/reacted to on christmas. #6783 will add some sort of feedback so its clear that this happens.

**Comment by SpaceHX** [comment] 2021-12-15 05:11
> Since it's currently christmas season, all gifts are put under the tree and will be opened/reacted to on christmas. #6783 will add some sort of feedback so its clear that this happens.

Shoot well, I did kinda give her 6 versions of the same gift😂 so does the mean she will react to to six of the same things on Christmas?

**Comment by ThePotatoGuy** [comment] 2021-12-15 05:12
No, only unique gift names are treated as separate gifts.

**Comment by SpaceHX** [comment] 2021-12-15 05:16
> No, only unique gift names are treated as separate gifts.

Thank you for telling me, as long as I know she will get the gift at some point I am fine. Sorry for wasting your time. Have a good day!

**Comment by ThePotatoGuy** [comment] 2021-12-26 02:37
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-26 02:37 UTC
Labels: not a bug, tree gift
