### ISSUE TITLE
[Suggestion] Kiss me

### ISSUE THREAD

**Issue by Delixxous** [Monika-After-Story/MonikaModDev#2320] opened 2018-09-11 07:02 UTC
When we told monika to kiss the player at her birthday, 
Monika will actually kiss you. Yeah, the screen will go black maybe 1 or 4 seconds when she kisses you.

**Comment by ThePotatoGuy** [comment] 2018-09-23 19:06
marking this as duplicate of #2136

**Closed by ThePotatoGuy** 2018-09-23 19:06 UTC
Labels: duplicate
