### ISSUE TITLE
Alterations to the new Leaning pose

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#3687] opened 2019-02-10 05:42 UTC
#3660 

[Updated Upright and Leaning Poses V2.1](https://drive.google.com/open?id=1EPyNNn-dJMFDWSmZlBRlPXtX3MphjEHs)

I've made some alterations to the new leaning pose, and with a little feedback from people in #artistry on the Discord server here's a list of things I've changed thus far:

- Monika's right-side bang is slightly visible behind  her neck while leaning.
- Her right forearm is a little shorter to try and better match proper arm length.
- Her left hand has been edited a bit to try and reduce the stretched look of the original.
- Her right hand fingers are slightly visible.
- Her jawline has been adjusted slightly to be smoother
- Changed her hair a bit so it doesn't look like it's being blown by a fan
- Changed some shading on her arms and face.

![comparison gif](https://user-images.githubusercontent.com/36512990/52530061-4c7d4100-2cc4-11e9-9b30-99a8fec203b7.gif)

Any feedback would be appreciated so I can continue to try and improve upon what others have suggested thus far, as well as what I personally feel could be different.

**Comment by Trilasent** [comment] 2019-02-10 05:54
After posting this I went ahead and smoothed out her jawline according to more feedback from people in #artistry.

**Comment by Trilasent** [comment] 2019-02-10 06:24
![4c23cdf0550905b99205adbb21227dcd-png](https://user-images.githubusercontent.com/36512990/52530373-35d9e880-2cca-11e9-975d-98d2d873b17a.jpg)

Update to her right side bang

**Comment by dennisOdenbreit** [comment] 2019-02-10 07:02
As I came here I did not expect to see her nude.

**Comment by Trilasent** [comment] 2019-02-10 07:09
> 
> 
> As I came here I did not expect to see her nude.

Well I merely used what was available to me, haha.

**Comment by Hapilone** [comment] 2019-02-10 07:22
Looks great imo

**Comment by Trilasent** [comment] 2019-02-10 09:29
Changed left forearm shading:

Before:

![before](https://user-images.githubusercontent.com/36512990/52532026-0041f900-2ce4-11e9-80d1-c946e84ba453.png)


After:

![after](https://user-images.githubusercontent.com/36512990/52532030-059f4380-2ce4-11e9-9aca-11f4c65076e1.png)

**Comment by EntonyEscX** [comment] 2019-02-10 13:56
I liked the changes. It looks more comfortable like that.

**Comment by Chrissenpai** [comment] 2019-02-10 16:45
Nice, another fellow artist that makes corrections, good job @Trilasent.
Now, test this because I'm not sure myself: if you can, make a colour correction in her hand so it matches with her face, let's see how it develops.

**Comment by AsuraShun** [comment] 2019-02-10 16:47
Enjoy it folks,this is the closest you'll get to see her nude in this mod

**Comment by ThePotatoGuy** [comment] 2019-02-10 16:52
@Olliesama @velius94 @metisz @professor-jmo

What are your opinions on these changes?

**Comment by ThePotatoGuy** [comment] 2019-02-10 17:04
@Trilasent can you upload psds to a gdrive and share it here? 

Also the jawline adjustment would have to be made to the upright base as well, since it has the same jawline.

**Comment by Professor-JMO** [comment] 2019-02-10 18:40
> I was there for most of these changes in `#artistry`.
>> Yeah, I'm very much in agreement with the right bang.
>> I agree with the jawline, too.
>>> I'm unsure of the arm just yet from this point of view but it does look better, imo.

**Comment by Trilasent** [comment] 2019-02-10 19:31
> 
> 
> @Trilasent can you upload psds to a gdrive and share it here?
> 
> Also the jawline adjustment would have to be made to the upright base as well, since it has the same jawline.

Yeah, I'll put them up soon. I'll edit this comment with the link when I do.

**Comment by Trilasent** [comment] 2019-02-10 19:32
> 
> 
> Nice, another fellow artist that makes corrections, good job @Trilasent.
> Now, test this because I'm not sure myself: if you can, make a colour correction in her hand so it matches with her face, let's see how it develops.

I can tinker around with it and see how she looks.

**Comment by Trilasent** [comment] 2019-02-10 20:43
Made some alterations to her down hair as well:

Old:

![oldnewhair](https://user-images.githubusercontent.com/36512990/52539300-167ea200-2d42-11e9-96ae-90d009154f24.png)


New:

![newnewhair](https://user-images.githubusercontent.com/36512990/52539304-1f6f7380-2d42-11e9-9b18-3cf224c587cb.png)


👍 or 👎

**Comment by Trilasent** [comment] 2019-02-10 21:05
@ThePotatoGuy Here's the [link](https://drive.google.com/open?id=1Xk0RwDRI47Tg49MewI2yBaDR7rXeqL52) to the updated PSDs.

**Comment by Trilasent** [comment] 2019-02-10 21:30
If I missed anything DM me on Discord and show me what I missed.

**Comment by jmwall24** [comment] 2019-02-12 04:36
here are some things I am noticing that need work.
the jawline work, the edges are jagged and the black outline was completely lost in parts of it
![screenshot_386](https://user-images.githubusercontent.com/36523761/52611892-921d4380-2e55-11e9-82d4-13c6e48ae65c.png)

and similar with the arm on the table, just needs to be smoothed out
![screenshot_385](https://user-images.githubusercontent.com/36523761/52611915-a7926d80-2e55-11e9-8e80-047d36a37daa.png)

i like what you did with the hand on her face, the shorter hand looks a lot better

**Comment by Trilasent** [comment] 2019-02-12 09:07
@jmwall24 Updated. Check the original post for the V2 revisions.

**Comment by EntonyEscX** [comment] 2019-02-12 20:29
This line in the fold of the hand it's strange. 😕
![52532030-059f4380-2ce4-11e9-9aca-11f4c65076e1](https://user-images.githubusercontent.com/38970166/52665931-fe4e8480-2ef3-11e9-8555-8a8d5a521aba.png)

**Comment by jmwall24** [comment] 2019-02-13 02:30
Face looks better, still some wavy/choppy spots on the top part of arm

![screenshot_393](https://user-images.githubusercontent.com/36523761/52682441-71182980-2f0d-11e9-9b01-d8e6c5294368.png)

**Comment by Trilasent** [comment] 2019-02-13 05:27
@jmwall24 Updated again.

**Comment by Velius94** [comment] 2019-02-13 17:52
#3651 
More related to the overall changes in the base, but seeing as the issue is closed, will post here since the bulk of the base-related work is here.

With the skin color changes, the night filter now makes Monika's skin too yellow.
![new filter](https://user-images.githubusercontent.com/1176163/52732282-1ab7f300-2fc0-11e9-8b37-36939abfb017.png)

I attempted to amend that by fiddling with the sliders in my psd, but still haven't achieved the desired effect (that being as close as possible to the original CG).
![my filter](https://user-images.githubusercontent.com/1176163/52732399-679bc980-2fc0-11e9-9fdd-e5024863ffb9.png)
![2](https://user-images.githubusercontent.com/1176163/52732398-679bc980-2fc0-11e9-93f8-bdabcb99bd58.png)

**Comment by EntonyEscX** [comment] 2019-02-13 23:11
@Velius94 For a while, the third is the best filter in my opinion.

**Comment by Velius94** [comment] 2019-02-14 00:03
@EntonyEscX
I got confirmation that the filters will be done internally, so there's no problem.

**Comment by jmwall24** [comment] 2019-02-14 00:48
My concerns have been addressed, thanks.  Gonna see if anyone else on the dev team has any issues and will let you know.

**Comment by ThePotatoGuy** [comment] 2019-02-15 05:00
I will look at this this weekend.

**Comment by ThePotatoGuy** [comment] 2019-02-15 05:02
@Velius94 are you sure you are using the correct filter? Use the one from the utility folder, I always replace filters+other stuff in submitted psds with the one from the utility folder.

**Comment by Trilasent** [comment] 2019-02-15 08:52
@ThePotatoGuy If you have any issues with it let me know via Discord, so I can see it sooner and get them taken care of.

**Comment by ThePotatoGuy** [comment] 2019-02-15 23:33
I have made some minor edits:
* made upright outlines on cheek darker
* made leaning outlines on right hand darker
* removed extra color coming off leaning left arm shoulder connection
* removed blemishes visible with night filter on left arm
* filled in transparency holes in right arm

[gdrive ](https://drive.google.com/open?id=10GVZDlCWCQVYqQ5sPOuhWgrEjbme-72I)

**Comment by ThePotatoGuy** [comment] 2019-02-15 23:39
So for next steps:
- I'm moving the new upright base into the base psds as well as applicable outfits (vday + santa + upcoming clothes).

The new leaning will have to wait until we get a unanimous decision regarding someone else who decided to also redraw leaning. @Trilasent I've mentioned you on discord about that, be aware and ready to review that leaning pose as well.

**Comment by ThePotatoGuy** [comment] 2019-02-15 23:41
* and the back hair bang will also be moved to leaning base hair styles

**Comment by ThePotatoGuy** [comment] 2019-02-20 05:22
This has been added to #3174 [closing]

**Closed by ThePotatoGuy** 2019-02-20 05:22 UTC
Labels: art, discussion
