### ISSUE TITLE
Brackets in path to game directory leads to endless errors upon taking a screenshot

### ISSUE THREAD

**Issue by swindlesmccoop** [Monika-After-Story/MonikaModDev#7154] opened 2021-04-07 12:11 UTC
Tested with regular and curly brackets, with both causing a near-infinite stream of errors. For reference, the folder is called either [Visual Novels] or {Visual Novels} respectively. From what I can tell, it sees the brackets as some sort of text tag. This may be a Ren'Py issue, but I figured I would report it here first in case it isn't and it's just a MAS issue.

The error that persitently occurs through the thousands is:
`Exception: Unknown text tag u'Visual Novels'`

**Comment by multimokia** [comment] 2021-04-07 14:01
Can you send the full `traceback.txt` file, please?

**Comment by swindlesmccoop** [comment] 2021-04-07 23:06
Yep.
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6274981/traceback.txt)

**Comment by TheElementalOfDestruction** [comment] 2021-04-09 08:23
Just checked and this error exists in unmodded DDLC, so it's not something caused my the mod. Either the mod is relying on the code of DDLC for screenshots and the bug comes from there or there is a bug in the Ren'Py engine.

**Comment by TheElementalOfDestruction** [comment] 2021-04-09 08:30
for reference, the problem is that the brackets in the path are not being escaped properly when the game tries to write it to the screen (to say where the screenshot was saved) and so it thinks that it is supposed to substitute that text. For a quick work around, you could make it so that your path uses `[[Visual Novels]` instead of `[Visual Novels]` and that should sort of fix it. Unfortunately the path that it writes will be incorrect (because it will say that it saved to simple `[Visual Novels]` but at least it won't cause a traceback.

**Comment by Booplicate** [comment] 2021-04-09 09:45
It's indeed a RenPy bug. Even if you override that function, there's still will be other issues. Just don't use `{}` or `[]`.

**Comment by ThePotatoGuy** [comment] 2021-05-04 04:38
marking as wontfix since we cantfix

**Closed by ThePotatoGuy** 2021-05-04 04:38 UTC
Labels: bug, wontfix
