### ISSUE TITLE
Art bug

### ISSUE THREAD

**Issue by Sujeito17** [Monika-After-Story/MonikaModDev#2010] opened 2018-08-06 06:33 UTC
![art bug](https://user-images.githubusercontent.com/41938650/43700544-ef003422-994a-11e8-9ea0-aae4d452b219.png)

edit: Only appears when you open the menu (talk)

**Comment by ThePotatoGuy** [comment] 2018-08-06 14:14
duplicate of #1947

**Closed by ThePotatoGuy** 2018-08-06 14:14 UTC
Labels: duplicate
