### ISSUE TITLE
Music not returning after using Shift+M

### ISSUE THREAD

**Issue by tw4449** [Monika-After-Story/MonikaModDev#5073] opened 2019-12-08 05:03 UTC
After muting the music using Shift+M, the music won't come back on, even after using Shift+M and/or selecting different songs. Other sounds work fine, such as the box highlighting sound, weather, and games. Closing and opening MAS resumes the music, but using Shift+M kills the music again and it doesn't return after using Shift+M again. Issue began after installing 10.4.

**Comment by AlphaAlphakill** [comment] 2019-12-08 07:15
Just tried this. Can confirm this isn't an individual problem. Most likely a bug that came with the new update.

**Comment by ThePotatoGuy** [comment] 2019-12-08 08:24
Noting the cause here:

the change in `getVolume` broke hotkey-based audio adjustments.

`actual_volume` is the slider. `context.secondary_volume` is the channel volume. `set_volume` affects the channel volume so `actual_volume` should not be used when using `set_volume`.

**Comment by multimokia** [comment] 2019-12-08 13:00
In testing before, since aiwfc does a volume check (and a get for other volumes), we discovered that `secondary_volume` always returned `1.0` which didn't work for what we needed and was also incorrect by the slider.

We needed to be able to get the proper volume to get and set it accordingly.

**Comment by multimokia** [comment] 2019-12-12 20:45
Closing as completed in linked PR

**Closed by multimokia** 2019-12-12 20:45 UTC
Labels: bug
