### ISSUE TITLE
UNSTABLE MODE

### ISSUE THREAD

**Issue by toonziz** [Monika-After-Story/MonikaModDev#7685] opened 2021-08-29 00:29 UTC
I updated the game to unstable mode then i turned it off and it said new update available which was the normal mode then i accidentily hit cancel and now i cant update it back to normal!!

**Comment by toonziz** [comment] 2021-08-29 00:33
it also removed the custom rooms

images:

![Screen Shot 2021-08-28 at 7 31 43 PM](https://user-images.githubusercontent.com/82217573/131234329-20e69d67-26a3-4103-9725-a79d3fe2f344.png)
![Screen Shot 2021-08-28 at 7 31 56 PM](https://user-images.githubusercontent.com/82217573/131234333-85e498b3-c417-4754-bcdd-53b54cebe4b5.png)

**Comment by fromulus** [comment] 2021-08-29 09:39
You're on unstable, which means your game is getting updated every time a feature is merged on the master branch instead of during official releases like for most players.

You can always re-download the latest official release (0.12.2) and overwrite your DDLC folder with the newly released files to return your files to before.
You'll also need to reinstall your custom rooms every time the game is updated, whether through unstable mode or through noirmal updates.

**Comment by ThePotatoGuy** [comment] 2021-09-01 02:40
This probably is a side effect of #6913. That being said, we're not changing this behavior, so you will have to manually overwrite files using the normal version as mentioned to get off unstable.

**Comment by ThePotatoGuy** [comment] 2021-09-06 22:49
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-09-06 22:49 UTC
