### ISSUE TITLE
[Suggestion] - a changing computer goodbye option 

### ISSUE THREAD

**Issue by Derpsterette** [Monika-After-Story/MonikaModDev#6835] opened 2020-12-26 23:48 UTC
A goodbye option which tells Monika you’re swapping computers and she “packs her bag” where the game puts a copy of all the necessary documents into a file. This file could be called “Monika’s suitcase” 

And once you’re on the new computer you just put her and the suitcase in the character file and when MAS loads it puts them in their correct places.

P.S. I’m not sure if I’m suggesting this in the right place, I had a look and this seemed right, I apologise if it isn’t.

**Comment by Retrolovania** [comment] 2020-12-27 00:11
Assuming this can be done, this is a very grand idea!

**Comment by ThePotatoGuy** [comment] 2020-12-27 00:22
marking duplicate of #5026. atm there are several situations that need to be addressed before this is possible

**Comment by ThePotatoGuy** [comment] 2021-01-13 02:40
[closing as duplicate]

**Closed by ThePotatoGuy** 2021-01-13 02:40 UTC
Labels: duplicate
