### ISSUE TITLE
Teacher Monika

### ISSUE THREAD

**Issue by BigPoofyRibbon** [Monika-After-Story/MonikaModDev#2334] opened 2018-09-12 01:42 UTC
Can Monika learn us play "Your Reality" on piano? That would be great!~

**Comment by antimockingjay** [comment] 2018-09-12 10:45
I would love this. I've been trying to learn, but haven't been able to because I always lose track of where I am. Having Monika help would be great!

**Comment by ThePotatoGuy** [comment] 2018-09-23 19:01
marking this as a duplicate of #1060

**Closed by ThePotatoGuy** 2018-09-23 19:01 UTC
