### ISSUE TITLE
[Suggestion] - Alarms, Reminders, & To-Do Lists

### ISSUE THREAD

**Issue by SirStylus** [Monika-After-Story/MonikaModDev#7554] opened 2021-07-26 08:10 UTC
Overview:
Adding a new tab for utility features that could contain scheduling tasks, such as alarms, reminders, and to-do lists. Many already have this feature as apps on their phones, but you can often see those in relationships helping each other keep up with those important tasks. 

Reminders / Alarms:
I'd suggest maybe having a few commonly used ones as options one can select for unique dialogue. This list could include options such as "Can you remind me to take my medication?" or "Can you remind me to get to bed on time?". 

Some options may be a little more in-depth, such as "Can you remind me to leave for work?" This could have a few follow-up questions, like if the job has a consistent weekly schedule or has an "as-needed" schedule, which could prompt her to ask what hours you work the following day.

Additionally, an option to add in manual alarms could be given for anything not covered specifically.

Timers:
Like above, Monika could have a few options pre-written for common situations such as "I'm cooking something, can you remind me to check it?" which would prompt Monika to ask the player how long to set the timer for.

It could also accept a generic inputted answer.

Appointments/Dates:
Could ask Monika to add a date to the calendar, and optionally have her remind you of the appointment X days/hours before it. Common suggestions could be doctor's appointments, grocery shopping days, birthdays of friends, interviews, exams.

General Shared Features of the Above Categories:
Getting Monika's voice right for this mod will likely involve ensuring the writers convey Monika's care for her player. She might subtly guilt her player for ignoring alarms that are good for their health, such as taking their medicine or doing household chores. She may utilize a menu option to ask whether the player has completed their task, and refuse to bring up random topics, or allow the player to select topics until they confirm their task is complete. 

Monika could incorporate random reminders into her rotating dialogue. "Hey, [Player]? Just wanted to make sure you remember your doctor's appointment is this week. [Weekday] the [Date] if I remember correctly." She could offer the player whether to forbid or allow these reminders when the Repeat Dialogue option is off.

Closing:
There are a lot of possible other scheduling-related items that could expand this list, and I may add or update items here later if I have other suggestions in this vein.

Thanks for the time! -Luca

**Comment by LeilanPAD** [comment] 2021-07-26 23:12
that sounds so swag

**Comment by Kritzb278** [comment] 2021-07-27 04:32
We need this

**Comment by Wingdinggaster656** [comment] 2021-07-27 06:38
The idea has been tossed around a lot, but no one seems to be doing it yet.
I'm a big fan of this idea , but developing this system would be time-consuming (I guess that's why the developer team didn't do it), so it's not a high priority.
If you can implement this system and open a PR for it, I think the developer team will be happy to accept it.

**Comment by ThePotatoGuy** [comment] 2021-08-07 22:27
duplicate of  #4914 

Speaking from experience, creating a scheduler is significantly harder than it seems.

[closing as duplicate]

**Closed by ThePotatoGuy** 2021-08-07 22:27 UTC
