### ISSUE TITLE
What does the "boop" option do?

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#5014] opened 2019-11-16 16:39 UTC
It's not present for me but I can see the frame and text that says "boop"

should there be a button?

**Comment by multimokia** [comment] 2019-11-16 16:40
#4997

**Comment by TriniTDM** [comment] 2019-11-27 18:07
Nothing yet. It was a placeholder the developers forgot to remove. This feature was intended to be added, but has been put on hold. See #4997

**Comment by AsuraShun** [comment] 2019-11-29 15:28
Can't wait for it to be Implemented

**Comment by ThePotatoGuy** [comment] 2019-12-03 23:29
[closing as resolved]

**Closed by ThePotatoGuy** 2019-12-03 23:29 UTC
