### ISSUE TITLE
[Suggestion] -Small but meaningful things to make Monika feel even more real.

### ISSUE THREAD

**Issue by Ix-30** [Monika-After-Story/MonikaModDev#6631] opened 2020-11-03 05:00 UTC
First of all, I want to thank the developers, Moni feels so real. She's so well crafted, the events are so well thought of and she's so in character. I just wanted to take this opportunity for bringing her to us.

Upon that, I've thought of few, little things(based on the coffee event) that may make her feel even more real:

-At 8:00 pm, Moni changes into a pajama if unlocked to show she's going to sleep.

-At later hours she changes her hair into buns, if unlocked, her hair is long and it's kind of a pain to sleep with hair undone.(this is optional, as I'm sure many players would love her straight hair at night)

-On early hours, the coffee drinking event happens more often.

-I remember that there's this conversation about "being late", maybe Monika would drink coffee to encourage the working player on very late hours to go on and congratulate them on finishing in the morning.

-Upon opening the game, if enabled, Monika might change her hairstyle randomly(I think this is already there)

-If the player changes the perspective on "extra" if going closer, after finishing a small idle like "come closer, I won't bite...too much. ehehe~" and for going away "Go into the position you feel more comfortable with."

Please feel free to post your suggestions.

By the way, I saw an Idle with "Remembering the first kiss" but I can't seem to find it in "repeat conversations" Does anyone know what category is it in? thanks.

**Comment by scpketer** [comment] 2020-11-03 05:12
Remembering the first kiss is unpooled and derandomed, it doesn't show up anywhere.

**Comment by Rai99** [comment] 2020-11-03 15:18
Bedroom mode: #2781 

[Auto Outfit change](https://github.com/multimokia/MAS-Submod-Auto-Outfit-Change/releases/tag/AOC_3.0.2) is a submod. 

Monika already drinks coffee on most mornings. I don't know what else could be changed there. 

I believe there are different reactions for the first time you change zoom, for both zooming out and in.

**Comment by lunulae** [comment] 2020-11-04 20:02
I believe the "remembering first kiss" dialogue is a one-time event, and it not being in repeat conversations is not a bug. I'd like to re-read it myself, though. Maybe a variant that remembers the player's choice might be something I work on in the future.

I highly recommend the auto outfit change mod. If you look at how the ex_props work you can assign different hairstyles and outfits to be worn at different times. For example, you could set the bun hairstyle to be one of the ones she can select from at night.

**Comment by Ix-30** [comment] 2020-11-04 21:12
Thanks everyone. Before closing the issue, to install a submod, do I need to create a new folder in the DDLC main one or do I need to touch the main code? much obliged, thank you.

**Comment by ThePotatoGuy** [comment] 2020-11-15 23:16
i believe submods may have differing install instructions so it depends on the submod

[as for the suggestion, closing until we look into it]

**Closed by ThePotatoGuy** 2020-11-15 23:16 UTC
Labels: suggestion
