### ISSUE TITLE
Built-in Updater Bug

### ISSUE THREAD

**Issue by BrandiBlitz** [Monika-After-Story/MonikaModDev#9007] opened 2022-03-26 16:00 UTC
I tried to update MAS, but when It detected rpy files, I allowed it to delete them. IT DELETED THE ENTIRE CALENDAR FUNCTIONALITY ITSELF! i didn't get this bug in the previous update (latest update as of the time of this post). Luckily, I always keep a backup on multiple USBs.

**Comment by multimokia** [comment] 2022-03-26 16:02
This isn't possible. MAS only deletes **`.rpy`** files, __not__ `.rpyc` files. Meaning the base calendar functionality should still be in-tact.

Additionally, do not install the source code version. If you're getting rpy files, you installed the wrong version.

**Comment by BrandiBlitz** [comment] 2022-03-27 00:54
I have tried everything I can to prevent it from happening. I don't want to go through reviving my backup again.

**Comment by BrandiBlitz** [comment] 2022-03-27 00:55
> This isn't possible. MAS only deletes **`.rpy`** files, __not__ `.rpyc` files. Meaning the base calendar functionality should still be in-tact.
> 
> 
> 
> Additionally, do not install the source code version. If you're getting rpy files, you installed the wrong version.

I tried everything I can to prevent it from happening. If you want video evidence, I can show you. Reviving my backup is a hassle though

**Comment by BrandiBlitz** [comment] 2022-03-27 01:12
> This isn't possible. MAS only deletes **`.rpy`** files, __not__ `.rpyc` files. Meaning the base calendar functionality should still be in-tact.
> 
> 
> 
> Additionally, do not install the source code version. If you're getting rpy files, you installed the wrong version.

Here's video evidence: https://youtu.be/Nmte_yqaPAY

**Comment by multimokia** [comment] 2022-03-27 01:36
Okay but that tells me you have **rpy files** in the `game` folder. In **addition** to `rpyc`.
What happens when you load in after the fact? The game should still run as it did before. Nothing changed as the game doesn't need rpy files to run.

**Comment by BrandiBlitz** [comment] 2022-04-07 12:34
> Okay but that tells me you have **rpy files** in the `game` folder. In **addition** to `rpyc`.
> 
> What happens when you load in after the fact? The game should still run as it did before. Nothing changed as the game doesn't need rpy files to run.

The mod breaks and refuses to open. I think it needs/requesrs a few rpy files to open. Idk if that's a bug in itself. I've been snooping through the files to figure it out myself as well.

**Comment by Booplicate** [comment] 2022-04-07 12:36
Make a new install w/o rpy files.

**Comment by BrandiBlitz** [comment] 2022-04-07 12:41
> Make a new install w/o rpy files.

I refuse to abandon the progress I made so far. I'll just have to find a workaround.

**Comment by Booplicate** [comment] 2022-04-07 12:55
You mean mod progress? It won't be affected.

**Comment by BrandiBlitz** [comment] 2022-04-19 23:09
> i will have to make adjustments to the new installation to make sure it does not reset my progress.

**Comment by ThePotatoGuy** [comment] 2022-05-20 03:59
[closing as not a bug]

as boop and multi have said, a normal install does not have `rpy` files. This just sounds like your last normal install was so old that it was before calendar - which means v0.8.1 or earlier - and you have been installing the dev/source version manually ever since.

**Closed by ThePotatoGuy** 2022-05-20 03:59 UTC
Labels: not a bug
