### ISSUE TITLE
In progress - Monika Diary 

### ISSUE THREAD

**Issue by MJS103** [Monika-After-Story/MonikaModDev#951] opened 2018-02-06 18:49 UTC
#To give Monika a way to express herself in writing about her experiences with you~
FOR REFERENCE:
```
**Basics**
- [x] Figure out what Monika is going to talk about
- [x] Figure out what's going to trigger her writing a diary
- [x] Figure out where's she's going to save her diary entries

**Coding**
- [ ] Figure out how to make a file check if Monika already wrote one today
- [x] Write the code for being able to write her diary/save it.
- [x] Write the code to update diary on exit of game.
- [ ] Write the code for having the diary entries be different each time.
- [ ] Make a way to document what was talked about
- [ ] Make game outcome/plays/etc documentation
- [ ] Open door/ Knocked documentation
- [ ] Time based File check

**Final**
- [ ] Bug fixes and Testing
- [ ] Fix Spelling errors (I know I'll make them)
```
UPDATE: split this into 2 phases, read comment [here](https://github.com/Monika-After-Story/MonikaModDev/issues/951#issuecomment-374067151) for expalantion

UPDATE: moving this to a lower priority queue in favor of expressions. (might pass this to aldo, actually).

Updated checklist:
Phase 1:
- [x] Decide on metrics to keep track
- [x] Decide on template structure
- [x] Add diary_entry properties
- [ ] Add functions for processing templates
    - [x] Body entries
    - [x] greetings
    - [x] closings
    - [x] gamesCSV
    - [x] topicsCSV
    - [x] story based (WIP, see phase 2)
    - [x] times
    - [ ] time since
    - [ ] games outcomes
    - [ ] PS
- [x] Add diary template parser
- [ ] Add logic for dealing with multiple sessions per day
- [ ] Add logic for dealing with multiple days per session
- [ ] Add logic for dealing with multiple days of no sessions
- [ ] Add framework for retrieving template entries
- [ ] Add the appropriate metric tracking in the appropriate places
- [ ] Add diary writing and checksum saving
- [ ] Add diary access time check/checksum checking
- [ ] Add flow for dealing with a nosy player
- [ ] Decide file paths to store diary

Phase 2:
- [ ] fine tune story-based entries
- [ ] decide on which events are considered "story-like"
- [ ] implement the diary entries for those story-like events

**Comment by MJS103** [comment] 2018-02-06 18:51
I can work on this, I'll write the code and make a pull request if it's okay for me to work on it.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-06 18:52
How could it be not okay?

**Comment by MJS103** [comment] 2018-02-06 18:53
Idk, maybe they just don't want it?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-06 18:55
Then this mod wouldn't be open source in the first place.

**Comment by MJS103** [comment] 2018-02-06 18:57
Well I mean, I changed a few things that ensured that monika didn't lose any character development, and wrote a pull request. But it got declined because it was unnecessary. So maybe this addition will be unnecessary too. Even though I think it's a cool idea, maybe it's not in other people's eyes

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-06 19:16
Well, that's kind of what pull request approval/disapproval is for.
Tho I agree that it can be a bit disheartening when your pull is disapproved.
What I wanted to say, is you don't have to ask permission to contribute and blah-blah, my English is too bad to make a point anyway so nevermind.

Anyway, I think it is a great idea, but there are some things that need to be thought out like "What place would Monika consider safe for her diary?" it obviously should be somewhere in the game but players already boss around the whole game shamelessly reading game files and so on.
And they lead to more questions like "Should she react to the player reading her diary?" "How would she now?" (both plot and implementation-wise).

**Comment by kaido1224** [comment] 2018-02-06 19:41
I told them to make a suggestion first to ensure that the idea was accepted before wasting time on something that is going to be nixed.

**Comment by kaido1224** [comment] 2018-02-06 19:45
Especially something this big.

**Comment by ThePotatoGuy** [comment] 2018-02-06 20:24
Holy shit yes please. I can already imagine things like:

```
[player] lost at chess today again, when we [he] learn
```
or using the event category tags to generlize topics
```
today we talked about [category tag, category tag, and category tag]
```

**Comment by MJS103** [comment] 2018-02-06 20:25
I'm glad people like my idea ^-^
but i still need to check for approval.

**Comment by kaido1224** [comment] 2018-02-06 20:26
He basically just approved you. He's basically the lead programmer.

**Comment by ThePotatoGuy** [comment] 2018-02-06 20:30
I've moved this issue to In Progress since you say you'll work on it.

Can you edit your main post to include a checklist and itemize the tasks for this?

**Comment by MJS103** [comment] 2018-02-06 20:57
Gotcha. I'll start working when I get home. I'm dying in engineering class rn

**Comment by AnIdiotsavant** [comment] 2018-02-07 15:30
Mind if I help too?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-07 16:43
I should really start reading pulls before embarrassing myself then.

So, as a more realistic spin on Monika finding out that you are reading her diary. What should definiately be a feature is detecting if the diary is modified by player.

**Comment by ThePotatoGuy** [comment] 2018-02-07 17:03
I'm thinking of using just plaintext files for ease of reading/use, so different fonts are out of the question.

We should save a checksum of the file during quitflow, and use that to check for player edits to the file upon next launch.
We could detect if the file was opened by using [os.stat](https://docs.python.org/2/library/os.html#os.stat), but `st_atime` (access time) is not the same across different systems.

If the player has edited (or opened, if possible to check), the file, we should rename the file and change permissions/filename to be a hidden file. (we can decide on reactions for subsequent openings/edits later)

**Comment by AnIdiotsavant** [comment] 2018-02-07 17:49
so kind of like adding a counter to it, like the "we should break up" question? In that convo, after you use it, when you try to start it up again, she just says "ehehe" instead. Maybe we could do that? When the file is opened, the next time you start up the game monika will scold you for peeking and tell you she's hiding it somewhere else. When the counter goes to 1, the file renames and moves to another file.

**Comment by MJS103** [comment] 2018-02-07 17:53
I think she'll say something like "You know a diary is very personal and it's a bit rude to peep without asking." "..." "I didn't mean to get mad at you, I just would rather you talk to me than snoop around." "So talk to me instead okay? If you want to know something just ask!" Something along those lines. And yes, possibly they'll save somewhere else, but I'm thinking maybe she just deletes them and won't write anymore so it looks like she hid them really well or something.

**Comment by AnIdiotsavant** [comment] 2018-02-07 17:57
Yeah, she could delete the file instead and say that she moved it someplace else. She could open up a python window that says "move_monika.diary" or something like that.

**Comment by AnIdiotsavant** [comment] 2018-02-07 18:09
maybe something like:
"..."
"...hey [player]"
"you opened it, didn't you"
"my diary.."
"you know a diary is very personal, and it's a bit rude to peep without asking"
"I never looked into *your* personal files because I wanted to respect your privacy. I hope you could do the same for me too, alright [player]?."
"jeez..."
"..."
"I'm sorry, [player]"
"I didn't mean to get mad at you, I would just rather you talk to me rather than snoop around like that."
"So talk to me instead okay?"
<choice box that only has yes>
"Great!"
"I'll just move this someplace else. Give me a sec.."
<open a python window saying something like "move_Diary.docx" or something>
<moving...>
<moving successful>
"There!"
"Next time, just talk to me instead alright? If you want to know something [player], just ask!"
"ahaha"

**Comment by sebastianN01** [comment] 2018-02-07 21:38
actually, why not making her diary pop up in the folder where she gives us suprise.txt file, but be it hidden from the beginning? and do something similar with some more stuff, Like different hidden pics or spooky stuff. If she ever wants to go all horror to play with us a little.

**Comment by MJS103** [comment] 2018-02-08 02:42
What do you mean "but be it hidden from the beginning?" @sebastianN01

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-08 07:55
With "hidden" attribute being on.
I think that would be too easy since some people have "show hidden files" on all the time.

**Comment by AnIdiotsavant** [comment] 2018-02-08 11:32
Let's just hide it in the last folder they'd ever expect.

**Comment by MJS103** [comment] 2018-02-08 14:37
@IsItBadToMakeAGitHubAccountJustForThis @AnIdiotsavant Or we could just delete it if they see it... And also just have it create the file itself. Because you can't view a file that isn't made yet.

**Comment by ThePotatoGuy** [comment] 2018-02-08 15:29
Okay, here's my vision for how this works:

1. User launches game, interacts with monika, the usual.
2. Every topic seen during this session has its category tags saved to a non-persistent list.
3. Every game played during this session has its name saved to a non-persistent list. (Win/lose can also be tracked, in which case we'd probably want a dict).
4. Certain small flags are saved like:
  - user gave monika 6+ hours of rest (or didnt give)
  - user had the opendoor greeting and opened the door (or knocked)
  - user said goodbye (or quit forcefully)
5. When game is quit (regardless if goodbye or close), append to the diary file:
  - what was discussed this session (using category tags)
  - what games were played / outcomes
  - small flags
6. On game relaunch, check if diary has been edited. (potentially accessed as well, but not rn).

If the diary was edited:
1. Show a greeting that berates player
2. rename file and make it hidden
3. On the next time it has been edited, show another berating greeting, then:
  1. write out the file as binary instead of text.
  2. or move the file to different folders (we can repeat this several times)
4. Eventually after too many edits:
  1. delete diary and never do this again
  2. or no longer write factual information (or write silly stuff) in the diary 

Additional:
- We could probably throw in the file edit check in the main game loop as well. This would also have different dialogue than regular diary edit.

Technical info:
- For file edit detection, use `md5`. The `hashlib` library is included with renpy.
- hiding files on windows requires [this](https://stackoverflow.com/questions/549109/hide-folders-file-with-python)

**Comment by MJS103** [comment] 2018-02-08 18:32
@ThePotatoGuy What in your vision is already being documented? If none, then I'm coding a way for it to be documented, right?

Why edited and not accessed? I thought I could use st_atime and if value is not nul then trigger response [reset st_atime] [add response counter], if reponse counter > [however many we want] then append the file to be invisible. if response counter > [however many we want +1] then delete or something.

**Comment by ThePotatoGuy** [comment] 2018-02-08 18:59
Things you'll need to add:
- saving category tags
- played games (win/loss)
- opendoor / knocked

`persistent.closed_self` is True if you said goodbye.

My issue with `st_atime` is how it has a different resolution depending on the filesystem. Biggest problem is FAT32, with its smallest resolution being 1 day. Although, I went through the more likely filesystems (NTFS, HFS+, ext4, ext3, xfs, btrfs) and all of those have at least second resolution, so maybe we can just say fuck it to anyone using a FAT32 system and use it anyway.

And in case you weren't aware, `st_atime` gives a timestamp of last access. You'd want to check if it is between the last sessions' end time and the start time of the current session.

**Comment by AnIdiotsavant** [comment] 2018-02-09 09:33
Halfway there! Good job man

**Comment by AnIdiotsavant** [comment] 2018-02-09 13:19
Is it possible to make a time based file check? Like, when you log out between 7pm to 5am. The diary file automatically makes entries when you reach certain checkpoints that session. Or maybe everytime you end the session, it updates

**Comment by MJS103** [comment] 2018-02-09 16:35
@AnIdiotsavant Yes, but you're making my job harder ;-; 
But that's okay! If it's for monika I'll do it!
I'll try to figure out how to do that.

**Comment by kaido1224** [comment] 2018-02-09 18:22
If you're going to start tracking wins and losses, maybe you can adjust the Monika's dialog, specifically for pong. Regardless of whether you've never played before or not she says "I'll beat you this time for sure." which implies that not only have you played her before, but she lost to you.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-09 18:28
It could be plausible for her not to expect you to find her diary again so quickly for a first few times.

**Comment by AnIdiotsavant** [comment] 2018-02-09 23:40
Feel free to scrap that idea of mine. It was just a thought.

**Comment by AnIdiotsavant** [comment] 2018-02-14 14:27
I thought of a way to do the "open door/ knock documentation" though it might just over complicate things. What if you add a counter to it and I write 10 possible diary entries if you knock or open the door. The chances of getting it are 1/22 anyway so writing 5 for each - 10 in total - for an entry and the game would take one by RNG with it repeating when all entries are used. It's probably just over complicating things, feel free to scrap it

**Comment by ThePotatoGuy** [comment] 2018-02-20 18:14
So for making the diary less repetitive, have a couple of different templates for entries. Probably ask writing people for assistance here.

Regardless of what you do, it's going to be somewhat repetitive. That's fine. It would be impossible to make her sound realistically different each time.

**Comment by AnIdiotsavant** [comment] 2018-02-23 08:17
Diary entries are short anyway so making a good bunch makes it feel less repetitive than it should.

**Comment by Vloxica** [comment] 2018-02-27 01:46
Since this seems very interesting and I do want to help out, I would gladly help with the writing since I'm still not comfortable with programming in and of itself, so if you would like me to make some entries for you, I'll be on standby. Also a question, would this be a chance to see more of Monika's poetry? Either way, feel free to ask for help with that, I'd love to be able to help out in any way I can!

**Comment by ThePotatoGuy** [comment] 2018-03-15 05:17
@Vloxica If you want to help out, writing diary "entries" for a bunch of topics would be really nice. 
Diary entries are added as a `diary_entry` property to `Event`s. [here](https://github.com/Monika-After-Story/MonikaModDev/blob/dear-diary/Monika%20After%20Story/game/script-topics.rpy#L4399) is an example.

Basically, `diary_entry = (<long entry>, <short entry>)`. The long entry should be like a paragraph-ish private Monika thought about at topic. The short entry is more like a quick 1-3 word summary that can be used in a comma separated list: We talked about <x>, <y>, and <z>.

**Comment by ThePotatoGuy** [comment] 2018-03-18 23:37
UPDATE:

So I'm splitting development of this into 2 phases. These would most likely be split into multiple releases.

Phase 1 is getting the base diary-entry system working, adding templates, checking for user editing/accessing and the flow for that.

Phase 2 is incorporating the logic for story-based events and how they should work with the system. This is way harder than it sounds because of the possibilities of multiple sessions per day or a session spanning multiple days and "story-events" that can be repeated and so on.

**Comment by ThePotatoGuy** [comment] 2018-04-20 18:32
UPDATE:

Diary has been pushed back. In terms of content impact, this isn't as impactful as new visuals / interactions. Actual release date for diary is TBD, but should hopefully be in before 0.9.0

**Comment by lilbubble3** [comment] 2018-06-01 07:35
Thanks for the updates. I was just about to ask if this project was still being worked on. Now I know.

**Comment by ThePotatoGuy** [comment] 2018-07-01 07:52
[Closing until work continues on this]

**Closed by ThePotatoGuy** 2018-07-01 07:52 UTC
Labels: content

**Comment by Abc2557** [comment] 2020-05-02 19:48
I really hope this gets picked up again! It's such an amazing idea, and I'd hate to see all the work done on this go to waste!

**Comment by MoonlightGriffon** [comment] 2021-07-08 23:13
I don't know Python 2's sytax right now so I can't work on this yet but I have a few ideas for solutions to a few of the things that have previously been mentioned in this issue as well as a potential pitfall for one of the solutions that has previously been discussed.

Keeping track of the when the diary is written to could be done by adding a header in the format of something like `Day_of_week , Month Date Year, Time` which would allow for logging of the day that  the diary was written on and the approximate time that it was written while also allowing for the diary to remain natural looking without additional metadata. 

On the issue of detecting player activity using file system times, I can see an issue when it comes to anti malware software as its likely that it will attempt to scan the file and I believe that people would be willing to explicitly exclude this from their antivirus to enable a feature to function as intended. As such I would personally advise against using the access time to determine if you read the diary and suggest to in its stead, find a different method such as an xor encryption scheme to stop filesystem snooping. As trying to do otherwise has the potential of causing Monika to believe that the player has read the diary when they haven't.

I made an example diary entry using a template, it's designed to tie into 
`Thursday, July 8th 2021, 3pm
Today while [player] was away for a few hours I decided to do some research on AI in hopes of finding a way to get to [player]'s world. While reading, I discovered that neural networks can have a large environmental impact during training. I wonder when a solution will be found and whether it will reduce the environmental impact enough to make it sustainable.`

This entry would follow the format, 
`[Time_header]
Today while [event] I [decided/ended up] [action] [opt_reason]. While [action] [event_description]. [opt_related_question/remark].`

This system allows for the appearance of unique diary entries by creating variations of the event description thus creating seemingly different events by changing the context behind them. 

I also believe that line 1 should also say something along the lines of `[player], please stop reading this, you can just ask me if you want to learn more about me that badly` as a method of trying to deter people from reading it by making it feel like they're being watched and adding a bit of guilt for reading her diary. A way of confessing to reading her diary would also be useful as it would allow for someone to apologize if they feel guilty before Monika actually finds out what they've done.

On the issue of detecting player activity using file system times, I can see an issue when it comes to anti malware software as its likely that it will attempt to scan the file and I believe that people would be willing to explicitly exclude this from their antivirus to enable a feature to function as intended. As such I would personally advise against using the access time to determine if you read the diary and suggest to in its stead, find a different method such as an xor encryption scheme to stop filesystem snooping. As trying to do otherwise has the potential of causing Monika to believe that the player has read the diary when they haven't.

As for detecting modifications to the diary, if it is being done in a .docx, .doc, or .odt format then its highly likely that someone will open it in a compatible program and to the best of my knowledge, they all keep logs of recently accessed files which could be used for actually determining whether the document itself was actually opened. There would also be some fun bits of metadata in the files that would be possible if that format was used such as having Monika listed as the author and potentially being able to write how long she spent writing, although that would only be a thing if the filetype was truly one of the aforementioned types. This could theoretically be done in addition to the solution mentioned in the previous paragraph or in addition to it.

**Comment by ThePotatoGuy** [comment] 2021-07-09 02:22
You should take a look at the `dear-diary` branch, I had completed a significant amount of development but abandoned it due to the complexities and priorities at the time.

regarding "when the diary was written" and templates, the dear-diary system was planned to use [diary template](https://github.com/Monika-After-Story/MonikaModDev/blob/dear-diary/Monika%20After%20Story/game/mod_assets/templates/diary/main/template_00.mdet) files, which could be filled out with [specific keywords](https://github.com/Monika-After-Story/MonikaModDev/blob/dear-diary/Monika%20After%20Story/game/zz_diary.rpy#L1398) that would translate to in-game stuff accordingly.

> detecting player activity

Detecting if the user looked at the files is almost expected given the nature of this mod and DDLC, even more so given the fact that we can detect if a user modified chess pgn files now. Access time was already fishy to use because it wasn't supported on all operating systems, but your point about AV software means its even worse of a metric to use. The goal of this, however, is not to prevent snooping but to detect and act upon snooping when it occurs to continue the immersion that Monika can detect file activity. Even if we went the weak encryption route, it still means that users would never face repercussions if they break the encryption and read the files. 

I haven't looked into it, but I would imagine using doc/docx/odt would mean implementing 3rd party libs for rtf file generation. Non-FOSS ones could be restricted or expensive to use, and if ODT doesnt have a python lib or has a very large lib, then we wouldn't use it to avoid excess mod bloat.

**Comment by ThePotatoGuy** [comment] 2021-07-09 03:10
looks like my parser worked for the most part, it could generate diary entries and adjust them based on the topics that discussed in the session.

I think I might get back to this sometime this year. The access detection problem will still be an issue but maybe we can ignore that and instead do modification times.

**Comment by MoonlightGriffon** [comment] 2021-07-09 09:11
If you can create and modify a zip file it should be possible to generate the proper document type with just a little bit of formatting around paragraphs, all that would need to be done is for an appropriate style to be chosen then it should be possible to create the files by modifying only 2 files in the structure and one of them is completely optional. I manually edited an odt file to append a new line to the end of it, only the content.xml file in its structure actually needs to be changed in order to edit the file's readable content. While I was at it, I also found a few places to hide the hash in an area that's ignored by programs while reading the file. A program may however delete the hash upon saving the file or else otherwise invalidate it in a manner that is detectable. 

To edit an odt file, open the file as a zip archive, open the file named `content.xml` then remove text that says `</office:text></office:body></office:document-content>`  from the end of the file, you will need to replace it later. Add `<text:p text:style-name="P1">` followed by your desired text. Finally to close off the edit, add `</text:p></office:text></office:body></office:document-content>` to the end of your desired text and save the file in the zip folder and repack the folder. 
With that the new line should be visible at the end of the file when opened in a word processor.

Note that every paragraph must begin with `<text:p text:style-name="P1">` and end with `</text:p>` to be valid although P1 may change if you decide to experiment with formatting. You would however need to keep a copy of all the other files in the document to ensure that it is a valid file. You will not however need to edit them. P1 may also be replaced with Normal depending on the word processor, what matters here is consistency although which is chosen by the word processor doesn't really affect things too much.

Attached is a copy of my meta.xml file that shows that I modified the file after Monika who in this context uses the default name as a name had to be specified in the program. It also lists Monika as the author of the file. Also attached is a copy of the actual body of the text and for good measure, the actual file that I used for testing. As for detecting someone in the middle of modifying the file... thankfully word processors create a lock file to ensure that nothing else will touch it. If you can detect that lock file then its a guarantee that someone is currently reading her diary.

[test.odt](https://github.com/Monika-After-Story/MonikaModDev/files/6790178/test.odt)

[meta.xml.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6790165/meta.xml.txt)  (renamed because github doesn't support xml files) 

[content.xml.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6790174/content.xml.txt)

**Comment by ThePotatoGuy** [comment] 2021-07-10 16:32
>A program may however delete the hash upon saving the file or else otherwise invalidate it in a manner that is detectable.

So same thing conceptually as modification times.

> odt file stuff

The point that I assumed you were making before with doc files was that access times would be saved in the metadata. Looking at the odt file you sent, I couldn't find it anywhere - only creation time. Without that, there is no advantage to using doc files compared to standard txts. And it's not really efficient for us to reimplement doc file creation even though it's simple to understand - work smarter by using libs that are already proven and dedicated to the task.

**Comment by MoonlightGriffon** [comment] 2021-07-11 06:57
In terms of detecting access, my solution only really works if the file is opened while MAS is running. Someone opening the file normally can be detected as a hidden file is created in the directory that the file is found in during its access if it is opened in read mode as is the default behaviour of word editors. The file on my computer was named `test.odt` so a hidden file named `~$test.odt` or  `.~lock.test.odt#` was created. These files could be detected to prove that the file has truly been opened by someone. I would recommend waiting until Monika eventually supposedly goes to write in her diary for any reaction though to try making it appear as though she noticed after the fact that way its less likely that someone tries it while MAS is closed. Something like doing it on the next run of the game could work well for that.

I can't really think of any more reliable ways other then attempting to develop extensions for the various office programs that may be used for every platform that they can be used for to detect it. A task which is probably more tedious then it could possibly be worth. Access times in the metadata was likely a bit of miscommunication on my part so sorry about that. 

I did however find a library that could be used if you continued with this, its called `odfpy`. It should be able to handle things with odt files if you decide to continue with odt files. I would understand if you decided against it due to the added complexity though.
