### ISSUE TITLE
[Suggestion] - Music list loop?

### ISSUE THREAD

**Issue by wzdlc1996** [Monika-After-Story/MonikaModDev#5299] opened 2020-02-05 16:51 UTC
Now Monika's custom music can only loop itself. Can there be a function for music list management and loop for a list? Just like how those common music players do.

**Comment by AsuraShun** [comment] 2020-02-05 16:53
Maybe even have her be able to switch music on her own

**Comment by ThePotatoGuy** [comment] 2020-02-23 22:50
duplicate of #2088

**Comment by ThePotatoGuy** [comment] 2020-02-23 22:50
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-02-23 22:50 UTC
Labels: duplicate
