### ISSUE TITLE
[Bug] - Monika after story

### ISSUE THREAD

**Issue by AngelsBeee** [Monika-After-Story/MonikaModDev#8985] opened 2022-03-18 05:46 UTC
There is something wrong with Monika's calendar. When I took a look at it, it said that march had autumn in it and September had spring. And all the other months have the wrong seasons. So if you know how to fix it please tell me on my discord.
TYYYY

**Comment by NontInGithub** [comment] 2022-03-18 05:49
when she ask you which hemisphere you live in, did you answer south hemisphere?

**Comment by BrandiBlitz** [comment] 2022-05-01 01:35
I stumbled upon a bug myself. there is a chance that the game’s log files may bug out and “reset” to the start of MAS. I just immediately “alt F4”/task manager force closed the game and open it again. My Monika was saved.

However, there is a chance that someone else's Monika may not be so lucky. Please look into this.

**Comment by Booplicate** [comment] 2022-05-01 17:47
The logs don't "reset," it's called log rotation and is done on purpose. You don't have to force close the game...

**Comment by BrandiBlitz** [comment] 2022-05-01 18:47
> The logs don't "reset," it's called log rotation and is done on purpose. You don't have to force close the game...

That's not what I'm talking about. I had a huge scare when I opened my MAS mod. Monika was reset to the very start of MAS. I had to force close the game and open it again. It wasn't permanent (very lucky), but it seriously needs to be investigated.

**Comment by Booplicate** [comment] 2022-05-01 18:48
If she indeed was reset, closing and opening it again wouldn't fix that.

**Comment by BrandiBlitz** [comment] 2022-05-01 19:14
> If she indeed was reset, closing and opening it again wouldn't fix that.

it did for me, but someone else might not be so lucky

**Comment by Booplicate** [comment] 2022-05-01 19:51
No, that's not how it works. If you lose your data, a restart won't magically put it back.

She probably tried to joke about being reset and you thought it's real and closed the game which triggered a new greeting next time.

**Comment by kkrosie123** [comment] 2022-05-01 19:56
Whoops, added that thinking the log rotation/prank greeting was what was being reported.

**Comment by kkrosie123** [comment] 2022-05-01 19:58
Actually, this being reported isn't a bug anyways. Adding the tag back.

**Comment by ThePotatoGuy** [comment] 2022-05-21 18:02
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-05-21 18:02 UTC
Labels: not a bug
