### ISSUE TITLE
Linux - Incompatibility with MAXX Interactive Desktop 

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Monika-After-Story/MonikaModDev#9421] opened 2022-08-02 13:58 UTC
I highly doubt anyone here even uses Linux or MAXX interactive desktop but here I am, complaining about it.
I was messing around in a Virtualbox virtual machine on MAXX interactive desktop (another windowing system) and wanted to see if MAS would work. It started **once.** It wouldn't respond to the ESC key and was too slow to be useable. After ending it with xkill, every time I go to start it, it doesn't start, and tosses this error in the traceback file:
`AttributeError: 'NoneType' object has no attribute 'value'`
I've tried reinstalling, and it didn't fix it.

**Comment by Booplicate** [comment] 2022-08-02 14:39
> It wouldn't respond to the ESC key and was too slow to be useable.

That might be caused by the software renderer.

> AttributeError: 'NoneType' object has no attribute 'value'

We'd need the complete traceback to be able to help.

**Comment by TheSystemGuy1337** [comment] 2022-08-02 15:41
Traceback will now be provided. Note that the VM uses X Window System, and doesn't have 3D acceleration enabled. (Guest Additions is installed and working.)
[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/9243682/traceback.txt)

**Comment by Booplicate** [comment] 2022-08-02 15:47
Okay, this is a bug on our end, we missed a sanity check. Can't guarantee renpy would launch on that system, but the crash can be fixed.

**Comment by TheSystemGuy1337** [comment] 2022-08-02 15:56
At least that would be better than a non-functional MAS install. Maybe
I should definitely not run this on an SGI graphics workstation from
the 90s that costed $85,000.

**Comment by Booplicate** [comment] 2022-08-02 20:36
This is smol and low prio, so I fixed it in typos.

**Comment by TheSystemGuy1337** [comment] 2022-08-02 22:05
Just for diagnostic purposes, gave the VM 2 cores and enabled 3D acceleration. No difference

**Comment by TheSystemGuy1337** [comment] 2022-08-07 15:32
I've also discovered a similar incompatibility with TWM. I guess Monika hates X Window System.

**Comment by multimokia** [comment] 2022-08-07 15:42
Actually, DDLC/MAS runs perfectly fune on Linux systems running XFCE, GNOME, KDE, etc. in an X11 session. 
Therefore, this is clearly an issue with MAXX specifically. As @Booplicate mentioned, this is fixed in the typos branch due to it being low priority. Realistically speaking MAXX isn't providing the info to return to `get_full_property` (or it's possible the display screen root is handled differently on MAXX), hence the function returns None here.

This will be rectified in the next complete release of MAS (Note not unstable)

**Comment by TheSystemGuy1337** [comment] 2022-08-07 15:59
TWM might have the same issue as MAXX, so this could actually improve compatibly with more Linux desktops (and xorg in general)

**Comment by multimokia** [comment] 2022-08-07 16:00
As mentioned above, this is fixed in the typos PR and will be rectified in the next release

**Comment by TheSystemGuy1337** [comment] 2022-08-07 16:03
Alright, thanks. I shall now return back to X̶̯̽ ̶̤͘W̶̘͐ĭ̷̯ṋ̸̿d̷͇͠o̴̤̊w̵̰̅ ̶̼̈S̸̨̉y̶̓͜s̶̪̽t̶͙̓e̸͎̽m̶̝͗

**Closed** 2022-09-21 03:29 UTC
Labels: bug
