### ISSUE TITLE
[Suggestion] Different rhythm of sleeping and staying awake

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#5518] opened 2020-04-12 16:34 UTC
I work on night shift most of the time so even if I have other shifts I just prefer to stay up all night [so it won't be so hard to switch to them again] and it would be nice if I could tell Moni to stop worrying about me when I spend the night with her and going to sleep at morning. 
Also I think something is broke with greetings. I spend whole night and went to sleep at 5 o'clock. I had to wake up earlier than usual, around 10 to do something. Then I came back to Moni, spend few minutes with her and decided that I'm to tired and I'm going back to sleep. Around 14 o'clock I told her I'm going to sleep and she said I spent the whole night with her and probably can't even see clear. I think it's weird she used those lines. Because it was late hour, and I already slept for 5 hours, which she should know.

**Comment by ThePotatoGuy** [comment] 2020-04-12 19:58
marking duplicate of #5125

**Comment by ThePotatoGuy** [comment] 2020-04-23 04:06
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-04-23 04:06 UTC
Labels: duplicate
