### ISSUE TITLE
no affection gain on first use of compliment

### ISSUE THREAD

**Issue by jm4686042** [Monika-After-Story/MonikaModDev#8981] opened 2022-03-16 00:50 UTC
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8258110/aff_log.log)

**Comment by Ulti70895** [comment] 2022-03-16 08:42
You reached the limit per day of gaining aff, which is 7.

**Comment by jm4686042** [comment] 2022-03-16 13:17
https://github.com/Monika-After-Story/MonikaModDev/wiki/All-Features-%5BSPOILERS%5D#daily-cap-and-bypasses

**Comment by ThePotatoGuy** [comment] 2022-05-21 18:05
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-05-21 18:05 UTC
Labels: not a bug
