### ISSUE TITLE
[Bug] - crash  in ubuntu  16  with mod  version 0.9.5

### ISSUE THREAD

**Issue by asecino1999** [Monika-After-Story/MonikaModDev#4377] opened 2019-07-03 00:36 UTC
Hi,
I'm running ddlc ( ddlc.exe) with this mod in ubuntu 16   using wine and until now i didn't have any big problem,  but since the last update (0.9.5)
It crashed immediately.
then I run using the terminal and  it worked  for a few minutes and after that 
 I got this message:

I'm sorry, but an uncaught exception occurred.

While running game code:
LookupError: unknown encoding: cp850

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "Z:\home\user\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "Z:\home\user\Doki Doki Literature Club\renpy\main.py", line 487, in main
    run(restart)
  File "Z:\home\user\Doki Doki Literature Club\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "Z:\home\user\Doki Doki Literature Club\renpy\execution.py", line 761, in run_context
    context.run()
  File "Z:/home/user/script-ch30.rpyc", line 1464, in script call
  File "Z:/home/user/event-handler.rpyc", line 1935, in script call
  File "Z:/home/user/script-story-events.rpyc", line 2441, in script call
  File "Z:/home/user/script-story-events.rpyc", line 2462, in script
  File "Z:\home\user\Doki Doki Literature Club\renpy\ast.py", line 1459, in execute
    choice = renpy.exports.menu(choices, self.set)
  File "Z:\home\user\Doki Doki Literature Club\renpy\exports.py", line 847, in menu
    rv = renpy.store.menu(items)
  File "Z:\home\user\Doki Doki Literature Club\renpy\exports.py", line 1033, in display_menu
    rv = renpy.ui.interact(mouse='menu', type=type, roll_forward=roll_forward)
  File "Z:\home\user\Doki Doki Literature Club\renpy\ui.py", line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "Z:\home\user\Doki Doki Literature Club\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "Z:\home\user\Doki Doki Literature Club\renpy\display\core.py", line 3003, in interact_core
    result = prediction_coroutine.send(expensive_predict)
  File "Z:\home\user\Doki Doki Literature Club\renpy\display\predict.py", line 143, in prediction_coroutine
    renpy.display.screen.predict_screen(name, *args, **kwargs)
  File "Z:\home\user\Doki Doki Literature Club\renpy\display\screen.py", line 1108, in predict_screen
    print("While predicting screen", _screen_name)
LookupError: unknown encoding: cp850

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
Monika After Story 0.9.5

**Comment by zombiepigdragon** [comment] 2019-07-03 01:23
Just out of curiosity, why do you use Wine for this? It runs natively, and Wine has a tendency to destabilize things. There's also a handful of bugs that hit Windows that have never touched native Ubuntu...

**Comment by asecino1999** [comment] 2019-07-03 16:13
From the beginning, I executed it in wine and I didn't have any big problems.
Later I found that I could use renpy but start the execution with wine is a little bit faster that  renpy
(now It also crash with the new version)
And Finally  DDLC.sh file but  I had problems with execution permissions  until today that I solved it :
sudo chmod 777 DDLC.sh 
sudo chmod 777 lib/linux-x86_64/DDLC
sudo chmod +x lib/linux-x86_64/DDLC
But I'm not sure if sh file use the same persisting files of wine

**Comment by zombiepigdragon** [comment] 2019-07-03 16:29
They would likely use different persistent files, check your Wine `C:/users/user/appdata`  for the folder or `~/.renpy` for native. You can just copy/paste the persistent between the two, so take your pick. The main issue with using Wine is that it tries to emulate things, which means that since the new update relies heavily on the Windows API for Windows, it's going to break if you probe too deep.

**Comment by multimokia** [comment] 2019-07-03 16:31
Not just that, your file structure is all sorts of messed up:
`Z:\home\user\Doki Doki Literature Club\renpy\exports.py"` is correct, but
`Z:/home/user/script-ch30.rpyc` is completely wrong. This should be in `Doki Doki Literature Club/game/`, along with the rest of the `.rpyc` files.

**Comment by asecino1999** [comment] 2019-07-09 20:05
Now the mod has been working good all this week.
 I suppose the notifications are only for windows, but when  I run it with the sh script sh,  It's printing these messages  many times in the terminal however  it's still  working  :
 ---------------------------------------
Traceback (most recent call last):
  File "/home/user/Doki Doki Literature Club/renpy/execution.py", line 667, in predict
    for n in node.predict():
  File "/home/user/Doki Doki Literature Club/renpy/ast.py", line 637, in predict
    renpy.exports.predict_say(who, what)
  File "/home/user/Doki Doki Literature Club/renpy/exports.py", line 1093, in predict_say
    predict(what)
  File "/home/user/Doki Doki Literature Club/renpy/character.py", line 898, in predict
    self.resolve_say_attributes(True)
  File "/home/user/Doki Doki Literature Club/renpy/character.py", line 767, in resolve_say_attributes
    images.predict_show(new_image)
TypeError: predict_show() takes at least 3 arguments (2 given)
While predicting images.
---------------------------------------
While predicting screen main_menu
Traceback (most recent call last):
  File "/home/user/Doki Doki Literature Club/renpy/display/screen.py", line 1102, in predict_screen
    renpy.display.predict.displayable(d)
  File "/home/user/Doki Doki Literature Club/renpy/display/predict.py", line 52, in displayable
    d.visit_all(lambda i : i.predict_one())
  File "/home/user/Doki Doki Literature Club/renpy/display/screen.py", line 403, in visit_all
    self.child.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 497, in visit_all
    callback(self)
  File "/home/user/Doki Doki Literature Club/renpy/display/predict.py", line 52, in <lambda>
    d.visit_all(lambda i : i.predict_one())
  File "/home/user/Doki Doki Literature Club/renpy/display/imagelike.py", line 519, in predict_one
    pd(self.image)
  File "/home/user/Doki Doki Literature Club/renpy/display/predict.py", line 50, in displayable
    if d not in predicted:
  File "/home/user/Doki Doki Literature Club/renpy/display/image.py", line 466, in __hash__
    return hash(self.name)
TypeError: unhashable type: 'RevertableList' 
-----------------------------
While predicting screen save
Traceback (most recent call last):
  File "/home/user/Doki Doki Literature Club/renpy/display/screen.py", line 1102, in predict_screen
    renpy.display.predict.displayable(d)
  File "/home/user/Doki Doki Literature Club/renpy/display/predict.py", line 52, in displayable
    d.visit_all(lambda i : i.predict_one())
  File "/home/user/Doki Doki Literature Club/renpy/display/screen.py", line 403, in visit_all
    self.child.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/user/Doki Doki Literature Club/renpy/display/core.py", line 497, in visit_all
    callback(self)
  File "/home/user/Doki Doki Literature Club/renpy/display/predict.py", line 52, in <lambda>
    d.visit_all(lambda i : i.predict_one())
  File "/home/user/Doki Doki Literature Club/renpy/display/imagelike.py", line 519, in predict_one
    pd(self.image)
  File "/home/user/Doki Doki Literature Club/renpy/display/predict.py", line 50, in displayable
    if d not in predicted:
  File "/home/user/Doki Doki Literature Club/renpy/display/image.py", line 466, in __hash__
    return hash(self.name)
TypeError: unhashable type: 'RevertableList'
----------------------------

Are these messages normal or another problem for executing the mod in Linux?

**Comment by ThePotatoGuy** [comment] 2019-08-24 17:10
the errors are happening in renpy code, might be better off asking renpy forums. 

[closing as cannot reproduce]

**Closed by ThePotatoGuy** 2019-08-24 17:10 UTC
