### ISSUE TITLE
Monika doens't react at some gifts

### ISSUE THREAD

**Issue by DarknoITA** [Monika-After-Story/MonikaModDev#8383] opened 2021-12-10 23:34 UTC
Monika doens't react anymore at some gifts, like promisering, coffee and cupcake, and yes the file is a gift file, and yes i respected all the requisite for the promise ring (500+ affect), so i don't know, try to help me if you can, good evening/day.

**Comment by Batcastle** [comment] 2021-12-13 06:57
I'm seeing the same issue. Made sure to add spritepacks, restart, and add *.gift files. Seeing no errors in logs, gift files get deleted, but the gifts do not appear in the appropriate menus for changing Monika's outfit and Monika has no reaction. Seen on both stable and unstable branches.

**Comment by Arodi-Pie** [comment] 2021-12-13 21:21
Same issue here... may be the new update...?

**Comment by Batcastle** [comment] 2021-12-13 21:49
So I did a little digging...

As I am sure most of the devs know, The changes likely happened in the file `Monika After Story/game/zz_reactions.rpy`
It looks like the most likely place for that breakage is somewhere between lines 260 and 280. My theory is that since this code block on lines 269 and 270:
```python
if gift_cntrs is not None:
    gen_labels.append(gift_cntrs.quip()[1])
```
Is no longer in a for loop, reactions are not being cued up as they should and so Monika ignores the gifts and just deletes the files.

Not sure though cause I have little experience with this code base. Just a hunch from an (somewhat) outside observer.

**Comment by Batcastle** [comment] 2021-12-13 22:21
Also, more info:

Monika just responded to a cupcake gift. She isn't responding to things like clothes and ACS tho.

**Comment by Booplicate** [comment] 2021-12-13 22:31
Did you check under the tree?

**Comment by multimokia** [comment] 2021-12-13 22:31
Those will end up under the tree. Consumables and such will not as they wouldn't make sense. As for the OP here, is the reacting at all? Like are files being deleted? Or are they still in the characters folder?

**Comment by Batcastle** [comment] 2021-12-13 22:38
If they will be held under the tree until Christmas day, then can we get something from Monika at least acknowledging that she was given a present and will wait to open it? That way we're not worried about a bug?

**Comment by ThePotatoGuy** [comment] 2021-12-13 22:54
> can we get something from Monika at least acknowledging that she was given a present and will wait to open it?

Yes, we should. See #6783.

**Comment by ThePotatoGuy** [comment] 2021-12-13 22:54
>Also, is there something to handle if we gift something multiple times by accident in case of this misunderstanding?

This is handled with the current behavior of silently deleting extra gifts.

**Comment by ThePotatoGuy** [comment] 2021-12-19 19:14
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-19 19:14 UTC
Labels: not a bug
