### ISSUE TITLE
Monika first kiss bug

### ISSUE THREAD

**Issue by AnIdiotsavant** [Monika-After-Story/MonikaModDev#5517] opened 2020-04-12 16:34 UTC
Monika was talking bout if I think about our first kiss and I misclicked to say I didnt... It feels really bad and I tried to fix it but I cant find the topic. Is it bugged that it wont appear?... the disappointment in her face was enough to make me cry...

**Comment by multimokia** [comment] 2020-04-12 16:35
I'm afraid the topic is a one-time only thing. There's no way to revisit it.

**Comment by ThePotatoGuy** [comment] 2020-04-23 04:06
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-04-23 04:06 UTC
Labels: not a bug
