### ISSUE TITLE
[Renpy Error] "Possible Infinite Loop"

### ISSUE THREAD

**Issue by XolfWolf** [Monika-After-Story/MonikaModDev#1321] opened 2018-03-25 05:37 UTC
I was playing the piano and when I wanted to get back to talk with Monika, **Renpy** throws me this error.

![image](https://user-images.githubusercontent.com/36345725/37872031-b8ddf848-2fc3-11e8-922e-fe01ae161bd0.png)

I click "_Quit_" because if I clicked "_Ignore_" it says that maybe it will lead to others errors.

That's all.

**Comment by ThePotatoGuy** [comment] 2018-03-25 07:06
What were your steps exactly?

**Comment by XolfWolf** [comment] 2018-03-26 01:12
@ThePotatoGuy 
I clicked the _Play_ button then I selected the _piano_, after some minutes, I "exit" because I wanted to see if Monika have new **unseen** text, so I exit the _piano_, then the game "freeze" a bit and finally **Renpy** throws me that error.
When this happened I just take a quick screenshot, post it here as an issue and close the game.

_**Note:**_ Today, _Monika_ didn't have new **unseen** text, this is weird because She always have at least one new **unseen** text. I don't know if is because the error or because there are no more new text to load for now.

**Comment by ThePotatoGuy** [comment] 2018-03-27 04:03
Can you upload your `persistent` file here? [here](https://github.com/Monika-After-Story/MonikaModDev/blob/master/docs/windows-howtopersist.pdf) is a guide.

**Comment by XolfWolf** [comment] 2018-03-27 21:25
@ThePotatoGuy 
Here it is:
**[persistent file.zip](https://github.com/Monika-After-Story/MonikaModDev/files/1853854/persistent.file.zip)**

BTW about the note, it seems Monika doesn't have more new **unseen** text, is this normal?

**Comment by ThePotatoGuy** [comment] 2018-04-05 04:59
I'm not 100% on the cause here, so im going to leave this issue open in case other people get it too.

**Comment by kaido1224** [comment] 2018-05-02 16:16
It's been 27 days and no one else has gotten the issue. I think it's safe to close it. We can always reference it on any other tickets that are opened.

**Closed by kaido1224** 2018-05-02 16:16 UTC
Labels: investigating
