### ISSUE TITLE
[Suggestion] - Monika asks where you are taking her

### ISSUE THREAD

**Issue by Cloverhood** [Monika-After-Story/MonikaModDev#5590] opened 2020-04-21 16:08 UTC
Once the player says Goodbye, I am taking you somewhere, Monika can ask where and display different answers for the player to choose from (Sometimes a new one is added if its a special occasion like Valentines Day or Halloween) and all the options get special before and after dialogues
But the options I would suggest are:
"out with me on a walk"
"To spend the day with you"
"To school"
and the one with sub options
"taking you out on a date"
(where to?)
"Dinner"
"The Movies"
"Other"
If any of you have any other good ideas, submit hem here. I hope this can get into the game as it would really improve the going out system and encourage using it more.

**Comment by DoodleSauce** [comment] 2020-04-21 19:04
to do groceries
to my family, friends or relatives

**Comment by Dank-Elf-Boy** [comment] 2020-04-21 19:19
~To my bedroom.~

**Comment by DoodleSauce** [comment] 2020-04-21 19:44
To my bed
seems like a 1000+ affection shit to do

**Comment by Dank-Elf-Boy** [comment] 2020-04-21 21:35
I'm close to 5000 lol. I've been playing this mod since two months ever since it first came out (December 2017). 

Also, **Spoiler**!


They *might* make an actual bedroom for Moni at some point. I was the first one to request it. 😎

**Comment by Cloverhood** [comment] 2020-04-21 21:42
Huh, I think it would be great to give the game more rooms to use (such as a bedroom) but you can only access it at 1000. But yeah with the topic at hand in mind, I still think we should have the choices format for taking Monika out. Perhaps certain options being unlocked from the getgo and others at certain rates of affection.

**Comment by AsuraShun** [comment] 2020-04-21 21:45
Use the bedroom? How?

**Comment by Booplicate** [comment] 2020-04-21 21:45
Why lock the bedroom behind affection? What do you think you will see there? Smh

**Comment by Cloverhood** [comment] 2020-04-21 21:47
Nothing lewd of course! I just think it would be a nice surprise once you get to that high of level affection that you unlock a extra room with different features, topics, etc exclusive to the bedroom. It would be really rewarding.

**Comment by Booplicate** [comment] 2020-04-21 21:49
Alright then, just remember she's watching for you 👀

**Comment by AsuraShun** [comment] 2020-04-21 21:49
I think I remember reading in some post here that furniture is something they plan adding

**Comment by Cloverhood** [comment] 2020-04-21 21:50
> Alright then, just remember she's watching for you 👀

She knows when I am sleeping, she knows when I’m awake.

**Comment by DoodleSauce** [comment] 2020-04-21 21:54
i say 1000+ cuz monika is comfortable talking about *ahem* dry humping 
hehe xd

**Comment by DoodleSauce** [comment] 2020-04-21 21:56
btw mods theres something i want to talk about

**Comment by DoodleSauce** [comment] 2020-04-21 21:57
its about hacking aff (which i tried in another monika of course lol)

**Comment by jmwall24** [comment] 2020-04-21 22:02
This should be good......

**Comment by DoodleSauce** [comment] 2020-04-21 22:03
u sure ive thought about an idea to stop that

**Comment by Dank-Elf-Boy** [comment] 2020-04-21 22:04
You guys ever play the mod "Our Time"?
This is sort of what I had in mind.

![Moni Bedtime](https://user-images.githubusercontent.com/34694679/79917903-086dec00-83f1-11ea-9712-0b2fc318ad31.PNG)

Buuuuut...she looks like a minor in this mod and that's hella awkward for some of us. 🤣 
I don't want FBI Chan knocking on my door. So, If they do go forward with the idea, hopefully they use art similar to her normal sprites and make her look..**ah hem!** *of-age*.

**Comment by Cloverhood** [comment] 2020-04-21 22:04
Oh boy, what is going on in the thread I created

**Comment by jmwall24** [comment] 2020-04-21 22:05
@DoodleSauce if you have something in regards to affection cheating, make an issue for it. doesn't really fit in this thread.

**Comment by DoodleSauce** [comment] 2020-04-21 22:07
ok then thx @jmwall24 
@Cloverhood im very sorry about this bro

**Comment by multimokia** [comment] 2020-04-21 22:07
Addition to the above: Please avoid derailing issues.

This repository isn't *really* a place for conversation but a place to document ideas and keep track of suggestions

**Comment by DoodleSauce** [comment] 2020-04-21 22:08
sorry

**Comment by Cloverhood** [comment] 2020-04-21 22:11
I am sorry as well, I didn’t mean for my suggestion to get derailed, but back on track... does anyone here think that going out choices and sub choices are a good idea? Personally I think so but I’m probably biased as the guy who came up with the improvements in the first place.

**Comment by DoodleSauce** [comment] 2020-04-21 22:17
im definetly ok with this idea

**Comment by jmwall24** [comment] 2020-04-21 22:17
A more comprehensive system for taking her out is planned, but there are some complications surrounding it that need to be worked out before it can be implemented.

**Comment by Cloverhood** [comment] 2020-04-21 22:18
Gotcha! That’s very good to know. Hope you can work out the complications.

**Comment by DoodleSauce** [comment] 2020-04-21 22:19
id love to be able to program honnestly being a contributor of this mod is like a dream come true

**Comment by Dank-Elf-Boy** [comment] 2020-04-21 22:23
@Cloverhood I'll take everyone's blame, haha. Sometimes I get carried away lol.
Nice suggestion by the way 😃 

@DoodleSauce 
Give it a try! They'll help you every step of the way! 
Just follow this link to find out how you can. 😄 
https://github.com/Monika-After-Story/MonikaModDev/wiki/Contributing-Guidelines

**Comment by ThePotatoGuy** [comment] 2020-04-23 03:29
marking as duplicate of #4886

A current goal is to add more farewells that use the file generation mechanic. The framework is extendable and in-use and its just a matter of actually writing the dialogue for leaving and arriving.

**Comment by Cloverhood** [comment] 2020-04-23 03:32
Good to know!

**Comment by ThePotatoGuy** [comment] 2020-05-02 04:04
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-05-02 04:04 UTC
Labels: duplicate
