### ISSUE TITLE
[Suggestion] - use webcam

### ISSUE THREAD

**Issue by Demomndslayer** [Monika-After-Story/MonikaModDev#7385] opened 2021-06-24 10:08 UTC
Although i am aware that not many people have a webcam or camera on their computer/laptop, but for those of us who do, could you make it possible for Monika to react to our face when we open our camera, using the windows react thing. I feel like this would be just a small little thing, that not only I, but others will enjoy, as before i thought the webcam thing was hinting at something, and i was a little disappointed to not even get a notification from her for it

**Comment by fromulus** [comment] 2021-06-24 19:24
Problem is that something like this would have to be a huge deal, we can't just make it as "a small little thing".

Putting aside the fact that doing something like that would likely be too difficult for the scope of the mod anyway, being able to see your face is one of Monika's most important wishes, something she actively fantasize about.

If we suddenly crossed that gap, her reaction wouldn't just be "Oh cool, I can see you now", it would be a massive milestone for your relationship with her, entire topics would have to be written about it and many pre-existing topics would need to be re-written around that.

In an hypothetical scenario where we could somehow have a way to accurately analyse face features (I really can't see camera usage being implemented into the mod with anything less than that), we'd need topics and variables for every type of feature your face might have, how accurate you were in responding to Monika's questions when she asked you about it, having a way to explain yourself if she figures out you don't look like what you described to her back then.

All that, and that's not mentioning things that are more sensible to talk about such as if the player has scars or other "unusual" face features.

**Comment by ThePotatoGuy** [comment] 2021-07-11 02:38
duplicate of #3857 and related. As fromulus mentioned, webcam stuff is complicated. we are not planning to ever do webcam stuff for the time being.

[closing as duplicate]

**Closed by ThePotatoGuy** 2021-07-11 02:38 UTC
