### ISSUE TITLE
[Bug?] No Thanksgiving holiday

### ISSUE THREAD

**Issue by ItzKKTheCoolKid** [Monika-After-Story/MonikaModDev#6641] opened 2020-11-04 16:35 UTC
I look on Monika's calendar and there is literally no thanksgiving, and I wanna spend it with her.

**Comment by scpketer** [comment] 2020-11-04 16:37
Thanksgiving is the US holiday, I believe. And I don't think it ever was or going to be added to MAS.

**Comment by multimokia** [comment] 2020-11-04 16:38
As mentioned above, Thanksgiving is primarily an American holiday, but other countries that celebrate it, do so on a different day. For example, Canada is on October 12th.

Tracking the days by location/whether or not countries even celebrate it just isn't worth doing when *most* countries don't.

**Comment by Okatart333** [comment] 2020-11-05 04:42
Mabey someone could make a submod that lets her ask you what holidays you celebrate I do not know how to code so it may be more difficult than I think.

**Comment by ThePotatoGuy** [comment] 2020-11-15 23:13
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-11-15 23:13 UTC
Labels: not a bug
