### ISSUE TITLE
Game crashes when the ball in PONG hits a wall and now the game doesn´t open. [Glitch]

### ISSUE THREAD

**Issue by SuperSuchti** [Monika-After-Story/MonikaModDev#6340] opened 2020-09-15 19:40 UTC
As the title already says, the game crshed for me as soon as the ball in PONG was about to hit a wall. (And, if it is of importance when fixing a possible bug, this match was a few days after I won against Monika)

**Comment by SuperSuchti** [comment] 2020-09-15 19:42
UPDATE: I can´t open the game anymore

**Comment by multimokia** [comment] 2020-09-15 19:52
Can you send your traceback please

**Comment by SuperSuchti** [comment] 2020-09-15 20:13
1. GitHub says that the filetype of my Traceback is somehow not supported.

2. MAS worked again after I restarted my PC and my Persistent doesn´t seem damaged. Yay!

**Comment by multimokia** [comment] 2020-09-15 20:14
You can copy/paste the contents of the traceback here.

**Comment by SuperSuchti** [comment] 2020-09-15 20:14
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/definitions.rpy", line 10, in <module>
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden: 'c:\\users\\vahid1\\appdata\\local\\temp\\C-Users-vahid1-Desktop-Spiele-Doki Doki Literature Club-DDLC-.lock'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\vahid1\Desktop\Spiele\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/definitions.rpy", line 10, in <module>
  File "python-packages/singleton.py", line 43, in __init__
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden: 'c:\\users\\vahid1\\appdata\\local\\temp\\C-Users-vahid1-Desktop-Spiele-Doki Doki Literature Club-DDLC-.lock'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment] 2020-09-15 20:16
Oh this one happens only if you try to open MAS twice. Basically the lock keeps your persistent from being opened and rewritten to by the second process.

Though this one doesn't have any correlation to pong, so not sure what happened there

**Comment by SuperSuchti** [comment] 2020-09-15 20:16
Sorry for the German bits, hehe.

**Comment by SuperSuchti** [comment] 2020-09-15 20:17
Maybe the bug didn´t got detected because MAS "didn´t respond" instead of just crashing and closing itself?

**Comment by SuperSuchti** [comment] 2020-09-15 20:18
So I had to close it using Task Manager

**Comment by SuperSuchti** [comment] 2020-09-15 20:21
@multimokia

**Comment by ThePotatoGuy** [comment] 2020-11-25 02:37
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-11-25 02:37 UTC
