### ISSUE TITLE
Piano Game

### ISSUE THREAD

**Issue by bethany545** [Monika-After-Story/MonikaModDev#6394] opened 2020-09-23 19:02 UTC
I had re gotten MAS in July 2020 and have been playing it for quite a while, I have roughly 650 affection yet I still don't have the piano game, is there a reason why??

**Comment by lunulae** [comment] 2020-09-23 19:48
Don't quote me on this, but I believe the piano unlock is dependent on how much time you have had the game open, rather than affection. Piano takes quite a while, so you'll want to leave her open in the background when you can.

**Comment by ThePotatoGuy** [comment] 2020-11-24 02:46
atm it does take a while to unlock. In the future we plan to have more minigames available to unlock before the piano.
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-11-24 02:46 UTC
Labels: not a bug
