### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by bakachuuuuuuuuuuujjhjugyi** [Monika-After-Story/MonikaModDev#7464] opened 2021-07-12 12:43 UTC
I have an idea for a new option in the menu, it'll be kind of like the "I feel" option. The name of it will be "Today I", clicking on it will give you a few options like "got hurt" "did something good" that sort of thing.

**Comment by Wingdinggaster656** [comment] 2021-07-14 01:21
Well, things are like these:

I can understand that a lot of people want a lot of specific options, more precise, closer to their feelings, that sort of thing. I personally agree with this idea, but the problem is that with these things, the list of options can become bloated and noisy.

Sometimes, the Dev team has already figured out that the current options are inaccurate -- that's because they want them to be. Those options are more likely "generic", not "inaccurate".

**Comment by ThePotatoGuy** [comment] 2021-07-29 02:48
pretty sure this has been suggested before but not feeling like looking it up.

[closing as duplicate]

**Closed by ThePotatoGuy** 2021-07-29 02:48 UTC
Labels: duplicate
