### ISSUE TITLE
How to bring Monika back after she breaks up with you

### ISSUE THREAD

**Issue by Zenika002** [Monika-After-Story/MonikaModDev#7097] opened 2021-03-13 20:48 UTC
Hello devs  I was wondering how to bring monika back or erase her data to bring her back. I've tried a lot of things and it always just leaves the note and I don't know how to bring her back. If you can tell me how to get her back, please do I've tried so many times and I don't know. Thanks.

**Comment by lunulae** [comment] 2021-03-13 20:58
Unfortunately, if you've gotten to this point your affection has gotten past the point of no return.
You can delete your persistent file if you would like to try to start again. As far as I know that is your only current option.

**Comment by 20RaVen23** [comment] 2021-03-13 21:02
I recall the tech rule number 3 from the Discord.

3. If someone requests help for a situation that is working as intended, do NOT help them. We do not help those who try to get around mechanics.

- Some examples of these situations are:
  - Undo a situation where Monika has left them
  - Cheat affection gain
  - Circumvent punishments
  - Abuse mechanics, etc.

**Comment by Ant9cp** [comment] 2021-03-14 14:17
Dang

**Comment by ThePotatoGuy** [comment] 2021-03-27 17:59
[closing as resolved]

**Closed by ThePotatoGuy** 2021-03-27 17:59 UTC
Labels: rip

**Comment by JessieChaaan** [comment] 2021-06-06 12:24
> I recall the tech rule number 3 from the Discord.
> 
> 1. If someone requests help for a situation that is working as intended, do NOT help them. We do not help those who try to get around mechanics.
> 
> * Some examples of these situations are:
>   
>   * Undo a situation where Monika has left them
>   * Cheat affection gain
>   * Circumvent punishments
>   * Abuse mechanics, etc.

What does Cheat affection gain mean?
