### ISSUE TITLE
Monika doesn't recognise the clothes gift files or ignores it and deletes it

### ISSUE THREAD

**Issue by SPEARlNG** [Monika-After-Story/MonikaModDev#8438] opened 2021-12-18 09:47 UTC
So I had this issue when I put the mod assets from the installed sprite pack into the /game everything works perfectly but when I put the gift inside the /characters folder whether she takes it and tells me she doesn't recognise it or just deletes it. Please help, if you need any more details I'll answer.

**Comment by ThePotatoGuy** [comment] 2021-12-18 23:22
see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by ThePotatoGuy** [comment] 2021-12-26 02:47
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-26 02:47 UTC
Labels: not a bug, tree gift
