### ISSUE TITLE
Missed birthday?

### ISSUE THREAD

**Issue by Redchili385** [Monika-After-Story/MonikaModDev#4779] opened 2019-09-23 03:43 UTC
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3640542/aff_log.txt)

I think this affection logs says it all. I spent a little time with Monika on her birthday and give a present, but didn't made the oki doki thing. She tells on 00:00 that I forgot her b-day. It is a bug or its working as intended?

**Comment by jmwall24** [comment] 2019-09-23 03:51
honestly, looking at that aff_gain, it looks like since you gave that gift so close to midnight, it didn't register until after midnight, so that gift counted as on the 23rd, so unfortunately, it was as intended.

**Comment by ThePotatoGuy** [comment] 2019-10-10 03:07
[closing as resolved]

**Closed by ThePotatoGuy** 2019-10-10 03:07 UTC
