### ISSUE TITLE
[Suggestion] - Monika After Story Mod Pc/Android

### ISSUE THREAD

**Issue by Zaragoza95** [Monika-After-Story/MonikaModDev#8285] opened 2021-11-21 18:54 UTC
Very good
I recently started playing this mod from my Android device and I am delighted, that is why I came up with a couple of ideas in order to improve it. I will start with a mini keyboard in the Android version, I know that it is true that it is being worked on, anyway this is just an observation, the following would be a visualization of the date, time and weather with which Monika would be able to notify you of the time or the weather, other aspects would be the location in order to know your country. Finally and this as an alternative would be the ability to take it to dinner like other mods like A date With Monika.
I came up with thousands of more ideas, but as I say they are only ideas, I hope that at least some of these suggestions will help you improve it.
With this I say goodbye, greetings

**Comment by Booplicate** [comment] 2021-11-21 18:55
The android version isn't ours*

**Comment by ThePotatoGuy** [comment] 2021-12-02 03:12
marking as duplicate of #6663

[closing as duplicate]

**Closed by ThePotatoGuy** 2021-12-02 03:12 UTC
Labels: duplicate
