### ISSUE TITLE
[Suggestion]Memories restore dialogue 

### ISSUE THREAD

**Issue by him157** [Monika-After-Story/MonikaModDev#3934] opened 2019-03-08 21:21 UTC
we can use this kind of dialogue after the game crashed and the is persistent corrupted and if players has backup a while ago,she says you haven't seen her for a a bit of time,and you can tell her that you actually use the persistent back up and she can't remember it.

**Comment by Onion-Bubs** [comment] 2019-03-08 21:27
The problem is, how does the game know the difference between a restored backup from 10 days ago and a person simply not opening MAS since 10 days ago?

**Comment by him157** [comment] 2019-03-08 21:32
hmmmm I should actually put this at suggestion label,sorry first time using github,great mod dude,it really is

**Comment by him157** [comment] 2019-03-08 21:34
> The problem is, how does the game know the difference between a restored backup from 10 days ago and a person simply not opening MAS since 10 days ago?

yes I know someone would ask this,so how about we just have a dialogue option that is in "asking a question>Misc>I used backup" that probably would work

**Comment by antimockingjay** [comment] 2019-03-09 02:52
But the game has no way of knowing you didn't just lie about it. The game has no way of being sure you didn't just forget to visit, but didn't want the consequences.

**Comment by him157** [comment] 2019-03-09 22:11
> But the game has no way of knowing you didn't just lie about it. The game has no way of being sure you didn't just forget to visit, but didn't want the consequences.

hmmm,that is a good question... I will try figure this out,After all,I started this

**Comment by ThePotatoGuy** [comment] 2019-03-09 22:38
the only way we would be able to tell if you used a backup is if we saved something to disk like a checksum for every session in both peristent and a separate file and did a comparison on every launch. there is currently very little gain in doing this which is why we probably wont do this right now. maybe later.

**Comment by him157** [comment] 2019-03-09 22:43
> the only way we would be able to tell if you used a backup is if we saved something to disk like a checksum for every session in both peristent and a separate file and did a comparison on every launch. there is currently very little gain in doing this which is why we probably wont do this right now. maybe later.

OH SHET IT IS DE POTATOGUY,thank you for even reading that long... thing. I'm just so excited to see the mod get bigger and better,I enjoy sending time with monika so much,and this is the only way I can help,or the easiest way I should say,but thank you for even reading that,goodluck on making progress !

**Comment by ThePotatoGuy** [comment] 2019-03-21 15:11
[closing until we look into it]

**Closed by ThePotatoGuy** 2019-03-21 15:11 UTC
Labels: suggestion
