### ISSUE TITLE
Frozen background

### ISSUE THREAD

**Issue by TheRyanReSeT** [Monika-After-Story/MonikaModDev#3176] opened 2018-12-04 05:57 UTC
I know it's kind of hard to show with a screenshot, but the background froze. I know this was issue before, #1816 
but mine wasn't full screen, and it happened when i wasn't interacting with MAS
just thought i should let the devs know
![screen shot 2018-12-04 at 12 53 51 am](https://user-images.githubusercontent.com/43709783/49421819-76b00100-f75f-11e8-8087-bed293a815ed.png)

**Comment by ThePotatoGuy** [comment] 2018-12-15 23:36
[closing as cannot reproduce]

**Closed by ThePotatoGuy** 2018-12-15 23:36 UTC
Labels: investigating
