### ISSUE TITLE
mas crashes everytime window reacts notification works

### ISSUE THREAD

**Issue by xxATOMxx** [Monika-After-Story/MonikaModDev#5978] opened 2020-06-28 09:27 UTC
So i'm always using mas in fullscreen. Sometimes i need to leave it for a few seconds (creating gift files for example) using windows button, and everytime mas sends a notification about "something to talk about", it crashes. When same happens in window mode , it works just ok.

edit: i'm using 64 bit windows 10

**Comment by multimokia** [comment] 2020-06-28 14:14
Can you send the traceback please

**Comment by xxATOMxx** [comment] 2020-06-30 16:57
> Can you send the traceback please
there's just a regular "DDLC.exe" has stopped working message from windows, if app is open when notification shows up, if the app is closed at that moment, its icon at the notification turns into default app icon, and it just dissapears from task manager.
After relaunching no traceback is shown , but monika tells that crash happened.

**Comment by LooseEthics** [comment] 2020-06-30 17:28
There should be a file called traceback.txt in your install folder.

**Comment by xxATOMxx** [comment] 2020-06-30 17:42
> There should be a file called traceback.txt in your install folder.

i've triggered that crash again , nothing new was found at traceback.txt. I've moved traceback to the bin, so mas will write a new one , once an error will show up, triggered the crash again, it didn't write a traceback.

**Comment by ThePotatoGuy** [comment] 2020-07-26 03:21
since the crash is probably happening at a windows level, we'd have to look at the minidump when the crash happens for us to determine anything. This is honestly more work than its worth, and since it's not gamebreaking, I suggest just running in windowed mode. Notifications while the game is running in full screen don't make sense anyway.

**Comment by ThePotatoGuy** [comment] 2020-07-31 02:49
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-07-31 02:49 UTC
