### ISSUE TITLE
searching up topics with letter j makes a few topics without that letter in name appear in the results

### ISSUE THREAD

**Issue by xxATOMxx** [Monika-After-Story/MonikaModDev#7287] opened 2021-06-03 09:12 UTC
![Screenshot](https://user-images.githubusercontent.com/55636014/120618955-763d7180-c453-11eb-89a4-d5aa520e7bf9.png)

there's definetely no j in neither "you're a murderer", nor in "DDLC's setting"

i'm pretty sure there's more of that that will come up later

**Comment by Booplicate** [comment] 2021-06-03 09:24
There's more criteria than just topic names. But as you can see, they have a lower priority (and hence at the bottom of the list).

**Comment by multimokia** [comment] 2021-06-03 12:06
`you're a murderer` is also with an eventlabel: `monika_justification`

As @Booplicate said, more criteria than just `prompt` but it's lower priority

**Comment by ThePotatoGuy** [comment] 2021-06-12 21:07
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-06-12 21:07 UTC
Labels: not a bug
