### ISSUE TITLE
[Suggestion] - Another goodbye option

### ISSUE THREAD

**Issue by spartalabouche** [Monika-After-Story/MonikaModDev#3526] opened 2019-01-19 03:47 UTC
I've seen quite a few other goodbye suggestions but one I'd like would be 'I'll be right back' for things like if I have to close the program just for a few minutes (like updating the mod or if I'm going out of the house just for a little while). Related to another suggestion I've seen it'd be neat if she understood how long you were gone, so if it was just a few minutes she could say 'That was fast! Welcome back!' or something like that, or if you don't return until the next day she could be kind of upset about you not being back as soon as you said. In general though I'd just like another goodbye option so I don't have to tell her I'm going to school or work or something when I'm not.

**Comment by Thimeo** [comment] 2019-01-19 08:21
Ha! I'm faster than @Rai99
Duplicate of #1908

**Comment by Rai99** [comment] 2019-01-19 15:00
#497, #607, ~~#1908,~~ #2033, #2243, #2549, #2556, #2614, #2811, #3270

You missed some.

**Comment by Thimeo** [comment] 2019-01-19 16:15
I don't know why I even try...

**Comment by ThePotatoGuy** [comment] 2019-01-27 22:35
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-01-27 22:35 UTC
Labels: duplicate
