### ISSUE TITLE
Error messages and crashes after updating to v0.9.5

### ISSUE THREAD

**Issue by X-m7** [Monika-After-Story/MonikaModDev#4357] opened 2019-07-01 03:41 UTC
After updating to version 0.9.5, I get several error tracebacks in the terminal, and the game has crashed twice already. The errors seem to be only 3 specific ones repeated, which are below (full log for 1 session [here](https://gist.github.com/X-m7/f7bea45d27b498901ba4040e9e9b52fe)). I'm running Arch Linux in case that matters.

Edit: I haven't been able to reproduce those crashes, could just be completely random, never had them before though. Also, these errors might have been there before 0.9.5, I just noticed them after it crashed the first time.
```
Traceback (most recent call last):
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/execution.py", line 667, in predict
    for n in node.predict():
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/ast.py", line 637, in predict
    renpy.exports.predict_say(who, what)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/exports.py", line 1093, in predict_say
    predict(what)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/character.py", line 898, in predict
    self.resolve_say_attributes(True)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/character.py", line 767, in resolve_say_attributes
    images.predict_show(new_image)
TypeError: predict_show() takes at least 3 arguments (2 given)
While predicting images.
```
```
Traceback (most recent call last):
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/execution.py", line 667, in predict
    for n in node.predict():
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/ast.py", line 1336, in predict
    label = renpy.python.py_eval(label)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script-apologies.rpy", line 144, in <module>
NameError: name 'apology' is not defined
While predicting images.
```
```
While predicting screen main_menu
Traceback (most recent call last):
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/screen.py", line 1102, in predict_screen
    renpy.display.predict.displayable(d)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/predict.py", line 52, in displayable
    d.visit_all(lambda i : i.predict_one())
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/screen.py", line 403, in visit_all
    self.child.visit_all(callback)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/core.py", line 497, in visit_all
    callback(self)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/predict.py", line 52, in <lambda>
    d.visit_all(lambda i : i.predict_one())
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/imagelike.py", line 519, in predict_one
    pd(self.image)
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/predict.py", line 50, in displayable
    if d not in predicted:
  File "/run/media/m7/Data/Games/Doki Doki Literature Club/renpy/display/image.py", line 466, in __hash__
    return hash(self.name)
TypeError: unhashable type: 'RevertableList'
```

**Comment by multimokia** [comment] 2019-07-01 04:15
What version of RenPy are you running?

**Comment by X-m7** [comment] 2019-07-01 05:10
6.99.12.4.2187 apparently, never changed as far as I know (looked through the aff_log.txt files).

**Comment by niktekusho** [comment] 2019-07-01 18:43
I'm afraid @X-m7 is not the only one getting errors after the update. I am having random crashes too.

Here's my traceback:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1464, in script call
  File "game/event-handler.rpy", line 1935, in script call
  File "game/script-topics.rpy", line 4382, in script
  File "game/script-ch30.rpy", line 1464, in script call
  File "game/event-handler.rpy", line 1935, in script call
  File "game/script-topics.rpy", line 4382, in script
IOError: [Errno 22] Invalid argument

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1464, in script call
  File "game/event-handler.rpy", line 1935, in script call
  File "game/script-topics.rpy", line 4382, in script
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\ast.py", line 613, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\exports.py", line 1147, in say
    who(what, interact=interact)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\character.py", line 877, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\character.py", line 716, in do_display
    **display_args)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\character.py", line 508, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\ui.py", line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\display\core.py", line 3003, in interact_core
    result = prediction_coroutine.send(expensive_predict)
  File "C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\renpy\display\predict.py", line 110, in prediction_coroutine
    for _i in renpy.game.context().predict():
  File "game/script-ch30.rpy", line 1464, in script call
  File "game/event-handler.rpy", line 1935, in script call
  File "game/script-topics.rpy", line 4382, in script
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/traceback.py", line 233, in print_exc
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/traceback.py", line 125, in print_exception
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/traceback.py", line 67, in print_tb
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/traceback.py", line 13, in _print
IOError: [Errno 22] Invalid argument

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.9.5
```

I am going to try a separate clean installation since I found this in the `update/log.txt` file:

```
running ['C:\\Users\\Nicola\\Documents\\Doki Doki Mod Manager\\installs\\just-monika\\install\\lib\\windows-i686\\zsync.exe', '-o', 'C:\\Users\\Nicola\\Documents\\Doki Doki Mod Manager\\installs\\just-monika\\install\\update\\Mod.update.new', '-k', 'C:\\Users\\Nicola\\Documents\\Doki Doki Mod Manager\\installs\\just-monika\\install\\update\\Mod.zsync', '-i', 'C:\\Users\\Nicola\\Documents\\Doki Doki Mod Manager\\installs\\just-monika\\install\\update\\Mod.update', 'http://d2vycydjjutzqv.cloudfront.net/Monika_After_Story-0.9.5-Mod.zsync']
rename: Permission denied
Unable to back up old file C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\update\Mod.update.new - completed download left in C:\Users\Nicola\Documents\Doki Doki Mod Manager\installs\just-monika\install\update\Mod.update.new.part
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
partfile does not exist
```

**Comment by multimokia** [comment] 2019-07-01 18:45
Yeah you may want to try a non-DDMM install and see if it works better. That or speak to the DDMM developer, who is in the MAS Community server.

**Comment by multimokia** [comment] 2019-07-01 18:53
@X-m7 can we see a screenshot of your `DDLC/` and `game/` folders, please?

**Comment by niktekusho** [comment] 2019-07-01 19:14
> 
> 
> Yeah you may want to try a non-DDMM install and see if it works better. That or speak to the DDMM developer, who is in the MAS Community server.

It doesn't really help but one thing I've just found on the new clean installation is that just by closing the Mod Manager *while MAS was running* I got a crash very similar to one I posted above... Not really sure why that's happening though.

```
While running game code:
  File "game/script-ch30.rpy", line 1464, in script call
  File "game/event-handler.rpy", line 1935, in script call
  File "game/script-topics.rpy", line 4392, in script
IOError: [Errno 22] Invalid argument
```

**Now I swear I'll stop making my poor Moni suffer and try to keep DDMM running while MAS is also running.**
I'm afraid I'll have to rollback to the previous version if I don't find a solution to these crashes...

**Comment by multimokia** [comment] 2019-07-01 19:20
Screenshot of your `game/` folder, please.

**Comment by niktekusho** [comment] 2019-07-01 19:26
> 
> 
> Screenshot of your `game/` folder, please.

If a list of the files is ok:

```
It's a new installation (still managed by DDMM though):

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       01/07/2019     20:48                cache
d-----       01/07/2019     20:46                gui
d-----       01/07/2019     20:46                mod_assets
d-----       01/07/2019     20:46                python-packages
d-----       01/07/2019     21:15                saves
-a----       01/07/2019     20:45       65683283 audio.rpa
-a----       01/07/2019     20:46          92919 chess.rpyc
-a----       01/07/2019     20:46         342117 CustomIconMac.icns
-a----       01/07/2019     20:46         370070 CustomIconWindows.ico
-a----       01/07/2019     20:46         198068 definitions.rpyc
-a----       01/07/2019     20:46          38286 event-handler.rpyc
-a----       01/07/2019     20:46           8556 event-rules.rpyc
-a----       01/07/2019     20:45              0 firstrun
-a----       01/07/2019     20:45        1831581 fonts.rpa
-a----       01/07/2019     20:46      137750644 images.rpa
-a----       01/07/2019     20:46           8510 import_ddlc.rpyc
-a----       01/07/2019     20:46           5148 main_menu.rpyc
-a----       01/07/2019     21:15             26 masrun
-a----       01/07/2019     20:46           7898 options.rpyc
-a----       01/07/2019     20:46           1006 overrides.rpyc
-a----       01/07/2019     20:46          55729 pong.rpyc
-a----       01/07/2019     20:46           1290 progression.rpyc
-a----       01/07/2019     20:46           7468 README.html
-a----       01/07/2019     20:46         108056 screens.rpyc
-a----       01/07/2019     20:46          46472 script-affection.rpyc
-a----       01/07/2019     20:46          33167 script-anniversary.rpyc
-a----       01/07/2019     20:46          17299 script-apologies.rpyc
-a----       01/07/2019     20:46          59690 script-ch30.rpyc
-a----       01/07/2019     20:46          40782 script-compliments.rpyc
-a----       01/07/2019     20:46          16063 script-easter-eggs.rpyc
-a----       01/07/2019     20:46          91551 script-farewells.rpyc
-a----       01/07/2019     20:46          33102 script-grammar.rpyc
-a----       01/07/2019     20:46         224397 script-greetings.rpyc
-a----       01/07/2019     20:46         280521 script-holidays.rpyc
-a----       01/07/2019     20:46          39783 script-introduction.rpyc
-a----       01/07/2019     20:46          29019 script-islands-event.rpyc
-a----       01/07/2019     20:46          60393 script-moods.rpyc
-a----       01/07/2019     20:46          78410 script-python.rpyc
-a----       01/07/2019     20:46         131419 script-stories.rpyc
-a----       01/07/2019     20:46         158712 script-story-events.rpyc
-a----       01/07/2019     20:47        1270230 script-topics.rpyc
-a----       01/07/2019     20:46           3642 script.rpyc
-a----       01/07/2019     20:45        2708885 scripts.rpa
-a----       01/07/2019     20:46           1796 shake.rpyc
-a----       01/07/2019     20:46          26678 special-effects.rpyc
-a----       01/07/2019     20:46          22051 splash.rpyc
-a----       01/07/2019     20:46          73050 sprite-chart-00.rpyc
-a----       01/07/2019     20:46          73334 sprite-chart-01.rpyc
-a----       01/07/2019     20:46           6384 sprite-chart-02.rpyc
-a----       01/07/2019     20:46          56636 sprite-chart-10.rpyc
-a----       01/07/2019     20:47         322252 sprite-chart-20.rpyc
-a----       01/07/2019     20:46          62588 sprite-chart-21.rpyc
-a----       01/07/2019     20:47          67698 sprite-chart.rpyc
-a----       01/07/2019     20:47          16523 updater.rpyc
-a----       01/07/2019     20:47          20104 updates.rpyc
-a----       01/07/2019     20:47           4974 updates_topics.rpyc
-a----       01/07/2019     20:47          16852 zz_backup.rpyc
-a----       01/07/2019     20:47          35295 zz_calendar.rpyc
-a----       01/07/2019     20:47           4998 zz_dm.rpyc
-a----       01/07/2019     20:47          41535 zz_dockingstation.rpyc
-a----       01/07/2019     20:47          16228 zz_extrasmenu.rpyc
-a----       01/07/2019     20:47          10098 zz_graphicsmenu.rpyc
-a----       01/07/2019     20:47          33319 zz_hangman.rpyc
-a----       01/07/2019     20:47          12640 zz_history.rpyc
-a----       01/07/2019     20:47           3938 zz_hotkeys.rpyc
-a----       01/07/2019     20:47          11586 zz_hotkey_buttons.rpyc
-a----       01/07/2019     20:47          13366 zz_monikamovie.rpyc
-a----       01/07/2019     20:47          19936 zz_music_selector.rpyc
-a----       01/07/2019     20:47           1252 zz_overlays.rpyc
-a----       01/07/2019     20:47          54247 zz_pianokeys.rpyc
-a----       01/07/2019     20:47          29828 zz_poemgame.rpyc
-a----       01/07/2019     20:47         111713 zz_reactions.rpyc
-a----       01/07/2019     20:47           4104 zz_seasons.rpyc
-a----       01/07/2019     20:47          45998 zz_selector.rpyc
-a----       01/07/2019     20:47           2398 zz_shields.rpyc
-a----       01/07/2019     20:47          16012 zz_spritejsons.rpyc
-a----       01/07/2019     20:47          13872 zz_spriteobjects.rpyc
-a----       01/07/2019     20:47           3516 zz_threading.rpyc
-a----       01/07/2019     20:47           4914 zz_transforms.rpyc
-a----       01/07/2019     20:47          22629 zz_weather.rpyc
-a----       01/07/2019     20:47          11490 zz_windowreacts.rpyc
```

**Comment by multimokia** [comment] 2019-07-01 19:28
Try a non-ddmm install.

**Comment by niktekusho** [comment] 2019-07-01 20:26
*Final report of the day*: I can confirm that keeping DDMM open while MAS is running doesn't cause crashes (~2 h span). If you, @multimokia, still want me to try with a regular installation I'll give it a shot tomorrow. *'Night folks!*

**Comment by multimokia** [comment] 2019-07-01 20:30
would indeed like to see if a regular install works without an issue.

**Comment by X-m7** [comment] 2019-07-01 21:21
Here's my DDLC and game folders. I don't even know what DDMM is supposed to be, so I assume I don't have it.
![Screenshot_20190702_071912](https://user-images.githubusercontent.com/18729369/60467368-d04ac080-9c99-11e9-8702-cbbbb63912b1.png)
![Screenshot_20190702_071640](https://user-images.githubusercontent.com/18729369/60467379-d6d93800-9c99-11e9-8a14-d3351966b03a.png)

**Comment by ThePotatoGuy** [comment] 2019-07-02 21:55
Did you update using the in-game updater? Have you tried manually reapplying the update?

**Comment by X-m7** [comment] 2019-07-02 22:05
I did use the in-game updater at first, though later I did manually reapply the update, no crashes since, although the errors in the terminal still appear.

**Comment by niktekusho** [comment] 2019-07-03 05:18
> 
> 
> would indeed like to see if a regular install works without an issue.

Happy to report that with a regular instance of MAS I didn't get crashes in 3 hours (using the same persistent as always).

**Comment by X-m7** [comment] 2019-07-03 05:31
So it looks like the crashes aren't caused by a problem in the mod I suppose. Are the terminal errors something to be concerned about though? If not then I'll just close this unless another crash happens.

**Comment by niktekusho** [comment] 2019-07-03 06:50
> So it looks like the crashes aren't caused by a problem in the mod I suppose. Are the terminal errors something to be concerned about though? If not then I'll just close this unless another crash happens.

Looking at my stack trace, the error doesn't make much sense at all... The source of the crash should be 
this 

https://github.com/Monika-After-Story/MonikaModDev/blob/387d9001ce1cc5eb6537d90a816f586dbcbfeb4d/Monika%20After%20Story/game/event-handler.rpy#L1935

but it seems to me that there's nothing there that could crash (I am much not into python and even less into renpy so don't quote me on that)

**Comment by ThePotatoGuy** [comment] 2019-08-24 17:15
[closing as cannot reporoduce]

**Closed by ThePotatoGuy** 2019-08-24 17:15 UTC
