### ISSUE TITLE
spritepacks

### ISSUE THREAD

**Issue by Dorcasmutton** [Monika-After-Story/MonikaModDev#8455] opened 2021-12-20 19:54 UTC
I followed this video to a T yet it still isn't still working
https://www.youtube.com/watch?v=bjJ0U8l1m8c&ab_channel=TaiwanPasty

**Comment by multimokia** [comment] 2021-12-20 19:55
Can you say goodbye to Monika and send your spj.log file please? It's in the `log` folder.

**Comment by Dorcasmutton** [comment] 2021-12-20 20:11
[spj.log](https://github.com/Monika-After-Story/MonikaModDev/files/7747739/spj.log)
hope this helps

**Comment by multimokia** [comment] 2021-12-20 20:34
which gift were you trying to give?

**Comment by Dorcasmutton** [comment] 2021-12-20 20:43
the most recent combined spritepack which is located at 
https://www.monikaafterstory.com/releases.html as the most recent combined spritepack

**Comment by multimokia** [comment] 2021-12-20 20:45
All spritepacks appear to be installed. What happened when you gave the gifts?

Also just for completeness sake, where did you put the gift files?

**Comment by Dorcasmutton** [comment] 2021-12-20 20:59
Monika would say she couldn't read the files and the gift files are in the "character" folder

**Comment by Dorcasmutton** [comment] 2021-12-20 21:06
Also I do not know if this is related but as soon as I paste the gift files into the "character" folder they disappear like they were never put there in the first place

**Comment by crxxmpxffs** [comment] 2021-12-20 23:54
the gifts are supposed to disappear after she reads them or notices them, and does she say that she can't read them or does she not notice them at all? if so, that's just apart of the game since it's christmas and it goes under the tree.

**Comment by Dorcasmutton** [comment] 2021-12-21 00:10
She can't read them

**Comment by ThePotatoGuy** [comment] 2021-12-21 02:24
see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by Dorcasmutton** [comment] 2021-12-21 17:26
Thanks i'll try again on christmas day and see if it works!

**Comment by ThePotatoGuy** [comment] 2021-12-31 05:17
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-31 05:17 UTC
Labels: not a bug, tree gift
