### ISSUE TITLE
[Suggestion] - Adding calendar events and Birthdays to the calendar

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9359] opened 2022-07-22 11:36 UTC
Being able to select a day and add events/Birthdays to the calendar, maybe Monika can bring these up to the player, or suggest singing happy birthday?

**Comment by Justformas** [comment] 2022-07-22 16:37
The idea to add events to the calendar has definitely been brought up before. Some types of events like times you go to work might be addressed with the Timeconcern Overhaul Issue I linked in another one of your issues (4914). But don't know about other events like other people's birthdays.

**Comment by ThePotatoGuy** [comment] 2022-09-24 02:03
marking duplicate of #1771

[closing as duplicate]

**Closed by ThePotatoGuy** 2022-09-24 02:03 UTC
Labels: duplicate
