### ISSUE TITLE
Hair Ribbon Oopsy

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3666] opened 2019-02-08 17:30 UTC
![image](https://user-images.githubusercontent.com/40907045/52494918-3e80d080-2b9d-11e9-82c9-8aa7a837a94e.png)

**Comment by ThePotatoGuy** [comment] 2019-02-08 17:33
going to need exact replication steps because we have not been able to reproduce

**Comment by AsuraShun** [comment] 2019-02-08 17:35
Why not just turn this into an actual hairstyle? It wouldn't be the first time a bug was turned into something official,kinda like what gave gta its origins

**Comment by AsuraShun** [comment] 2019-02-08 17:36
But the bow would need to be smaller,and a tiny bow on both bangs

**Comment by Chrissenpai** [comment] 2019-02-08 17:41
I repeated the steps but it actually got fixed, I guess the bug was because I changed the clothing right after the download of the game, so therefore I just closed and opened the game and it got fixed.

**Comment by jmwall24** [comment] 2019-02-08 17:42
what clothes hair style did you start from?  was this from uniform with hair down ->santa

**Comment by Chrissenpai** [comment] 2019-02-08 17:50
actually, I started with school clothes with white ribbon, but the ribbon was partially cropped, like an incomplete work at photoshop, then I changed the ribbon colour to see if the problem persisted and it got fixed, afterwards, I´ve changed back to Santa hair down, being first santa and then hair down, then, i wanted to change again and it appeared to me the change ribbon option (i said hmmm interesting, will it crash?) then I chose that and it displayed just like in the screenshot, with all the different colours available. Thats my story.

**Comment by jmwall24** [comment] 2019-02-08 17:52
you had the change ribbon option available when hair was down?

**Comment by Chrissenpai** [comment] 2019-02-08 17:55
indeed

**Comment by ThePotatoGuy** [comment] 2019-02-08 18:11
[leaving this as a non-producible issue. investigations will reopened if we get another report]

**Comment by ThePotatoGuy** [comment] 2019-02-19 05:29
[closing as no reports have come in]

**Closed by ThePotatoGuy** 2019-02-19 05:29 UTC
Labels: investigating, more info needed
