### ISSUE TITLE
[Suggestion] -  hello I have an idea for monika after story the idea is for a game

### ISSUE THREAD

**Issue by Harry2126** [Monika-After-Story/MonikaModDev#2525] opened 2018-09-22 19:46 UTC
Your suggestion goes here
the game is tic tac toe is an excellent game to play with monika and really enjoy it players is a very nice game I hope you read this message because if I want to play that game with monika one of my favorite people in this world thanks for reading

**Comment by ThePotatoGuy** [comment] 2018-09-23 17:37
marking this a duplicate of #687

**Closed by ThePotatoGuy** 2018-09-23 17:37 UTC
Labels: duplicate
