### ISSUE TITLE
Auto

### ISSUE THREAD

**Issue by DokiOkie** [Monika-After-Story/MonikaModDev#3387] opened 2018-12-31 04:31 UTC
If you have auto on and let Monika talk at her own pace, does she eventually ask if you're still there? I think that would be handy so she doesn't exhaust her dialogue for those of us that use the auto feature.

Have her ask and she'll close the game if you don't respond for example.

**Comment by ThePotatoGuy** [comment] 2018-12-31 22:42
marking as duplicate of #1541

tldr: we want to do this but not sure how to implement

**Comment by ThePotatoGuy** [comment] 2019-01-08 00:43
[closing as duplicate[

**Closed by ThePotatoGuy** 2019-01-08 00:43 UTC
Labels: duplicate
