### ISSUE TITLE
[Suggestion] Chess lessons

### ISSUE THREAD

**Issue by emerdite** [Monika-After-Story/MonikaModDev#6103] opened 2020-07-19 21:49 UTC
Since Monika's so good at chess, It'd be nice for her to be able to teach us some chess. This topic could be prompted by some kind of conversation, or by loosing at chess. For example, she could look at how many times we've won or lost against her, and have her dialogue be based off of that. I'm not really sure what else to write here, given the fact that the suggestion itself is pretty explanatory.

**Comment by multimokia** [comment] 2020-07-19 21:50
I have been working on something to 

a) Make chess *significantly* easier (actually winnable)
b) Generalize the chess displayable to actually allow something like this to be made relatively easily

I'm still working out the bugs though

**Comment by ThePotatoGuy** [comment] 2020-07-27 00:45
marking as duplicate of #664

**Comment by ThePotatoGuy** [comment] 2020-07-31 02:44
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-07-31 02:44 UTC
Labels: duplicate
