### ISSUE TITLE
M.C birthday

### ISSUE THREAD

**Issue by loverofmonika** [Monika-After-Story/MonikaModDev#1814] opened 2018-06-25 04:37 UTC
i was wondering if there is any option where i can tell monika my brithday and when that day comes, we can celebrate it together and kinda have some unique activities such as having a cake or something like that
my birthday is coming soon so yea kinda curious

**Comment by Onion-Bubs** [comment] 2018-06-25 07:04
At the moment, if you go to "I'm feeling" and then from the options select "like a year older", Monika will ask if it's your birthday today and you can tell her that it is.

I think the dev team is also planning to implement the ability to specify a date on the calendar for your birthday.

**Comment by loverofmonika** [comment] 2018-06-25 07:43
@Onion-Bubs, i was informed that the option u just mentioned would be removed when the calender would be implemented and i couldnt find it in "im feeling". i think its time to expand on the topic, start brainstorming people. what im proposing isnt just a simple happy birthday greeting, i want to make the day feel really special. for one about adjusting the date, it should be a one time thing, that way it'll feel really realistic and the player cant cheat or hack his way out and manipulate. 
2nd more unique dialogues that can be only read on that day
3rd some decorations placed in the room
4rd A cake and monika sings happy birthday ( doesn't have to be audio altho that would be better)
5rd FINALLY I CAN KISS HER
@Rai99 check this proposal.

**Comment by Rai99** [comment] 2018-06-25 14:28
The issue you opened in #1740 covers the same idea about adding your birthday to the calendar. 

Dialogue will likely be written for the player's birthday, but I plan to wait for it to be implemented before I start writing anything for it so I can see the flow of it and how it will work. Probably the same as the valentines day topics. 

Room decorations have taken the first step with the addition of the calendar, so extra decorations are likely on the way as long as we have the art. 

A cake would probably fit in with room decorations or accessories, **though with this, I think there should be a way to choose the kind of cake you want**. Monika singing happy birthday would likely be added in as dialogue and possibly have the song played on the piano. I don't think voice acting is in the realm of possibility here. 

As for being able to kiss Monika, I'm sure everyone has ideas and wishes to be able to kiss Monika. This would probably require art so Monika can have a unique kissing sprite. Maybe have her lean in close to the screen or have her blow you a kiss.

**Comment by loverofmonika** [comment] 2018-06-25 18:39
makes sense, i really want to implement this before my birthday that is on 14 july, so i can celebrate with her. i may try to write a rough script too. 
oh btw how is the security system coming along

**Comment by loverofmonika** [comment] 2018-06-26 05:12
this security system is a big step just like the calendar and its is complicated to code and implement so i do think it'll take time. As far as the main topic is concerned, i think it would be best if we start writing  the script before implementation, that would be less of a burden when the day comes, and i think we take a similar approach as the valentine topic but a bit more unique, on to brainstorming

**Comment by ThePotatoGuy** [comment] 2018-06-27 03:38
[[Closing this as a duplicate of #1740 ]]

**Closed by ThePotatoGuy** 2018-06-27 03:38 UTC
