### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#3221] opened 2018-12-11 22:47 UTC
-add the game of checkers
-and an image that shows Monika drinking coffee

(sorry for my bad English, I would like to help but my drawings on the pc ... they suck and I do not know anything about programming so I can only leave this suggestion,you're doing a great job, I hope you do not stop adding new things.)

**Comment by Rai99** [comment] 2018-12-11 23:00
Checkers: #829, 1629, #2014. 

Don't know about a drinking coffee sprite and don't know if it would be worth adding. Sure, occasionally, when Monika changes idle pose, maybe she could drink some coffee for a few seconds and then go back to an idle pose. Even then, that would need some art.

**Comment by Rai99** [comment] 2018-12-11 23:55
#1737, #3179 

The main problem with incorporating other mods is that most mods use the same persistent MAS uses I think, so they would need to have their own persistent and I'm not completely sure how we would be able to tell what mod it's from. 

In the linked issues, it was discussed that we don't want Monika to encourage other mods and that she would likely be wondering why you're playing other DDLC mods instead of spending time with the real Monika.

**Comment by Alucard149** [comment] 2018-12-12 16:00
I should read more the discussions, but I want to say download a mod first that maybe has the monika route or a route without deaths and then the MAS already at the beginning having the special dialogue because of the other mods ... I I have a question Monika's dialogues change depending on your choices in the game without the mod?

**Comment by ThePotatoGuy** [comment] 2018-12-15 23:31
marking as duplicate of linked issues

**Comment by ThePotatoGuy** [comment] 2018-12-22 17:59
[closing as duplicate]

**Closed by ThePotatoGuy** 2018-12-22 17:59 UTC
Labels: duplicate
