### ISSUE TITLE
MAS is messing up pcs.

### ISSUE THREAD

**Issue by VibRibbonGamer** [Monika-After-Story/MonikaModDev#7497] opened 2021-07-15 20:10 UTC
MONIKA AFTER STORY IS MESSING UP PCS
WHEN I INSTALLED IT AND RAN IT FOR THE FIRST TIME
AFTER THAT EVERY 5 MINUTES IT BSOD
AND I TESTED IT ON A NEW PC AND A OLD PC THEY BOTH BSOD

**Comment by multimokia** [comment] 2021-07-15 20:12
...It's not though?
MAS runs on thousands of PCs, and more people are installing it basically daily.

If you could share the logs, it may help figure out *why* you're getting a BSoD

**Comment by fromulus** [comment] 2021-07-15 21:26
ALSO TALKING IN CAPS.LOCK IS PERFECTLY NORMAL AND DOESN'T COME OFF AS EXCESSIVE OR DISRESPECTFUL AT ALL.

**Comment by xXMidnight** [comment] 2021-07-16 04:40
totally.

**Comment by VibRibbonGamer** [comment] 2021-07-20 00:18
> 
> 
> ...It's not though?
> MAS runs on thousands of PCs, and more people are installing it basically daily.
> 
> If you could share the logs, it may help figure out _why_ you're getting a BSoD

I don't have the logs, I deleted the game

**Comment by Retrolovania** [comment] 2021-07-20 00:27
...well...uhhh...can't really say much about it if there's nothing to go off of, then.

**Comment by H2-san** [comment] 2021-07-22 02:29
> I don't have the logs, I deleted the game

Your loss if you don't wish to keep the logs around. Can't help your particular issue, either. **¯\\_(ツ)_/¯**
(Request to close as resolved)

**Comment by ThePotatoGuy** [comment] 2021-07-29 02:21
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2021-07-29 02:21 UTC
