### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by CreepFort** [Monika-After-Story/MonikaModDev#4255] opened 2019-06-02 10:22 UTC
![61563140_685957608492378_2761517053381705728_n](https://user-images.githubusercontent.com/44503785/58759744-4ccd7080-852f-11e9-8121-57ab7aa8d0fe.jpg)
![61691278_2110753735888654_3811214215939620864_n](https://user-images.githubusercontent.com/44503785/58759745-4ccd7080-852f-11e9-80d1-f7388088b15e.jpg)

While playing the game of Pong, the displayed name isn't the one I had chosen.
Sorry for bad quality.

**Comment by fromulus** [comment] 2019-06-02 10:38
Weird, I'm sure the name displayed was Monika's nickname in previous versions.

**Comment by multimokia** [comment] 2019-06-02 12:21
Intentional, it's kinda weird for it to be some nicknames.

**Comment by ThePotatoGuy** [comment] 2019-06-24 04:11
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-06-24 04:11 UTC
Labels: not a bug
