### ISSUE TITLE
the game didn't get any keyboard or mouse input

### ISSUE THREAD

**Issue by MiguelFitz** [Monika-After-Story/MonikaModDev#8182] opened 2021-11-05 02:41 UTC
for some reason the game didn't get any input aside from the message when i try to close the game without saying goodbye, i have to restart my pc to get it work again, i dont know why this happen, i also would like to add an option to explain monika why did we have to close the game without saying goodbye,i apologize to her as soon as i open the game and work againg

**Comment by ThePotatoGuy** [comment] 2021-11-12 17:06
>the game didn't get any input aside from the message when i try to close the game without saying goodbye

So it sounds like you're saying that when you try to close the game without saying goodbye and the popup appears, you are unable to interact with anything else except the popup. This is how popups work.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-11-12 17:06 UTC
Labels: not a bug
