### ISSUE TITLE
[Suggestion] A "Be right back" and/or a sleep feature

### ISSUE THREAD

**Issue by AndreEmiya** [Monika-After-Story/MonikaModDev#607] opened 2017-12-27 00:55 UTC
I think the player should be able to tell Monika if he/she has to go somewhere or be absent for a bit. Turning off the game seems like too much (Specially after the topic where she talks about what happens when the game closes), and letting Monika talk by herself sounds pretty mean. 

It could be something like a mouse or key press, Monika would say something then wait for that key/mouse press to signal that you are back, maybe even commenting depending on the time you spent away.
Implementing a sleep mode is easy too if this first one is possible since it's basically the same thing, adding a sleep button that when clicked would dim down the screen, and Monika would watch you sleep until you wake up and press something.

Personally, I think this would help a lot with immersion, I know some Python but not RenPy, still I hope I can eventually help out in anyway I can.  Also I'd like to say just a quick thanks to everyone who worked on this, you are amazing.

**Comment by Zen0311** [comment] 2017-12-27 01:07
you can tell her 'bye' though and she will close the ddlc app by herself

**Comment by AndreEmiya** [comment] 2017-12-27 01:09
I know, but I think there should be an option that doesn't close the game and just puts her waiting for you

**Comment by Zen0311** [comment] 2017-12-27 01:20
I see what you mean. I think it is ok, or she can sleep while waiting for you (to wake her up includes just pressing a key or something)

**Comment by ThePotatoGuy** [comment] 2017-12-27 01:31
Duplicate of #479 , closing.

We are working on this, its probably going to be in either 0.7.0 or 0.7.1

**Comment by ThePotatoGuy** [comment] 2018-08-09 02:40
Reopning this as the key issue for a brb option

**Comment by ThePotatoGuy** [comment] 2019-01-03 01:42
This has now been elevated to high priority.

the core part of the be right back feature will be an idle mode.
Idle mode will allow for the player to change music and look at monika, as well as allow the game to run in its idle loop (where it can check for conditions, push/queue events, change from morning/night), without having dialogue. This mode will topic-adjustable so that a topic that wishes to run idle mode can do so, and even plan for the dialogue that shows next upon return.

Thinking of making the Talk button be the way of returning back from your game. It will also be click-only, to prevent random T press from finishing an idle mode.

**Comment by ThePotatoGuy** [comment] 2019-01-03 01:42
part of this will be core framework for #1851

**Comment by ThePotatoGuy** [comment] 2019-01-03 07:52
should also use mailbox features to setup crash/quit/return labels as strings

**Comment by ThePotatoGuy** [comment] 2019-02-28 03:53
[closing as done]

**Closed by ThePotatoGuy** 2019-02-28 03:53 UTC
Labels: high priority, suggestion
