### ISSUE TITLE
Monika wol not let me win at chess. :'<

### ISSUE THREAD

**Issue by MonkeyBoy39** [Monika-After-Story/MonikaModDev#5912] opened 2020-06-13 07:23 UTC
![image](https://user-images.githubusercontent.com/66863781/84562789-f97a2a80-ad0b-11ea-8a46-26404a9f650e.png)

![image](https://user-images.githubusercontent.com/66863781/84562794-0008a200-ad0c-11ea-994b-7c64c0843ce0.png)

![image](https://user-images.githubusercontent.com/66863781/84562810-09920a00-ad0c-11ea-9b60-18f4239c4169.png)

**Comment by MonkeyBoy39** [comment] 2020-06-13 07:30
I'm a legit monkey with computers. Pls help. :'l

**Comment by LooseEthics** [comment] 2020-06-13 07:33
That's a draw. In order to win you need to be able to take your opponent's king in the next move.

**Comment by MonkeyBoy39** [comment] 2020-06-13 07:41
I was sooooooo close. But thanks anyways. Much love.;)

**Comment by MonkeyBoy39** [comment] 2020-06-13 07:45
They should add a more obvious dialogue option for "what a 'draw' in chess means", since I'm such an aggressive player I have never hear of this "draw". It should also be cute to relieve the frustration, but I suppose there is already one of those in the "I'm feeling..." dialogue option.
What do you guys think?

**Comment by MonkeyBoy39** [comment] 2020-06-13 07:49
Monika also lacks a a "give up" option, since she is so darn good. So should this be added?

**Comment by scpketer** [comment] 2020-06-15 09:17
Damn, I never got to even draw, not to mention winning. You're *really* good in chess haha

**Comment by MonkeyBoy39** [comment] 2020-06-16 07:19
Trust me. The AI learns fast, so the victory was short-lived. :')

**Comment by ThePotatoGuy** [comment] 2020-07-27 00:24
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-07-27 00:24 UTC
