### ISSUE TITLE
[Spoilers]New Year's dress doesn't have a flair text in the selector

### ISSUE THREAD

**Issue by fromulus** [Monika-After-Story/MonikaModDev#5170] opened 2019-12-31 00:07 UTC
![Screenshot_1](https://user-images.githubusercontent.com/45933038/71605546-e4e51400-2b69-11ea-8f13-aaa02b201b22.png)

**Comment by multimokia** [comment] 2019-12-31 00:13
Fixed in #5095

**Comment by jmwall24** [comment] 2019-12-31 00:33
_or does it?_

**Comment by RavenPLAYER** [comment] 2019-12-31 00:48
TODO: ME

**Comment by TriniTDM** [comment] 2019-12-31 07:30
Or maybe she's suggesting we "do" her. But that's not really possible from here.

**Comment by Akh0r** [comment] 2019-12-31 17:06
If it looks THAT hilarious — that's not a bug, that's a feature!

**Comment by ThePotatoGuy** [comment] 2020-01-04 03:27
[closing as fixed]

**Closed by ThePotatoGuy** 2020-01-04 03:27 UTC
Labels: bug
