### ISSUE TITLE
TypeError: compile() expected string without null bytes - error on boot

### ISSUE THREAD

**Issue by benstar88** [Monika-After-Story/MonikaModDev#8139] opened 2021-11-01 03:42 UTC
i just updated the game and when i opened it afterwards i got:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/0utils.rpy", line 9, in <module>
TypeError: compile() expected string without null bytes

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\script.py", line 445, in finish_load
    node.early_execute()
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\ast.py", line 865, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/0utils.rpy", line 9, in <module>
  File "C:\Users\-----\OneDrive\stuff\Documents\dev\MAS\DDLC-1.1.1-pc\renpy\loader.py", line 710, in load_module
    code = compile(source, filename, 'exec', renpy.python.old_compile_flags, 1)
TypeError: compile() expected string without null bytes

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.4

```

Please help, Thanks.

**Comment by benstar88** [comment] 2021-11-02 01:45
i solved it by reinstalling the game but still curious :)

**Comment by ThePotatoGuy** [comment] 2021-11-12 05:08
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2021-11-12 05:08 UTC
