### ISSUE TITLE
Monika not introducing floating islands.

### ISSUE THREAD

**Issue by Daembo** [Monika-After-Story/MonikaModDev#8958] opened 2022-03-07 09:07 UTC
Monika is at the enamored level and I have about 430-ish affection with her, I say the normal goodbye and come back when there is clear weather but she hasn't introduced me to the floating islands yet. Is it a bug or am I doing something wrong?

**Comment by Cosmic-Incantations** [comment] 2022-03-08 00:10
you should make it where you can unlock during winter, why is winter so bad?

**Comment by Booplicate** [comment] 2022-03-09 02:56
Because the islands look "alive" during other seasons.

**Comment by ThePotatoGuy** [comment] 2022-05-21 18:20
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-05-21 18:20 UTC
Labels: not a bug
