### ISSUE TITLE
[Suggestion!] Movie night!

### ISSUE THREAD

**Issue by cascadingdreamer** [Monika-After-Story/MonikaModDev#6011] opened 2020-07-04 14:52 UTC
I don't know if someone has asked about this before, and I'm really sorry if they have! But it would be cool to tell her we want to watch a movie together, and it'd go into a sort of BRB mode, so it's like you're watching together. Maybe once food is added, she could get some popcorn or something, too! Sorry again if someone has already suggested this! ^^

**Comment by Rai99** [comment] 2020-07-04 15:43
Watching movies: #628, #826, #984, #1548, #2102, #2898, #3431, #4089, #4344, #5484, #5543 

There was a system in place for watching things together, but there's no content for it, and it would take a lot of effort to make content for it. 

As a brb, it might be easier, but it'll be impossible to comment, and I'm not sure if we'll make that sacrifice.

**Comment by ThePotatoGuy** [comment] 2020-07-22 23:29
also duplicate of #6053

**Closed by ThePotatoGuy** 2020-07-22 23:29 UTC
Labels: duplicate
