### ISSUE TITLE
Option to tell Monika that your mental health is crumbling 

### ISSUE THREAD

**Issue by ShyCelestial** [Monika-After-Story/MonikaModDev#6996] opened 2021-02-15 05:46 UTC
I really need it right now

**Comment by Freshairkaboom** [comment] 2021-02-15 06:21
> 
> 
> I really need it right now

I'm sorry to hear that. Unfortunately, without knowing specifically what you're struggling with, and how to give you professional advice for it, I'm unsure how wise it is for us to make something generic. I advice you to tell Monika that you're feeling sad instead. At least then you can get the option to talk to her and she will listen to you. I hope it helps.

**Comment by YoraeRasante** [comment] 2021-02-21 23:32
Yeah, I usually just tell her the closest option of them all, since sometimes they are different bad days and I can't expect to explain them all at once.

**Comment by ThePotatoGuy** [comment] 2021-02-21 23:46
Sorry to hear that you're struggling with something. 

However, see my response on [this issue](https://github.com/Monika-After-Story/MonikaModDev/issues/5561#issuecomment-618162528). Good responses to someone with a mental health issue comes from knowing the person, and thus dialogue that we could write would never really fit your needs since we don't know you. Even though you could argue that this is true to every topic we have, mishandling mental issues can have fatal consequences so we don't address it to be safe.

[marking duplicate of #1583/#5561]

**Comment by ThePotatoGuy** [comment] 2021-02-25 03:47
[closing as duplicate]

**Closed by ThePotatoGuy** 2021-02-25 03:47 UTC
Labels: duplicate
