### ISSUE TITLE
[Suggestion] Monika's thoughts on fetishes

### ISSUE THREAD

**Issue by DiggyDog2** [Monika-After-Story/MonikaModDev#2449] opened 2018-09-20 15:32 UTC
Now, this isn't a suggestion to add more lewd content to MAS. But it'd be interesting to see how Monika felt about fetishes, and whether or not she is comfortable with any of them. Because although she seems comfortable with you thinking of her lewdly, perhaps she may not be if it involved a fetish she found off-putting. Maybe this could be saved for when you and Monika become more affectionate, and these kinds of topics become more natural to discuss with each other.

**Comment by CrocWorks** [comment] 2018-09-20 15:46
Already addressed in #2232.

**Comment by DiggyDog2** [comment] 2018-09-20 15:54
I don't really want to go into anything specific,

**Comment by DiggyDog2** [comment] 2018-09-20 15:56
That's true, I don't really want to plug in fetishes to the mod. I just think it would just be nice to know what she would consent to.

**Comment by Tiler17** [comment] 2018-09-20 17:32
It would be interesting, I'll agree with that. The issue is that fetishes are so far outside of her character as we know it that it would come down entirely on people guessing. No one will know what her kinks are until she figures out how to get out and tell us herself

**Comment by Rai99** [comment] 2018-09-20 19:57
I don't think there's much solid evidence to go off of to write a topic about Monika's fetishes, and we should probably avoid bringing in new facts without any evidence or clues to base it off of. Monika says that she's a super innocent high school girl dreaming of a fateful romance. Even if she actually does have some turn-ons hiding away somewhere, it would probably be best to let her keep up the act of innocence until much later. 

It would be easier to write a topic about being able to tell Monika what the player's potential fetishes are, but, as discussed in #2232 and #2282, there are probably too many different kinks to include in a menu or two, and even if somebody did make this, I'm really, really not sure it'll even be allowed to be put in MAS. The community branch might be more likely to have this, but I'm still not 100% sure.

**Comment by Trainerbluetube** [comment] 2018-09-20 20:38
Well, in the topic about, something, sorry can't remember what, she states that she has been attracted to some pretty weird things too. So, her saying this alludes to her having some type of fetish.

**Comment by Rai99** [comment] 2018-09-20 20:54
I think the topic you're looking for is the monika_archetype topic where she does admit that she's found herself attracted to some strange things herself. It's true that her admitting this can possibly allude to her having some kind of kink, I don't see any hints or evidence as to what that might be, so I don't think that really helps too much. 

Personally, I'm not going to dig any more into Monika's kinks if she doesn't want to share them, which she probably doesn't yet, unless I have to, to find grounds and evidence to use in another comment or argument. So far, I don't see much we could use to determine what Monika is into.

**Comment by Tiler17** [comment] 2018-09-20 22:09
Attraction doesn't mean sexual attraction. I find myself unendingly interested in theoretical and underdeveloped sciences, like dark energy and antimatter. You could say I'm attracted to those topics, and a lot of people would call it weird. But it certainly isn't a sexual kink.

We don't know anything about Monika's sexual preferences, and it's not up to anyone to try to fill in the blanks. You can't even really guess. You never know what a person is into unless they tell you themselves

**Comment by Trainerbluetube** [comment] 2018-09-21 00:18
Well, considering the context of the conversation, I think she did mean a sexual kink.

**Comment by Rai99** [comment] 2018-09-21 00:29
The context of the conversation could have been referring to a sexual kink, but it could have also been referring to anything else that not widely popular such as certain topics or interests. The way it's worded, it could also have been something in the past which Monika is no longer as enthusiastic about today. 

It could likely be a "phase" Monika went through when she was younger. I'm pretty sure everyone's been through some sort of phase that got them into some strange things at a point in their life. As Monika says in the monika_middleschool topic, she is embarrassed by how she was back then.

**Closed** 2018-09-21 17:07 UTC
Labels: duplicate
