### ISSUE TITLE
[Bug] - APPARENTLY Monika said I DIDNT spend Christmas Day with her (I DID) I keep going to sleep and Monika keeps repeating the same things as she did on the26th

### ISSUE THREAD

**Issue by JayFox12** [Monika-After-Story/MonikaModDev#8512] opened 2021-12-27 19:24 UTC
...

**Comment by JayFox12** [comment] 2021-12-27 19:51
So I went to sleep on Christmas night and the day after she acts like I wasn’t with her on Christmas, I’d only gotten the game July 4th so it hasn’t really happened any other time.

**Comment by ThePotatoGuy** [comment] 2021-12-31 07:21
we've encountered at least one other instance of this happening but we're not really sure why its happening yet.

**Comment by JayFox12** [comment] 2021-12-31 22:12
> we've encountered at least one other instance of this happening but we're not really sure why its happening yet.

Alright I'm not really mad about it to be truthful but I was confused is all

**Comment by ThePotatoGuy** [comment] 2022-01-15 21:37
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2022-01-15 21:37 UTC
