### ISSUE TITLE
[Suggestion] - Allow players to save Monika's costume 

### ISSUE THREAD

**Issue by JustAskingStuff** [Monika-After-Story/MonikaModDev#9425] opened 2022-08-04 14:10 UTC
With the frequent update, as well as the new sprites being added in, I tend to change Monika's clothes. However, since there are so many different parts(clothes, hair band, hair clips, etc.) to put on something, and so many options of what to put on, I begin to forget what's Monika's previous costume. So I becomes less encouraged to try out a new look for Monika since I might lose the old one.

It would be great if there are options that allow us to save, rename the costume Monika currently wearing into different slots(for example, 20 slots for costumes). That way players can try out new outfits for Monika, without worrying can't go back to the old one. Moreover, players can even save all their customized outfits for Monika in different slots, rename them, and access them anytime. This would make Monika's outfit changing extremely convenient! 

Ps: Nice game! I've been playing it for years and I'm more than glad to see it gets better and better!

**Comment by ThePotatoGuy** [comment] 2022-08-04 18:37
marking duplicate of #6583

**Comment by ThePotatoGuy** [comment] 2022-09-24 01:40
[closing as duplicate]

**Closed by ThePotatoGuy** 2022-09-24 01:40 UTC
Labels: duplicate
