### ISSUE TITLE
Changing backgrounds issue

### ISSUE THREAD

**Issue by aahelloim** [Monika-After-Story/MonikaModDev#8492] opened 2021-12-25 01:04 UTC
So, after the update I think this is all that shows up when I try and change the background, even though I have all the submods and folders installed. Is it a glitch, am I just doing something wrong?
![Screenshot 2021-12-24 4 56 22 PM](https://user-images.githubusercontent.com/71156569/147375282-042f4438-161e-4754-a424-de4c14cb2494.png)
![Screenshot 2021-12-24 4 57 24 PM](https://user-images.githubusercontent.com/71156569/147375284-8aead8ce-b098-48b4-b3ca-267a08b6db54.png)

**Comment by Cosmic-Incantations** [comment] 2021-12-25 01:14
what is the sub mod? I want to do more on Christmas with her.

Oh is this the time you need help? wrong time for this? IDC, I don't get anything at the floating islands, so I want this.

**Comment by multimokia** [comment] 2021-12-25 01:19
Only backgrounds that support D25 deco are enabled for the event. We understand this is somewhat unintuitive, so we're looking into a different menu style which shows locked options that can help provide more information

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:07
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-01-09 22:07 UTC
Labels: not a bug
