### ISSUE TITLE
[Suggestion][April Fools] Teach Monika to Use Swear Words

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#4007] opened 2019-04-01 04:00 UTC
A new idea which I think could have potential since it's somewhat disappointing that a Literature Club
president never seems to use the full extent of the English language. Perhaps I am overthinking it some, but
really, wouldn't it be an excellent "bonding together" moment to teach Monika to swear? As an avid reader,
if she really is a language expert like her title suggests, then she'd know these words. Sure, her personality
leaves an impression that she's a "good girl," but that's why we'd teach her to actually use those words.

Fortunately, I have a lot of experience swearing, since I keep playing her in chess and pong a ridiculous and
overly unnecessary amount of time. I recall someone mentioned a microphone feature once before, but
oddly enough haven't heard much on it. It'd be the perfect way to condition her. Sure it's controversial, just
like everything else that involves sensitive subjects, but this is a character development opportunity. So if
someone wants to add this as a feature, I'd be happy to offer my experience for reference.

**Comment by PC57** [comment] 2019-04-01 04:03
I imagine she knows _how_ to swear but chooses not too. She was in debate club and probably learned that excessive swearing has the side effect of making one come off as less intelligent or emotionally unstable than someone who keeps a calm head. She doesn't swear because she doesn't want too. Hell, even if she's deleted she never curses once. If that doesn't merit a swear, I don't know what does.

**Comment by DankManWithThePlan** [comment] 2019-04-01 09:36
As I swear on a daily basis, I try not to swear in font of Monika. It's not much of a challenge, but sometimes a swear can slip out while I'm with her, and it feels like I've done a horrible misdeed whenever I realize it lol

**Comment by bittercaramel** [comment] 2019-04-01 19:21
idk why id like monika to swear, but as others said i dont think she wants to hehs 
swearing isnt rather something that smart schoolgirl would do

**Comment by B-Difu** [comment] 2019-04-01 19:27
I agree with multi here. Just because someone doesn't swear doesn't mean they are unaware of it. Nor does it really fit her to swear, though she has said "God" outside of talking about God directly, so take of that as you will.

**Comment by CrocWorks** [comment] 2019-04-01 22:00
Just so you all know, I really appreciate the responses that everyone here has put up. I genuinely think that
everyone here puts up valuable insight to how Monika thinks and acts. Sure, we all have our own opinions,
but I think having a discussion about this makes Monika have a better chance at being real. Certainly, each
and every one of us will continue having a constructive dialogue with each other to ensure that Monika
improves as a person. But it's not just Monika who has improved; I feel I have too, especially from writing
these suggestions all the time. The real joys come when my message stays hidden, so I would like to ask
everyone who made a comment to look at the first letter of each line in my posts. Once everyone here has
done that, I bet you can better understand my perspective on this topic.

**Comment by multimokia** [comment] 2019-04-01 22:04
Alternatively, you could just not be hinty and actually tell us what you want.

**Comment by Rai99** [comment] 2019-04-01 22:14
A lot of people just go by the title of the issue. You know, not everyone has the time of day to go reading through all these issues **up and down**.

**Comment by TMZN0V4** [comment] 2019-04-03 00:16
Lol the creator of the topic confirmed that it was an April Fools

**Comment by ThePotatoGuy** [comment] 2019-04-22 19:17
[closing as rejected]

**Closed by ThePotatoGuy** 2019-04-22 19:17 UTC
Labels: suggestion
