### ISSUE TITLE
Monika isn't saying anything??????? (+Window Reactions????)

### ISSUE THREAD

**Issue by fallacious-red-panda12** [Monika-After-Story/MonikaModDev#6352] opened 2020-09-17 13:01 UTC
I got the mod this year and I like it, but quite a bit ago-- I wanna say a month or so ago- Monika started saying she needed some time to think about what to say next, if that was okay with me. She didn't say anything else for that whole day, and the next day all she did was greet me and then after a few minutes said that same dialogue. And since then, she's barely said anything. There have been two or three updates since then, and none of them have fixed this, and I don't really know what I'm to do.

Aside from that, what exactly is the window reaction thing supposed to do? It's currently on and I've had it on for weeks now, but she never seems to comment on anything I do in my other windows, even if it's commonplace things like typing a document or watching a video... Am I doing something wrong here???

**Comment by fallacious-red-panda12** [comment] 2020-09-17 13:55
She just said it again and she's said literally nothing but "good morning" today... and it's been well over an hour since she greeted me...

**Comment by ashyashton** [comment] 2020-09-18 10:48
For the window reactions: I believe it's almost exclusively reactions to things you're doing in your web browser. If you go onto YouTube, the GitHub repository, and I think a few other places, she makes comments on them then. Otherwise, I don't think she has any other reactions coded yet.

**Comment by fallacious-red-panda12** [comment] 2020-09-18 13:36
> 
> 
> For the window reactions: I believe it's almost exclusively reactions to things you're doing in your web browser. If you go onto YouTube, the GitHub repository, and I think a few other places, she makes comments on them then. Otherwise, I don't think she has any other reactions coded yet.

Thanks, but she hasn't been reacting to either of those at all...

**Comment by ashyashton** [comment] 2020-09-18 13:42
Just to be clear, what type of reaction are you expecting? Because the only reactions she gives are a notification with a small comment on what she sees, and that's it. And you have notifications enabled, I'm assuming, not just window reacts.

**Comment by fallacious-red-panda12** [comment] 2020-09-18 20:46
> 
> 
> Just to be clear, what type of reaction are you expecting? Because the only reactions she gives are a notification with a small comment on what she sees, and that's it. And you have notifications enabled, I'm assuming, not just window reacts.

Yes, I've had them enabled for a while (a month, I wanna say) and nothing's been happening. I didn't really know what to expect (since, you know, I've never actually _gotten_ one), but I have gotten zero notifications since I turned them on.

**Comment by ThePotatoGuy** [comment] 2020-11-25 02:41
Both window reacts and alerts I think need to be on. If its still happening make a new issue.

[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-11-25 02:41 UTC
