### ISSUE TITLE
Bug with new topics

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8087] opened 2021-10-27 17:17 UTC
In the new update, new topics have been added, but for some reason only some of them function for me, while others do not work or do not appear for a reason unknown to me. For example topic about fireworks works while about being deleted doesn't work

**Comment by ThePotatoGuy** [comment] 2021-12-02 03:39
answering that would ruin the surprises.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-02 03:39 UTC
Labels: not a bug
