### ISSUE TITLE
[Suggestion] - Monika's MP3

### ISSUE THREAD

**Issue by Mosexelle** [Monika-After-Story/MonikaModDev#8525] opened 2021-12-29 21:22 UTC
Gentlemans, first of all, I don't speak English very well, so if you don't understand WTF I wrote don't hesitate to tell me what exactly is not clear to you.

In game one track is played on repeat, sometimes it's a little bit awful to listen for hours at the same track again and again. I know that player can change track, but I think it would be a good idea to give Monika her own MP3 with the possibility to include/exclude songs that will be played or/and form different playlists. Not like a current music menu, but like a different object (for example: a calendar).

**Comment by Mosexelle** [comment] 2021-12-31 03:58
Lurking around I found a very similar suggestion, here is link:
https://github.com/Monika-After-Story/MonikaModDev/issues/6565

**Comment by ThePotatoGuy** [comment] 2021-12-31 07:31
marking as duplicate of #2088

A visual representation of a music player wouldn't be related to playlist functionality.

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:03
[closing as duplicate]

**Closed by ThePotatoGuy** 2022-01-09 22:03 UTC
Labels: duplicate
