### ISSUE TITLE
[Suggestion] - Bigger Piano?

### ISSUE THREAD

**Issue by UnknownCop** [Monika-After-Story/MonikaModDev#9219] opened 2022-06-09 01:13 UTC
I was wondering if you could possibly make the piano longer than the 20 key piano that's already offered in-game.  While the 20 key piano gets the job done, I want to be able to play songs with a wider variety of notes for Monika.  This doesn't have to be done, I was just wondering if it could be. :)

**Comment by Wingdinggaster656** [comment] 2022-06-09 04:17
I personally like this idea because bigger pianos do provide more accurate melody.

But here's the thing: The piano playing is bad enough the way it is now, and I don't want to think about more keys.

**Comment by Justformas** [comment] 2022-06-14 06:18
Additionally, what keyboard keys would even be assigned to a bigger piano to make it feel right, other than more numbers for more sharps and flats? The keys "Q" to "]" are already used on the current piano, with the black keys being assigned to the appropriate number keys. I personally would like those keys to keep the current notes that are assigned to them, or retain that as an option without having to customize every key for that.

But what does that leave for more keys? "Tab", "\", numpad 7 8 9 and +? Even that would only be a range of 6 more notes (other than more sharps and flats on numbers), unless people would be willing to have more rows of keys.

**Comment by ThePotatoGuy** [comment] 2022-06-17 03:15
marking duplicate of #1923 

[closing as duplicate]

**Closed by ThePotatoGuy** 2022-06-17 03:15 UTC
Labels: duplicate
