### ISSUE TITLE
[Suggestion] Talking with Monika about mourning and telling her someone left you

### ISSUE THREAD

**Issue by emcchiaki** [Monika-After-Story/MonikaModDev#7460] opened 2021-07-11 12:08 UTC
[Suggestion] Talking with Monika about mourning and telling her someone left you

This may seem sad and gruesome, but I think it could add a reality to the "I'm feeling sad" reason. Maybe we could pick if a pet left us, or a parent maybe...

**Comment by fromulus** [comment] 2021-07-11 13:48
So, just in case you're making this issue due to a past experience, recent or not, I should probably start with saying I'm sorry for your loss (again, assuming something like that happened to you).

With that being said, this kind of topic is problematic to tackle and like the Player's death, it is preferrable for us to just not acknowledge it at all.
The problem is that talking about these things is very heavy and difficult, all the more so for people currently mourning, and we have no way of judging accurately how the player is currently feeling, what their temperament is like and so on.

Meaning that while some words of recomfort could help to soothe some people's pain, it could just as well come off as completely inapropriate to other people.
There is really any way to come up with a solution that would satisfy everyone, and since it's unlikely that Monika alone could help someone dealing with this on her own, especially from where she is right now, we would rather avoid taking the risk of deeply hurting some players just for the sake of only partly recomforting some others.

**Comment by ThePotatoGuy** [comment] 2021-07-29 02:54
[closing as rejected]

**Closed by ThePotatoGuy** 2021-07-29 02:54 UTC
Labels: suggestion
