### ISSUE TITLE
Problem with new update 10.2 about not having option to change ribbon.

### ISSUE THREAD

**Issue by DABnoREGRET** [Monika-After-Story/MonikaModDev#4937] opened 2019-10-30 15:03 UTC
For some reason i can not see the option to change Monika ribbon.
I have the sprite pack installed.
I also don't have any special day costume if that does affect.
Here are the logs.
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3789619/mas_log.txt)
[log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3789622/log.txt)
[logger_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3789638/logger_log.txt)
Thank you in advance!
EDIT:
Sorry here is the 
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3794144/aff_log.txt)
EDIT 2:
![image](https://user-images.githubusercontent.com/57186199/68024085-a521bd80-fcdb-11e9-9fbe-5c94ac633a06.png)
Here a picture of the problem if my text were abit too confusing (sorry)

**Comment by RavenPLAYER** [comment] 2019-10-30 17:59
Remember the option "Can you change your ribbon?" is no longer, now is "Can you tie your hair with something else?", do you see that option in your MAS?

**Comment by DABnoREGRET** [comment] 2019-10-31 09:33
But then for that instance that there were no option

Ahh maybe you need to restart your computer to fully update the game?

**Comment by DABnoREGRET** [comment] 2019-10-31 14:06
Sorry here is the aff log:
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3794101/aff_log.txt)

**Comment by multimokia** [comment] 2019-10-31 15:53
Hm, okay. Well it's high enough but yeah, the prompt was just changed.

**Comment by DABnoREGRET** [comment] 2019-11-04 14:58
Ummm sorry but i have an edit on the main post, can you check it ?

**Comment by thezotikrus** [comment] 2019-11-04 15:05
Ask her to change her hair style. She can't wear a ribbon with hair down.

**Comment by DABnoREGRET** [comment] 2019-11-06 09:05
Ahhhhhhh I see thank you Sorry dumb me

**Comment by ThePotatoGuy** [comment] 2019-11-13 03:39
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-11-13 03:39 UTC
Labels: not a bug
