### ISSUE TITLE
error message incorrectly implies there is an 'update/' folder in 'game/' even when there isn't

### ISSUE THREAD

**Issue by LeeSpork** [Monika-After-Story/MonikaModDev#9949] opened 2023-04-05 11:34 UTC
in updater.rpy line 921, it checks `if not persistent._mas_can_update` and displays the following message:

> Error: Failed to move 'update/' folder. Please manually
move the update folder from 'game/' to the base 'ddlc/'
directory and try again.

This message implies that there exists a folder `ddlc/game/update/`, however there is no check if this is actually the case.

If it happens that this folder does not exist for whatever reason, then the above error message displayed to the user becomes incorrect and unhelpful. This situation was encountered by Basil on the Discord here: [(Discord message link)](https://discord.com/channels/372766620977725441/393978515802030091/1093127764179177593)

(Maybe in this case, the error message should instead provide instructions on how to get a new 'update/' folder? Though I personally don't know how the updater works so I don't know.)

**Comment by Booplicate** [comment] 2023-04-05 16:20
The error happens when we fail to move the folder by any reason (e.g. if it's not there). However there should always be that folder.

**Comment by ThePotatoGuy** [comment] 2023-06-15 00:30
[closing as not a bug]

**Closed by ThePotatoGuy** 2023-06-15 00:30 UTC
Labels: not a bug
