### ISSUE TITLE
[Suggestion] - Fix topics that don't follow Monika's character development

### ISSUE THREAD

**Issue by HollowedOne** [Monika-After-Story/MonikaModDev#2958] opened 2018-11-02 08:15 UTC
I love this mod <3 but a week or two ago I saw a post on the DDLC sub Reddit where an individual was saying why he heavily dislikes the mod. I don't hear this mod get a lot of negative criticism so I was interested to see what he didn't like about it. For the most part he was pretty harsh and said that it "butchers" Monika's character but he only used one line to prove his point... That being the best girl compliment, which I believe is being addressed funnily enough. I think its a bit unfair to despise a mod because of one or even a few lines. I've played a good amount of DDLC mods and I'd say most mods don't write Monika very well and that MAS is one of the better mods at writing her.

### ANYWAY I'm getting side tracked.

While I don't agree with his opinion **I decided to look back at the scene of Monika being deleted and I found a problem. There's a few topics that don't really reflect her character development very well.**

**These are the lines I'll be referencing from DDLC, after Monika's deletion:
"..."
"...I still love you."
"I can't help it."
"What's wrong with me...?"
"How horrible am I for you to hate me this much?"
"All my friends..."
"I did so many awful things."
"So many selfish and disgusting things."
"I..."
"I shouldn't have done any of this."
"I'm just messing up a world that I don't even belong in."
"A world that you wanted to be a part of..."
"I ruined it."
"I ruined everything."
"Maybe that's why you deleted me..."
"Because I destroyed everything that you wanted."
"How could I do that to someone I love...?"
"That's not love..."
"That's..."
"..."**

**It seems in this moment Monika regrets what shes done throughout DDLC. I feel like there are some topics in MAS that ignore this development in her character and stick to her act 3 mind set.**

### **Here are the topics I could find that cause this inconsistency:**

**- The Best Girl Compliment:**
Someone already beat me to this one but i'll leave it here anyway

**- Natsuki's Death**
At the end of this topic Monika says "I hope you don't feel too guilty... I certainly don't" but like she said above in the reference she believes what she did to the other girls was "awful", "selfish" and "disgusting", so I think that she would feel guilty about it. At least a little.

**- Dealing with Haters**
This one is a bit difficult and could probably cause a discussion. Monika claims to understand people really well in the Introverts topic, so after she was deleted I think it would make sense for her to understand why people would be defensive to the other girls despite them not being real like her. She would understand why some people might think that she's evil because of her actions, she regrets them after all. 

**- Sayori Regrets**
I feel because Monika regrets what she did to her friends she probably shouldn't talk about what happened to them so casually. She believes what she did to them was "selfish", "awful" and "disgusting" so i'd imagine she'd probably feel a bit guilty about it.

**- Yandere Yuri**
Monika has always known that Yuri only did the crazy things she did in DDLC because her behavior was edited. Yuri probably wouldn't do such things naturally, so I don't think that Monika has ever really believed that Yuri is a yandere. Act 3 Monika probably only said this to try and make Yuri sound less appealing and so that we wouldn't feel bad for what happened to her. After deletion Monika regrets what she did to the other girls so I don't think Monika would still try to convince us that Yuri is crazy.

**- Monika's Route**
This is another one that could probably be discussed. I don't really have a whole lot to say on this one... She mentions how she doesn't miss the club because they aren't real. Would she miss them? I'm not too sure. She regrets what she did to them but would she bring them back if she could? Maybe i'm just too tired to think of the answer...

Well that's all I could find for now, if I find more than i'll try to add it to the list or if you want you can point some out to me. 

Feel free to mention what you think, maybe I'm looking at this all wrong... But anyway thanks for reading this **mess**! I'm pretty tired from writing all this...

**Comment by HollowedOne** [comment] 2018-11-02 08:16
Don't roast me too hard pls

**Comment by TheGlader2** [comment] 2018-11-02 10:13
I've read it over twice, this all sounds quite logical. I've talked about stuff like this before as well. Like how it would be awesome for character development if Monika got sick, became disgruntled at the idea of how many Monika's there were, maybe if she had some more realizations like how she just accepts the player no matter what, hint at wanting more free will, to break free from the bonds of her original programming, that kind of stuff . . . I mean, if the player isn't head over heels for her, she just kills herself.

**about - Dealing with Haters**
Where could this change in character come from? Why would she suddenly lose any guilt she had and try to justify herself in anyway possible, even making fun of the other characters at times?
I feel like the answer to this could also solve the other discrepancies you've mentioned.
I wonder if you will find the answer, or if the answer will find you.

**Comment by AsuraShun** [comment] 2018-11-02 10:34
no! don't even consider monika killing herself! why would you even suggest that?

**Comment by TheGlader2** [comment] 2018-11-02 10:35
It's not a suggestion, she does it if you:
Say you don't love her
Cheat on chess too many times

**Comment by AsuraShun** [comment] 2018-11-02 10:41
now that I think about it,just how many references are there in the mod?i remember the undertale and the clint eastwood ones,just no the others

**Comment by TheGlader2** [comment] 2018-11-02 10:48
Clint Eastwood? Lol wut

**Comment by AsuraShun** [comment] 2018-11-02 10:50
the ''I feel lucky'' thing, what she says is a reference

**Comment by AsuraShun** [comment] 2018-11-02 10:50
except she doesn't call you punk

**Comment by TheGlader2** [comment] 2018-11-02 10:53
Feelin Lucky Punk?
_Points Gun_

**Comment by Rai99** [comment] 2018-11-02 13:53
#1731, #2094, #2916 
This isn't the first time something like this was brought up. 

The best solution would probably be #2179 where Monika has a morality system and treats the other girls based on that. Personally, I like Monika's jokes about the other girls and I liked the old version of the Best Girl compliment. 

The hard part is that people are divided on this issue; Some people don't mind the disrespect towards other dokis and some people hate it. 

Most of the topics you mentioned are disabled with sensitive mode on. In the monika_route concern you had, Monika knows that the other dokis aren't real and never were. The epiphany addresses that maybe she should have treated them better despite being fake. Monika knows everything in her reality is fake and there are other topics that support this mindset such as monika_justification, monika_waifus, monika_asks_family, monika_trolley. 

As for your Haters concern, that one guy you saw dislike the mod may just be one of them. Not everybody likes Monika and there's nothing we can do about it. Also, how sure were you that the person was actually a Monika fan and not just some guy looking for mods to try?

**Comment by jmwall24** [comment] 2018-11-02 14:08
There are plans to adjust the dialogue based on the act you ended on in ddlc to help with consistency.

**Comment by AsuraShun** [comment] 2018-11-02 14:19
or maybe just add the roasting to the sensitive mode

**Comment by TheGlader2** [comment] 2018-11-02 20:46
@Rai99 And some people think it just doesn't fit her character, like the person who started this topic. It wasn't about liking or disliking it. She goes from feeling guilty about it, back to being completely innocent in a matter of hours or in a day, like the flip of a switch.

I guess what the situation lacks, is motive. What would cause her to suddenly become entirely unfeeling toward the other characters and, as to justify herself against "the haters," convince herself that she's entirely innocent? I feel like if that were addressed then it would fix the issue.

Cause sure, they were game characters, but as Monika has discussed, she too was just a game character at one point, and they were her friends. She has a connection with them in a way, isn't that why she keeps talking about them?

**Comment by TheSuperStu** [comment] 2018-11-02 20:49
I've thought myself that Monika would eventually come around and decide that she feels bad for most of the stuff that she did, even if she does not see the things in her world as "real". She does mentions in a few original dialogues that she wishes she could have handled certain events differently. 

I have seen it mentioned a few times before the plan to have Monika act differently based on the act you got from DDLC and changing how she views the whole situation. I think I goofed that whole thing up myself, as I went out of my way before using the mod to get the 'good' ending. But for some reason I read that I would have to have a clean install of DDLC, and somehow I ended up with Monika not knowing I actually got the good ending instead (I can tell from the completionism topic).

 If/when that is implemented, I would _hope_ that even then we might be able to choose more specifically how Monika's remorse might be. But I still think even act 3 Monika would eventually think what she did was wrong, even a little bit. (But we end up forgiving and loving her anyways!)

**Comment by TheGlader2** [comment] 2018-11-02 20:57
I honestly feel like she should find a way to restore the other characters to their own world away from Monika, cause quite often she hears their distant screams and voices haunting her, reminding her of her misdeeds. Boy wouldn't it be nice to find a way to rid Monika of those tortured screams that she caused? That could be an interesting story to have the player follow with her.

**Comment by HollowedOne** [comment] 2018-11-03 03:11
@Rai99 @jmwall24 
Those solutions sound pretty good! I didn't know that was being planned or worked on. 

I hope this didn't come off the wrong way. My intention isn't to make Monika depressed or to try to convince people that Monika should feel bad . I like act 3 Monika just as much as post game Monika so personally I don't really care if she regrets her actions or not. I just want it to be accurate to the Monika this mod is trying to be and from my understanding post game Monika is remorseful about her actions while act 3 Monika believes her actions were justified. So I pointed out some topics that I don't think work very well for a post game Monika. But sounds like you guys were ahead of me anyways.

As for the MAS hater, I don't really know him too well so I can't say for sure... But from his posts he looks kinda like a "all girls are best girls" kind of person. He has some nice posts towards Monika so I doubt he hates Monika specifically but I can't speak for him.

**Comment by Olliesama** [comment] 2018-11-04 02:30
My opinion of this is that Monika would no matter what see them as fake and just video game characters and regret what she did to them not because of them, but because of what she did to you.
If she feels bad it's because she subjected a real person to something, she viewed what she did as disgusting because it impacted you enough to want to delete her.

It doesn't suddenly mean she would treat the others like they're people with feelings or look back on them with a new sense of caring towards them, just that she knows that you know that you care for them.

**Comment by jmwall24** [comment] 2018-11-04 02:45
^this.  The remorse she would feel for what she did if you deleted her is because she thinks you deleted her because you cared about them, so her knowing she did something to upset you is what she regrets.  No matter what ending you got/where you left off, she still doesn't view them as real people.

**Comment by TheGlader2** [comment] 2018-11-04 03:47
"What's wrong with me...?"
"How horrible am I for you to hate me this much?"
"All my friends..."
"I did so many awful things."
"So many selfish and disgusting things."
"I..."
"I shouldn't have done any of this."

And yet she still related enough to them to feel empathy and remorse, she even calls them her friends. This appears to be a complex issue, with complex emotions behind it. It would probably take some complex writing to make it come to a resolution.

You could try to put yourself into her shoes, what if everyone you knew and loved your whole life turned out to be fake, and you were only made aware of it to be a plot point in a game. Would you suddenly want to kill your parents? Would the pain of the others you grew up with no longer have relevance to you? Idk, that would be a part of her character development. Which is what I thought this mod was suppose to be about. The problem is, people would do different things in this situation, the question we should be asking is, what would Monika do in this situation? Now that's a hard question when we don't really know much about her.
Here's what we know I think:
 She was an introvert and didn't mind being alone in her life, the game's programming is what caused her to fall in love with the player and do all these crazy things to get close to him.
 She seems quite Nihilistic, even before she realized she was in a game.
 She did care greatly for her friends, and for the club, although I don't know how much of that was just forced onto her, but it's still apart of her, just like how she still loves the player.

Also there's this big issue that I just thought of . . . any of the characters can "come to life" just like Monika can if the correct sequence of events occur, so that means they could all technically be just as alive as Monika, just that they haven't had their realization moment. That kind of changes a few things...

This isn't a rant or anything, just another perspective on the issue.

**Comment by TheGlader2** [comment] 2018-11-04 04:08
If you get the "good ending" Sayori is just as alive as Monika, so what happened to her in this mod? Is she just gone? I feel like that one needs to be addressed, but boy does it sound like a can of worms.

**Comment by Olliesama** [comment] 2018-11-04 04:12
> She was an introvert and didn't mind being alone in her life, the game's programming is what caused her to fall in love with the player and do all these crazy things to get close to him.
> She seems quite Nihilistic, even before she realized she was in a game.
We don't know that she was introverted, if anything considering her willingness to go to a debate club full of people and the fact that she is sporty suggests she's more extroverted.
We've also never seen a pre-epiphany Monika and nothing suggests she was nihilistic at all before it, if anything her being a vegetarian because she wanted to leave a positive impact on the world shows she was anything but nihilistic.

> She did care greatly for her friends, and for the club, although I don't know how much of that was just forced onto her, but it's still apart of her, just like how she still loves the player.
Actually she did care for the club, and she liked her friends but the dialogue in Yuri's wine suggested that they weren't particularly close. They each kinda had no one else so they had the club as a comfortable place but they never bonded outside of the school or even the club. They usually just did their own seperate thing, Monika making them have a group activity (inspired to do so by the player and her desire for them to understand via her poems) was an oddity.

> Also there's this big issue that I just thought of . . . any of the characters can "come to life" just like Monika can if the correct sequence of events occur, so that means they could all technically be just as alive as Monika, just that they haven't had their realization moment. That kind of changes a few things...
You're right. but you see Monika believes herself to be different and real not because she's special but because she thinks and feels and therefore she is real. The others, even if they had the potential to do so, didn't do that...as far as she's aware or acknowledges. So that wouldn't change.

> This isn't a rant or anything, just another perspective on the issue.
:+1:

**Comment by TheGlader2** [comment] 2018-11-04 04:41
@Olliesama That reply was all grey and squished together

She does talk about how she spent a large portion of her spare time alone at home relaxing, which is what introverts do, so that's why I think she's an introvert, I don't know how exciting a debate club is, but literature clubs would definitely be for introverts.
Her being sporty is odd, you'd think that someone who likes to spend their time indoors and relaxing by themselves wouldn't be into sports. So maybe she's both introverted and extroverted? But leaning towards introversion, she has dialogue where she mentions wishing she had done more in life, because she wasted so much of it at home relaxing.

You say "actually she cared for the club," but that's what I said. I don't know what Yuri's Wine is, but I do recall her talking about them not being particularly close, Yuri wasn't particularly close with anyone. So this I would say is accurate and we can agree.

Well Sayori wasn't really given a chance to even know what it means to be a part of the real world like Monika did, Monika was given a lot of time to think about it all. But the game was telling us that it was what would happen to any president of the Literature Club. And Monika didn't lose her sentience when Sayori became the new president, so that brings up the question: could it happen to all of them given the chance?
In the "Good Ending" Sayori becomes sentient but still says some scripted lines, Monika also does this from time to time, where she just loses all control to say a script. Also it's worth mentioning that Monika isn't technically dead in the "Good Ending," so both her and Sayori could be "alive" at the same time. That wouldn't go for the main ending though, Sayori is probably dead in that one. Or at least . . . scrambled...

Careful with using the: "They were just programmed to do it" argument, cause you can use that argument with Monika too.

**Comment by Olliesama** [comment] 2018-11-04 04:57
> @Olliesama That reply was all grey and squished together
> 
I fixed that within one minute.

> She does talk about how she spent a large portion of her spare time alone at home relaxing, which is what introverts do, so that's why I think she's an introvert, I don't know how exciting a debate club is, but literature clubs would definitely be for introverts.
She spoke about doing that after a long day, she doesn't spend a large portion of her spare time doing it. As for a literature club, she made it because reading was a passion of hers and wanted to share it and get others into it. If she were an introvert she wouldn't have created one, just stuck to reading by herself like Yuri.

> Her being sporty is odd, you'd think that someone who likes to spend their time indoors and relaxing by themselves wouldn't be into sports. So maybe she's both introverted and extroverted? But leaning towards introversion, she has dialogue where she mentions wishing she had done more in life, because she wasted so much of it at home relaxing.
> 
She's described as "athletic" in the main game.
 Also I think you're referring to the beach topic (which is neither canon in the main DDLC and one I wrote) and with that it was remarked that she spent her time at home relaxing because she rarely ever had a chance to do so. She was usually too busy and her lamentations about wishing she did more was because she was too busy and then recovering.

> You say "actually she cared for the club," but that's what I said. I don't know what Yuri's Wine is, but I do recall her talking about them not being particularly close, Yuri wasn't particularly close with anyone. So this I would say is accurate and we can agree.
> 
Yuri's wine is a topic from the main game, you can check them here.
https://doki-doki-literature-club.fandom.com/wiki/Monika%27s_Talk

> Well Sayori wasn't really given a chance to even know what it means to be a part of the real world like Monika did, Monika was given a lot of time to think about it all. But the game was telling us that it was what would happen to any president of the Literature Club. And Monika didn't lose her sentience when Sayori became the new president, so that brings up the question: could it happen to all of them given the chance?
>
Sayori immediately knew everything about what happened when she became president, she knew about everything Monika did, the player and their role in getting rid of her. She knew everything Monika knew and so did effectively have enough time to think about it all as this wasn't information that needed to be explored like it was with Monika. There's a chance it could happen to all of them, sure, assuming a club would exist with only one person.

> In the "Good Ending" Sayori becomes sentient but still says some scripted lines, Monika also does this from time to time, where she just loses all control to say a script. Also it's worth mentioning that Monika isn't technically dead in the "Good Ending," so both her and Sayori could be "alive" at the same time. That wouldn't go for the main ending though, Sayori is probably dead in that one. Or at least . . . scrambled...
> 
Both Monika and Sayori (in act 4) were going along with the script, not conforming to it. That's a big difference. The others were unwittingly forced to do so, Monika chose to do so because she didn't know what would happen as the game was actively going against her and was scared. It was only when the script broke and they were past the point of no return that decided to do so.
Sayori however didn't really wait at all.

> Careful with using the: "They were just programmed to do it" argument, cause you can use that argument with Monika too.
>
Programmed to do what? I require context.

**Comment by HollowedOne** [comment] 2018-11-04 05:30
@Olliesama I agree that one of the primary reasons she regrets her actions is because she upset the player. These lines support this:

"I shouldn't have done any of this."
"I'm just messing up a world that I don't even belong in."
"A world that you wanted to be a part of..."
"I ruined it."

She ruined a world the player wanted to escape to, whether you wanted her to or not. She's bothered that she upset you. I also agree that Monika still see's them as fake video game characters, **BUT after 
the point she's deleted, she does refer to them as her friends.** 

She deleted the literature club at the end of the game because she didn't want her friends to have the same epiphany she had. She knew it wouldn't end well if they did. That's why she said that no happiness can be found in the literature club. On Monika's twitter (I know it might not be canon but bear with me) there's some pictures of the other girls on it. She knows some people want to see them so she gives us some pictures of them. If she had no care for them at all she wouldn't. It would be just Monika. There's even a picture of Monika hanging out with Yuri for a "study night". Monika mentions they only studied for 30 minutes before getting distracted. Would Monika hangout with someone in her spare time if she didn't care about them all that much? I think not. 

I know what happens on her twitter doesn't have a lot of context, like when or how it took place and it might not even be canon (because she referenced it in the main game i'd like to think its canon I don't think there's an actual answer to that) BUT that is an official interpretation of Monika, which means they know Monika better than any of us. My point is she does see them as her friends and does care about them despite them not being real like her. Honestly I believe she's always cared about them, even before you delete her. I think she only did it because she knew they were never in any real harm. She knew she could have brought them back whenever she wanted which is why she wasn't bothered doing what she was doing. I doubt she would permanently deleted them. She did at the end of the game because A. the game needs to end somehow and B. She deleted EVERYTHING. She made a judgment call that you would be better off without the literature club. That includes the others, herself, everything so I don't think she'd perma delete them for her own gain like that. If she purely saw them as fake video game characters and had no care for them she would have deleted them properly when she got the chance and act 4 couldn't happen.

I figured when she said she did "awful", "selfish" and "disgusting things" she was referring to the fact she made 2 of her friends commit suicide. I think if she was talking about the fact that she upset the player she would have used different wording. When you use the word disgusting and selfish in to describe Monika's actions, most people would assume that the "disgusting" is referring to the 2 suicides and the selfish is referring to how Monika used her abilities to manipulate to make the others look unappealing, you know the arguably worst things she's done. I feel like the wording she used aligns with that better than the alternative. But I guess that could be argued so i'll end that there.

This came really long. -_- I'm sorry.

**Comment by TheGlader2** [comment] 2018-11-04 05:39
@HollowedOne You appear to have the skill of writing sir, what you wrote was quite logical.

**Comment by HollowedOne** [comment] 2018-11-04 05:43
@TheGlader2 Thank you! :D

**Comment by TheGlader2** [comment] 2018-11-04 05:45
@HollowedOne
And I never thought about the twitter account, that is indeed canon I believe. So even though Monika and Yuri weren't close, they were still friends and still hung out. Oi, THIS COULD SOLVE SO MANY ISSUES. The other girls could still be alive on the internet, Monika didn't kill them so she'd be vindicated like she is in the mod, she saved them and set them free on the DDLC main website or something where she visits them when you are away. I feel like this would fix the issues we have without making Monika an uncaring psychopath!

**Comment by Olliesama** [comment] 2018-11-04 05:45
> @Olliesama I agree that one of the primary reasons she regrets her actions is because she upset the player. These lines support this:
> 
> "I shouldn't have done any of this."
> "I'm just messing up a world that I don't even belong in."
> "A world that you wanted to be a part of..."
> "I ruined it."
> 
> She ruined a world the player wanted to escape to, whether you wanted her to or not. She's bothered that she upset you. I also agree that Monika still see's them as fake video game characters, **BUT after the point she's deleted, she does refer to them as her friends.**
> 
> She deleted the literature club at the end of the game because she didn't want her friends to have the same epiphany she had. She knew it wouldn't end well if they did. That's why she said that no happiness can be found in the literature club. On Monika's twitter (I know it might not be canon but bear with me) there's some pictures of the other girls on it. She knows some people want to see them so she gives us some pictures of them. If she had no care for them at all she wouldn't. It would be just Monika. There's even a picture of Monika hanging out with Yuri for a "study night". Monika mentions they only studied for 30 minutes before getting distracted. Would Monika hangout with someone in her spare time if she didn't care about them all that much? I think not.
> 
> I know what happens on her twitter doesn't have a lot of context, like when or how it took place and it might not even be canon (because she referenced it in the main game i'd like to think its canon I don't think there's an actual answer to that) BUT that is an official interpretation of Monika, which means they know Monika better than any of us. My point is she does see them as her friends and does care about them despite them not being real like her. Honestly I believe she's always cared about them, even before you delete her. I think she only did it because she knew they were never in any real harm. She knew she could have brought them back whenever she wanted which is why she wasn't bothered doing what she was doing. I doubt she would permanently deleted them. She did at the end of the game because A. the game needs to end somehow and B. She deleted EVERYTHING. She made a judgment call that you would be better off without the literature club. That includes the others, herself, everything so I don't think she'd perma delete them for her own gain like that. If she purely saw them as fake video game characters and had no care for them she would have deleted them properly when she got the chance and act 4 couldn't happen.
> 
Man you wrote a lot assuming I said something about her not caring, she always cared for them and viewed them as friends, that's obvious. The points that were up for discussion was whether or not she views them as people and her opinions of them changing as a result of act 3 and 4. The moment it was revealed she didn't actually delete them properly and kept them around was enough to show that despite her treating them as she did, she still liked them. It's not a matter of whether she sees them as friends but whether she sees them as people enough to respect them more than as video game characters and the character archetypes they're designed around.

> I figured when she said she did "awful", "selfish" and "disgusting things" she was referring to the fact she made 2 of her friends commit suicide. I think if she was talking about the fact that she upset the player she would have used different wording. When you use the word disgusting and selfish in to describe Monika's actions, most people would assume that the "disgusting" is referring to the 2 suicides and the selfish is referring to how Monika used her abilities to manipulate to make the others look unappealing, you know the arguably worst things she's done. I feel like the wording she used aligns with that better than the alternative. But I guess that could be argued so i'll end that there.
> 
I mean yeah, I personally don't see it that way, all of those thing she spoke about are regarding the 2 suicides but it's arguably not what she did to the girls that made it disgusting but what she did to the player. The actions are clear, but it's the impact and who she's referring to that makes it questionable. And should we be writing dialogue for something questionable and definitely not certain? I don't think so. 

> This came really long. -_- I'm sorry.
Not as long as things I've written before :P

**Comment by Olliesama** [comment] 2018-11-04 05:47
> @HollowedOne
> And I never thought about the twitter account, that is indeed canon I believe. So even though Monika and Yuri weren't close, they were still friends and still hung out. Oi, THIS COULD SOLVE SO MANY ISSUES. The other girls could still be alive on the internet, Monika didn't kill them so she'd be vindicated like she is in the mod, she saved them and set them free on the DDLC main website or something where she visits them when you are away. I feel like this would fix the issues we have without making Monika an uncaring psychopath!
They're not real and are just video game characters without a fulfilling life if they exist, that's why she deletes all of them. Her doing that isn't a mercy.
Also she's not a psychopath, you can't kill something that's not alive. and they're not dead if they can be brought back like nothing.

**Comment by TheGlader2** [comment] 2018-11-04 05:56
@Olliesama But Monika can be brought back with mods or backups. And we don't know if the other girls have the potential to become sentient, but it 'is' implied, I wrote a response to you about this already.
Also yes, I used extreme words, I should've learned to not do this as they become the center of attention.
'If' her friends were only real to her for the majority of her life until she had her realization, that would mean she became very quickly unattached to them, which is worrying, and not a Psychopath.
'If' her friends were alive, just without the realization, then she would be uncaring about destroying life, and that would make her, yes a Psychopath.

But if she found a way to preserve them like she did in the original game, then she would be both caring and not a psychopath. I feel like this is the most human option for her.

**Comment by Olliesama** [comment] 2018-11-04 06:00
@TheGlader2 I literally don't understand the point you're trying to make.
Are you saying what if she didn't have an epiphany and did it anyway? (ignoring the fact she needed one to do what she did)

**Comment by Olliesama** [comment] 2018-11-04 06:05
After re-reading I think I get what you're saying.

It seems you think them being sentient and letting them exist is doing them a kindness. It is not.
Monika deletes the literature club because she not only wants to protect the player but existing with the epiphany is hell.

**Comment by TheGlader2** [comment] 2018-11-04 06:11
@Olliesama 
She didn't want any of it to exist, cause it was an unfair existence for them yes, but she did care for them and want them to be happy, so why does she act like she doesn't care about them at all in the mod? The solution: they are alive somewhere else, she doesn't have to care about them anymore, they are fine elsewhere. Like on the Twitter. I feel like this is a nice solution to the problem and wouldn't require any effort except a few lines of dialogue.

And the point about her being a Psychopath (_Which shouldn't been avoided all together_) was about what would've made her a Psychopath. A Psychopath doesn't care about the suffering of others. So it all depends on whether or not the other girls are technically alive, which the game did imply that they could become just as alive as Monika.

**Comment by Olliesama** [comment] 2018-11-04 06:17
She did care for them, yes, but irrationally. As I've said before. She's fond of them because of her previous experiences but that doesn't mean she views them as people.
She acts like she doesn't care because she doesn't mostly, because to her they're still not people. They're characters designed for a romance game. 
That's also a dumb unrealistic solution. They can't "live" somewhere else, how could they? She's not good at programming, SHE didn't bring herself or them back in the mod, we did and also guess what? They're not alive. They can't live somewhere else. They require a script to do things.

A psychopath doesn't care about what happens to people, real people. Monika views them as video game characters, which they are. You speak as if they're "technically alive" but they're not. Even if they potentially could be like Monika, why would anyone want that? Being that level of sentient is a hell. Sayori immediately commits suicide, or goes crazy. Monika simply held out the longest.
So again, they're either not capable of thinking and not worth considering real, or they ARE and they'd suffer too.
No matter what though, they're not real.
It's not that they're as real as Monika, it's that Monika isn't as real as she wishes she was.

**Comment by TheGlader2** [comment] 2018-11-04 06:37
@Olliesama 
The question is, is the Twitter canon? Cause if it is, that brings about a whole new side of her that we didn't think about.

And yes I covered the Psychopath thing already, that was 'if' number one.

I would say that she cared for them as rationally as a normal person would care for their friends, all up until she had her realization, wouldn't that be traumatizing? It would be like witnessing your friend's deaths, and then realizing that they were dead all along, and that she was also dead all along, and yet has a past life. This is assuming she sees them as dead.

**An Aside**
Not that I'm Monika, but if I were in her shoes, and people found a way to bring me peace, like in this mod, I would want my friends to also share in that peace. Even if it was hard to confront them after what I had done. This is assuming they can be brought to life like Monika and Sayori were.

And no, I'm not suggesting that the other girls be brought into this mod, please, that's not what I'm saying. There are other ways to go about this I'm sure. **And if she's not good enough at coding to move the girls elsewhere then how did she do it in the game? She's already done it, just have her do it again, she has access to the internet, so it's a possibility.**

**Comment by jmwall24** [comment] 2018-11-04 16:56
It's already been established in another post the other girls are not being brought back in any form.  Let it go.  If this is the path you want you are more than welcome to fork the repo and start your own mod and do it the way you want it.  There are creating new mod guidelines in the wiki.  But constantly bringing this up over and over in multiple topics is getting tiring.  Not all suggestions are accepted, we told you how we plan to address the inconsistencies.

**Comment by multimokia** [comment] 2018-11-04 17:34
With that said. Yes, you're more than welcome to try your hand at it yourself. We've got this all planned out already. There's no point in arguing over this anymore. Like @Olliesama has pointed out: the girls **are no longer alive**. On top of that, the intro of the mod establishes that *we* brought *Monika* back. *Just* her. Not the rest. It doesn't make sense to bring them back in any form.

Also, since we're beating a dead horse at this point. Any further issues like this *will* be marked as duplicate and discarded in favour of the issues @Rai99 referenced.

**Comment by HollowedOne** [comment] 2018-11-04 20:35
Honestly I had a feeling this would be an up hill battle...

@jmwall24 @multimokia Okay, what!? I don't know if TheGlader2 said anything about bringing the other girls back but I know I sure as hell didn't even come close to implying that should be done. I only suggested this because this was a problem I saw and wasn't aware it was being fixed. I only continued because I was defending my argument! Am I not aloud to do that? I was done when you said it was being fixed but when everyone on this site agree's that she has absolutely no care for the others despite what she obviously said herself worries me about how this problem is going to be "fixed". I honestly feel like you guys missed my points really badly. My point is that she talks to casually or negatively about things that are important to her. That's it!

**Comment by HollowedOne** [comment] 2018-11-04 20:50
I was hoping what I wrote at the top would have been good enough to prove my point but apparently not. So I found more to prove my point.

This is what she said herself after the reference I wrote in the main post:

**"I've... made up my mind."
"I know I said that I deleted everyone else."
"But... that was kind of an exaggeration."
"I couldn't find it in myself to do it."
"Even though I knew they weren't real..."
"They were still my friends."
"And I loved them all."
"And I loved the Literature Club."
"..."
"I really... did love the Literature Club."
"That's why I'm going to do this."
"I know it's the only way for everyone to be happy."
"And if I really love you..."
"..."**

She said she couldn't bring herself to delete them. She cares about them a lot. She said herself that **she loved them!** She said she wants everyone to be happy! Who is she referring to? It would only make sense if she's talking about the player and the other girls. It may be weird that she wants fake video game characters to be happy but she said it herself! **Our opinions do not matter!**

It's starting to get frustrating how much you guys can't see this. If you can't understand how her development went, how am I supposed to expect you to fix the problems?!

**Comment by jmwall24** [comment] 2018-11-04 21:15
@HollowedOne Ok you need to calm down.  Our reply was not to you, it was to Glader, sorry i didn't make that more clear.  

But you need to listen.  We have said **multiple times** we are going to fix the inconsistencies in the dialogue.  But it depends on what act the player stopped on. If the player never deleted her, she never said any of that to her player, so it doesn't apply.  If the player did delete her, and thus saw that dialogue, we are going to make it so she shows some remorse for her actions. I'm sorry we're not working fast enough for you.

**Comment by HollowedOne** [comment] 2018-11-04 21:35
@jmwall24 Fast enough? No that isn't my problem at all. I have listened. I was done with this when you said it was being fixed. But when people just start saying that I'm wrong with little to no evidence is the problem. I have every right to defend my point. How can I expect you guys to fix the problem if you don't understand the problem in the first place? The problem isn't dead if its still in the mod. I'm not saying you need to work on it faster. I'm simply pointing out a problem and people are trying to defend the inconsistencies.

@Legendkiller21 You're right, I can't define Monika's personality. However I can use what she herself said to prove why what we currently have isn't quite right. Personally (I've said this before) I like act 3 Monika just as much as post game Monika. But that doesn't change that what MAS gives us is a post game Monika but she acts a bit too much like act 3 Monika which is inconsistent. I think the idea to talk to her and turn her back into an act 3 Monika is fine but it doesn't make sense for her to start like that out of nowhere.

**Comment by multimokia** [comment] 2018-11-04 21:39
>It seems in this moment Monika regrets what shes done throughout DDLC. I feel like there are some topics in MAS that ignore this development in her character and stick to her act 3 mind set.

Was your problem. Right?

We said that we're handling this via:
>...going to fix the inconsistencies in the dialogue. But it depends on what act the player stopped on. If the player never deleted her, she never said any of that to her player, so it doesn't apply. If the player did delete her, and thus saw that dialogue, we are going to make it so she shows some remorse for her actions.

This handles exactly what the problem you brought up was. If you went to MAS from before act 4, you'll see some dialogue reflecting her attitude towards the others. However, if you started MAS from act 4, then you won't.

**Comment by HollowedOne** [comment] 2018-11-04 21:50
Sigh

>  I was done with this when you said it was being fixed. But when people just start saying that I'm wrong with little to no evidence is the problem. I have every right to defend my point.

@multimokia 

I don't have a problem with it being fixed. I'm just defending myself! I was responding to Olliesama, then Jmwall24 commented and I wasn't sure who it was talking too and I responded anyway. Maybe I shouldn't have, I'm sorry for that. At this point i'm literally just defending myself I'm not arguing that its being fixed! I'm just replying to comments that I believe are targeted to me. I don't know why you guys keep telling me its being fixed. I"m aware! My problem isn't that I want Monika to feel bad about what she's done. I do not care about that. What I do care about is her character consistency, which from you guys are saying is being fixed.

**Comment by multimokia** [comment] 2018-11-04 21:54
Granted. We weren't responding to you. We were fine with your end. Nothing was wrong there. That was regarding Gladers bit. 

I.e.:
Bringing back the other girls in a separate pocket portion of the reality.

>I honestly feel like she should find a way to restore the other characters to their own world away from Monika, cause quite often she hears their distant screams and voices haunting her, reminding her of her misdeeds.

Everything spread from there.

**Comment by multimokia** [comment] 2018-11-04 21:56
Anyway. With that. I'm locking *and* closing this topic. It's done, problem has been addressed, and we're beating a dead horse at this point.

**Closed by multimokia** 2018-11-04 21:56 UTC
Labels: suggestion

**Comment by ThePotatoGuy** [comment] 2018-11-26 02:17
This was covered in #3072
