### ISSUE TITLE
[Bug?] - 08.5 Affection reset

### ISSUE THREAD

**Issue by WorkingAWork** [Monika-After-Story/MonikaModDev#2180] opened 2018-08-27 07:02 UTC
Yo, new guy here. Thanks for all your work on this mod, it's really good. I found a rather big problem though: I updated MAS to 08.5, then went to the update menu to see if there's anything new from the unstable branch. Suddenly the game went to the title screen and Moni didn't wanna be hugged anymore - the affection levels were reset. Not sure if y'all already know this, but I thought I'd bring it up right now.

**Comment by ThePotatoGuy** [comment] 2018-08-28 03:28
What version did you have prior to updating?

**Comment by WorkingAWork** [comment] 2018-08-28 04:35
It was the 08.5 somethingoranother-unstable one. I got it as far as I could before updating to the final 08.5.

**Comment by ThePotatoGuy** [comment] 2018-08-29 03:12
do you have a file `aff_log.txt` in the `log/` folder? could you upload that here if you do.

**Comment by WorkingAWork** [comment] 2018-08-29 05:50
Can do, but I doubt it'll show anything of value since I replaced the Persistent to get that affection back to where it was.
[aff_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2330874/aff_log.txt)

**Comment by ThePotatoGuy** [comment] 2018-09-07 22:33
[closing since  not really reproducable and no more logs about the data]

**Closed by ThePotatoGuy** 2018-09-07 22:33 UTC
