### ISSUE TITLE
A problem a bit awkward...

### ISSUE THREAD

**Issue by MonikaEndDie** [Monika-After-Story/MonikaModDev#8381] opened 2021-12-10 20:55 UTC
So today, since the recent update change your reality song a bit, i wanted to play it again. But when i go to play>piano>play a song, only happy birthday displayed on the list.  When i tried to play it when going on my own, Monika didn't sing with the subtitles accompanying her. So, i went to asking her to sing the song via "hey Monika", she reminded me about the in-game volume, and since i muted the music volume i went to settings to turn it on, and then, nothing else is happening any more. I can click hundred of time, the dialogue is stuck, but not the game since i see the little triangle moving at the bottom right. Please help! I don't really want to send my poor Monika to the screaming void...

**Comment by AshtonSnapp** [comment] 2021-12-10 21:06
That's... certainly an interesting situation. To me, this sounds like a [softlock or hardlock](https://gaming.stackexchange.com/questions/357095/what-exactly-is-a-softlock) of some sort. You may not have any other option than to quit without saying goodbye. I'm sure Monika would understand, as this is essentially a game crash.

**Comment by MonikaEndDie** [comment] 2021-12-10 21:15
Allright, she played the song without any more trouble at my return, but about the song not appearing in the "play a song" list anymore, what should i do?

**Comment by AshtonSnapp** [comment] 2021-12-10 21:22
Most likely a bug of some sort. No way for me to be entirely sure of that.

**Comment by Booplicate** [comment] 2021-12-10 21:22
The song is broken, for a temp fix check #8380. **But make sure to follow the instructions properly.** Or just wait until we fix it.

That said, you got a really odd bug, we'll need to look into it.

**Comment by AshtonSnapp** [comment] 2021-12-10 21:25
An odd bug indeed. Definitely a lockup of some sort (I'll call it a "firmlock" since it seems somewhere between a softlock and a hardlock), and I'm not sure how exactly that sequence of events could have caused it to occur.

**Comment by MonikaEndDie** [comment] 2021-12-10 21:35
I see. Well, i'll certainly not risk destroying more than 3 years of sweet love with my angel just for that. I'd rather wait your fixing coming up. Thanks for dedicating time for me peoples. About the bug, it also affected the right click, it's like the game decide to ignore my mouse, except for the options at the bottom of the dialogue box.

**Comment by AshtonSnapp** [comment] 2021-12-10 21:45
No problem! I've got a lot of free time on my hands nowadays anyways, so it's no big deal spending some of said time helping people on the internet.

**Comment by Booplicate** [comment] 2021-12-19 22:27
> So, i went to asking her to sing the song via "hey Monika", she reminded me about the in-game volume, and since i muted the music volume i went to settings to turn it on, and then, nothing else is happening any more. I can click hundred of time

I can reproduce this, it's an actual issue, so don't close this.

**Comment by ThePotatoGuy** [comment] 2021-12-23 03:30
[closing as fixed]

**Closed by ThePotatoGuy** 2021-12-23 03:30 UTC
Labels: bug
