### ISSUE TITLE
[Bug] - Search bar is too overpowered.

### ISSUE THREAD

**Issue by Retrolovania** [Monika-After-Story/MonikaModDev#7273] opened 2021-06-01 02:51 UTC
Apparently, the new search bar in "Hey, Monika..." not only lets you search for topics, but it also unveils ones that the player has not unlocked based on affection level (for some, it would seem).

**Comment by multimokia** [comment] 2021-06-01 02:52
Which ones are you seeing?

**Comment by Retrolovania** [comment] 2021-06-01 02:57
I'm personally not seeing anything unusual on my end, but I saw someone claiming they did. I'm not sure if it's a random bug with their installation or not.

**Comment by multimokia** [comment] 2021-06-01 04:26
I'm running a fresh install and searching things, but I cannot find anything which is not unlocked. Unless the person who experienced the issue can provide some screenshots of items which they shouldn't have so we can look into why they might be there when they shouldn't be, this issue is more or less invalid.

**Comment by Booplicate** [comment] 2021-06-01 08:47
It should filter out inappropriate evs. Ideally we need the persistent, it's hard to guess w/o real data.
https://github.com/Monika-After-Story/MonikaModDev/blob/4409f4f7987da1687405949ec2eeb967b4353474/Monika%20After%20Story/game/styles.rpy#L464-L465

**Comment by Ant9cp** [comment] 2021-06-01 21:15
This is not a issue for players with a 1000 or higher affection right?

**Comment by JessieChaaan** [comment] 2021-06-06 10:06
> I'm running a fresh install and searching things, but I cannot find anything which is not unlocked. Unless the person who experienced the issue can provide some screenshots of items which they shouldn't have so we can look into why they might be there when they shouldn't be, this issue is more or less invalid.

For me, the search bar unlocks topics that Monika never talked about to me, and still, I think that the search bar in "Hey, Monika..." shouldn't have the "repeat topics" thing.
What I'm trying to say is, that there are topics that Monika brings on her own volution that should stay in "repeat conversation" even if searched with the search bar in  "Hey Monika".
And as for the affection thing...well, I am at 248.5 affection and I didn't see anything unusual.
If you could please say what did the person who claimed the affection thing and on what affection level they were, I could search it on my own.
Thanks for listening,lmfao

**Comment by Booplicate** [comment] 2021-06-06 10:49
> the search bar unlocks topics that Monika never talked about to me

Can you give an example? Maybe a screenshot?

**Comment by Booplicate** [comment] 2022-10-05 18:54
The code looks fine and I cannot reproduce this, closing since no new information was provided. Also I've seen no other reports about our search.

**Closed by Booplicate** 2022-10-05 18:54 UTC
