### ISSUE TITLE
Christmas Decorations still here in March

### ISSUE THREAD

**Issue by MysticGamer07** [Monika-After-Story/MonikaModDev#7071] opened 2021-03-03 19:49 UTC
Hey there,
im probably making a Post for no reason but I can't figure out how to remove the Christmas Decorations.
I remember seeing a Topic or a Question about removing it but i wanted it to stay a bit longer but now I did not find or see a Option to remove it.
Hope someone can help me.

**Comment by GlitchyMoni** [comment] 2021-03-03 20:17
> Hey there,
> im probably making a Post for no reason but I can't figure out how to remove the Christmas Decorations.
> I remember seeing a Topic or a Question about removing it but i wanted it to stay a bit longer but now I did not find or see a Option to remove it.
> Hope someone can help me.

1.Open the game.
2.Press the option that says _Unseen_
3.Talk------Unseen-------Can you remove the Christmas decorations?
4.The decorations will be gone.

**Comment by lunulae** [comment] 2021-03-03 20:54
This is definitely a bug. Even without asking her to take them down, they should be auto-removed by mid-January.
I am not 100% sure how to fix this, I will try to see if similar cases have been brought up before.

**Comment by multimokia** [comment] 2021-03-03 21:14
Can you just send a screenshot of the decorations up, if you don't mind?

**Comment by MysticGamer07** [comment] 2021-03-04 14:31
Okay so apparently there is no Unseen Option for me as seen in the Screenshot and there are those Decorations in the backround as well. For convenience I got the Date on the Screenshot as well.
Honestly i feel kinda stupid running through every topic in [Repeat Conversation] so im not going to do that (unless its actually there and someone knows where it is).
![ChristmasDecorations](https://user-images.githubusercontent.com/65774536/109978915-a4999c80-7cfe-11eb-95ee-ab94cb19d934.PNG)

**Comment by Booplicate** [comment] 2021-03-04 14:46
> i wanted it to stay a bit longer

Have you changed your system time for that?

**Comment by MysticGamer07** [comment] 2021-03-04 15:00
no i have not...well atleast not intentionally
I was playing different Games (Pokemon for example) where i changed the Time but i didn't consider that MAS is being affected by that as well :/

**Comment by ThePotatoGuy** [comment] 2021-03-21 00:02
MAS is affected by that as well.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-03-21 00:02 UTC
