### ISSUE TITLE
A "To do list" with Monika's help. Also alarm and timer included

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#1914] opened 2018-07-13 02:37 UTC
You could do a to do list with Monika, you can type the to do list and organize it personally, there might be a "check" button when you check the to do list (lol) in other words you check when its done, as always she will motivate you when you make progress, you know, be creative there.
Timer, with the timer option you can set the time (lol) also alarm the same thing, and when time reaches its end, she can advice you with a simple "time's up dear" OR she can jump scream you, you can change settings once she jump screamed you once, then its your choice if you can set it to random, fixed or not to do it at all

**Comment by Rai99** [comment] 2018-07-13 03:28
> we are not doing a reminder system. At least, there are no plans to do that. #1829 

I don't think Monika would jumpscare you for something like this, especially if it's without knowing if you would even want that.

**Comment by HarmonicDistortion** [comment] 2018-07-13 21:44
I kinda like the idea of an alarm system and/or be able to customize the calendar which would be sweet.

**Comment by Rai99** [comment] 2018-07-13 22:20
I'm pretty sure calendar customization and the ability to add your own events is coming.

**Comment by loverofmonika** [comment] 2018-07-14 11:08
maybe one day, we might do a reminder system. for now adding more topics are what im focusing on.

**Comment by ThePotatoGuy** [comment] 2018-07-17 04:23
I like the TODO list idea. probably would just have Monika show you the list on startup or something.

I guess the issue is deciding how in depth the list could be. Having timers / timedeltas associated with todo items makes sense, but it would be limited to day / hour granularity because of the async nature of MAS.

**Comment by ThePotatoGuy** [comment] 2018-07-21 18:10
[Closing until we look into this]

**Closed by ThePotatoGuy** 2018-07-21 18:10 UTC
Labels: discussion, suggestion
