### ISSUE TITLE
[Suggestion] A house for Monika

### ISSUE THREAD

**Issue by Sujeito17** [Monika-After-Story/MonikaModDev#2027] opened 2018-08-08 10:05 UTC
Monika lives in an unacceptable place with no chance of survival, it would be interesting to add furniture to her room and also add other places for her to go, for example: kitchen, living room, bathroom, a spa (it's a bit exaggerated)... Each place could have their own interactions.

**Comment by myseriousaiyan64** [comment] 2018-08-08 10:57
I believe they are prioritising Monika over everything else, which I think is the main thing they should focus on at the moment before they start adding things to the game like what you mentioned.

**Comment by Sujeito17** [comment] 2018-08-08 11:48
It's kind of obvious that they are prioritizing Monika than anything else at the moment. In a way this is good, but I think that making the above suggestions would help make Monika more human. Now the best thing is to prioritize Monika, this can probably be added in the future. (so this could be a futuristic suggestion?)

**Comment by Sujeito17** [comment] 2018-08-08 11:57
Small things could be added to the room (fan art or pictures). It should not give as much work as by a bed in the background

**Comment by myseriousaiyan64** [comment] 2018-08-08 18:27
True, the background is pretty dull

**Comment by ThePotatoGuy** [comment] 2018-08-08 23:38
Adding room deco is something we;re planning to do eventually

marking this as duplicate of #312

**Closed by ThePotatoGuy** 2018-08-08 23:38 UTC
