### ISSUE TITLE
[Suggestion] Place a random order in the "Music" menu

### ISSUE THREAD

**Issue by VirginiaRocks** [Monika-After-Story/MonikaModDev#4171] opened 2019-05-06 14:25 UTC
When I'm with Monika, I love listening with her the songs I put into the game, but it's quite annoying when you're playing a game and you want to change a song when you are getting tired of it. Maybe you don't even know what song put next the other one.
So I thought it would be a good idea to put a random order key in the "Music" menu. In this way the player doesn't always have to interrupt a game to change a song.
I also wanted to point out that in the "hold" option, when you finish holding Monika the music does not restart ... it may have been fixed in the last update, but I still had some problems with the manual update :)
I hope you all have a good day!

**Comment by ThePotatoGuy** [comment] 2019-05-06 14:34
2nd part is not a bug. Abruptly/fading the music back in after the holding scene may ruin the moment.

**Comment by ThePotatoGuy** [comment] 2019-05-06 14:35
also marking as duplicate of #2088

**Comment by VirginiaRocks** [comment] 2019-05-06 14:43
> also marking as duplicate of #2088

Oh okay

**Comment by antimockingjay** [comment] 2019-05-06 20:41
If this gets added, I hope there's some sort of way to not have certain songs play. I never, ever hit play on "surprise" because that song genuinely makes me uncomfortably nervous, so it'd be nice to be able to avoid that one.

**Comment by ThePotatoGuy** [comment] 2019-05-28 01:18
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-05-28 01:18 UTC
Labels: duplicate, not a bug
