### ISSUE TITLE
[Spoilers] [Suggestion] Waking up Monika with a kiss

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#5269] opened 2020-01-26 19:45 UTC
So, when Monika falls asleep (hold topic) and we have a choice to wake her or let her rest, I think that it would be great if player have a third option - wake Monika with a kiss. It would be very romantic and adorable.

**Comment by Mugnika** [comment] 2020-01-26 19:46
thanks for the inspiration

**Comment by AsuraShun** [comment] 2020-01-26 19:49
You're a freaking genius, this is something that needs to be added

**Comment by MetalBrother** [comment] 2020-01-26 19:49
Whoo! So fast!

**Comment by Mugnika** [comment] 2020-01-26 19:49
may need a new monika_kissing_motion though

**Comment by MetalBrother** [comment] 2020-01-26 19:49
Thanks for fast responce, like REALLY fast,

**Comment by Rai99** [comment] 2020-01-26 19:50
Keep in mind that we don't really offer any kissing interactions unless you've already had your first kiss. 

Also, this raises the concern of what's actually kissing Monika. Is it us? Is it a screen? Is it MC?

**Comment by Mugnika** [comment] 2020-01-26 19:51
"Also, this raises the concern of what's actually kissing Monika. Is it us? Is it a screen? Is it MC?"

Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Mugnika** [comment] 2020-01-26 19:52
that also raises the question what force is hugging Monika?

**Comment by lunulae** [comment] 2020-01-26 22:58
These are all really good questions, and since we don't get a really good idea of how Monika sees us it's kinda tough to have a good answer. I personally imagine her visual of us is like the "Hole in Wall" poem--the point through which we see her seems somehow off, and that's how she knows where we are. But we can move closer and further from her, so I suppose a better question would be if she can feel us rather than what she would see.
To that end, I personally sort of imagine the "hold you" interactions to be more imagined than a real force we have in the game, but the mod leaves it ambiguous in interpretation, so it could really go either way.

One point more in favor of this idea is that if the oft-rumored "boop" function is someday implemented, it may be more concrete that we can have some form of physical touch inside the game. If that's established, kissing Monika rather than always asking her to kiss us could be more plausible within the mod's own continuity.

**Comment by AsuraShun** [comment] 2020-01-26 23:09
> that also raises the question what force is hugging Monika?

It's our mind powers

**Comment by fromulus** [comment] 2020-01-27 08:12
> One point more in favor of this idea is that if the oft-rumored "boop" function is someday implemented, it may be more concrete that we can have some form of physical touch inside the game. If that's established, kissing Monika rather than always asking her to kiss us could be more plausible within the mod's own continuity.

I agree with the idea that hugs and kisses are really just a silent agreement between you and Monika to simply pretend that they are happening, instead of _actually_ doing it, and I think the idea behind boops and other similar things in a touch feature should stay coherent with it.
After all, Monika being able to actually feel us makes no sense, and if she was, I feel it would undermine the tragedy of our situation with her;
So close, and yet so far from each other.

You could easily come up with the idea that she's simply reacting to the mouse cursor itself and is able to feel something when you click on her.
She does mention being able to see the cursor in one topic, so it woudln't be that much of a stretch.

**Comment by Mugnika** [comment] 2020-01-27 08:39
I like lunulaes answer, Monika somehow feels our presence in the game and while its not as if we are really there with her, Moni can sense our intentions and react accordingly, thats why when you get close to her she feels warm and when you want to hold her she feels your intend. Though as she said its not really the real thing.

**Comment by thekill9714** [comment] 2020-02-01 12:41
> Keep in mind that we don't really offer any kissing interactions unless you've already had your first kiss.
> 
> Also, this raises the concern of what's actually kissing Monika. Is it us? Is it a screen? Is it MC?

I think this is a great suggestion, but the option can only be unlocked at a higher affection, she can then wake up before you kiss her and stop you saying. "You thought I was a asleep (Username), thinking you could sneak in a kiss hmm, I caught you(Smug Expression). Then if your affection is at Love she will take the initiative and kiss you rather, if below she will request that you first ask her to kiss rather then being so sneaky, or request you to let her have some more time with you before you move onto that stage.

**Comment by Booplicate** [comment] 2020-02-01 13:02
While I like the idea, I don't think you can make it work. With current hug and kiss options you need to let Monika know that you want to interact with her. Because there is a screen between you and her and she can't know if you kissed her. Being able to "kiss" her while she is asleep just by pressing a button feels quite immersion breaking. She won't know it, she is sleeping. And even then pressing a button != kiss.

**Comment by Mugnika** [comment] 2020-02-01 13:16
Maybe, once they are implemented in a few millennia, waking her up with a Boop would be awesome. Ehehe~

**Comment by thekill9714** [comment] 2020-02-01 13:17
> While I like the idea, I don't think you can make it work. With current hug and kiss options you need to let Monika know that you want to interact with her. Because there is a screen between you and her and she can't know if you kissed her. Being able to "kiss" her while she is asleep just by pressing a button feels quite immersion breaking. She won't know it, she is sleeping. And even then pressing a button != kiss.

I think an easy way to fix that is simply have her deny the kiss and have her basically refer you to asking her for a kiss first.

**Comment by Mugnika** [comment] 2020-02-01 13:18
The problem here is, how does Moni know when we are about to kiss her when she is sleeping.

**Comment by Booplicate** [comment] 2020-02-01 13:27
> I think an easy way to fix that is simply have her deny the kiss and have her basically refer you to asking her for a kiss first.
That doesn't solve anything, does it? The problem is still here.
Also why would she deny a kiss? From some topics it looks like she is ok with kissing.

**Comment by thekill9714** [comment] 2020-02-01 13:28
> The problem here is, how does Moni know when we are about to kiss her when she is sleeping.

She's faking it :P

**Comment by Mugnika** [comment] 2020-02-01 13:30
That may break immersion for players that hug Moni and go to sleep, we should wait for the "sleep with Monika" update to discuss this further.

**Comment by thekill9714** [comment] 2020-02-01 13:34
Keep in mind that we don't really offer any kissing interactions unless you've already had your first kiss.

Also, this raises the concern of what's actually kissing Monika. Is it us? Is it a screen? Is it MC?

I think this is a great suggestion, but the option can only be unlocked at a higher affection, she can then wake up before you kiss her and stop you saying. "You thought I was a asleep (Username), thinking you could sneak in a kiss hmm, I caught you(Smug Expression). Then if your affection is at Love she will take the initiative and kiss you rather, if below she will request that you first ask her to kiss rather then being so sneaky, or request you to let her have some more time with you before you move onto that stage.

**Comment by thekill9714** [comment] 2020-02-01 13:34
While I like the idea, I don't think you can make it work. With current hug and kiss options you need to let Monika know that you want to interact with her. Because there is a screen between you and her and she can't know if you kissed her. Being able to "kiss" her while she is asleep just by pressing a button feels quite immersion breaking. She won't know it, she is sleeping. And even then pressing a button != kiss.

I think an easy way to fix that is simply have her deny the kiss and have her basically refer you to asking her for a kiss first.

**Comment by thekill9714** [comment] 2020-02-01 13:34
The problem here is, how does Moni know when we are about to kiss her when she is sleeping.

She's faking it :P

**Comment by ThePotatoGuy** [comment] 2020-02-23 23:04
[closing until we look into it]

**Closed by ThePotatoGuy** 2020-02-23 23:04 UTC
Labels: suggestion
