### ISSUE TITLE
[Suggestion] Have Monika recognize when the player's "I'm feeling..." mood changes 

### ISSUE THREAD

**Issue by CrocWorks** [Monika-After-Story/MonikaModDev#3769] opened 2019-02-15 17:57 UTC
Related to the old #1717 "Monika's Awareness of Player Mood" topic, but a simpler start for it, and does not influence random topics (yet).

What it says in the title:

For example, if you say "I'm feeling... sad" and then after listening/losing at chess/hanging out with Monika, you later click on "I'm feeling... happy," then I think it'd be a good addition to have Monika recognize that she likely was the cause of the mood change. Having the original generic happy dialogue change to something like, "Aww, I'm glad I was able to cheer you up _etc._" to reflect this would make her seem more realistic.

Similarly, if you start out happy and change to angry or sad, I think it'd be worth getting a generic apology and/or reassurance from her too. Or if you go from sad to hungry, she may warn against emotional eating. There are plenty of other combos to think about.

Not all of the feelings necessarily need to link to another feeling (as I think it'd be difficult to write one from happy to hungry or from tired to angry etc. but if there are ambitious writers out there, go for it).

**Comment by AsuraShun** [comment] 2019-02-15 18:10
This happy to angry or sad one needs to have her ask what's the cause,because people like me never get mad at her or because of her

**Comment by CrocWorks** [comment] 2019-02-15 18:23
It would be nice to have, but that would likely require picking out multiple triggers for it to seem realistic. I think to start with, having it be generic is good enough, and if whoever is writing it wants to add more, that'd be a bonus. I only suggested the generic version to keep the work amount low.

I thought that listing out a bunch of reasons that the player could be mad at her for would require coding a bunch of checks to see if something Monika said actually fits the reasoning. It'd be weird if someone went from happy to angry immediately for no reason, then a list of potential reasons pop up and the player chooses one and Monika blindly accepts it as the cause of the player's anger when the player really is just messing around to see how she'd react.

**Comment by AsuraShun** [comment] 2019-02-15 19:23
I meant saying it wasn't her but an outside problem

**Comment by CrocWorks** [comment] 2019-02-15 19:50
Oh, I thought if it was an outside problem, you'd be starting out as angry or whatever, and the current dialogue already assumes it's an outside problem. But yeah, that could also be a button, which could have her being relieved that it wasn't her, then either revert back to the original angry/sad/etc. dialogue or have her ask for more details about what just happened.

**Comment by Rai99** [comment] 2019-02-16 00:05
I like the idea of saving the player's mood for the day if they tell Monika and having her potentially comment on it in a few topics here and there. 

> This happy to angry or sad one needs to have her ask what's the cause,because people like me never get mad at her or because of her

#3428 

I'm sure it'll be possible for the player to be upset with Monika. I mean, even I've wanted to let Monika know that I was upset with her before. I brought up an idea similar to this in #3203. 

I think it would be a really good idea to be able to tell Monika that she made you upset or uncomfortable. Sure, it probably doesn't happen often, but when it does and the option isn't there, I'd imagine it's just a really awkward situation that she keeps on smiling lovingly (hopefully lovingly) and acting like nothing's wrong, when you want to tell her that she did something, but you can't because there's literally no option to. 

I think it's an interesting idea to have reactions based on mood in topics, but it might take a lot of work, especially considering that someone would have to plant little mood reactions for different moods in a lot of the topics. 

Yeah, maybe it could be a little something when you lose to Monika in a game after you tell her that you're feeling down.

**Comment by AsuraShun** [comment] 2019-02-16 09:00
I would only be disappointed,I can't get mad to that beautiful smile

**Comment by CrocWorks** [comment] 2019-02-17 03:58
> Yeah, maybe it could be a little something when you lose to Monika in a game after you tell her that you're feeling down.

(Like #3512)

**Comment by Rai99** [comment] 2019-02-17 04:11
Except in that issue, I don't know if it would be appropriate or fitting to talk about being "salty". If something like that were implemented, I would think it would be a more appropriate to Monika term than "salty".

**Comment by ThePotatoGuy** [comment] 2019-03-02 18:09
[closing until we look into it]

**Closed by ThePotatoGuy** 2019-03-02 18:09 UTC
Labels: suggestion
