### ISSUE TITLE
[BUG]In the morning, after open DDLC shortly, goodbye and sleep, option mojibake?

### ISSUE THREAD

**Issue by MansaSakura** [Monika-After-Story/MonikaModDev#3620] opened 2019-02-02 00:09 UTC
In the morning, after open DDLC shortly, goodbye and sleep

The option answering Monika comes to this, is it a bug?

<a href="http://imgbox.com/WOtM5UHB" target="_blank"><img src="https://thumbs2.imgbox.com/4e/d2/WOtM5UHB_t.png" alt="image host"/></a>

**Comment by Rai99** [comment] 2019-02-02 00:13
No, that's intended if you tell her you're going to sleep and it's the morning. She assumes that you stayed up all night and can't see, so you get those 2 options. 

Something could probably be done about that actually so she doesn't scold you if you did go to sleep on time and just came to see her before going back to sleep again.

**Comment by MansaSakura** [comment] 2019-02-02 00:18
Coz I am wondering the case like checking her in with jet lag and then go back to sleep, but what is really the difference between two options?

**Comment by multimokia** [comment] 2019-02-02 02:37
There isn't a difference.

**Comment by ThePotatoGuy** [comment] 2019-02-19 04:52
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-02-19 04:52 UTC
Labels: not a bug
