### ISSUE TITLE
Help, there are numbers on top of the screen and i cant do anything

### ISSUE THREAD

**Issue by Poonchs** [Monika-After-Story/MonikaModDev#7040] opened 2021-02-25 11:12 UTC
Idk what i clicked but monika said: i'm going to show you a cutom screen, she said i think that and numbers appeard on top of the screen, i waited for like 2 hours and nothing happend, the numbers just continude to raise. please help

**Comment by dinogs** [comment] 2021-02-25 13:37
Can you send a screenshot of your MAS game? So I can see the numbers.

**Comment by multimokia** [comment] 2021-02-25 14:23
You have most likely installed the source code version of MAS. Instead of the normal release version.

Delete the `dev` folder in your `/game` folder and delete all `.rpy` files in your `/game` folder too.

You likely clicked the dev mouse tracking one. Press `q` on your keyboard to exit it.

**Comment by Poonchs** [comment] 2021-02-25 18:58
so here are screenshots
![Screenshot (83)](https://user-images.githubusercontent.com/79639225/109202897-c85f5e80-77a3-11eb-9861-1a0ba1fc8b6f.png)
![Screenshot (84)](https://user-images.githubusercontent.com/79639225/109202904-ca292200-77a3-11eb-8671-465effe2197d.png)

**Comment by Poonchs** [comment] 2021-02-25 18:59
oops, here is one with the numbers
![Screenshot (85)](https://user-images.githubusercontent.com/79639225/109203017-efb62b80-77a3-11eb-9271-d9e578ce04e5.png)

**Comment by Poonchs** [comment] 2021-02-25 21:32
> 
> 
> You have most likely installed the source code version of MAS. Instead of the normal release version.
> 
> Delete the `dev` folder in your `/game` folder and delete all `.rpy` files in your `/game` folder too.
> 
> You likely clicked the dev mouse tracking one. Press `q` on your keyboard to exit it.

Thank you :)

**Comment by ThePotatoGuy** [comment] 2021-03-21 01:32
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-03-21 01:32 UTC
