### ISSUE TITLE
More pronoun options

### ISSUE THREAD

**Issue by IndependantFlower** [Monika-After-Story/MonikaModDev#9294] opened 2022-07-08 09:37 UTC
I don't know if this was already suggested, or if you're working on something like this already, but I think that a lot of people (Including me) would like more pronoun options. I know that there are a lot of options for this, so maybe you could add this as something the player would be able to type, or something similar.  Sorry for bothering you, and thanks for listening!

**Comment by Booplicate** [comment] 2022-07-10 13:03
Duplicate of #3495 #6203 and similar. Technically it should be easier now with #8996, there's also already submods that add this.

**Closed** 2022-07-24 02:48 UTC
Labels: duplicate
