### ISSUE TITLE
Eyes 

### ISSUE THREAD

**Issue by Pbm13** [Monika-After-Story/MonikaModDev#1288] opened 2018-03-20 00:38 UTC
This probably has been covered, but I think It'd be nice if Monika can blink, move her eyes or even her body, meaning she has more freedom. She has a subtle moving animation as if she's breathing, or just have small subtle smiles and glances in other directions. It'd be cool if this was implemented as a secondary priority but It makes for good discussions for now.

**Comment by Tiler17** [comment] 2018-03-20 00:58
I dunno a lot about Ren'Py yet, but from what I understand from reading around here, animations are a right pain in the ass, or terrible-looking, if not downright impossible. Which is too bad, because I've seen a number of interesting ideas that could improve on this mod if Monika could be animated, at least a small bit

**Comment by kaido1224** [comment] 2018-03-20 02:26
Blinking isn't that difficult ive been told. But it's a low priority. Someone in the discord made an unofficial blinking animation.

**Comment by sebastianN01** [comment] 2018-03-20 19:20
yeah, also, monikAI has blinking done pretty well. I don't think its gonna be hard to implement, just low priority.

**Comment by kaido1224** [comment] 2018-03-31 17:33
Duplicate of https://github.com/Monika-After-Story/MonikaModDev/issues/375

**Closed by kaido1224** 2018-03-31 17:33 UTC
