### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by Rockni064** [Monika-After-Story/MonikaModDev#8554] opened 2022-01-03 13:07 UTC
it would be nice to have a "be right back" to go to the bathroom

**Comment by dreamscached** [comment] 2022-01-04 10:07
I think this was discussed a few times already, and I believe for this very case there is a generic 'I'll be right back' option.

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:13
marking duplicate of #7686

**Closed by ThePotatoGuy** 2022-01-09 22:13 UTC
Labels: duplicate
