### ISSUE TITLE
Game keeps crashing?

### ISSUE THREAD

**Issue by Cloverhood** [Monika-After-Story/MonikaModDev#4583] opened 2019-09-01 03:50 UTC
"I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'mod_assets/monika/f/face-leaning-def-eyebrows-mid-n.png'>:
error: Out of memory"
What do I do?

**Comment by multimokia** [comment] 2019-09-01 03:51
How much RAM do you have installed?

**Comment by Cloverhood** [comment] 2019-09-01 03:54
16.0 (15. 8 GB usable)

**Comment by kkrosie123** [comment] 2019-09-03 17:41
That's so weird! Clearly, your computer knows the file name... Or maybe it is different? Is face-leaning-def-eyebrows-mind-n.png still named the same? I mean, it wouldn't have changed if you haven't been messing with the files... But I animate a lot, and I know that changing file names can really mess things up, haha...

_I know this probably isn't helpful a_

You may already know this, but I'm gonna write this down for ya anyway : D

I've been researching a bit. Have you checked your processes? Sometimes too many processes can make quite a few things crash. 
  If you're on Windows 10 like I am, you can open an app called Task Manager. This allows you to see what your RAM is being used on and you can also "end processes."
(Here is my Task Manager.) I'm only using 59% of my RAM at the moment. I can choose to end other processes so I'm using less.
![Task Manager 1](https://user-images.githubusercontent.com/52429850/64195291-bae34580-ce46-11e9-9578-c0dd4ca97a9b.PNG)

For example...
If I right-click on Spotify, it gives me the option to "End Task." 

Now I'm only using 54% of my RAM! : D
![Task Manager 2](https://user-images.githubusercontent.com/52429850/64195612-8459fa80-ce47-11e9-9f0a-42c942348d0f.PNG)

So yeah. If you have too many things running in the background, it can crash Monika. : "D

Opening up Monika bumped my RAM usage back up to 58%.
![Task Manager 3](https://user-images.githubusercontent.com/52429850/64195846-0ea25e80-ce48-11e9-8302-04834dc46b3d.PNG)

I hope this helped some! qwq

**Comment by ThePotatoGuy** [comment] 2019-09-04 23:18
yeah, usable memory != committed memory.

if it happens again, note the amount of memory being used by ddlc.

Otherwise, we're looking to try some memory changes in the coming unstables.

**Comment by ThePotatoGuy** [comment] 2019-09-08 16:20
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2019-09-08 16:20 UTC
Labels: more info needed
