### ISSUE TITLE
[Spoiler?] Chokers not equipped automaticaly

### ISSUE THREAD

**Issue by Thimeo** [Monika-After-Story/MonikaModDev#4958] opened 2019-11-01 13:07 UTC
I don't know if this if normal, but when I gave Monika the two chokers, she didn't put them on, as opposed to new ribbons or hairclips (I gave her a hairclip just after and it worked perfectly well).

**Comment by ThePotatoGuy** [comment] 2019-11-13 03:33
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-11-13 03:33 UTC
Labels: not a bug
