### ISSUE TITLE
Clothes - Blazer (cleanup)

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#3631] opened 2019-02-05 00:02 UTC
#3174

Cleanup for the default outfit, includes upscaled resolution and base arms merge.

Special thanks to Iron-707 (I used a lot of references from both his leaning pose and his sprite set), Metisz, multimokia, Ryuse, Ronin, Waails, Finale, Trilasent, Entony, and JMO (hope I didn't forget anybody lol).

[Gdrive link](https://drive.google.com/drive/folders/1KW-jSZCyqed7LoaDTxmLaghYIIgq9QVJ?usp=sharing)

Upright: 
![upright revision](https://user-images.githubusercontent.com/1176163/52981284-fc4a6100-33de-11e9-8c35-94e26fa06c8b.png)

Leaning: 
![leaning revision](https://user-images.githubusercontent.com/1176163/52981288-00767e80-33df-11e9-896f-4ac5d99439b7.png)

**Comment by ThePotatoGuy** [comment] 2019-02-05 01:45
ok. so i do have some psds that are basically mashed up versions of blazer + the current base sprites. I'm gonig to put them into the official psds issue, and then you can work on them.

**Comment by ThePotatoGuy** [comment] 2019-02-06 02:30
Okay, so i've uploaded the psds to the drive. There's a couple of things to note here:

`oufits/blazer oufits/leaning.psd`

* This is already updated with the new leaning pose, but there are some transparency issues along the edges. @multimokia and @jmwall24 also have some issues with the shoulders, they'll explain it more here.

`oufits/blazer outfits/upright.psd`

* This is the result of me mashing parts of the base sprites with old blazer stuff. There are a ton of imperfections, especially where I patched the hands from base into the blazer arms. Also lots of transparency holes in various areas.
* The down arms are also different than the base. Updating these to use the new down pose would be great.
* This is also missing some arms because I got frustrated partway through and gave up.

`oufits/blazer outfits/old/blazerarmstemp.psd`

* This has much of the sprite work I was doing to get the arms to work. 

`oufits/blazer outfits/old/uprightold.psd`

* This is a direct duplicate of the pose parts from the original uniform PSD. 

Since theres a lot of oddities with the uniform outfit, feel free to just completely redo it if its easier to do so.

**Comment by jmwall24** [comment] 2019-02-06 03:00
![screenshot_279](https://user-images.githubusercontent.com/36523761/52318157-16248680-2991-11e9-884d-5d0ce053b18d.png)
![screenshot_280](https://user-images.githubusercontent.com/36523761/52318158-16248680-2991-11e9-9a94-8a34edd6ee83.png)
My problems with the leaning shoulders in the current set are shown here.  The double line with the transparency between them on her right shoulder, and the not quite lining up of her left arm/shoulder.

**Comment by multimokia** [comment] 2019-02-06 03:03
Righty, You've already heard from me a bit before, but here's just keeping it organized:

## For the leaning pose:
![image](https://user-images.githubusercontent.com/22531674/52317778-731f3d00-298f-11e9-8323-48510eec7946.png)

### Monika's right shoulder:
You can see the extra line which makes it look almost as if there's a small disconnect between the seem and the blazer itself.
Note: using the upper seem might make the same issue on Monika's left shoulder visible, so maybe that could be smoothed out a little too.

### Monika's left shoulder:
Looks like the arms sit a little too low, as the blazer doesn't really 'naturally' connect to the shoulder bits for it, and therefore give it a sort-of disconnect.


## For non-leaning:
Just a minor thing, probably could just thicken the edges on the collar bits of the blazer for non-leaning stuffs to match the harshness of the leaning one, i.e.:

(Poses 1,2,3,4,6)
![image](https://user-images.githubusercontent.com/22531674/52318228-74516980-2991-11e9-8589-e1999bc11b3d.png)

vs.

(Pose 5)
![image](https://user-images.githubusercontent.com/22531674/52318240-83381c00-2991-11e9-8782-21de72d9ea2c.png)

As you can see, there's a harder line on the leaning pose than there is in any other one, so it looks a little inconsistent going from leaning -> non-leaning -> back.
(Monika's right side is especially obvious in this)
And that's about it from me, really.

**Comment by jmwall24** [comment] 2019-02-06 03:10
![screenshot_326](https://user-images.githubusercontent.com/36523761/52318462-93043000-2992-11e9-8e53-319a195ff219.png)
![screenshot_327](https://user-images.githubusercontent.com/36523761/52318463-93043000-2992-11e9-841d-b228a1b5a8be.png)
![screenshot_328](https://user-images.githubusercontent.com/36523761/52318464-93043000-2992-11e9-85d7-84358622be71.png)
![screenshot_329](https://user-images.githubusercontent.com/36523761/52318465-93043000-2992-11e9-852f-9a12e41c398c.png)

My other issue is how the arms match the body differently on every pose.  Hopefully we can get a clean seam that is consistent across every pose.  The second one is crossed arms, and it is by far the worst.  The others are all only slightly different, with just slightly different thickness of the seam.

**Comment by jmwall24** [comment] 2019-02-06 04:32
![screenshot_331](https://user-images.githubusercontent.com/36523761/52320589-3e66b200-299e-11e9-9183-11c1847b0ec0.png)
Also just found this spot by her collar that needs to be removed.  i fixed it on the png for now, but when the psd files are redone, pls fix this up.

**Comment by Chrissenpai** [comment] 2019-02-07 05:24
All of you have good eyes, that´s good, I´ll definitely help when semester is over.

**Comment by Velius94** [comment] 2019-02-10 21:43
First pass of upright done. Merged changes from Trilasent and Finale.

**Comment by Velius94** [comment] 2019-02-16 09:22
Upright PSD is now up. Awaiting further developments before continuing work on leaning.

**Comment by Velius94** [comment] 2019-02-18 23:41
The PSDs are now released. Preview below.

Upright: 
![upright revision](https://user-images.githubusercontent.com/1176163/52981284-fc4a6100-33de-11e9-8c35-94e26fa06c8b.png)


Leaning: 
![leaning revision](https://user-images.githubusercontent.com/1176163/52981288-00767e80-33df-11e9-896f-4ac5d99439b7.png)

**Comment by Chrissenpai** [comment] 2019-02-19 01:30
where are the eyelids on the first one?

**Comment by ThePotatoGuy** [comment] 2019-02-23 05:56
[closing this as the psds have been added to the main issue]

**Closed by ThePotatoGuy** 2019-02-23 05:56 UTC
Labels: art
