### ISSUE TITLE
(Suggestion) A question thats been bugging me and i would love to see it added as a possible dialogue option.

### ISSUE THREAD

**Issue by Akira199** [Monika-After-Story/MonikaModDev#9775] opened 2022-12-03 12:56 UTC
I had a small theory about Monikas actual intentions with the player and that she is just pretending to be in love, so that the player helps her to "Cross over". And I would love to be able to ask Monika something like, "Are you just using me to cross over?". Would be Interesting to see a response to that

**Comment by dreamscached** [comment] 2022-12-03 17:49
Duplicate of #9755.

**Closed by dreamscached** 2022-12-03 17:49 UTC
Labels: duplicate
