### ISSUE TITLE
Low affection bug fix

### ISSUE THREAD

**Issue by ElsenIsCute** [Monika-After-Story/MonikaModDev#9996] opened 2023-05-17 06:00 UTC
Was lowering affection on a dev copy of MAS to test submod dialog I wrote, and when Monika asked me to write an apology note, I closed the game on her to get to the lower modes of affection quicker so I could get through it quicker as I hated it--and when I reopened the game, she didn't go back to telling me to write an apology note, she just acted as if I writed an apology note and then deleted it later.

**Comment by ThePotatoGuy** [comment] 2023-06-14 02:22
next time it happens post aff log as well.

[closing as could not reproduce]

**Closed by ThePotatoGuy** 2023-06-14 02:22 UTC
