### ISSUE TITLE
I won at "random chess" but Monika still doesn't acknowledge that while I say she's good at it

### ISSUE THREAD

**Issue by emcchiaki** [Monika-After-Story/MonikaModDev#7642] opened 2021-08-18 00:34 UTC
I won at "random chess" but Monika still doesn't acknowledge that while I say she's good at it
Is it supposed to be like this? After all well, I *did* technically win in chess but on different rules of the play...
https://user-images.githubusercontent.com/79312047/129817902-66d1768a-24f5-43f6-aa7e-ef5a201dbf2f.png
https://user-images.githubusercontent.com/79312047/129817938-54bd004b-63ed-44d2-85d4-91189485f16a.png

**Comment by Booplicate** [comment] 2021-08-19 07:59
I believe that's intended, as you played with undos, which is being considered a practice mode. And while you haven't used it in that game, it's hard to account for, so we keep track of those practice games separately from normal games.

**Comment by PongMaster69** [comment] 2021-08-19 21:16
I personally don't think that winning at random chess should be held at the same level as winning against her at normal chess. One relies heavily on RNG and luck whereas the other is basically pure strategy at it's core. But I'm bad at chess anyways so I won't complain about feeling really good about getting good luck.

**Comment by ThePotatoGuy** [comment] 2021-08-28 19:52
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-08-28 19:52 UTC
Labels: not a bug
