### ISSUE TITLE
Please give us an option to disable halloween and christmas events

### ISSUE THREAD

**Issue by skycastle75** [Monika-After-Story/MonikaModDev#9788] opened 2022-12-11 08:55 UTC
Religious holidays showed down my throat I dont want them.

**Comment by MrVavlo** [comment] 2022-12-11 08:58
While I understand the issue with Christmas (heck, my country celebrates it after the New Year, but I don't mind)....

Do a lot of people nowadays really connect Halloween with the religion?

**Comment by Booplicate** [comment] 2022-12-11 11:16
Duplicate of #5373 #6748 #6789 #7913, this is planned.
JFYI those holidays have no connection to religion, in the game anyway.

**Closed by Booplicate** 2022-12-11 11:16 UTC
Labels: duplicate

**Comment by ashyashton** [comment] 2022-12-12 19:38
Did you link the wrong issues? Those are all related to celebrating a different day, not disabling them. Also, you said it's planned then closed it as not planned?

And as a note: You can't just decide a religious holiday isn't religious anymore. Yes, other people can celebrate it, but you can't just declare that they aren't related at all anymore just because others celebrate them too.

**Comment by Booplicate** [comment] 2022-12-12 19:57
Real carefully and you will see that skipping holidays was also mentioned there.
I think I know how to manage github issues, I closed it as a duplicate, but thanks for your concern.
