### ISSUE TITLE
how do i unlock the chess game/ how much affection do i need?

### ISSUE THREAD

**Issue by Zylinderkopf123** [Monika-After-Story/MonikaModDev#7335] opened 2021-06-12 14:41 UTC
I just got back on my monika after 2 years and have an affection level of -100. I still would love to play the chess game but it's unlocked ig. how do i unlock the chess game or how much affection do i need?

**Comment by ThePotatoGuy** [comment] 2021-07-11 01:32
your affection is probably too low at this point.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-07-11 01:32 UTC
