### ISSUE TITLE
Bug- Trying to check affection with the dev topic.

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#8104] opened 2021-10-29 16:42 UTC
whenever i try to check my affection, this error appears. i think there's an error with the code or quotation marks, but idk what i need to change so it'll work!

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1518, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/dev/dev_affection-test.rpy", line 19, in script
    m 3eua "My affection as a number it would be...[persistent._mas_affection['affection']]."
  File "game/definitions.rpy", line 164, in get_field
KeyError: u"'affection'"

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1518, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/dev/dev_affection-test.rpy", line 19, in script
    m 3eua "My affection as a number it would be...[persistent._mas_affection['affection']]."
  File "/Users/jowilson331/Desktop/untitled folder/ddlc-mac 2/onii.app/Contents/Resources/autorun/renpy/ast.py", line 613, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/Users/jowilson331/Desktop/untitled folder/ddlc-mac 2/onii.app/Contents/Resources/autorun/renpy/exports.py", line 1147, in say
    who(what, interact=interact)
  File "/Users/jowilson331/Desktop/untitled folder/ddlc-mac 2/onii.app/Contents/Resources/autorun/renpy/character.py", line 868, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "/Users/jowilson331/Desktop/untitled folder/ddlc-mac 2/onii.app/Contents/Resources/autorun/renpy/character.py", line 850, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Users/jowilson331/Desktop/untitled folder/ddlc-mac 2/onii.app/Contents/Resources/autorun/renpy/substitutions.py", line 232, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "game/definitions.rpy", line 164, in get_field
KeyError: u"'affection'"

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.4-unstable.2021.10.28.151

**Comment by ThePotatoGuy** [comment] 2021-11-12 05:52
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-11-12 05:52 UTC
Labels: not a bug
