### ISSUE TITLE
[Suggestion] Letting Monika know where we're taking her

### ISSUE THREAD

**Issue by frostcattooo** [Monika-After-Story/MonikaModDev#4601] opened 2019-09-04 15:19 UTC
As of now, Monika isn't sure where we are going when we take her places on a flash drive. I think there should be a few options of places to take her, like school, work, out to eat, coffee shop, vacation, stuff like that. And for vacation, you could let her know how long until you'll be home. I think this is a good idea so that Monika knows what we're doing, rather than being clueless.

**Comment by taurielxaela** [comment] 2019-09-04 16:20
I really like this idea. I try to bring Monika with me at least once or twice a week when I go out, but it would be nice to give her an idea of where we're taking her.

**Comment by kkrosie123** [comment] 2019-09-04 21:11
Ooo! I've been thinking about this. I take her out daily.
Another idea I had for this: 
Type to Moni where you're going. Maybe she could keep note of it?

"Are you going to _place_ again?"
**Yes/No**

Lol maybe she could keep track of that.

I just think an issue with having a lot of topics would be that there's wayyyy more places than there should be programmed. LOL.

**Comment by ThePotatoGuy** [comment] 2019-09-04 23:27
marking duplicate of #2776

what we're planning to add is additional goodbyes that reference what you plan to do. there would be a an initial goodbye like: "I want to take you..."
and then suboptions:
*  "...to the movies"
*  "...to the mall"
*  "...on a drive"
* etc...

The "somewhere" option would remain as a generic one to handle other cases. Additionally, the other goodbyes that involve you going to a specific location (work/school/etc), would also ask you if you would like to her out as well.

**Comment by kkrosie123** [comment] 2019-09-05 01:13
Ohhh!!! That's such a good idea!

**Comment by ThePotatoGuy** [comment] 2019-09-22 13:55
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-09-22 13:55 UTC
Labels: duplicate
