### ISSUE TITLE
[Suggestion] - Monika changing outfit between visits

### ISSUE THREAD

**Issue by BracketsGuy** [Monika-After-Story/MonikaModDev#9360] opened 2022-07-22 11:41 UTC
Monika is always wearing what the player wants her to wear, maybe make a toggleable option to have her choose her outfit/clothing at random? Or maybe have favorite outfits and have values set to what outfits are preferred (Previous outfits can have a default, or something).

**Comment by Justformas** [comment] 2022-07-22 15:27
There's a submod for this too, don't know about favorite outfits but still: https://github.com/multimokia/MAS-Submod-Auto-Outfit-Change

**Comment by ThePotatoGuy** [comment] 2022-09-24 02:02
marking duplicate of #3768

[closing as duplicate]

**Closed by ThePotatoGuy** 2022-09-24 02:02 UTC
Labels: duplicate
