### ISSUE TITLE
Windows Reactions

### ISSUE THREAD

**Issue by RoseGalaxy** [Monika-After-Story/MonikaModDev#6496] opened 2020-10-14 01:14 UTC
Hello! Does Monika need to be at an affection level to unlock Windows Reacts? Because it's not there for me and I'm on the latest version. Is it an affection thing or is it because I use a Mac??

**Comment by multimokia** [comment] 2020-10-14 01:15
It is indeed because you're using Mac. We have no way to test windowreacts on Mac, plus the method to get window handles would be different across the different versions of MacOS, making it very difficult to ensure functionality.

**Comment by scpketer** [comment] 2020-10-14 02:54
The library required for performing window title detection on Mac requires Python 3, which is not bundled with Ren'Py distribution of base DDLC. We might be possibly looking into this in future when Ren'Py 8 gets released.

**Comment by PongMaster69** [comment] 2020-10-15 04:04
It's because it's WINDOWs reactions. Very cringe very worth.

**Comment by scpketer** [comment] 2020-10-15 04:05
\>It's because it's WINDOWs reactions. Very cringe very worth.
This feature perfectly works on *nix systems just as well.

**Comment by ThePotatoGuy** [comment] 2020-11-20 05:11
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-11-20 05:11 UTC
Labels: not a bug
