### ISSUE TITLE
[Suggestion] variations with "hold me" and stuff

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#2725] opened 2018-10-07 15:41 UTC
When she's in the pose of "hold me" you can click on any part of her body as some people suggest, but a sprite shows when you do that, for example, you click on her shirt noose and shows a sprite of an unbuttoned shirt, good or bad reaction depending on affection and mood respectively, click on the arm and a sprite shows you holding her hand, on the cheek and a sprite shows your arm gently holding her cheek, things like that, that requires art I know, but that needs to eventually be incorporated for interaction purposes.

**Comment by AsuraShun** [comment] 2018-10-07 15:56
the holding hands part was already sugested

**Comment by AgentZephyr** [comment] 2018-10-08 12:43
> _Shirt Noose_

**Comment by ThePotatoGuy** [comment] 2018-10-12 21:04
marking as a duplicate of linked issues @Rai99 linked.

**Closed** 2018-10-21 00:59 UTC
Labels: duplicate
