### ISSUE TITLE
[Suggestion] - Chess 1-move Win Dialogue

### ISSUE THREAD

**Issue by CoveneyPlayz** [Monika-After-Story/MonikaModDev#7321] opened 2021-06-10 23:54 UTC
I found out you can beat monika on randomized chess in one turn. 
![image](https://user-images.githubusercontent.com/85714471/121611081-116ab400-ca1d-11eb-8703-6833d49ddef0.png) Try and make it so monika reacts to this. It feel like a huge downer when you lose this fast, so maybe make affection go down?
Just a little thing i found

**Comment by Erenussocrates** [comment] 2021-06-11 03:38
I don't think affection should be affected over a game at all. But I like the idea of Monika reacting to a fast win. That would be novel indeed.

**Comment by Wingdinggaster656** [comment] 2021-06-12 02:01
A notice could be that it's impossible to beat your opponent in the first turn, except the current randomized chess mode.
The fastest way to lose in Chess costs 2 turns, it's: 1.f4 e6   2.g4 Qh4#
This is a great deal of cooperation from your opponent, which means it takes both of you to lose so quickly. The current Monika, even at the lowest level, will never make such moves, at least not in my thousands of games.
So this dialogue should only occur in the random chess case, we can based on this notice to write dialogues.

**Comment by Booplicate** [comment] 2021-06-12 12:04
This is a bug that should be fixed. And because of that there's no need in dl, since we'd have to remove it once we fix the bug.

**Comment by ThePotatoGuy** [comment] 2021-07-11 01:22
marking as duplicate of #6973 

[closing as duplicate]

**Closed by ThePotatoGuy** 2021-07-11 01:22 UTC
Labels: duplicate
