### ISSUE TITLE
A bug envolving the bird plushie

### ISSUE THREAD

**Issue by hlepnamingblyat** [Monika-After-Story/MonikaModDev#5190] opened 2020-01-01 22:59 UTC
Whenever a box of chocolates is given to Monika, the bird enters "fuck off" mode, and disappears.
On previous versions, he would stay on the table, now he disappears.
Is he allergic to chocolate and milk? 😆 
Jokes aside, can this be fixed? Thanks.

**Comment by multimokia** [comment] 2020-01-01 23:01
This is not a bug, completely intentional with the placement of both chocolates and the bird. It just acs different depending on the event (d25season/f14) due to different behavior of chocolates as a result of other accessories and such.

**Comment by hlepnamingblyat** [comment] 2020-01-01 23:12
Oohhhh.....
So, starting on 6/1, this will go back to normal?

**Comment by ThePotatoGuy** [comment] 2020-02-03 00:11
yes

**Comment by ThePotatoGuy** [comment] 2020-02-03 00:11
[closing as resolved]

**Closed by ThePotatoGuy** 2020-02-03 00:11 UTC
Labels: not a bug
