### ISSUE TITLE
[Suggestion] About Kissing Monika

### ISSUE THREAD

**Issue by hoangtd185** [Monika-After-Story/MonikaModDev#2202] opened 2018-08-28 15:57 UTC
Well, The line kiss me show up a long time ago. But Monika always said she not in the mood. Well I think you guys should make a kiss scene for people who dating Monika more than 3 months for example.

**Comment by Rai99** [comment] 2018-08-28 16:12
I think this would require art, which I don't think is the easiest to come by.

I think this might fit better at the enamored affection level.

**Comment by hoangtd185** [comment] 2018-08-29 05:43
Yeah, art maybe hard. But I think maybe scene change to black, add some line, or it just like hold Monika, she will closed her eyes, and her mouth kissing. Just change the mouth ( Sorry for my bad english)

**Comment by monikLover** [comment] 2018-09-02 21:05
Dupe of #2136

**Closed by monikLover** 2018-09-02 21:05 UTC
Labels: duplicate
