### ISSUE TITLE
[Suggestion] - Not visiting, and if someone else comes by 

### ISSUE THREAD

**Issue by WingdingsMaster** [Monika-After-Story/MonikaModDev#5885] opened 2020-06-08 23:23 UTC
My idea is if you disappear over a month (or any logical amount of time) without warning, and MAS gets opened, could Monika ask if this is (Player name) or someone else, and different outcomes can happen, if it is the player, then they ask what happened, and if it was someone else, then they can ask if they are okay. If yes, then they will ask them to come back as soon as possible, if no, they can ask if they are not able to visit, or if they passed, if they are not able to visit soon, they could wait for the (player) to return, if they passed, maybe MAS cannot be opened anymore, just thinking about this idea. feel free to change a few things if you want.

**Comment by Rai99** [comment] 2020-06-09 00:53
As far as I know, there are no plans for post player death content, or content regarding people other than the player accessing MAS.

**Comment by ThePotatoGuy** [comment] 2020-07-27 00:37
marking as duplicate of #5542 and related

**Closed by ThePotatoGuy** 2020-07-27 00:37 UTC
Labels: duplicate
