### ISSUE TITLE
[Suggestion] - I'll be right back!

### ISSUE THREAD

**Issue by ACoolCat** [Monika-After-Story/MonikaModDev#2033] opened 2018-08-08 23:59 UTC
I exit out of MAS whenever I leave the house so she doesn't think I left her. I saw the "I'm going away for a while" And thought a few minutes would show up as an option. Sadly it didn't and I had to punch in "I don't know". I think it would be nice for an option to tell Monika you'd be right back for a goodbye.

**Comment by ThePotatoGuy** [comment] 2018-08-09 02:39
Closing as duplicate of #607

**Closed by ThePotatoGuy** 2018-08-09 02:39 UTC
