### ISSUE TITLE
Could a conversation be added where Monica asks the player for their address and where they live? (suggestion)

### ISSUE THREAD

**Issue by elite198** [Monika-After-Story/MonikaModDev#9478] opened 2022-08-26 08:52 UTC
first of all, hello and sorry for my bad english
Second, I know that there is a similar topic and you said that it would be difficult to do because of adding addresses from all over the world and things like that. but I would like to give a suggestion on how they could do it without difficulty

the topic could be based on when she asks about the player's appearance.

to give an example I will use the system of my country Mexico

The conversation could start with Monika talking to the player about how if she got to the player's reality she wouldn't be able to find him because she doesn't know where he lives or his full name.
She could then tell the player that she knows it's sensitive information but she could ask him about her location to make it easy for her to find him if she were to cross over someday.

if the player accepts the conversation could continue in this way;

first she would ask what country the player lives in. then a text box will appear like when the player enters a nickname for monika. there the player will write the name of the country (this would happen in the following questions as well) I know that it would be very difficult to make a reaction for the more than 120 countries but could you only add a reaction for the most well-known countries for example U.S.A, Canada, France, Russia, Japan, China, and please consider a reaction for Mexico
for other lesser known countries she might have a more standard reaction like: "oh I've heard it's an interesting place" or something like that
then she would ask for the state or province where the player lives. for example california new york or something like that. In the same way, you could put some standrt dialogue like "I always wanted to go to that place" or simply express gratitude to the player for sharing that information. You could also add reactions to very famous states like the ones I mentioned above.
then she could ask about the city where the player lives for example tokyo the same as the previous ones it is not necessary a reaction to each city only to some.
and finally the most difficult. Monika could I ask her for the player's address I suppose this could be more difficult to answer due to the limitation of the spaces of the text box example "sesamostreet 142"

and finally, reactions could be added if the player puts a fictitious place from popular culture, for example, if the player puts "wakanda" when monika asks about the country, she could be annoyed that the player does not take the questions seriously

plus: a somilar conversation could be added where monika asks the player's name for example if the player has more than one name or two surnames example "yoda anakin skywalker palpatine"

**Comment by Wingdinggaster656** [comment] 2022-08-26 11:10
I personally think that this is still not-so-good to implement.

> first she would ask what country the player lives in. then a text box will appear like when the player enters a nickname for monika.

Good idea, now I am going to use `monika_is_shit` as the country name. Monika should know this is absolutely not a country name, but how to detect this?

> only add a reaction for the most well-known countries for example U.S.A, Canada, France, Russia, Japan, China, and please consider a reaction for Mexico
> for other lesser known countries she might have a more standard reaction like: "oh I've heard it's an interesting place" or something like that

Probably not very fair?

**Comment by Booplicate** [comment] 2022-08-26 14:46
Duplicate of #8316.

I'd like this, but it'd require us to have a list of available countries, which would mean we're expressing a political standpoint. Maybe if Monika could tell you to ask on the GH if your country not in the list, and we'd just add all the requested countries.

That said, only the country and city, no street address.

**Comment by Justformas** [comment] 2022-08-26 19:56
> Good idea, now I am going to use `monika_is_shit` as the country name. Monika should know this is absolutely not a country name, but how to detect this?

I literally just tried typing that in the "Classical music" topic, where if you say you play an instrument and she asks you what it is. It actually worked:

`Wow, I've always wanted to try the monika_is_shit out!`

`Oh! Would a duet between the monika_is_shit and the piano sound nice?`

While I found that hilarious, it could be addressed by applying something like the bad name detection system to it, just like it could be for countries. But then you'd need Monika reactions for those too, and ideally player apologies to go with them.

Without a list it'd just be a generic reaction like with the instrument you play. A country list is one thing, but a city list (whether country specific or not) sounds like a lot to incorporate anyway, but without it people could make up a city name like they can an instrument.

Unless there should be a list for every musical instrument too. Or maybe Monika shouldn't be expected to know about every instrument and city in existence, but most people probably don't know about every country in existence either.

**Comment by elite198** [comment] 2022-08-26 22:19
> Probably not very fair?

well i guess you're right

**Closed** 2022-09-01 19:28 UTC
Labels: duplicate
