### ISSUE TITLE
Monika's Face disappears sometimes...

### ISSUE THREAD

**Issue by MysticGamer07** [Monika-After-Story/MonikaModDev#5814] opened 2020-05-22 14:29 UTC
Yo, i downloaded the Mod a couple days ago and i really enjoy it.
One Day Monika came up with a Topic about a Ghost or something like that, and for some reason her Face was COMPLETELY gone. Like no Eyes, no Mouth and no Nose. Literally nothing. I was like "Ye probably intended because Ghost and creepy and stuff.
But recently she talked about Highschool and it appeared (rather disappeared) again. No eyes, no mouth, no nothing.
So my Question for this...am I supposed to see what i was seeing or is something wrong with the Game?
If I see this happen again I will come back and Attach a Screenshot to this because after a trip in google i found nothing compareable to my issue.
Hope someone can help me with this :/

**Comment by multimokia** [comment] 2020-05-22 14:30
What are your computer specs. Also are you running MAS off of a USB?

**Comment by MysticGamer07** [comment] 2020-05-22 17:57
CPU: AMD Ryzen 5 1600
GPU: AMD 570 RX
RAM: 32GB 3200MHz
1x HDD, 1x SSD

No I got the game on my Desktop and it's not on Steam. I downloaded DDLC from the Website

**Comment by Booplicate** [comment] 2020-05-22 18:32
Did you have other heavy programs and/or games running in the background when that happened?

**Comment by MysticGamer07** [comment] 2020-05-22 18:43
Probably yeah, I played some League, Monster Hunter World and ARK while i was keeping the Window on my other Monitor. Sounds a bit unbelivable that something like Games could cause that. I actually go and try to get her face to disappear while having a Game running just to make sure. Actually I saw it right after my second reply. Telling her "I love you" (my Affection level is f*cked for some reason but i like it this way so i have some "grinding" in some way xd) caused her face to go poof gone. I might spam a bit "I love you" to see if i can trigger this again.

**Comment by Booplicate** [comment] 2020-05-22 18:57
I think it might be caused by your GPU and several programs running at once. When you play other games, you can disable the animation in the settings, or you can tell her that you're going to play something and you need to close MAS.

You can also try to go to the settings and change renderer to something else (**not** software though!). But don't think it will help.

**Comment by MysticGamer07** [comment] 2020-05-22 19:07
I looked at the Render Setting but after changing to Angle/DirectX and back to Auto i didn't see/felt like anything changed. For now I will do what u said about closing the Game while playing something else. If i see her Face going poof gone i will definitly come back but for now im gone.
Thanks a lot!

**Comment by Booplicate** [comment] 2020-05-22 19:14
Well, you may not see the difference between the renderers at a glance, but it might help in the long run, you never know.

**Comment by ThePotatoGuy** [comment] 2020-07-31 02:58
[closing as resolved]

**Closed by ThePotatoGuy** 2020-07-31 02:58 UTC
