### ISSUE TITLE
this hug thing just bugs me

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#8457] opened 2021-12-20 21:43 UTC
the previous versions had Monika turn off the music when you hold her, but now it keeps playing! if this is a feature, the music button should be there. And when she asks me to hold her, she turns of the music, so it can't be intentional. but if it is, can you do something about the button? Cause it is weird accessing the music menu with only the M key

**Comment by crxxmpxffs** [comment] 2021-12-20 23:52
what i do is either mute it before or mute the game entirely. maybe that's a bit far fetched but i wanna listen to my music while holding monika in the background >:/

**Comment by Booplicate** [comment] 2021-12-20 23:58
People wanted to keep the music they had during holding her. If you don't want the music, don't start it or mute beforehand. If you forgot, you can open the music menu via `m` or mute using `-` or `shift`+`m`. We're hiding the UI for aesthetics, but the hotkeys still work.

**Comment by Cosmic-Incantations** [comment] 2021-12-21 03:39
I am glad to know this is a feature, I love listen to confession or My Feelings or even some deltarune music in custo_bgm. I just wanted to know if it was a bug cause I cant listen to music in the rain topic, and the lack of buttons on the screen just annoy me regardless. it's fine though, cause I love that I now can listen

**Comment by ThePotatoGuy** [comment] 2021-12-31 05:18
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-31 05:18 UTC
Labels: not a bug
