### ISSUE TITLE
[Suggestion] Busy mode

### ISSUE THREAD

**Issue by SaiPrithvi123** [Monika-After-Story/MonikaModDev#3510] opened 2019-01-16 18:15 UTC
Something to let Monika know that the player is busy and can't interact with her right now. It could be initiated with a new button near the `Talk` button. Monika would stay silent and won't interact with the player while busy mode is active with a few exceptions, like nagging the player to go to bed, or detecting a gift. I'm not sure but I'm seeing stuff about inactivity detection being in works. If player ignores Monika without initiating the busy mode, then there could be affection loss, which would make this mode really useful if the player is just running the game in background. This was inspired by a post by @softombre in #3509.

**Comment by ThePotatoGuy** [comment] 2019-01-16 20:33
Framework is being worked on in #3435 

Marking this as a duplicate of #607

**Comment by ThePotatoGuy** [comment] 2019-01-27 22:36
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-01-27 22:36 UTC
Labels: duplicate
