### ISSUE TITLE
[Bug or maybe not] All spritepacks stuff gone after update

### ISSUE THREAD

**Issue by MetalBrother** [Monika-After-Story/MonikaModDev#5481] opened 2020-04-06 21:34 UTC
So that pretty much it. All spritepacks stuff is gone, I tried to reinstall spritepacks and regift it to Monika, but she tells every time that she can't see what I'm gifting, I also tried to restart a game and computer, but it didn't work. So I'm asking is this in plans to get rid of spritepacks, 'cause if not, I will be very worried.

**Comment by multimokia** [comment] 2020-04-06 21:37
Sounds like you're using unstable. See #5465 for reason + fix

**Comment by MetalBrother** [comment] 2020-04-06 21:49
I have a question. Do I need to regift everything?

**Comment by multimokia** [comment] 2020-04-06 22:08
You do not

**Comment by MetalBrother** [comment] 2020-04-06 22:23
Thank for fast response, you really helped me so fast, thank you!

**Comment by ThePotatoGuy** [comment] 2020-04-16 08:02
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-04-16 08:02 UTC
Labels: not a bug, unstable
