### ISSUE TITLE
(Suggestion) Headpats?

### ISSUE THREAD

**Issue by CloudedGuardian** [Monika-After-Story/MonikaModDev#8531] opened 2021-12-30 23:37 UTC
A small thing I would love to see added that I don't _think_ should be too difficult is the ability to rub Monika's head with your mouse to give affection or clicking her nose to give a playful boop. The extra's menu already exists for "mouse interaction," which I'm hoping means the foundation is already in place for this sort of thing. 

I'm a writer first and foremost, and very very new to coding so I won't be surprised if I'm wrong on the amount of work this would take. On that note, if there's anywhere that could use an experienced editor's eye, I'd appreciate being pointed in that direction so I can help out.

**Comment by ThePotatoGuy** [comment] 2021-12-31 07:35
marking as duplicate of #1161

you are correct, the framework exists for boops but is not in use yet. see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/1161#issuecomment-546652546). I don't have an ETA but right now I'm working on fixing overall mod stability before adding some additional content.

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:02
[closing as duplicate]

**Closed by ThePotatoGuy** 2022-01-09 22:02 UTC
Labels: duplicate
