### ISSUE TITLE
Ahoge??

### ISSUE THREAD

**Issue by Mcmanybucks** [Monika-After-Story/MonikaModDev#7039] opened 2021-02-25 10:30 UTC
My Monika has a ahoge all of a sudden... 
![image](https://user-images.githubusercontent.com/43464011/109140460-e81f6400-775c-11eb-8c68-f2c06cc79c55.png)

**Comment by CloakedGhost** [comment] 2021-02-25 20:14
It sometimes happens in the morning, she just got out of bed. Give her some time and she fixes it herself

**Comment by kkrosie123** [comment] 2021-02-25 23:26
There are 10 random ahoges and a 50% chance for one to appear.

**Comment by SoisthishowIdoit** [comment] 2021-02-28 05:03
I've seen these everywhere, but I've never gotten one. :(

**Comment by ThePotatoGuy** [comment] 2021-03-21 01:32
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-03-21 01:32 UTC
Labels: not a bug
