### ISSUE TITLE
[Suggestion] Add the ability to boop monika

### ISSUE THREAD

**Issue by BigCat2477** [Monika-After-Story/MonikaModDev#8570] opened 2022-01-07 22:11 UTC
It would kinda be like the kiss, but instead of a kiss you just *boop*. And there could be a random chance that it catches her off guard.
When you boop her and it catches her off guard she could say something like "Oh!" then giggle, then boop you back

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:58
marking duplicate of #1161

**Comment by ThePotatoGuy** [comment] 2022-01-15 21:44
[closing as duplicate]

**Closed by ThePotatoGuy** 2022-01-15 21:44 UTC
Labels: duplicate
