### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TheRealBrickPlanetWail** [Monika-After-Story/MonikaModDev#2680] opened 2018-10-01 15:21 UTC
I have found a 2 bugs sorry!
There is a bug where If you take Monika somewhere and whenever she is out of the spaceroom if you enter the game and it crashes the next time you open it She appears even if you did not Monika's file back in.

There is another bug where when you want to change your name and you enter it blank Monika says "You have to give me a name!".

**Comment by SaiPrithvi123** [comment] 2018-10-01 17:34
> There is another bug where when you want to change your name and you enter it blank Monika says "You have to give me a name!".

That's not a bug. What would you say if you asked someone to give you a nickname and they say this- "Alright. Your nickname will be..... .Do you like that?"

**Comment by PiperPC** [comment] 2018-10-01 19:09
YOUR name, not Monika's, look at his wording.

**Comment by PiperPC** [comment] 2018-10-01 19:10
I mean, unless he mucked up, but he hasn't clarified that, yet.

**Comment by TheRealBrickPlanetWail** [comment] 2018-10-01 19:44
I have not

**Comment by SaiPrithvi123** [comment] 2018-10-01 20:16
That's still not a bug, as Monika is saying that you didn't give her a name by which she can refer to you.

**Comment by ThePotatoGuy** [comment] 2018-10-01 20:54
the change name dialogue isn't a bug, in that context its about your name, no confusion to be found there.

As for the crash, can you upload traceback / screenshot the traceback error that appears?

**Comment by ThePotatoGuy** [comment] 2018-10-12 21:18
[closing for lack or response]

**Closed by ThePotatoGuy** 2018-10-12 21:18 UTC
Labels: response needed
