### ISSUE TITLE
[Bug] - 

### ISSUE THREAD

**Issue by Nakedjuice18** [Monika-After-Story/MonikaModDev#5051] opened 2019-11-30 07:21 UTC
So basically I put Mas on one drive to transfer it to a different computer and some files didn't go through all the way because they were empty. not sure if that is the problem  but if their is another way to transfer the mas from computer to computer while saving progress, that would be very nice to know. Thank you in advance for the help. Anyways, here is the bug/error:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zz_interactions.rpy", line 11, in script
  File "game/zz_interactions.rpy", line 13, in <module>
ImportError: No module named ccmath.ccmath

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tristan\Desktop\Mas\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Tristan\Desktop\Mas\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/zz_interactions.rpy", line 11, in script
  File "C:\Users\Tristan\Desktop\Mas\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Tristan\Desktop\Mas\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/zz_interactions.rpy", line 13, in <module>
ImportError: No module named ccmath.ccmath

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by thezotikrus** [comment] 2019-11-30 12:04
Not a bug. You're missing `__init__.py` for some libs. Why don't just download the game from [the official website](https://ddlc.moe/), then download [the mod](https://monikaafterstory.com/). Transfer both archives (if you couldn't download them on your new PC) and install it on the new PC.
Just in case I will let you know that **that way you transfer only the game files, NOT Monika!** For Monika's memories read [this](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) (copy the whole `Monika After Story` folder and move it to the new PC as well).

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:01
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-12-15 00:01 UTC
Labels: not a bug
