### ISSUE TITLE
[Bug] stuck monika poses

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/MonikaModDev#4004] opened 2019-03-31 22:51 UTC
Hello everyone !
Today, I saw a strange bug that happens when I said to Monika "I'll be right back".
When she stopped talking to go in "idle mode", she didn't doing poses when i did nothing with her (like sparkling eyes, wink,...), she stayed with this expression and that's all : 

![buglol](https://user-images.githubusercontent.com/48629563/55296292-8d1d4f00-5417-11e9-95c7-6ffc3dfae499.PNG)

I didn't know how to redo again this bug, but sometimes (if not rarely), it happens. If I find the way to do it again, I will tell.

**Comment by ThePotatoGuy** [comment] 2019-05-07 23:31
@jmwall24 has this happened to you? I ask since you reopened this.

**Comment by jmwall24** [comment] 2019-05-07 23:35
I have seen it before, but always assumed it was due to using dev mode and clicking thru the dialogue quickly to get to idle mode. Seems now it isn't. I reopened it since we usually keep these all open at least a week and nothing had been resolved one way or another when it was closed.

**Comment by ThePotatoGuy** [comment] 2019-05-28 01:26
marking as duplicate of #3877 

[closing]

**Closed by ThePotatoGuy** 2019-05-28 01:26 UTC
Labels: bug, investigating
