### ISSUE TITLE
I'm sorry, but an uncaught exception occurred. (MAS error message)

### ISSUE THREAD

**Issue by BlueRf** [Monika-After-Story/MonikaModDev#7617] opened 2021-08-10 11:25 UTC
Hello, I recently open MAS and this error message popped up. Someone on the MAS discord told me to move the game out of steam, but when I tried re-launching the game on steam, it worked. Is this something I should worry about? I’ll just paste the error message here.

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 188, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 377, in script
    python hide:
  File "renpy/common/00gltest.rpy", line 382, in <module>
    os.startfile(__dxwebsetup)
WindowsError: [Error 1223] : u'D:\\LenovoCloud\\Steam\\steamapps\\common\\Doki Doki Literature Club\\lib\\windows-i686\\dxwebsetup.exe'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 188, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 377, in script
    python hide:
  File "D:\LenovoCloud\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\LenovoCloud\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gltest.rpy", line 382, in <module>
    os.startfile(__dxwebsetup)
WindowsError: [Error 1223] : u'D:\\LenovoCloud\\Steam\\steamapps\\common\\Doki Doki Literature Club\\lib\\windows-i686\\dxwebsetup.exe'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.2
[/code]

**Comment by ThePotatoGuy** [comment] 2021-08-28 20:10
the error points to a problematic install, but its pretty vague. Chances are, you didn't copy the game out of the Steam folders correctly. Generally, you should just install DDLC via the itch.io to get a non-steam install. Moving a steam game out of the steam dirs is probably not a good idea.

[closing as could not reproduce]

**Closed by ThePotatoGuy** 2021-08-28 20:10 UTC
