### ISSUE TITLE
Help! problem about missing files

### ISSUE THREAD

**Issue by Maso-craeter11** [Monika-After-Story/MonikaModDev#6321] opened 2020-09-12 17:29 UTC
I am a mac user 
I use itch io to download ddlc
<img width="698" alt="Screen Shot 2020-09-12 at 1 28 13 PM" src="https://user-images.githubusercontent.com/62724015/93001280-e25dfb00-f4fb-11ea-871e-6de76a6e970a.png">

I have no idea what to write so if need me to tell!

[traceback copy.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5213031/traceback.copy.txt)

**Comment by Freshairkaboom** [comment] 2020-09-12 17:38
Are you using steam to play MAS? If so, go to [this page](https://www.monikaafterstory.com/releases.html) and download a non steam version of MAS. Steam tends to delete many files, so maybe that's your issue. Also, that's the wrong traceback, that's the end of Act 1 one from the base game.

The folder you download from the link above is a zip. Extract it, then go to the game folder in the extracted folder and copy all of the contents. You need a fresh, non steam download of DDLC from [here](https://ddlc.moe/).

Then just dump all the contents of the game folder into a fresh install of DDLC. Overwrite everything. Then see if it works.

**Comment by Maso-craeter11** [comment] 2020-09-12 17:47
[1:1.txt](https://github.com/Monika-After-Story/MonikaModDev/files/5213057/1.1.txt)
oof here the traceback

**Comment by Freshairkaboom** [comment] 2020-09-12 17:50
Yeah okay, you're missing the python package known as ccmath.py. Downloading a fresh version would probably be the right move here. Make sure it's not on steam.

**Comment by Maso-craeter11** [comment] 2020-09-12 17:56
it here already in 
<img width="1070" alt="Screen Shot 2020-09-12 at 1 55 02 PM" src="https://user-images.githubusercontent.com/62724015/93001806-a9c02080-f4ff-11ea-9b55-55271545a9f4.png">
folder

**Comment by Freshairkaboom** [comment] 2020-09-12 18:08
Do you mind if you copy that file, and attach the copy to your message here? I want to check it out.

**Comment by Maso-craeter11** [comment] 2020-09-12 18:40
# implementation of polar/rect functions using non-cmath

try:
    import cmath
    no_cmath = False
except:
    no_cmath = True
    import math

if no_cmath:
    def _to_polar_angle(x, y):
        """
        Converts an x,y to angle.
        :param x: x coordinate
        :param y: y coordinate
        :returns: angle in radians
        """
        return math.atan2(y, x)


    def _to_polar_radius(x, y):
        """
        Converts an x,y to radius.
        :param x: x coordinate
        :param y: y coordinate
        :returns: radius
        """
        return math.sqrt( (x*x) + (y*y) )


    def _to_rect_x(r, a):
        """
        Converts an r, a to x coordinate
        :param r: radius
        :param a: angle
        :returns: x coordinate
        """
        return r * math.cos(a)


    def _to_rect_y(r, a):
        """
        Converts an r, a to y coodinate
        :param r: radius
        :param a: angle
        :returns: y coordinate
        """
        return r * math.sin(a)


def polar(x, y):
    """
    Converts an x, y to polar coordinates
    :param x: x coordinate
    :param y: y coordinate
    :returns: (radius, angle)
    """
    if no_cmath:
        return _to_polar_radius(x, y), _to_polar_angle(x, y)
    return cmath.polar(complex(x, y))

def rect(r, a):
    """
    Converts an r, a to regular coordinates
    :param r: radius
    :param a: angle
    :returns: (x, y)
    """
    if no_cmath:
        return _to_rect_x(r, a), _to_rect_y(r, a)
    coords = cmath.rect(r, a)
    return coords.real, coords.imag

**Comment by Maso-craeter11** [comment] 2020-09-12 18:40
sorry was on a 30 min break

**Comment by Freshairkaboom** [comment] 2020-09-12 18:41
Not exactly what I meant. You can attach files to the bottom of your comment here. I need to see the lines inside the file to know they're in the proper place.

**Comment by Maso-craeter11** [comment] 2020-09-12 18:44
![Screen Shot 2020-09-12 at 2 43 44 PM](https://user-images.githubusercontent.com/62724015/93002639-61f0c780-f506-11ea-8146-6601b2905ee2.png)

**Comment by Freshairkaboom** [comment] 2020-09-12 18:49
Oh woops, nevermind I wanted to look at zz_interactions.rpyc but ofc it's encoded. Have you tried getting a new download? I know it will take a little while but I can't exactly look into your encoded files to see if there's anything wrong with them, so you'll need a fresh download (outside Steam) I feel.

**Comment by Maso-craeter11** [comment] 2020-09-12 18:54
nope still the same thing happened no ccmath.ccmath but i can find them

**Comment by Freshairkaboom** [comment] 2020-09-12 19:13
It seems to be a more comprehensive issue with Mac OS, and since none of us have Macs, we can't really test any fixes to this problem at the moment. The problem is that the game is not looking for the file in that folder. I'll try to get back to you when I know more.

**Comment by Maso-craeter11** [comment] 2020-09-12 19:42
ok

**Comment by Maso-craeter11** [comment] 2020-09-12 19:42
thank you!

**Comment by Maso-craeter11** [comment] 2020-09-12 19:47
Do you think what mod i can do?

**Comment by ThePotatoGuy** [comment] 2020-11-25 02:32
guessing there was no resolution. There's not much we can do for macs, sorry.

[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-11-25 02:32 UTC
