### ISSUE TITLE
[Suggestion] - Be right back/or a new topic > going to sleep

### ISSUE THREAD

**Issue by GGGabrie** [Monika-After-Story/MonikaModDev#5970] opened 2020-06-25 19:48 UTC
When you click on this option, you could either close the game, or ask her to sleep too!
If you ask her to go to sleep with you, there could be a sprite included (From the DDLC OUR TIME mod) where she lays down on a bed.

I'm aware that there is always the hug-sleep option, and with this new option+Sprite, this mod would be an even more authentic expierience. If someone asks, I could search for the sprite.

**Comment by fromulus** [comment] 2020-06-25 19:53
We're definitely _not_ going to steal sprites from other mods, even with permission from their original artists, so we'd need new art for this.

**Comment by multimokia** [comment] 2020-06-25 19:58
linking: #5787 for sleep brb (Though not quite what you're asking here)

There's plans for what you're describing, but it'll use art we commission most likely, rather than using sprites from an existing mod.

**Comment by ThePotatoGuy** [comment] 2020-07-26 03:23
marking as duplicate of #2781

**Closed** 2020-07-26 03:23 UTC
Labels: duplicate
