### ISSUE TITLE
[Suggestion] Topics for the player

### ISSUE THREAD

**Issue by LordOfDeath35** [Monika-After-Story/MonikaModDev#1372] opened 2018-04-02 15:26 UTC
I think it would be cool if you as the player could talk about more topics too and not just click some of the options and then Monika starts talking. For this cou could make dialogue with the name of the player above it and then make Monika react to whatever topic you chose to talk about (just like in DDLC). And you could also add options the player can choose while talking about the topic. Depending on what choice the player makes, the dialouge changes. This would make the whole conversation with Monika feel more natural. As of right now Monika basically does all the talking and all the player ever does is answer or click a topic and Monika starts talking about it. I believe that many people would enjoy actually being able to talk about topic longer than just pressing one button and then letting Monika take over the part of talking about the topic. I also believe that a few people would really like for their character/person to actually have dialogue and not just having to read Monika´s dialogue the whole time, cause it gets boring to just listen to what Monika says and not being able to actually talk about something yourself.
This is just a suggestion and doesn´t have to be added.

**Comment by ThePotatoGuy** [comment] 2018-04-02 16:14
Duplicate of #1368

**Closed by ThePotatoGuy** 2018-04-02 16:14 UTC
