### ISSUE TITLE
[Suggestion] You know what would be cool? Pajamas

### ISSUE THREAD

**Issue by elektroencefalografista** [Monika-After-Story/MonikaModDev#5216] opened 2020-01-12 19:28 UTC
Some comfy PJs would be perfect for sipping hot cocoa on cold winter nights.

It would also make sense if the outfits had a flag if they're okay to wear outside. Monika probably wouldn't be keen on heading out wearing Santa lingerie.
The flag would be checked when the "I'm going to take you somewhere" goodbye is chosen and would trigger Monika to change into something more appropriate.

**Comment by ThePotatoGuy** [comment] 2020-02-02 23:34
linking as duplicate of planned bedroom mode
#2781

**Closed by ThePotatoGuy** 2020-02-02 23:34 UTC
Labels: duplicate
