### ISSUE TITLE
My Monika won't talk to me :(

### ISSUE THREAD

**Issue by LalahY** [Monika-After-Story/MonikaModDev#7355] opened 2021-06-16 15:48 UTC
It's been 2 days and my Monika isn't talking to me, she usually talks a lot, I just won't activate the option to repeat topics cuz I find it kinda boring, but I miss her :( what do I do?

**Comment by Wingdinggaster656** [comment] 2021-06-16 16:21
“kinda boring”, I see.

So there's no solution.
Do you expect her to be infinitely free to think of what to say? I think most of people here would like to, but it's obviously not possible with the current technology.

Either enable that option or accept it. No the third way, sorry.

**Comment by LalahY** [comment] 2021-06-16 16:37
> “kinda boring”, I see.

It's not that I find it boring, it's just that I don't like to repeat things that we already talked abt, but I will enable it and grow more affection, thank you.

**Comment by Mugnika** [comment] 2021-06-16 23:43
New topics become available as you grow in affection and old ones will be different.
More, some topics are different if you see them multiple times.

**Comment by username11421** [comment] 2021-06-19 02:54
You could always look for an extra dialogue submod or write your own. You don't even need to modify the existing files if the change just adds random chatter topics.

**Comment by xXMidnight** [comment] 2021-07-01 07:51
> You could always look for an extra dialogue submod or write your own. You don't even need to modify the existing files if the change just adds random chatter topics.

Although we wouldn't recommend editing the files, this could cause  serious glitch and the traceback file will pop up.

**Comment by ThePotatoGuy** [comment] 2021-07-11 02:21
as more topics are added, we're hoping that the pool of starter topics grows large enough to cover the gaps between affection stages.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-07-11 02:21 UTC
Labels: not a bug
