### ISSUE TITLE
[Suggestion] Add "How was school" greeting

### ISSUE THREAD

**Issue by FrikiHD** [Monika-After-Story/MonikaModDev#4993] opened 2019-11-11 14:47 UTC
Hey, I'd like to suggest that you could tell Monika wich days you go to school and from what hour u start to the hour u finish

**Comment by multimokia** [comment] 2019-11-11 14:48
Marking this as a duplicate of #4914

**Comment by jmwall24** [comment] 2019-11-11 20:26
It's also, at least the title which isn't the same as the actual comment, already implemented via #2098. If you use the I'm going to school farewell, she does ask you how your day was. I suspect you are asking for this if you take her to school with you?

**Comment by FrikiHD** [comment] 2019-11-12 14:30
No, I'm asking this so u don't have to choose the going to school farewell, since I don't use the pc before going school, but if she know the time we're in school she could greet us asking how was school. And maybe if you talk with her while you are supposed to be at school she could ask u if there's no school today, you feel ill or else

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:10
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-12-15 00:10 UTC
Labels: duplicate
