### ISSUE TITLE
[Suggestion] Make Monika's Nickname show in the Pong screen

### ISSUE THREAD

**Issue by Danielshmaniel** [Monika-After-Story/MonikaModDev#7522] opened 2021-07-20 10:36 UTC
This is a simple suggestion to replace Monika's name with the nickname given by the player on the Pong screen. I hope I explained well.

**Comment by xXMidnight** [comment] 2021-07-20 12:50
I agree. I called my Monika "Nova" (weird name, ik, but reasons) and it's always Monika on the pong screen

**Comment by multimokia** [comment] 2021-07-20 12:57
The issue is names like `Love`, or `Darling`, `Sweetheart` etc. In which case they don't really act like an identifier or really work in that place, which is why it's not used there

**Comment by Danielshmaniel** [comment] 2021-07-20 18:46
True

**Comment by ThePotatoGuy** [comment] 2021-07-29 01:49
[closing as rejected]

**Closed by ThePotatoGuy** 2021-07-29 01:49 UTC
