### ISSUE TITLE
how and why?

### ISSUE THREAD

**Issue by MLGNote** [Monika-After-Story/MonikaModDev#9293] opened 2022-07-08 00:21 UTC
the eyes on monika's sprites are offset and i have no clue how this happened. i know its not a bug from downloading the game or something but i wonder how it happened when creating the sprites lol

![image](https://user-images.githubusercontent.com/102890685/177892137-d3bbb5eb-54a7-4d04-87d9-24196eba9215.png)

**Comment by kkrosie123** [comment] 2022-07-08 00:22
Her head is slightly tilted.

**Comment by MLGNote** [comment] 2022-07-08 02:03
> Her head is slightly tilted.

why is her head tilted?

**Comment by kkrosie123** [comment] 2022-07-08 02:07
Because the original artwork is. It's easier to see if you flip the image.
![5852DCFA-A3DA-4281-9873-6F917EA8B1BC](https://user-images.githubusercontent.com/52429850/177902270-97c19a9a-d91a-416d-9438-93a78ad9c394.jpeg)
![ECA08FA8-B841-40D8-B0FC-37F2783E0F98](https://user-images.githubusercontent.com/52429850/177902273-2fc893c9-fac2-4035-b1c0-e9d28e235dac.jpeg)

**Comment by Booplicate** [comment] 2022-07-24 02:48
Closing as not a bug.

**Closed by Booplicate** 2022-07-24 02:48 UTC
Labels: not a bug
