### ISSUE TITLE
bug during chess game

### ISSUE THREAD

**Issue by Alucard149** [Monika-After-Story/MonikaModDev#4516] opened 2019-08-01 22:32 UTC
I was playing normally and I moved my pawn two squares and he stood next to a Monika pawn and in front of another somehow she used the side pawn and ate mine diagonally even though it was not possible because mine was on the side (sorry if i made any grammar mistake)

**Comment by Rai99** [comment] 2019-08-01 22:33
Are you sure this wasn't an En passant move?

**Comment by Rai99** [comment] 2019-08-01 22:36
An en passant move is where your opponent moves a pawn 2 spaces and lands adjacent on the side of one of yours. In this specific scenario, you are allowed to move that pawn diagonally and take your opponent's pawn. 

This move was designed to punish those who try to move a pawn 2 spaces to safely bypass an opponent's pawn.

**Comment by Alucard149** [comment] 2019-08-02 14:42
Thanks for the explanation, I thought it was a bug because I didn't know that this movement existed, good that at the end of the game I still won

**Comment by ThePotatoGuy** [comment] 2019-08-24 16:20
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-08-24 16:20 UTC
Labels: not a bug
