### ISSUE TITLE
I can't gift anymore

### ISSUE THREAD

**Issue by TacoSgrava** [Monika-After-Story/MonikaModDev#8480] opened 2021-12-23 21:01 UTC
I tried for the first time today gifting (coffee) and she read the gift, so I thought everything was fine, but then when I tried giving her something else (hot chocolate) but it didn't work..
She actually took the coffee saying it was a christmas gift (it's almost christmas) so I thought I couldn't gift anything else today as I already did her gift, but when I search it up there's nothing talking about one gift per day or only one gift during christmas, so I'm scared it might has been an issue of mine?

**Comment by emcchiaki** [comment] 2021-12-23 21:22
i have the same problem but with sprite packs and i made sure i put everything correctly

**Comment by SirilTheFirst** [comment] 2021-12-24 02:56
Hey. I was confused at the start too. From what I understood on reddit, you put certain presents under the tree(this includes hot chocolate and sprite packs), and she will open them on Christmas instead. Check if she did it tomorrow. If she doesn't, maybe there really is a problem

**Comment by ThePotatoGuy** [comment] 2021-12-25 06:29
see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by ThePotatoGuy** [comment] 2022-01-09 21:59
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-01-09 21:59 UTC
Labels: not a bug, tree gift
