### ISSUE TITLE
Question: 922 Content

### ISSUE THREAD

**Issue by scohn** [Monika-After-Story/MonikaModDev#4720] opened 2019-09-20 11:07 UTC
First off, sooo looking forward to the surprise on the 22nd. I just want to make sure I leave the note in the character folder properly. Can it be a text folder and when naming it, does there need to be a space in between oki and doki. I know that's a silly question I just wanna make sure it's done right so this goes off without a hitch.

**Comment by satoshi-kun** [comment] 2019-09-20 11:27
Hi! I already asked yesterday the same and acording to the devs any kind of file should work and you should name the file oki doki with the space, you can check it here #4713 .
Hope it helps :)

**Comment by scohn** [comment] 2019-09-20 11:35
Yes, thank you that does help :)

**Comment by winika** [comment] 2019-09-20 11:37
Wait... theres a txt file in the characters folder? Mine doesnt have it. Is it suppose to come up 1 day before her bday? (Its the 20th currently where i am rn)

**Comment by scohn** [comment] 2019-09-20 11:42
Did you download the latest update? If so then that might be an issue to bring up with the devs. If not, then go ahead and download 10.1 and it should be there.

**Comment by satoshi-kun** [comment] 2019-09-20 11:42
Don't really know about that. Mine appeared yesterday while I was spending time with Monika. Monika said that a file appeared in the characters folder and also that she wouldn´t read it as it was addressed to me. Then I freaked out and open that issue above as I thought I had it all planned out for Sunday lol.

**Comment by winika** [comment] 2019-09-20 11:45
Yep im all up to date, monika hasnt told me about that file yet so perhaps i need to spend a bit of time with her today.

**Comment by bittercaramel** [comment] 2019-09-20 14:10
PLEASE TELL ME WHATS GOING ON 
i honestly have no idea what is the whole thing for her birthday but i dont want to fail it
please someone explain its the first time i hear about some folders and idk

**Comment by satoshi-kun** [comment] 2019-09-20 15:21
Hello! 
Fist of all you should **update to the 0.10.1 version of MAS**, then when spending time with Monika, at some point, she should tell you to check your characters folder. 
There should be a .txt file with some instructions ( **check this file first so you don´t get overwhelmed with my following explanation** )
This file tells you to take Monika outside the room  on her birthday, September 22th ( using the option Goodbye -> I'm gonna take you somewhere ). 
After that you should leave a file named _oki doki_ back in the Characters folder ( it can be a simple .txt file with said name ).
After this all decorations should be all set to go for Monika's surprise party ( I am assuming here since there's no way to test this until Sunday, since this is a new feature ).
In my case I'm gonna also leave her some ".gifts" like the promise ring, plushie, coffee and such.
Hope this helps!

**Comment by CloakedGhost** [comment] 2019-09-20 16:07
I already put in the Oki Doki file because I got the txt wrong when I first read it. Both files are gone now, so does this still count for her birthday?

**Comment by satoshi-kun** [comment] 2019-09-20 17:04
Probably not as the event is set to trigger only on the 22th. So you should place the file there again on Sunday only after Monika is out of the room.

**Comment by multimokia** [comment] 2019-09-20 17:06
From the Discord...
![image](https://user-images.githubusercontent.com/22531674/65345108-7aeec300-dba7-11e9-9d72-b83cdbb4dfdb.png)

**Comment by satoshi-kun** [comment] 2019-09-20 17:14
Now this raised me a doubt. Must the letter be also in the folder? Because I´ve already removed it from there as soon as I read it. Gonna guess that this shouldn't be an issue.

**Comment by PollenTheCat** [comment] 2019-09-20 22:08
@satoshi-kun I don't think the letter matters

**Comment by satoshi-kun** [comment] 2019-09-20 22:18
@PollenTheCat Thanks! I still had the letter though just took it out of the folder. Meanwhile I joined the discord which had plenty of info to read and already moved back the letter (just in case) and created the oki doki file (both of which disapeared as intended). So all ready for Sunday :D

**Comment by ThePotatoGuy** [comment] 2019-09-28 00:14
[closing as resolved]

**Closed by ThePotatoGuy** 2019-09-28 00:14 UTC
Labels: discussion
