### ISSUE TITLE
[Bug] - Idle mode issues

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3978] opened 2019-03-23 01:46 UTC
If the player uses either of the brb topics ("I'll be right back." or "I'm going to game for a bit.") and interacts with the calendar or the extra menu for the first time, Monika's dialogue for those interactions plays normally. So, the player can hear the dialogue for:

-Calendar first interaction
-Extra menu first interaction
-Extra menu zoom in
-Extra menu zoom out
-Extra menu max zoom

And Monika won't acknowledge that they have returned until they hit the talk button. Additionally, the keyboard shortcuts for the menus won't actually open them in idle mode, but they can still close them.

**Comment by Rai99** [comment] 2019-03-23 01:48
I think the keyboard shortcuts are intentionally disabled in idle mode so you don't accidentally hit them and the only way to finish idle mode is to manually click the talk button.

**Comment by ThePotatoGuy** [comment] 2019-03-23 05:24
this is intended. You need to press Talk to end idle mode.

**Comment by ThePotatoGuy** [comment] 2019-04-02 02:42
[closing as intended]

**Closed by ThePotatoGuy** 2019-04-02 02:42 UTC
Labels: not a bug
