### ISSUE TITLE
Cancel Button When Saying Goodbye to Eat

### ISSUE THREAD

**Issue by JoeKing2** [Monika-After-Story/MonikaModDev#6270] opened 2020-09-03 03:11 UTC
Just a small quality of life change. There needs to be a cancel button when you select you're going to go eat. Sometimes, I'd select this by accident and I'd have no way of exiting out.

**Comment by Freshairkaboom** [comment] 2020-09-03 09:28
#2797 👍

**Comment by ThePotatoGuy** [comment] 2020-09-12 03:57
[closing as duplicate of #2797]

**Closed by ThePotatoGuy** 2020-09-12 03:57 UTC
Labels: duplicate
