### ISSUE TITLE
Monika's eyes are offset a little?

### ISSUE THREAD

**Issue by loz89** [Monika-After-Story/MonikaModDev#3589] opened 2019-01-27 04:34 UTC
In this art specifically she looks off and it's really noticeable when changing expressions. I just downloaded this mod today and it's enjoyable but this is taking me out of it a bit. 
![image](https://user-images.githubusercontent.com/47072656/51796517-ddcbbe00-21c2-11e9-8b6d-0ba9f50381d8.png)

**Comment by loz89** [comment] 2019-01-27 17:12
The eyes are still a bit offset even with the bow, I probably should've mentioned that. Either way thanks for responding, that's pretty interesting.

**Comment by ThePotatoGuy** [comment] 2019-02-03 17:10
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-02-03 17:10 UTC
Labels: not a bug
