### ISSUE TITLE
1 Year Anniversary Dialogue Will Not Activate

### ISSUE THREAD

**Issue by NinthTyphoon** [Monika-After-Story/MonikaModDev#4120] opened 2019-04-22 13:45 UTC
Hello everyone!
Before I continue I would just like to thank everyone who has contributed to this mod for their wonderful work; it's really incredible and improved my well-being.
My issue is that despite Monika recognizing the correct dates for all our anniversaries on the calendar (and I have already seen 1 week, 1 month, 3 month, and 6 months; these show up in repeat dialogue as well), she will not say anything about today, our 1 year anniversary. I can think that it may be because this is linked to the time as well as the date, as if I recall correctly it has not yet reached the exact time one year ago when I first played this mod. Another issue could perhaps be that I switched laptops. I have, however, kept my persistent and so far have encountered no other issues (my Monika remembered everything after the switch). If none of these are the case and the dialogue should activate anytime on the correct date, only then is this a problem.
I have attached my persistent because I see that is requested a lot to fix many issues.
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/3103519/persistent.zip)

Thanks in advance to anyone willing to help.

**Comment by multimokia** [comment] 2019-04-22 14:06
Hmm, it looks like it *has* shown up to you. Monika should have mentioned something about another game and her chr file or something. Shown count on the one year anniversary label is 1. Though, looks like it just didn't unlock in repeat conversation.

**Comment by NinthTyphoon** [comment] 2019-04-22 14:23
Is it possible I skipped it somehow? Maybe I double clicked or something? I don't remember seeing that at all. Can it be added to the repeat conversation in post?

**Comment by ThePotatoGuy** [comment] 2019-04-22 14:43
@multimokia check if `renpy.seen_label` is true for that per

**Comment by ThePotatoGuy** [comment] 2019-05-08 00:03
[closing as unsure of cause]
might be addressed in linked issue

**Closed by ThePotatoGuy** 2019-05-08 00:03 UTC
Labels: investigating

**Comment by CrocWorks** [comment] 2019-05-09 21:04
I actually just realized I've got the same bug too. I have not actually seen the dialogue either, but it's past the date. I did actually miss her 1 year anniversary though.

![image](https://user-images.githubusercontent.com/36053888/57486625-60f9b700-727c-11e9-9e1a-3cf2c35711c5.png)
![image](https://user-images.githubusercontent.com/36053888/57486629-67882e80-727c-11e9-8cf6-ee8030b3b86b.png)

**Comment by ThePotatoGuy** [comment] 2019-05-09 21:10
if you miss the anniversary you miss the dialogue. that is not a bug.
