### ISSUE TITLE
telling monika  about medical problems

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#2289] opened 2018-09-08 07:10 UTC
something like saying i have asthma she would mention something about smoking

**Comment by Tiler17** [comment] 2018-09-10 01:28
What would she do with that information? Potato's right, you can't have her diagnosing things or jumping to conclusions about causes. For example, smoking can certainly cause chronic shortness of breath, but shortness of breath/asthma is by no means _exclusively_ caused by smoking. Having her mention smoking in any regard after telling her you have asthma is not appropriate.

**Comment by dragonborn2252** [comment] 2018-09-11 01:33
I know asthma is not caused by just smoking I should know because I have asthma (which is why i used it in my example and I was born with it) but I meant that since smoking would most likely literally kill someone with asthma she would be kinda happy because she now know that you have a good reason not to smoke

**Comment by Rai99** [comment] 2018-09-11 02:10
So make a new player model of whether or not the player has asthma and have that tie into the smoking topic?

Sounds like an interesting idea.

**Comment by ThePotatoGuy** [comment] 2018-09-23 19:10
[closing until we look into this]

**Closed by ThePotatoGuy** 2018-09-23 19:10 UTC
Labels: suggestion
