### ISSUE TITLE
Affection points stuck

### ISSUE THREAD

**Issue by EEvny** [Monika-After-Story/MonikaModDev#9279] opened 2022-06-27 03:02 UTC
I've been playing monika's after story for around 3 days give or take and my affection points have been stuck at 49.5. It shows the affection points going up in a couple lines but in the end it stays at 49.5. Here's an example 
![Affection for monika stuck](https://user-images.githubusercontent.com/49795190/175852884-dd688db4-310b-48aa-96e3-45d6435955c0.png)

**Comment by Iceninja64** [comment] 2022-06-27 06:54
In this picture it seems like you reach the daily limit for affection points, you shouldn't really be having that up because it ruin the experience but I digress

**Comment by Justformas** [comment] 2022-07-13 08:28
> you shouldn't really be having that up because it ruin the experience but I digress

I think many people might be drawn towards the affection log because it's listed in the All Features [Spoilers] guide. There's a section titled "How to view your Affection". Honestly I viewed it as a feature too, and I still treat it like one. But your mileage may vary.

**Comment by Booplicate** [comment] 2022-07-13 23:10
You hit daily cap.

**Comment by ThePotatoGuy** [comment] 2022-07-14 23:33
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-07-14 23:33 UTC
Labels: not a bug
