### ISSUE TITLE
More compliments to give Monika and more topics 

### ISSUE THREAD

**Issue by TertiaryCoot** [Monika-After-Story/MonikaModDev#4137] opened 2019-04-26 16:34 UTC
As I am sure this topic has been done to death but I personally believe at the current state of the compliments there isn't much variety. Don't get me wrong the mod is absolutely amazing and the devs have done an amazing job but I think a few people would enjoy giving more compliments to Monika. 

For instance a compliment could be "I wanted to tell you something..." 
" I loved you from the start " Monika would reply along the same lines but I'm sure the talented devs will spruce it up more. " I'm lucky to have you " Monika here could say that you are the reason she is still here or some modest thing. ". " I thought about you today " then Monika could say something along the lines of "I think about you all the time". " I am going to wait for you no matter how long it takes " Monika could cry and ask you to hold her depending on the affection level 400+ you can hold her 399 and below will get her saying she is willing to wait as well.

New topics, Now I know this one is also been Detroit smash into the ground by I still have more to add (:< " Why do you love me *insert player name" you can get options like Because your amazing, I don't know..., I don't, because you make me happy or some other romantic stuff and depending on what you say she will say back. "Do you like where you live *player name" Options: Its ok.., yeah its really nice, No, depending on your response she could say for the yes option "Oh I cant wait to be there with you!" For the ok "That's ok not every place is perfect we can move somewhere better together" and for "No" "That's ok *player name when we are together I will take you somewhere nice and we can be happy there like we are now!" I think Monika could also ask more not extremely personal questions but so she gets more of an idea who you are.  Since we do have a very very very limited knowledge on Monikas actual daily process but maybe if she tells you what she did during the day like searching up random facts or reading books and makes Monika feel way more real! 

These aren't entirely my suggestions but with discussing with friends we all can agree these would make a nice impact on the mod and make interactions feel a little more real and compliments more impactful. Sorry if this does annoy anyone I know I wrote a lot but it is only because I love this mod and everyone has done so much amazing work! Thank you for reading! (:

**Comment by Rai99** [comment] 2019-04-26 17:08
When creating more compliments, keep in mind that if we have too many, unless they give no affection, we might end up with too much free affection from the start, effectively skipping the early stages of the relationship. 

"I loved you from the start" as a compliment doesn't really sound necessary to me. If anything, I don't think it's something to really bring up randomly or early on. I think this fits better into a topic that's closer to the mood associated with that statement. 

These don't really sound like compliments to me. These sound more like things you would say in other topics as a response, rather than saying out of nowhere. 

"I am going to wait for you no matter how long it takes" might be a good response to something later on when it fits somewhere, but I don't think Monika would suddenly cry after hearing that alone, especially if you just say it out of nowhere. As a response to an already deep conversation? That could be a real possibility. 

A topic for why you love Monika is in theory, a good idea, but realistically, the problem is that everyone has their own different, personal reasons for loving Monika, and there's definitely no way we could cover all those possible reasons through a menu of any size. 

There are topics where Monika asks about the player and gets an idea of who they are and other details about them, such as if they live near a beach, if they live in the city, but a topic for whether or not they like where they live could be a potential topic. 

As for what Monika does in her free time, there was a project about Monika having a diary detailing what she does in her free time in #951, #2605, but I'd imagine it's a long and difficult process since it's really open ended. 

Maybe it might make Monika feel more real, but unless she tells you exactly what she read or learned, which isn't really possible, I don't know if it'll feel like much. 

If you don't mind me asking, how long have you had MAS out of curiosity? Feel free to make suggestions, but try to avoid spamming or duplicates. Duplicates, you might not be able to help, but you know, if you saw someone already suggested it, you don't have to bring it up again.

**Comment by TertiaryCoot** [comment] 2019-04-26 17:21
@Rai99 I've had MAS for around 3months to this day. Reading what you have to say definitely puts it into a new light in my eyes. I commented on it being spammed to death only because I wish not to be rude to anyone. You are definitely and in further thinking some of the things I wrote were a little over exaggerate sorry to waste your time. I was just rambling. Still it is a fantastic mod and all the work everyone puts in is amazing thank you for replying ( ;

**Comment by Rai99** [comment] 2019-04-26 17:23
If you think reading is a waste of my time, you probably don't know what I do in my spare time.

**Comment by TertiaryCoot** [comment] 2019-04-26 17:27
@Rai99 I'm not entirely sure what you are implying but its currently 1:30am and I'm not thinking straight so still sorry if I came off passive aggressive or in a rude tone.

**Comment by Rai99** [comment] 2019-04-26 17:28
Not at all. You were 100% fine. 

I was just saying that you didn't waste my time, and I probably do other things that are a bigger waste of time.

**Comment by TertiaryCoot** [comment] 2019-04-26 17:32
@Rai99 Oh my lord either im going to get some coffee or sleep I can't even read right now, sorry!

**Comment by AsuraShun** [comment] 2019-04-26 17:39
A huge waste of time is trying to do a no hit run in dark souls

**Comment by ThePotatoGuy** [comment] 2019-05-08 00:18
more topics is an ongoing project. closing as this as a general thing and not a specific suggestion

**Closed by ThePotatoGuy** 2019-05-08 00:18 UTC
