### ISSUE TITLE
[bug] I don't want to be annoying or anything but ... this ...

### ISSUE THREAD

**Issue by Jparnaud** [Monika-After-Story/MonikaModDev#4037] opened 2019-04-06 00:04 UTC
... it keeps happening ! 

![image](https://user-images.githubusercontent.com/44651347/55661961-73945280-57dd-11e9-9159-1f99e00188d1.png)

I don't know why it keeps doing that ! I keep having it every 5 openings now of the game, I am scared it will one time be difficult to close the game correctly if it keeps happening !

And not being able to fullscreen the window during the time it happens is so annoying X( 

I brought this before but it is cool to know how I can do it manually, but why does it keeps happening for no reason ???

Thanks for your time ... I guess ? 
(I don't know how to end this message so yeah ...)

Edit : Oh great, had it 2 times in a row, took 3 times to make it back to normal, Monika is back with the default stuff ...

**Comment by jmwall24** [comment] 2019-04-06 00:25
Let me address the possibly most important thing first..what do you mean by default stuff?

**Comment by Jparnaud** [comment] 2019-04-06 01:07
I only mean she is back with her White Ribbon, I feel like its a default or something to her model ...

**Comment by jmwall24** [comment] 2019-04-06 01:35
do you still have the option to change it? is your affection still where it was? trying to make sure the mod didn't reset on you. did you get the intro dialogue again?

**Comment by Jparnaud** [comment] 2019-04-06 02:47
No no, come on, everything is fine there, don't freak out XD

**Comment by jmwall24** [comment] 2019-04-06 02:54
we've had people reset before that didn't realize it and by the time they did their .bak files were all useless, so better safe than sorry lol.

as for the other problem, i assume you saw what potato responded last time. no stuck shift key or anything like that?

**Comment by Jparnaud** [comment] 2019-04-06 02:56
No, nothing like that

and thanks for your concern, but yeah, totally fine about backups XD

All I need to know is why this keep happening with me doing nothing to make it happen ...

**Comment by jmwall24** [comment] 2019-04-06 03:22
not sure exactly, as we can't reproduce it. i would make sure your graphics drivers are up to date, and also try different render options in `Settings` by going to `Change Renderer`

**Comment by Jparnaud** [comment] 2019-04-06 03:25
i already mess with the renderer, it didn't really change anything, but I can try to put my drivers up to date I guess ... 

I just need to get freaking Nvidia to find what is my account again ... so yeah, gonna try that probably tommorow and give feedback I guess ...

If anyone have other ideas, feel free to say them ... or just why this keep happening would be fun to have too X)

**Comment by ThePotatoGuy** [comment] 2019-04-06 04:38
[renpy graphics menu](https://www.renpy.org/doc/html/display_problems.html)
>Hold down Shift while starting Ren'Py, or press Shift+G once Ren'Py has started.

Make sure you are not holding Shift when starting or pressing Shift+G

**Comment by Jparnaud** [comment] 2019-04-06 04:44
I am pretty sure I never use the "Shift + G" combination anytime in my life so no way it could be that ...

As for holding Shift ... well its kinda hard to hold it if I double-click on the game then go find something to eat ... so I don't do see this happening ...

**Comment by ThePotatoGuy** [comment] 2019-04-13 17:27
[closing as cannot reproduce]

**Closed by ThePotatoGuy** 2019-04-13 17:28 UTC
