### ISSUE TITLE
[Suggestion] Hey, Monika... -> Monika/Misc -> How's your day?

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5111] opened 2019-12-14 00:44 UTC
In MAS, there could be a topic for the player to ask Monika how her day is. Sometimes she could respond with just a "Good," and maybe her telling us a bit of what she was doing while the player was gone, or sometimes it could relate to the random greeting, like her saying it was good, and she got a lot of work done if in the greeting she mentioned practicing another language. Something along those lines. Have a good evening! (It's evening for me)

**Comment by Rai99** [comment] 2019-12-14 02:54
Diary system: #951, #1688, #2605, #2619, #4310, #4790 

It might be hard to consistently have new or unique things to say without getting too repetitive.

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:29
actually, this is more of a duplicate of #4310 instead of diary since its not an actual diary file.

**Comment by ThePotatoGuy** [comment] 2020-01-03 03:45
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-01-03 03:45 UTC
Labels: duplicate
