### ISSUE TITLE
GENDER

### ISSUE THREAD

**Issue by Cosmic-Incantations** [Monika-After-Story/MonikaModDev#8622] opened 2022-01-16 22:54 UTC
I don't need much done, but the gender option of neither bugs me cause I kind of lye in-between gender and not just simply none
I know this is a minor thing and I am being whiny, but can someone change it to "I am something else" then neither? cause it helps for those who are not a boy or girl but dose not go by none. it can still be they/them pronouns

sorry for complaining, but I think of myself more as both but I can only choose neither. you can dismiss this since a gender update has happened already and this is not a lot

**Comment by Booplicate** [comment] 2022-01-16 23:00
`neither` isn't none, it means neither *of the options*, not a boy, not a girl. So Monika will use `they`/`them`. Although, there's only like one or two places where we use pronouns.
That said, there's plans to change this, since it's not really about genders, but about pronouns, which are 2 different things.

**Comment by Cosmic-Incantations** [comment] 2022-01-16 23:11
ok, I often misinterpret things, it's good to know that. But that was what I am getting at, it's about pronouns and such

**Comment by ThePotatoGuy** [comment] 2022-01-28 03:20
marking duplicate of #6084 . all discussion should be moved to that issue.

**Closed by ThePotatoGuy** 2022-01-28 03:20 UTC
Labels: duplicate
