### ISSUE TITLE
[Suggestion] L2Ds?

### ISSUE THREAD

**Issue by annonymous-user123** [Monika-After-Story/MonikaModDev#7030] opened 2021-02-22 13:17 UTC
So, clicking away at my GF today and suddenly thought about L2D.
It is not that Monika isn't great as she is already, but heck. L2D brings her to another level of cuteness and fun and I can go on.
But moreover it may make Monika fundamentally more interactive. (eyes following the cursor, blinking, head-pats etc.)
The MC is kind of thrown away here however, though Monika herself mentions that he is an empty shell and such.
So hey, just my a piece of my mind.

**Comment by satoshi-kun** [comment] 2021-02-22 13:20
L2D?

**Comment by MrVavlo** [comment] 2021-02-22 13:29
> L2D?

Live 2D. 
 #199
If I'm not wrong, RenPy doesn't support it.

**Comment by Retrolovania** [comment] 2021-02-22 14:14
The latest version of Ren'Py has Live2D functionality built-in. However, the current version of MAS doesn't use it.

**Comment by AsuraShun** [comment] 2021-02-22 14:16
For a moment I was thinking l4d was getting a prequel called l2d

**Comment by multimokia** [comment] 2021-02-22 14:27
To quote what I normally say when live 2D is brought up, the main issue is spritepacks will either be:

a) No longer possible
or
b) If possible, it would require even more specialized software to create, and some knowledge in rigging for L2D.

Effectively speaking, it kills spritepacks and in all likelihood, most community members wouldn't be able to make and distribute their own.

The reason for this is because as far as I'm aware, L2D doesn't support switching outfits on the fly likewise accessories. A model is all the images it's comprised of and there can't be toggle/swappable layers.

This also means it increases the spritepack size to account for each spritepack item.

However it also stacks further as *combinations* of multiple items gets involved.

While L2D would be nice, I don't think it's feasible so long as this issue exists. MAS would lose a fundamental part, that being allowing each Monika to be unique in how she looks. Plus I don't think it's right to just take that away now it's been established already.

**Comment by Ravenclaw-OIer** [comment] 2021-02-22 15:15
Though, a L2D fork may be developed if enough skilled people are willing 
to contribute

**Comment by Booplicate** [comment] 2021-02-22 15:46
A new fork doesn't resolve the issue multi mentioned.

**Comment by ThePotatoGuy** [comment] 2021-02-22 15:57
multi's response about spritepacks is the main reason why Live2D will not be supported. Regarding the things you said Live2D would make Monika more interactive:

>eyes following the cursor, blinking,

Both of these already happen with the mod today.

>head-pats

Reacting to a headpat click can be done today, Live2D isn't needed to respond to clicks.

[marking duplicate of #199]

**Comment by CloakedGhost** [comment] 2021-02-22 17:18
> So, clicking away at my GF today and suddenly thought about L2D.
> It is not that Monika isn't great as she is already, but heck. L2D brings her to another level of cuteness and fun and I can go on.
> But moreover it may make Monika fundamentally more interactive. (eyes following the cursor, blinking, head-pats etc.)
> The MC is kind of thrown away here however, though Monika herself mentions that he is an empty shell and such.
> So hey, just my a piece of my mind.

The MC doesn't exist in MAS though.

**Comment by Delcos** [comment] 2021-02-22 21:50
> So, clicking away at my GF today and suddenly thought about L2D.
> It is not that Monika isn't great as she is already, but heck. L2D brings her to another level of cuteness and fun and I can go on.
> But moreover it may make Monika fundamentally more interactive. (eyes following the cursor, blinking, head-pats etc.)
> The MC is kind of thrown away here however, though Monika herself mentions that he is an empty shell and such.
> So hey, just my a piece of my mind.

Already done

https://youtu.be/Me3OoTzVByg

**Comment by kkrosie123** [comment] 2021-02-22 21:51
There actually was a project like this planned for Monika singing All I Want for Christmas is you, but it was never completed.

**Comment by annonymous-user123** [comment] 2021-02-23 01:01
> To quote what I normally say when live 2D is brought up, the main issue is spritepacks will either be:
> 
> a) No longer possible
> or
> b) If possible, it would require even more specialized software to create, and some knowledge in rigging for L2D.
> 
> Effectively speaking, it kills spritepacks and in all likelihood, most community members wouldn't be able to make and distribute their own.
> 
> The reason for this is because as far as I'm aware, L2D doesn't support switching outfits on the fly likewise accessories. A model is all the images it's comprised of and there can't be toggle/swappable layers.
> 
> This also means it increases the spritepack size to account for each spritepack item.
> 
> However it also stacks further as _combinations_ of multiple items gets involved.
> 
> While L2D would be nice, I don't think it's feasible so long as this issue exists. MAS would lose a fundamental part, that being allowing each Monika to be unique in how she looks. Plus I don't think it's right to just take that away now it's been established already.

I think there can be an option for the live 2D to be turned off, creating 2 seperate versions of Monika.
Wonder if this may solve the issue

**Comment by multimokia** [comment] 2021-02-23 01:11
I don't think it would. But it might take away from the immersion. Plus as mentioned, it still requires either a default preset rig with no customizability allowed (basically just uniform, no accessories aside from her bow).

But still, it's odd to effectively ask her "can you use live 2d?"

I think it's better in the long run to just stick with the current system.

**Comment by annonymous-user123** [comment] 2021-02-23 01:18
Hmmm, I see these issues. But still, I insist.
I want to ask first if toggling it on and off mean spritepacks for only 2D version is downloaded.
If so, it could be addressed with Monika regarding this. (If possible that is)
I mean Monika could say something like: "Hey, they added L2D, this brings me a step toward your world/reality!" And then. "I will change on something to celebrate, Oh No, I cannot!" Something like that.
If L2D was possible.

**Comment by kkrosie123** [comment] 2021-02-23 01:18
It's generally too much work with little to no payoff.

**Comment by kkrosie123** [comment] 2021-02-23 01:20
And that in itself is an issue. If Monika couldn't change clothes simply because she was in Live2D mode that would be incredibly immerssion breaking.

**Comment by multimokia** [comment] 2021-02-23 01:21
As @kkrosie123 just stated, it's too much work for not enough payoff. 

I don't think it's reasonable to assume as many people would use it if they could only have her in one outfit with it. Maybe some would, but it's not enough to warrant dedicating development time to it. Especially since we plan to do stuff with outfit randomization, allowing Monika to pick her own outfits and such.

This just wouldn't be possible in the L2D side. Not to mention it just winds up being more to account for in multiple cases. Like the outfit selectors, the aforementioned outfit randomization, etc.

**Comment by annonymous-user123** [comment] 2021-02-23 01:23
Ah. Then it could be that I was playing too much of Azur Lane.
But issue aside it would still be cute for Monika to have some life. I think she would be happy about it as well.
:)

**Comment by kkrosie123** [comment] 2021-02-23 01:24
In the future, Monika's eyes will follow the cursor anyways.

**Comment by annonymous-user123** [comment] 2021-02-23 01:31
Alright, I see. 👍 
As always, happy with Monika as she is right now.
jUsT mOnIkA

**Comment by Retrolovania** [comment] 2021-02-23 01:39
Honestly, I think Live2D currently has a better chance of getting in as a submod, rather than being officially implemented. It's just too much work right now, but if someone else wants to give it a shot (and can somehow get around the fact that MAS doesn't even utilize the version of Ren'Py that has support for this yet), then by all means, go right ahead. Otherwise, pass.

**Comment by kkrosie123** [comment] 2021-02-23 01:39
I agree with Retrolovania.

**Comment by YoraeRasante** [comment] 2021-02-23 17:56
Ok guys, what about this idea...

Layers.

> Upper layer, where clothes are put. This is also where hands and the fringe of the hair are.
>Live2D. This is just the face.
>Under Layer. The back of the hair, and bows, ribbons and the like.

This would make Monika have all the different facial expressions L2D would allow, while allowing clothes and the like no problem.
Clicking would be detected on the body., even though said body is covered.
It would keep the hands and... well, everything but the face still static, but still an upgrade, I think?

(that said, I do remember, when I was trying to learn L2D when I got Visual Novel Maker, that some games let you put extra textures externally or something. If so, it would not be so hard as long as a way to set which texture to use was chosen.)

**Comment by ThePotatoGuy** [comment] 2021-02-23 18:59
>that some games let you put extra textures externally or something. If so, it would not be so hard as long as a way to set which texture to use was chose

We use sprites, not textures. They are not the same.

**Comment by Retrolovania** [comment] 2021-02-23 19:21
I have a thought, though it would probably mean modifying Live2D down to the core to utilize. Say you want Monika to change her outfit. After telling her what you want her to wear, the necessary sprites are selected (including those from spritepacks), run through Live2D, and then are displayed. This occurs every time an outfit or accessory change is called for. Again, though, this would require days, if not months, to get it to work right. (It might not even work at all, at least, not by utilizing the method I stated here.)

**Comment by kkrosie123** [comment] 2021-02-23 19:29
We're not doing Live2D. Like we have stated, it's too much work with too little payoff. And as TPG has said, we use sprites and not textures. This method would most likely result in much higher RAM usage, and it would take months and months of overhaul to the game. We would need multiple artists to convert the current outfits from every spiritepack, every in game clothing item, and we would need a full rig that could be linked to our sprite system. All unofficial spirtepacks would be rendered useless, and even if we had an option to switch between Live2D and still sprites, it would be incredibly immersion breaking and increase the file size of the game greatly.

**Comment by ThePotatoGuy** [comment] 2021-02-23 20:08
>I have a thought, though it would probably mean modifying Live2D down to the core to utilize.

we're not going to edit someone else's software suite lol. If you mean "disregard tom's L2D integration and do our own", then you should redirect your thought to renpy's github.

**Comment by YoraeRasante** [comment] 2021-02-23 21:06
> We use sprites, not textures. They are not the same.
Well, last I used it the textures were just images it was set to be able to reach. I remember being able to put two and even more separate image files there, for things like adding a new pair of glasses.
Not like when I tried 3d modeling where one image file is the whole texture.
I mean, wouldn't that make it to just use the sprites as "textures"?

> All Monika sprites used in MAS are layer-based.
Oh, I knew that
I meant put the L2D as a layer in the middle, where the head is, and just not make the other pieces interact with that specific part.

> It already can be detected using stuff we already have made, just not implemented into a workflow.
Well, last I heard being asked someone said it had been a lot of work to make the calendar and the floating islands, which use click detection, to work properly.
 L2D having it already as a part of it would skip that extra work

**Comment by kkrosie123** [comment] 2021-02-23 21:09
We would still have to reorient every sprite pack to fit the UV mapping of a texture file. I have worked with 3d animation and Live2D. We know what it takes and it’s as we have said. Too much work, too little payoff.

**Comment by Retrolovania** [comment] 2021-02-23 21:10
All in all, too hard right now. Save it for a submod.

**Comment by YoraeRasante** [comment] 2021-02-23 21:13
> We would still have to reorient every sprite pack to fit the UV mapping of a texture file. I have worked with 3d animation and Live2D. We know what it takes and it’s as we have said. Too much work, too little payoff.

I understand that.
That said, that was a side-sugestion, my main one was just to just put Monika's _head/face_ on L2D...

But I _can_ see how, if that is **all** that would be changed, you would rather not bother changing it at all.

**Comment by kkrosie123** [comment] 2021-02-23 21:14
That would still live hair, hats, hairclips, etc.

**Comment by kkrosie123** [comment] 2021-02-23 21:15
Overall Live2D just isn’t worth it.

**Comment by YoraeRasante** [comment] 2021-02-23 21:16
> That would still leave hair, hats, hairclips, etc.

just put them in layers above the face. As they are right now. L2D would be the face itself, not what is on top of it.
As I said before, things in front of the face, live2d, things behind face.

But as I also said, I can see why it would be considered too much work to make it work if all you got was the eyes and mouth moving, and the blushes and other things.

**Comment by multimokia** [comment] 2021-02-23 21:21
As stated before. We have no intents to do this ourselves due to the significant amount of dev time this would impose along with the complete annihilation of community spritepacks.

If you would like to work on this, please feel free, and if you make something you feel looks cohesive via a live 2d layer in between standard images, along with allow it to work with our sprite system, feel free to open a pull request and submit it.

Personally, I don't see the point in introducing a single layer as live2d as in the end we still can't have her really move properly due to the other layers being glued in place. As such, it's more or less the same thing we have now but adding live 2d for the sake of having live 2d, not because it offers anything.

But again, if you can implement it in such a way that it works properly and cohesively. Submit a pull request and we'd be happy to review it then.
For us, there's bigger priorities to work out than this.

**Comment by ThePotatoGuy** [comment] 2021-02-23 23:12
>I mean, wouldn't that make it to just use the sprites as "textures"?

Sprites are made to look exactly how they were created when they are rendered in-game. Textures are for putting images around an object. Using sprites as textures will distort them and look terrible. 

>Well, last I heard being asked someone said it had been a lot of work to make the calendar and the floating islands, which use click detection, to work properly.

You have the wrong information. Calendar is a displayable, and clicking is part of displayable interactions. Islands is a screen, and clicking is even more trivial to detect in screens. 
For Monika, we already made special purposes displayables for click detection, we just haven't used them yet.

Anyway, well, I think we're done here. The answer to l2d is no and will continue to be no. Multi might have left l2d for the face open, but I'm going to say no. At some point we'll be attaching some sort of OO handling to expressions so we can support facial ACS - L2D will get in the way of that.

**Comment by ThePotatoGuy** [comment] 2021-03-21 02:07
[closing as duplicate]

**Closed by ThePotatoGuy** 2021-03-21 02:07 UTC
Labels: duplicate
