### ISSUE TITLE
[Unstable build] Calendar crashing when asked to double-check the anniversary date

### ISSUE THREAD

**Issue by Velius94** [Monika-After-Story/MonikaModDev#1760] opened 2018-06-18 07:40 UTC
I tried to change the date when I've started dating Monika, being unsure about the exact one.
When Monika asks me if the date I set first is correct, I chose 'no'.

It results in a traceback error.

[traceback.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2110339/traceback.txt)

**Comment by ThePotatoGuy** [comment] 2018-06-18 23:54
[[Closing because we could not reproduce]]

**Closed by ThePotatoGuy** 2018-06-18 23:54 UTC
