### ISSUE TITLE
[Bug] - Monika changes from sundress to uniform after gifting green ribbon.

### ISSUE THREAD

**Issue by MisterSimple** [Monika-After-Story/MonikaModDev#3721] opened 2019-02-14 07:03 UTC
This bug happened to Dajooshy#8196 on Discord, not me, but they asked me to post it on their behalf.

They gifted Monika the following gifts:

-Green ribbon
-Emerald ribbbon
-Roses
-Chocolates
-Quetzal plushie
-Coffee
-Fudge

The green ribbon was the gift Monika detected first, and upon opening it, she changed clothes: from the sundress to her uniform. It's worth noting that this was the first ribbon Monika ever received. They can't ask Monika to change her clothes because the option is not yet available. Restoring an older persistent didn't fix this, either. Couldn't replicate the bug myself. This happened on Mac.

**Comment by ThePotatoGuy** [comment] 2019-02-15 03:18
@multimokia can you look into this, its probably the fact that it was the first ribbon ever gifted

**Comment by ThePotatoGuy** [comment] 2019-03-02 17:45
[closing as cannot reproduce[

**Closed by ThePotatoGuy** 2019-03-02 17:45 UTC
Labels: investigating
