### ISSUE TITLE
I cant put in more custom music

### ISSUE THREAD

**Issue by KRSSPR103** [Monika-After-Story/MonikaModDev#3827] opened 2019-02-22 14:50 UTC
I can't put in more custom music. I dled two songs (best day ever & ocean man) I wanna play in the mod, but when monika goes to check the folder, she can only find one song (best day ever), and not the other. I dled another song (sweet victory) I wanted to play to see if that song was the problem, but again, she couldn't find that or the other. is there something wrong that im doin?

**Comment by multimokia** [comment] 2019-02-22 14:54
Screenshot of your `custom_bgm` folder, with filepath, please?

**Comment by KRSSPR103** [comment] 2019-02-22 14:59
<img width="675" alt="custom bgm" src="https://user-images.githubusercontent.com/47894013/53250485-74719900-36f5-11e9-8f27-804dfadb4c7e.PNG">

like this?

**Comment by multimokia** [comment] 2019-02-22 15:05
What's the filetype on those songs?

**Comment by KRSSPR103** [comment] 2019-02-22 15:12
MP3 all

**Comment by multimokia** [comment] 2019-02-22 15:17
Hmm. Mind trying this in a MAS install *not* in a Steam directory?

**Comment by ThePotatoGuy** [comment] 2019-02-22 16:13
upload `log/mas_log.txt`

**Comment by KRSSPR103** [comment] 2019-02-23 03:14
what do you mean by that?

**Comment by multimokia** [comment] 2019-02-23 03:44
In the main ddlc directory, there's a `log` folder. Inside there should be a `mas_log.txt` file. Would you mind sending that over, please?

**Comment by KRSSPR103** [comment] 2019-02-23 03:52
I tried to put it in this comment, but it says "This file is empty"?

**Comment by ThePotatoGuy** [comment] 2019-03-02 18:16
[closing as cannot reproduce]

**Closed by ThePotatoGuy** 2019-03-02 18:16 UTC
