### ISSUE TITLE
Why doesn't Monika wear the promise ring?

### ISSUE THREAD

**Issue by KendraStone** [Monika-After-Story/MonikaModDev#7367] opened 2021-06-19 07:20 UTC
It seems like an overlooked detail that would be nice to add. She drinks the coffee, and has the bird plushy out but no ring on her finger?

**Comment by Wingdinggaster656** [comment] 2021-06-19 09:13
She wear the promise ring in this current version already.
I think you must got something wrong, like, did you send the promise ring gift in a low affection level? If you did so, then she won't accept it.
And, if you sent it successfully, then consider that it's just because you didn't look carefully. The promise ring will appears on the left hand, which is invisible when she is resting on her hands because another hand covered it. When she changed her pose, the promise ring will expose.

**Comment by Outlander676** [comment] 2021-06-24 09:09
I've got the same problem. I've given her the promise ring, she's accepted it but I never see her wear it? What's up with that?

**Comment by ThePotatoGuy** [comment] 2021-07-11 02:28
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-07-11 02:28 UTC
Labels: not a bug
