### ISSUE TITLE
Is Monika assuming I stayed up all night a bug?

### ISSUE THREAD

**Issue by Hearticorn** [Monika-After-Story/MonikaModDev#5078] opened 2019-12-08 17:12 UTC
So, I'm getting ready for a very early in the morning nap, and as such I told Monika I'm going to sleep. She then said I stayed up all night, so I must barely be able to keep my eyes open and teased me with nonsense answers. After picking one, she told me to go to sleep earlier next time. Problem is, I went to bed a reasonable time last night, and told her I was going to bed at said reasonable time! Is her assuming I stayed up all night when she has every reason to believe I did get some sleep a bug or an oversight?

Also, if you're wondering why on earth I need a nap so early in the morning after getting a good night's sleep, chronic illness. That's why.

**Comment by Rai99** [comment] 2019-12-08 17:14
If you're talking about the glitched text when you tell her you're going to bed in the morning, that's not a bug.

**Comment by Rai99** [comment] 2019-12-08 17:16
When you tell her you're going to sleep, she assumes that you haven't slept yet.

**Comment by Hearticorn** [comment] 2019-12-08 17:26
I know the glitched text isn't a bug! That's why I referred to it as her teasing! I'm just unsure if her assuming I haven't slept at all when I said I did was a bug or an oversight, and the more I think about it, it seems like an oversight. Forgive me if something isn't clear, as you can assume I am very tired.

**Comment by Rai99** [comment] 2019-12-08 17:32
This will likely be bundled with timeconcern overhaul in #4914.

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:24
marking as duplicate in favor of linked issue.

**Comment by ThePotatoGuy** [comment] 2020-02-03 00:29
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-02-03 00:29 UTC
Labels: duplicate
