### ISSUE TITLE
[Discussion/Suggestion] Monika reads SCP Foundation

### ISSUE THREAD

**Issue by AfroFluff** [Monika-After-Story/MonikaModDev#8198] opened 2021-11-07 20:57 UTC
Now I know there are a metric ton amounts of SCPs out there but I was wondering, do you guys think she would read something like that? I believe she would be inspired by the fact that hundreds of people are being creative on 1 site, expanding a fictional universe every passing day, week, month. 

I think she would read a couple, probably the most known ones first, just to dip her toe into the pool of madness but maybe then she ends up making her own? I would be interested to see if she is aware of it at least. She doesn't need to specifiy any SCP (cause again, there is so many) but maybe she just talks about the foundation site as a whole.

What do you guys think?

**Comment by ThePotatoGuy** [comment] 2021-11-12 17:15
duplicate of #2815

**Comment by ThePotatoGuy** [comment] 2021-12-02 03:32
[closing as duplicate]

**Closed by ThePotatoGuy** 2021-12-02 03:32 UTC
Labels: duplicate
