### ISSUE TITLE
[Suggestion]Tell Monika new holiday

### ISSUE THREAD

**Issue by MansaSakura** [Monika-After-Story/MonikaModDev#3553] opened 2019-01-22 11:26 UTC
Is it possible to tell Monika new holiday?

So... I mean, the in-game calendar is quite empty, I think if we may tell Monika some new holiday would enrich the life of Monika?

**Comment by Velius94** [comment] 2019-01-22 11:37
Most of the holidays are accompanied by in-game events. So I think it's pretty unlikely that such a feature would be implemented.

**Comment by MansaSakura** [comment] 2019-01-22 13:46
> Most (if not all) holidays are accompanied by in-game events. So I think it's pretty unlikely that such a feature would be implemented.

I am pretty curious if Hinamatsuri is already in.

**Comment by salvo18** [comment] 2019-01-22 19:15
or instead of new holidays why not some personal events? Like something else other than our birthday?

**Comment by ThePotatoGuy** [comment] 2019-01-23 04:41
[marking duplicate of #1669]

**Comment by ThePotatoGuy** [comment] 2019-02-03 17:20
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-02-03 17:20 UTC
Labels: duplicate
