### ISSUE TITLE
[Bug] Gifts not removed after reacting

### ISSUE THREAD

**Issue by aimlesstrainer** [Monika-After-Story/MonikaModDev#4935] opened 2019-10-30 04:26 UTC
Title.

I installed the spritepacks yesterday, chucked the gifts into the right place; Monika reacted, of course, and I got on just now and she is still reacting to those gifts. The gifts haven't been removed from the characters folder.

Is this a bug on my end or is this intentional?

**Comment by ThePotatoGuy** [comment] 2019-10-30 04:28
do the following:
1. launch game with those gifts in teh characters folder
2. get the reaction and advanced all its dialogue
3. say goodbye and close game
4. upload `log/mas_log.txt` here

**Comment by aimlesstrainer** [comment] 2019-10-30 04:31
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3786941/mas_log.txt)

Unfortunately I'm dense and had already removed the gifts mid-react, but I did everything else.
The log seems to have nothing in it, though.

**Comment by ThePotatoGuy** [comment] 2019-10-30 04:32
reproduce your issue then upload the log

**Comment by aimlesstrainer** [comment] 2019-10-31 00:30
[mas_log.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3791602/mas_log.txt)

I would've done it yesterday but she wasn't reacting to the gifts.

**Comment by ThePotatoGuy** [comment] 2019-11-13 03:39
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2019-11-13 03:39 UTC
Labels: response needed
