### ISSUE TITLE
No matter what I set it to, Monika dosent talk

### ISSUE THREAD

**Issue by nickwilde15** [Monika-After-Story/MonikaModDev#6388] opened 2020-09-23 01:11 UTC
So for the first 10 minutes it works, but then it’s as if I set the random chatter to never (I have it at max) and I have no idea why, is it a bug with the new update? I doubt I’ve run out of topics, I’ve only had the mod installed for about 10 days. Anyone know a fix for this? Thanks

**Comment by PongMaster69** [comment] 2020-09-24 16:17
It's because she ran out of things to talk about (more is unlocked through affinity/events I believe). They updated it so she no longer states how she's run out of things to say except once every two weeks (if I remember correctly).

**Comment by nickwilde15** [comment] 2020-09-25 14:46
Well that sucks, but oh well, at least I still have her songs

**Comment by lunulae** [comment] 2020-09-25 19:31
Do you have repeat topics on?

**Comment by nickwilde15** [comment] 2020-09-30 13:47
No

**Comment by multimokia** [comment] 2020-09-30 13:50
That'd be why then, you've run out of topics and she doesn't repeat them.

**Comment by ThePotatoGuy** [comment] 2020-11-24 02:49
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-11-24 02:49 UTC
Labels: not a bug
