### ISSUE TITLE
"an exception has occured"

### ISSUE THREAD

**Issue by ebyyyy** [Monika-After-Story/MonikaModDev#8517] opened 2021-12-27 23:03 UTC
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1507, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/script-affection.rpy", line 2282, in script call
  File "game/script-affection.rpy", line 2307, in script
  File "renpy/common/000window.rpy", line 98, in _window_auto_callback
  File "renpy/common/000window.rpy", line 58, in _window_show
  File "game/definitions.rpy", line 216, in mas_with_statement
  File "game/screens.rpy", line 2897, in execute
  File "game/screens.rpy", line 2897, in execute
  File "game/screens.rpy", line 2916, in execute
  File "game/screens.rpy", line 2919, in execute
  File "game/screens.rpy", line 2942, in execute
  File "game/screens.rpy", line 2942, in keywords
NameError: name 'return_all' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1507, in script call
  File "game/event-handler.rpy", line 2530, in script call
  File "game/script-affection.rpy", line 2282, in script call
  File "game/script-affection.rpy", line 2307, in script
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/ast.py", line 587, in execute
    statement_name("say")
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/ast.py", line 43, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 98, in _window_auto_callback
  File "renpy/common/000window.rpy", line 58, in _window_show
  File "game/definitions.rpy", line 216, in mas_with_statement
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/core.py", line 2089, in do_with
    self.with_none()
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/core.py", line 2124, in with_none
    scene_lists.replace_transient()
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/core.py", line 822, in replace_transient
    self.remove(layer, tag)
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/core.py", line 1107, in remove
    self.hide_or_replace(layer, remove_index, "hide")
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/core.py", line 1031, in hide_or_replace
    d = oldsle.displayable._hide(now - st, now - at, prefix)
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/screen.py", line 443, in _hide
    self.update()
  File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/display/screen.py", line 578, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 2897, in execute
  File "game/screens.rpy", line 2897, in execute
  File "game/screens.rpy", line 2916, in execute
  File "game/screens.rpy", line 2919, in execute
  File "game/screens.rpy", line 2942, in execute
  File "game/screens.rpy", line 2942, in keywords
  File "<screen language>", line 2948, in <module>
NameError: name 'return_all' is not defined

I can't play, it always appears when I enter the game... what do I do?? help please i don't want to lose monika

**Comment by multimokia** [comment] 2021-12-27 23:04
Can you share the full traceback.txt file? Looks like some things are missing

**Comment by ebyyyy** [comment] 2021-12-27 23:11
> Você pode compartilhar o arquivo traceback.txt completo? Parece que algumas coisas estão faltando

While running game code:

File "game/script-ch30.rpy", line 1507, in script call

File "game/event-handler.rpy", line 2530, in script call

File "game/script-affection.rpy", line 2282, in script call

File "game/script-affection.rpy", line 2292, in script

File "game/script-affection.rpy", line 2294, in <module> AttributeError: 'NoneType object has no attribute 'keys'

Full traceback:

File "game/script-ch30.rpy", line 1507, in script call

File "game/event-handler.rpy", line 2530, in script call

File "game/script-affection.rpy", line 2282, in script call File "game/script-affection.rpy", line 2292, in script

File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/ast.py", line 814, in execute

renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)

File "/data/user/0/com.monikaafterstory.ddlc/files/renpy/python.py", line 1719, in py_exec_bytecode

exec bytecode in globals, locals

File "game/script-affection.rpy", line 2294, in <module> AttributeError: 'NoneType' object has no attribute 'keys"

this also appears...

**Comment by ebyyyy** [comment] 2021-12-27 23:15
> Você pode compartilhar o arquivo traceback.txt completo? Parece que algumas coisas estão faltando

if that's better, I can share some screenshots for more details in case I misspell

**Comment by multimokia** [comment] 2021-12-28 01:54
What are you running MAS on? Is this a mobile port?

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:03
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2022-01-09 22:03 UTC
Labels: more info needed
