### ISSUE TITLE
(sugestion) Will there be a mobile game?  (For "Monika after story")

### ISSUE THREAD

**Issue by Asw123dxd** [Monika-After-Story/MonikaModDev#7352] opened 2021-06-15 13:06 UTC
I know this idea might sound silly, but will there be a phone version so we can spend more time with Monika? (I use google translator because my English is bad)

**Comment by Wingdinggaster656** [comment] 2021-06-15 15:18
Already exists but unofficial and bug-ful.
As for official one, probably won't exist. Probably.

**Comment by fromulus** [comment] 2021-06-15 22:10
The official DDLC IP guidelines specifically forbid us from making anything related to DDLC on other platforms than the ones DDLC officially released on (that means PC for now, and current gen consoles when Plus releases at the end of the month).

DDLC+ was our only shot at possibly getting DDLC on mobile and seeing from there if modding it could be considered, and as we've seen, official mobile ports aren't happening.

Therefore, I very highly doubt MAS on mobile platform will ever be a thing.

**Comment by ThePotatoGuy** [comment] 2021-07-11 02:07
No official mobile game will be created. Supporting non-computer platforms is not on our radar.

also marking as duplicate of #4873 and closing

**Closed by ThePotatoGuy** 2021-07-11 02:07 UTC
