### ISSUE TITLE
gifts

### ISSUE THREAD

**Issue by github1783** [Monika-After-Story/MonikaModDev#8466] opened 2021-12-22 00:34 UTC
so evrytime i wanna gift something to monika i do everything but when i launch the game it deletes the .gift files making me unable to give something to her, sad

**Comment by Cosmic-Incantations** [comment] 2021-12-22 07:40
maybe try backing up your persistent? this happened when I corrupted mine in attempt to time travel a bunch through the Christmas thing to see how gifts work, if it doesn't, idk.

**Comment by ShyCelestial** [comment] 2021-12-22 21:46
The gifts should appear underneath the Christmas tree I believe

**Comment by ThePotatoGuy** [comment] 2021-12-23 00:30
see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

**Comment by github1783** [comment] 2021-12-24 02:59
> see [this comment](https://github.com/Monika-After-Story/MonikaModDev/issues/8402#issuecomment-994296332)

so uhh, that didnt happen?

**Comment by Cosmic-Incantations** [comment] 2021-12-25 13:32
yeah, again, try backing up the persistent. You could have broken it somehow, this happened to me and I backed up Monika's memories, and now I can gift again

**Comment by Booplicate** [comment] 2021-12-25 16:21
Backing up doesn't fix anything... It just allows you to recover if something bad happens in future.

**Comment by ThePotatoGuy** [comment] 2021-12-31 05:24
if you continue to have gift giving problems, make a new issue.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-31 05:24 UTC
Labels: not a bug, tree gift
