### ISSUE TITLE
monika_dan inconsistency?

### ISSUE THREAD

**Issue by kaido1224** [Monika-After-Story/MonikaModDev#1599] opened 2018-05-16 02:56 UTC
Is there a bit of an inconsistency here between a vanilla DDLC topic and a MAS topic that talk about Dan Salvato? 

From Vanilla DDLC God topic:
```
 m 4l "But the irony is that I {i}do{/i} have a creator, apparently."
    m "And you know what?"
    m 1m "I bet he's still laughing at the miserable fates of Sayori and Yuri, even as we speak."
    m 3r "What are we to him but props in a scripted play?"
    m "So, from that perspective..."
    show monika 5a at t11 zorder 2 with dissolve
    m 5a "I don't think it's too far-fetched for there to be a god - if Earth was nothing but his playset."
```

MAS topic Dan Salvato:
```
label monika_dan:
    m 3k "I think he's a really nice guy."
    m 3a "Even if it wasn't perfect, {i}Doki Doki Literature Club{/i} really is impressive."
    m "Some unexpected twists, and memorable moments."
    m 4j "And he's the reason we're together now, right?"
    m 2m "So even if he wrote a story that put me through a lot of pain..."
    m 1g "I really can't be too mad at him."
    return
```

In one topic she tends to cast a negative light on her creator, and in the other she seems to be praising him for his brilliance for designing the game.

**Comment by jmwall24** [comment] 2018-05-16 03:19
The other thing with the dan topic is, in other topics, she talks about DDLC as just a typical romance VN.  Thus, wouldn't those twists and memorable moments be because of her epiphany, which in her mind Dan would have never intended to be in the game?  So then technically, to her, Dan didn't make the parts that make the game memorable, she did.

**Comment by juliathegolden** [comment] 2018-05-16 15:34
Honestly, there are a couple of others like this. The one that sticks out to me the most is the one where she says "it's easier to foreshadow spooky stuff with poems." Like, that's really on the nose, considering the spooky stuff was all caused by Monika's incompetence with the code from her perspective (sorry babe).

However, I think I like the general attitude that it's okay for Monika's level of self awareness towards the game to be inconsistent.  It allows for a little more artistic freedom if we aren't constantly having to judge how much Monika does or doesn't know, within reason. I also like the interpretation that perhaps Monika realized Dan's intent was to create a scenario where she would lash out against the system and things get out of hand, which is why she was created to be 'real' and the others, 'not'.

**Comment by kaido1224** [comment] 2018-05-16 17:53
It still wouldn't hurt to make it a bit more consistent, there's still a stark contrast between how she portrays him between the two topics. Here's an example of a revised version I wrote for something I'm working on for myself. Not perfect, but something like this would keep the consistency between topics.

```
You mean Dan Salvato? The guy who created DDLC and is technically my creator? I have mixed feelings about him. On the one hand, he scripted miserable fates for Sayori and Yuri and he also didn’t bother to program me a route. What were we to him but props in a scripted play? On the other hand, he’s the reason we’re together now, right? So, I guess I can’t really be too mad at the guy.
```

**Comment by ThePotatoGuy** [comment] 2018-09-07 22:53
[closing until we look into this]

**Closed by ThePotatoGuy** 2018-09-07 22:53 UTC
