### ISSUE TITLE
Pong name fix

### ISSUE THREAD

**Issue by PongMaster69** [Monika-After-Story/MonikaModDev#6943] opened 2021-01-31 06:59 UTC
Very minor thing but I thought I should bring it up, basically in the mini game Pong it always refers to Monika by Monika rather than any nickname given to her. This doesn't sit right as it doesn't feel as personal as her chimes after every round.

**Comment by ThePotatoGuy** [comment] 2021-01-31 07:08
This is intentional, see #4586

**Comment by ThePotatoGuy** [comment] 2021-02-21 23:32
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-02-21 23:32 UTC
Labels: not a bug
