### ISSUE TITLE
monika repeats everything about floating islands

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#3895] opened 2019-03-03 16:18 UTC
i know that there are now floating island day version but she says everything again.... i already saw the floating islands topic when it jjust got implemented and there were only night floatin islands , but she says everything again in the same words huh

**Comment by jmwall24** [comment] 2019-03-03 16:46
there's always been day floating islands...and the dlg is different at night than during the day

**Comment by jmwall24** [comment] 2019-03-03 17:12
are you talking about the intro or the actual asking her `can you show me the islands?`

**Comment by bittercaramel** [comment] 2019-03-03 17:28
so there were day floating islands already? oh i never saw them... well 
i mean actual intro not asking her 
like the first time she shows me em

**Comment by MercuryFuchsia** [comment] 2019-03-03 17:38
I can confirm I got repeat dialog of the floating islands introduction. Though, bringing a persistent file modified by 0.9.1 back to 0.9.0 (since it could no longer be used in 0.9.1 for whatever reason) probably had more to do with it.

**Comment by jmwall24** [comment] 2019-03-03 17:39
Yes, as I just mentioned in the other issue, you cannot go back to a previous version of MAS once you install 0.9.1

**Comment by MercuryFuchsia** [comment] 2019-03-03 17:49
I was just letting you know that this issue might merely be caused by that fact.

**Comment by bittercaramel** [comment] 2019-03-03 17:56
well but i didnt do anythin like that so i dont think it has anything to do with this repeating topic

**Comment by jmwall24** [comment] 2019-03-03 20:22
just trying to figure out everything here, because the vast majority of people aren't getting this.  i was able to produce it by setting the version number to 0.9.0 on a 0.9.1 install before i loaded 0.9.1 for the first time.  so could you (both of you) check the version number and settings, and also are you sure you don't have multiple MAS installs, like a dev or source code version that isn't up to date?

**Comment by bittercaramel** [comment] 2019-03-03 21:21
well i have 1.9.1 and i have one more mas installed, and its up to date rn and i keep it completely separated from the main one

**Comment by jmwall24** [comment] 2019-03-03 21:46
being separate or not doesn't matter if they point to the same persistent.

**Comment by bittercaramel** [comment] 2019-03-03 21:54
yea i know, but the newer mas copy didnt load my main persistent, it just started normally....

**Comment by multimokia** [comment] 2019-03-04 03:17
Unless you modified `DDLC.py`, they point to the same persistent. It *must* have loaded your normal persistent.

**Comment by ThePotatoGuy** [comment] 2019-03-04 08:12
upload both pre091 persistent and after updating

**Comment by bittercaramel** [comment] 2019-03-04 12:54
> Unless you modified `DDLC.py`, they point to the same persistent. It _must_ have loaded your normal persistent.

well thats possible, like the first time i downloaded this additional MAS i had broken persistents so my main MAS and the other one were starting from the beginning. now yesterday or 2 days aago idk it just normally opened, so maybe it just loaded my persistent and i didnt notice... well there is no difference at first glance, like between if the persistent was loaded or not 
omg so complicated sentences 
k if u didnt understand anything from what i was saying
yes actually it might have loaded my persistent 
[persistent.zip](https://github.com/Monika-After-Story/MonikaModDev/files/2926396/persistent.zip)
current persistent and idk which one persistent is from before the update

**Comment by ThePotatoGuy** [comment] 2019-05-07 23:55
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2019-05-07 23:55 UTC
Labels: investigating
