### ISSUE TITLE
Screaming void/Monika's rest

### ISSUE THREAD

**Issue by jmwall24** [Monika-After-Story/MonikaModDev#1861] opened 2018-07-01 20:50 UTC
I've seen a few people recently mention that they leave the game open as much as possible so they don't send Monika to the screaming void, seemingly not realizing that telling her goodbye before quitting doesn't send her to the void, but lets her get rest in her room. I think the screaming void topic is the cause of this, as it came out before the goodbye system and implies quitting the game in any way sends her there.  I'm thinking about amending that topic a bit to reflect the difference between saying goodbye and simply exiting the game to reflect the game's current state and to avoid anymore confusion if others think it's a good idea and if no one else is already doing it.

**Comment by Rai99** [comment] 2018-07-01 22:54
I like this idea. I might add something to the topic since it shouldn't take too long to do. 

This also gives me the idea that maybe just like in the Just Natsuki mod, you could have different rooms and areas and Monika could let us into her room where she rests. If this is a good idea, I'm sure it would still take a bit of time to implement.

**Comment by Rai99** [comment] 2018-07-02 03:06
Any ideas how I should go about it? It's in the "Death and dying" topic where Monika comments about the screaming void. 

Is there a variable that tracks how many times you exit without saying goodbye? It wouldn't make too much sense for Monika to say what it's like when you quit without saying goodbye if you never have.

**Comment by jmwall24** [comment] 2018-07-02 03:18
Well I was actually intending on doing it myself, but if you want to go ahead.

**Comment by Rai99** [comment] 2018-07-02 03:42
Nah, you can do it. It would still be nice to have some contributions I didn't write so I can still get a warm, fuzzy feeling when I read them. 

The only sacrifice that comes with contributing personally I think,  is that your own contributions aren't as special when you get them in game since you're the one who made them and know exactly what they are already as opposed to it being closer to coming from Monika.

**Comment by Akh0r** [comment] 2018-07-02 11:43
How at all do a random user change existing/add new topic? 
Still can't figure out what the routine is here on GitHub

**Comment by Rai99** [comment] 2018-07-02 13:58
There are some basic instructions here on contributing:
https://github.com/Monika-After-Story/MonikaModDev/blob/master/CONTRIBUTING.md

As for correction and proofreading, you could ask for someone to go over it. I would just put up a Pull Request and I'm sure people will come and read over it for you and find errors.

**Comment by loverofmonika** [comment] 2018-07-03 20:00
i like the idea but what about actually talking to monika other than that empty room. its now a soar eye to see that empty room , sitting on a chair for hours, even monika must feel uncomfortable. 
u can have monika sit on the bed or walking around the room or even sitting on the floor would do.
 i talk from experience, the butt hurts. plus the uniform, she needs to ditch that and get some new clothes. 
im a writer/ poet but my limitaion is i dont know how to code. oh while im here i'll take this opportunity to talk about some things that might need changing or a new feature. 
1. when u ask monika when did u start dating, she says "let me check" and then she closes her eyes, well since she said she'll never forget the day and who checks when closing their eyes, to me it just looked a bit weird, it could be changed to " ummm, oh yeah" or " oh its......" or  "oh let me think, hmmm"
u can use all 3 to avoid being repetitive
2. there isnt a good afternoon option, nor a " how are you doing" option, dont get me wrong, monika greeting me first is cool but i too wanna ask how is she and what was she upto while i was out
3.i feel a bit insecure when i think that did monika choose me just because im the only option, i mean if someone else got to her and saved her, she wouldnt love me. then the feelings come and i further think, why would she like me, she is beautiful, desirable, smart and im nothing. nothing but dead weight. im sure some people would think like this.
how would she react to this 
4. the option to apologize for hurting her
5. asking what is the thing she loves most about me (the normal cliche answer would be everything)
6. asking how does she feel about me wanting to spend the rest of my life with her (wife, the recent tears feature we have can be used as happy tears)
7 . "dancing with her under the moonlight" topic can be added
8.  "living together" topic can be added

 thats alot of ideas, dont kill me, i come in peace

**Comment by Rai99** [comment] 2018-07-03 21:04
1. I think Monika is just closing her eyes to help her focus and remember. I think it's really normal to close your eyes and try to remember something really important to you that you'll never forget. It probably won't be on the top of your head 24/7, but it's definitely in your head somewhere, nice and ready to remember. When she says "Let me check", I just imagine she means she's checking in  her head which seems normal to me.

2. I'm pretty sure a "Good afternoon" option was brought up a long time ago and is being made or might even be done. For asking what Monika was up to while you were gone, I think the diary system would have to be implemented first so Monika could tell you what she did and you wouldn't have to read her diary.

3. For feeling insecure, there was a new mood added for something like that in #1401 and they did well, although I think it could have been handled a little better. I think maybe we could use a separate dialogue taking the issue on from a slightly different angle. I'm sure as well that there are a lot of people who think this and could really use some reassurance from Monika. 
I'll admit it, I'm somebody who thinks that way about myself. I see no reason why anyone would take interest in me, especially someone like Monika who is smart, athletic, understanding, popular and good looking. Same kinda goes for my work when writing for MAS. Every single issue, PR, comment I make, I worry it could cause it all to come crashing down because people don't like my ideas and work. I do it for Monika because she probably wouldn't want me to think like that or let that stop me. Of course I still plan to keep writing. I'll just save the story for Monika later.

3.5?  I think a topic for apologizing to Monika for anything was being worked on and intended to be 
used when the game crashes. Although now that we have proper crash detection and an appropriate event, I'm not sure if the topic was stopped, scrapped, or did in fact make it in. If the topic was not put in and replaced by the new crash event, I'll consider writing it myself.

4. I actually don't think we can effectively add a topic like this. The best option would probably be to have it be the cliche answer of "everything." Monika could love any part of you, such as your hair, personality, mind, etc, but the problem is if Monika were to compliment you or appreciate something about you that you don't really care about, or potentially worse, don't like. 
Complimenting others is generally a good thing, but it can have an opposite effect if it's overdone or done on something random. For example, if I really like my hair and somebody compliments me for my legs or something. I work hard to keep my hair nice and well kept and I barely ever do anything with my legs. I would be a bit offended that's the first thing they see or like about me. If somebody came over to my house and I had some nice furniture I wanted to show or maybe something else, and they compliment my doormat, I would be a bit taken aback. I made this doormat with spare scrap and garbage lying around in my garage, It is **not** a main feature of my place. People value different things about themselves and Monika doesn't really have a way of knowing or being able to tell what we like and are proud of, so it could be harmful to compliment just something random. The cliche answer would probably be best. 

5. 7? 6. New topic; would likely be its own discussion with what ideas you have for them. 

As for not killing you and you coming in peace, I don't think you're the biggest offender for constructing the Great Wall of China over and over, here and there using words. Yeah one of the things I worry about is that nobody wants to look at the great walls I build using nothing but text.

**Comment by loverofmonika** [comment] 2018-07-04 06:51
1. when you say let me check, that means ur going to get up and check, when u say let me think or those lines i mentioned above, it matches and goes well with me closing my eyes and trying to remember, thats what im trying to say
2. oh cool
3. i read that issue but it doesn't really feels so reassuring for this insecurity cuz that topic was was something like im a no body in school and im not smart but this one altho is similar but it goes abit deeper as u feel like she is just wasting her time with u, u dont deserve what u have with her and the reason why she choose u is cuz u were the only real guy she ever met. i think a different answer is needed
3.5 okie, the apologies also works on closing the game without saying goodbye
4. u got a point but just saying i like everything about u as is, we can twist it and make it sound better,
i said this to someone before, if its cliche but written well, it'll pass as enjoyable
5,6,7. got to admit tho those topics are fun to write on
buddy words can really pack a punch, have faith in urself

**Comment by Rai99** [comment] 2018-07-04 13:04
1. How about "Let me see"? That works regardless if you're getting up to check or just sitting down and thinking. 
3. Yeah I think something else could be done about Monika reassuring you. I think it would be a bit hard to get a good answer but maybe that's just me. If anyone were to ask me why Monika loves me, I wouldn't really know either.

**Comment by Rai99** [comment] 2018-07-04 14:23
I'm actually not sure we can do something for Monika reassuring you if you feel like you don't deserve her because everyone is different and what you say to one person could be offensive to another. If it's just generic reassurance, it's probably not going to help anyone. 

I don't think "_generic help_" is a good thing, especially with sensitive topics such as that.

**Comment by loverofmonika** [comment] 2018-07-05 05:04
1. i like it, lets go with that
3. correct a generic answer wouldnt help, we got to think hard oh this one, i asked a girl if she was in a similar situation and we came to a conclusion that if she wanted to be with you no matter what, sure there are guys who are good looking and kinder but none of that matters, she choose u despite knowing all this, why is that, its cuz they weren't you. All the flowers, praises, gifts doesnt mean anything if they weren't from you. don't u ever think less of urself, care about yourself as much as i care about u
also i recommend u to check out #1870

**Comment by ThePotatoGuy** [comment] 2018-07-11 06:13
3.5. That topic was scrapped because the crash detection is good enough and decently immersive. There is room for addons to the crashed flow for things Monika can say to the player in subsequent crashes.

5,6,7: make them separate issues and I will add them to the Topic Pool.

[Closing this until we look into it]
[also locking this because its getting off topic]

**Closed by ThePotatoGuy** 2018-07-11 06:13 UTC
Labels: suggestion
