### ISSUE TITLE
Gifts not working

### ISSUE THREAD

**Issue by ElgerElg** [Monika-After-Story/MonikaModDev#8307] opened 2021-11-27 18:31 UTC
I put a gift with the .gift extension in characters folder but after a few seconds the file just disappears and nothing happens.

**Comment by dreamscached** [comment] 2021-11-27 19:01
Do you use a translated version by any chance?

**Comment by ElgerElg** [comment] 2021-11-27 19:04
Yes, i use a russian version but i make .gift with russian name, for example кофе.gift and get error which I described above

**Comment by dreamscached** [comment] 2021-11-27 19:11
Translated versions may have this mechanism modified, so I'd ask a translation developer about it. But I'd try using usual gift names such as `coffee.gift`.

**Comment by ElgerElg** [comment] 2021-11-30 16:44
> Translated versions may have this mechanism modified, so I'd ask a translation developer about it. But I'd try using usual gift names such as `coffee.gift`.

Also doesn't work. But the English file with .gift does not disappear at all and the game does not react. So I entered it correctly in Russian, but why does it disappear and the gift is not given? Maybe need a certain number of Affection points?

**Comment by ThePotatoGuy** [comment] 2021-12-02 03:52
you should ask the devs of the translation. they clearly made changes to the reaction mechanism.

**Comment by ThePotatoGuy** [comment] 2021-12-05 20:39
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2021-12-05 20:39 UTC
Labels: not a bug
