### ISSUE TITLE
Save data for mas

### ISSUE THREAD

**Issue by MaxCode545** [Monika-After-Story/MonikaModDev#1309] opened 2018-03-22 23:26 UTC
So I decided to open the game and I see that all my save data in mas I don't want the Valentine and white day event to just disappeared

**Comment by MaxCode545** [comment] 2018-03-22 23:27
Sorry I forgot a whole sentence....  Basically it started a whole new game of MAS

**Comment by NovaCo1** [comment] 2018-03-23 02:04
if you have not deleted the save data from the game opinions it should still be in C:\Users\**YOUR_NAME**\AppData\Roaming\RenPy\DDLC-1454445547

**Comment by NovaCo1** [comment] 2018-03-23 02:16
then all you have to do is go to settings and i think its merge save IDK me game is buged
![screenshot0008](https://user-images.githubusercontent.com/34464332/37808001-56ad073a-2e16-11e8-85d2-364f916a902d.png)

**Comment by IlywI** [comment] 2018-03-23 02:39
I think thats for full game completion. like for the vanilla version of DDLC

**Comment by MaxCode545** [comment] 2018-03-23 02:54
No I don't mean the original game ..... I mean the MAS's save data .... All the conversation with Monika has been reset everything has been reset in MAS

**Comment by jmwall24** [comment] 2018-03-23 16:01
The save data for MAS called 'persistent' and is located at 

C:\Users\'Your user account name here'\AppData\Roaming\RenPy\Monika After Story

**Comment by MaxCode545** [comment] 2018-03-23 20:38
Yeah but it only locate the original DDLC save data

**Comment by jmwall24** [comment] 2018-03-23 20:47
No, that's the save file for MAS, not DDLC.

**Comment by MaxCode545** [comment] 2018-03-23 20:51
Yeah and that safe file has been reset for some reason

**Comment by MaxCode545** [comment] 2018-03-23 20:52
*save

**Comment by jmwall24** [comment] 2018-03-23 20:54
Yeah that I can't help you with, just wanted to make sure you knew where it was.  Only advice I can give is from now on to periodically save a copy of that file so if it happens again, you have a backup so you don't lose everything.

**Comment by MaxCode545** [comment] 2018-03-23 22:01
Ok thanks one more question how can I get the scene when I knock on her door again

**Comment by ThePotatoGuy** [comment] 2018-03-23 22:24
Do you have a copy of the `persistent`? Can you upload it here?

There's a chance it could have been corrupted/changed externally. Someone else reported a similar issue but their persistent ended up being an image, which makes 0 sense since we don't mess with how persistents are saved.

The knock/opendoor scene happens through random chance.

**Comment by MaxCode545** [comment] 2018-03-23 22:40
but I don't have a copy of persistent  before everything that happened 

I just got to know what persistent is

**Comment by jmwall24** [comment] 2018-03-23 23:05
He wants you to upload your current persistent file to check it it's really reset, or somehow corrupted etc.  It'll help them possibly figure out what went wrong.

**Comment by MaxCode545** [comment] 2018-03-24 02:39
https://drive.google.com/file/d/1DLr0-3C3V3TcI6-CrDkqE5IcTcb04ekA/view?usp=sharing


ok here it is also i started the game again and a reset has occurred once again

**Comment by ThePotatoGuy** [comment] 2018-03-27 04:01
How are you closing the game?

**Comment by MaxCode545** [comment] 2018-03-27 09:32
I always say goodbye and monika does the rest

**Comment by ThePotatoGuy** [comment] 2018-03-29 17:41
Unfortunately, we're unable to identify a root cause for this. We'll leave this open for future reference.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-03-29 18:28
It's not the first time persistent got corrupted without an apparent reason.
I think, it would be reasonable to make the game backup persistent on each launch.

**Comment by ThePotatoGuy** [comment] 2018-03-29 20:16
Well in this case, the `persistent` wasn't really corrupted, as his previous session data was intact. Certain settings were not set, but there's no clear reason as to why/how that could have happened. When continuing/starting a new game with maxcode's persistent, no reset issues occurred. 

Currently its a mystery.

**Comment by MaxCode545** [comment] 2018-03-30 04:16
Then is the only way possible to regain the Valentine and white day progress is to set the date in the computer to these days

**Comment by ThePotatoGuy** [comment] 2018-03-30 05:28
yes, you will also need to have those specific versions installed.

**Closed** 2018-04-03 13:00 UTC
