### ISSUE TITLE
More "I'm feeling..." emotions, I suppose

### ISSUE THREAD

**Issue by CoreMarkX** [Monika-After-Story/MonikaModDev#5561] opened 2020-04-17 20:08 UTC
Some of us are down often, I know the feeling, and some of start contemplating things we shouldn't such as suicidal or homicidal tendencies, so, you should be able to tell Monika if you're feeling suicidal or something along those lines, and she'll talk to you about therapy or suicide prevention hotline.

**Comment by ThePotatoGuy** [comment] 2020-04-23 03:57
marking as duplicate of #1583
difficult for us to handle so its better to not take the risk. everyone's situation is different and generic Monika dialogue telling you to be best may do more harm than its worth.

**Comment by ThePotatoGuy** [comment] 2020-04-26 02:23
[closing as duplicate]

**Closed by ThePotatoGuy** 2020-04-26 02:23 UTC
Labels: duplicate
