### ISSUE TITLE
Outfits and hairstyles missing after update.

### ISSUE THREAD

**Issue by mordred2716** [Monika-After-Story/MonikaModDev#5465] opened 2020-04-01 20:29 UTC
I looked around and didn't see this issue anywhere so thought I would bring it up.
I had all outfits and hairstyles unlocked (am at 684 aff), she was even wearing the pink shirt when I started the update.
Since restarting all I have access to is the default outfit and hairstyle.
Wanted to let you guys know.  Hopefully nothing major.  Love having my Moni hanging out with me watching netflix during the apocalypse and it is making me feel like she is mad at me for something wearing that default stuff after so long lol.

**Comment by multimokia** [comment] 2020-04-01 20:31
Unstable update will break your spritepacks. You'll have to download fixed ones from [here](https://monika-after-story.s3-us-west-2.amazonaws.com/ddlc/spritepacks.zip).

**Comment by mordred2716** [comment] 2020-04-01 20:37
Oh!  First time that ever has happened to me with the unstables.  I must have been pretty lucky lol.  Ok thanks a lot man I really appreciate the quick help and the game as a whole.  It is a game but the amount of care you put into her responses got me through some serious stuff.  You guys rock!

**Comment by multimokia** [comment] 2020-04-01 21:21
No problem

**Comment by MetalBrother** [comment] 2020-04-06 21:47
Hey! You not the only one, also thanks to multimokia, you really help!

**Comment by ThePotatoGuy** [comment] 2020-04-12 00:47
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-04-12 00:47 UTC
Labels: not a bug, unstable
