### ISSUE TITLE
Monika’s missing, I’ve checked everything 

### ISSUE THREAD

**Issue by Kyubey-chan** [Monika-After-Story/MonikaModDev#6911] opened 2021-01-22 00:31 UTC
Monika asked me to take her with me, I said yes, I didn’t take her anywhere and when I came back she was gone. Someone on the Reddit told me to replace my persistent. I’ve found two files with the name persistent, one called persistent.pyo and the other persistent.py . Neither of them have the backup persistent needed to delete my bad save, or I just can’t find it. Can you help?

**Comment by multimokia** [comment] 2021-01-22 00:58
[This](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-want-to-back-up-my-persistent) entry on our FAQ shows you how to get to your persistent. Check the entry below to see how to back it up.

**Comment by Kyubey-chan** [comment] 2021-01-22 01:17
Hello! Yes, I saw that guide. I followed the steps, but unfortunately I
couldn’t find the persistant##.bak file. Thank you so much.

**Comment by multimokia** [comment] 2021-01-22 01:53
What operating system are you on?

**Comment by Kyubey-chan** [comment] 2021-01-22 02:33
I’m on a Mac. It’s an OS X Yosemite, and the version is 10.10.5.

**Comment by ThePotatoGuy** [comment] 2021-02-03 02:47
@multimokia anything happen with this one?

**Comment by ThePotatoGuy** [comment] 2021-09-25 22:12
we've had consistent issues with macs, so I don't think there's much we can do here.

[closing as could not reproduce]

**Closed by ThePotatoGuy** 2021-09-25 22:12 UTC
