### ISSUE TITLE
Visuable bug after playing pong

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#4983] opened 2019-11-06 23:35 UTC
When a game of pong end, a small glitch in the middle of the screen appear and disappear really quickly.

I don't have screenshots because it's way to fast to take a screenshot, but the glitch looks like a small line made of colored squares. 

I sadly can't describe better, but still report it and maybe it can be found and be fixed in the future.

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:14
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2019-12-15 00:14 UTC
