### ISSUE TITLE
Winking Facial Expressions

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#1063] opened 2018-02-16 03:36 UTC
@ThePotatoGuy posted this: https://github.com/Backdash/MonikaModDev/commit/c069014aff71de4a5d8e48a5928c71eb8dae0a3c and I noticed that there was mention of a "wink" or "smug" facial expression when the line is being said. So I'm here to submit some edits I made for just that. I included the images for the eyebrows and nose, for the sake of knowing which ones were used. 

[Expression Images.zip](https://github.com/Backdash/MonikaModDev/files/1730130/Expression.Images.zip)
![moni-wink](https://user-images.githubusercontent.com/36512990/36292555-233cc06e-1298-11e8-8cdf-f3cedf8f959f.jpg)
![moni-wink-n](https://user-images.githubusercontent.com/36512990/36292558-2804ef18-1298-11e8-8868-dfffe6d7c9bf.jpg)

**Comment by ThePotatoGuy** [comment] 2018-02-16 04:12
oh my god. ❤️ 

Alright, this is going in almost instantly.

**Comment by Trilasent** [comment] 2018-02-16 04:28
@ThePotatoGuy I thought about having her right eye closed, but I feel like it looks more natural to have her left eye shut while she's leaning.

**Comment by antimockingjay** [comment] 2018-02-16 07:27
I really love this. Though it seems like less of a wink and more like she's just really happy and her eye ended up closing. But that's not a bad thing! I really like what it looks like! She looks really really cute like this!

**Comment by Trilasent** [comment] 2018-02-16 07:52
I can easily tweak it so that it looks like more of a wink if need be. Just let me know if there are plans to use it in the mod so I know about how much time I’ll have.

**Comment by Ulvsblakk** [comment] 2018-02-16 09:12
You sir are a genius.

**Comment by Trilasent** [comment] 2018-02-16 09:26
I tilted her head just a tiny bit, and redid the positioning of the left bow string. I also decided to spitball with some blushing just because I figured it could possibly be a little cuter with her letting a little bit of that affection out. ;)

What do you think? I'll keep a copy of this in case it's good now, but I'll continue to tweak as well.

https://gyazo.com/c4eddbb8c8e935c8d632c740723935bf

**Comment by Ulvsblakk** [comment] 2018-02-16 09:59
I'm personally a fan of less blush. 
She looks so freaking adorable.

**Comment by Trilasent** [comment] 2018-02-16 10:02
Atm I'm experimenting to see what it would be like if she was resting her cheeks on both of her hands

**Comment by Trilasent** [comment] 2018-02-16 10:57
Here's a VERY early rough draft of what it could possibly be like for her to have both of her hands on her cheeks simultaneously:
![roughdraft1](https://user-images.githubusercontent.com/36512990/36304572-bb1679e2-12d5-11e8-82f1-a30b5f520251.png)

Still quite a bit of fixing and polishing to do though.

**Comment by IlywI** [comment] 2018-02-16 15:27
Maybe make her do the palm on cheek pose? Cos that posture looks kinda unnatural to me.
An example of this:(i just ripped it of google images)
![image](https://user-images.githubusercontent.com/23725018/36314808-e62c9ff8-1370-11e8-9b9f-bc35afafb746.png)

**Comment by IlywI** [comment] 2018-02-16 15:28
Maybe keep the blushing for for *ahem* 'intimate' conversations.

**Comment by Trilasent** [comment] 2018-02-16 18:12
Alrighty. I'll see what I can do with that. I'm having a lot of fun with this so I don't mind tweaking it as you folks see fit. C:

**Comment by Trilasent** [comment] 2018-02-16 21:20
Okay, here's another update: 
![palms on cheek 1](https://user-images.githubusercontent.com/36512990/36329803-e483e4d4-132c-11e8-8502-d210c3ae532c.png)

How's it looking so far?

**Comment by Valllaion** [comment] 2018-02-17 02:53
Amazing! But I have a suggestion if it's not too much, what if rarely she had her hands in the yuno yandere position and the music changed to just Monika as a little Easter egg

**Comment by Trilasent** [comment] 2018-02-17 02:56
@Valllaion That'll have to come down to whether or not the devs want to use the  pose in the mod or not. Also I'm honestly not sure what that position is, so I can't say much on my end, haha.

**Comment by Bam8647** [comment] 2018-02-17 04:33
Very well done! Can't wait to see them implement this! So freaking adorable btw x3

**Comment by Trilasent** [comment] 2018-02-17 04:35
If there's one thing that I hold above anything else, it's making Monipop as adorable as I can, because I quite honestly can't get enough of her, heh.

**Comment by Bam8647** [comment] 2018-02-17 04:41
As can I. We have great taste, my good friend. #MonikaBestGirl

**Comment by Trilasent** [comment] 2018-02-17 04:42
That reminds me, I need to make another submission on a custom outfit I'm working on redrawing to work with her sitting pose.

**Comment by IlywI** [comment] 2018-02-17 05:59
Pretty cute imo. Maybe ask for other's opinions?

**Comment by Trilasent** [comment] 2018-02-17 06:07
@IlywI Definitely :).

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-17 07:38
The mouth looks somewhat strange to me.
Am I the only one?

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-17 14:55
I dunno.
My only complaint with most of the sprites is that they never look quite "Satchely" enough and mouths and hands seem to suffer the most.
I am probably just too picky is all.

**Comment by Trilasent** [comment] 2018-02-17 17:44
Well I'm not completely finished just yet, hehe.

**Comment by Valllaion** [comment] 2018-02-17 22:22
I can't wait to see this make it into the game... bec honestly if it doesn't make it in there's gonna be problems lol  #MonikaBestGirl

**Comment by Trilasent** [comment] 2018-02-17 22:30
@Valllaion Damn straight on that #!

**Comment by PopeAesthetics** [comment] 2018-02-18 13:10
Trilasent, your contributions to the Monika Empire shall be rewarded one day.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-18 16:46
![#](https://user-images.githubusercontent.com/34412685/36354347-02a0b808-14e4-11e8-990b-27b23eb85d6b.jpg)
I feel like we are getting a bit off topic here tho.

**Comment by Trilasent** [comment] 2018-02-18 19:45
@PopeAesthetics I've already gotten my reward. I get to spend time with Moni every day. ;)

**Comment by TDCPKaout** [comment] 2018-02-18 20:30
As an idea on top of this, how about a surprised eye art. I noticed how in this most recent edition of Valentines Day, that when you give her the gift her eyes are the same as normal. Almost like she wasn't as surprised as was intended to be portrayed. So perhaps a surprised expression is in order? Like her eyes are more open, and eyebrows raised.
Or perhaps I'm just being stupid. But I think this as a new edition would be helpful for future plans. Such as gifts, and branching dialogue. It just seems appropriate to add since we've got a winking face. 
(I tried a sample art, but I'm not cut out for digital stuff.)

**Comment by Trilasent** [comment] 2018-02-18 20:32
I can experiment with something like that for sure. I'll save your comment on a Notepad so I'll be able to remember if I happen to forget about it during the day.

**Comment by ThePotatoGuy** [comment] 2018-02-18 23:10
Alright so, expressions are getting reworked for 0.8.0. If this does get in, it will be quite a while.

**Comment by Trilasent** [comment] 2018-02-19 05:43
@ThePotatoGuy Alrighty. I'll get to work on refining what I've got tomorrow, and go from there. Is there any way I can show them to you without unnecessary posting on this thread/making new threads?

**Comment by ThePotatoGuy** [comment] 2018-02-19 07:32
Keep it on this thread. It helps us keep track of related things.

**Comment by Trilasent** [comment] 2018-02-19 07:47
@ThePotatoGuy Okidokie, I'll update this comment whenever I feel like I've made considerable progress.

**Comment by IlywI** [comment] 2018-02-19 13:42
All the best!

**Comment by Valllaion** [comment] 2018-02-19 15:40
so I'm still kinda new here... may I ask how long it usually takes to put out an update? sorry for asking a stupid question

**Comment by PopeAesthetics** [comment] 2018-02-20 12:07
@Valllaion don't be sorry! We are a community of Doki Doki fans (and Monika fans) just like you! So don't be nervous to ask questions, we aren't gonna bite your head off. 

Updates vary in release dates. Sometimes it's months in between each release. sometimes a couple weeks, and usually something gets added for each holiday that comes up. It's best not to worry too much about the next release. The admins and community are very passionate and dedicated to making MAS as best as we can, and to get Monika as close to reality as possible.

**Closed** 2018-05-09 21:35 UTC
Labels: art
