### ISSUE TITLE
[Bug] A very confusing phenomenon about greetings

### ISSUE THREAD

**Issue by Wingdinggaster656** [Monika-After-Story/MonikaModDev#9961] opened 2023-04-15 02:00 UTC
After the player has chosen to go to work or to class and returned to MAS, Monika will ask the player how the day was. If the player chooses a negative option, Monika will ask the player why.

And now, a confusing bug appears:
<img width="1002" alt="image1" src="https://user-images.githubusercontent.com/84446131/232177654-f4b27697-05fb-44b9-b769-25a51daa4a5e.png">
Although in the source code, MAS intends for the text spoken by Monika and the options offered to the player to appear simultaneously, in fact, only the options will appear.

The strange thing is - this bug only appears when the player triggers this event normally. If the tester calls these greetings via a function like `renpy.call()`, then:
<img width="1031" alt="image2" src="https://user-images.githubusercontent.com/84446131/232177759-845f143c-eac4-4c85-97b9-8a58fcd793c6.png">
Conversations get displayed properly.

This would probably be considered a low priority thing to do, but it should be done anyway.

**Comment by Booplicate** [comment] 2023-04-15 08:15
Try w/o the submods.

**Comment by Wingdinggaster656** [comment] 2023-04-15 08:57
> Try w/o the submods.

I have never installed any Submod. I even reinstalled MAS once just to test the bug.

**Comment by dreamscached** [comment] 2023-04-15 10:46
Might probably have something to do with the way Ren'Py handles interaction (since this is used with `nointeract`.)

**Comment by Wingdinggaster656** [comment] 2023-04-15 11:04
> Might probably have something to do with the way Ren'Py handles interaction (since this wasn't used with `nointeract`.)

I think I didn't make this clear enough: `greeting_back_from_school` also has the same bug, and that event uses `nointeract`.

**Comment by Wingdinggaster656** [comment] 2023-04-15 11:12
> Might probably have something to do with the way Ren'Py handles interaction (since this wasn't used with `nointeract`.)

Probably not - this bug exists in `greeting_back_from_school`, which uses `nointeract`.

**Comment by Booplicate** [comment] 2023-04-15 12:02
Both have `nointeract`. Also I can't reproduce the issue on my end.

**Comment by Wingdinggaster656** [comment] 2023-04-15 14:34
I've had a few other people I know run tests on it, and they report that they can reproduce it.

Did you trigger this event normally? I mean, normally select `I'm going to work` from the Goodbye menu, then normally launch the game and normally select a negative option? All other approaches seem to cause the bug not to appear. Note that I said:

> The strange thing is - this bug only appears when the player triggers this event normally.

**Comment by Booplicate** [comment] 2023-04-18 17:29
Yes. Also FYI it's going through `renpy.call` call anyway.

**Comment by Booplicate** [comment] 2023-04-18 17:42
Our code there is weird, not sure what was the logic, so I will just clean it up and maybe it fixes the bug.

**Comment by Booplicate** [comment] 2023-04-18 18:12
Found it, thanks for the report.

**Comment by Booplicate** [comment] 2023-09-17 21:41
This will be fixed in next upd.

**Closed by Booplicate** 2023-09-17 21:41 UTC
Labels: bug
