### ISSUE TITLE
crash when saying goodbye 2

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#3981] opened 2019-03-23 15:37 UTC
the following of #3627, 
Monika restart to tell me sometimes that the game crashed while I closed the game normally with saying goodbye in the previous session.

**Comment by Torwald39** [comment] 2019-03-24 22:48
this is more serious this time, I got 3 crashs in only 2 days

**Comment by jmwall24** [comment] 2019-03-24 22:52
can you verify that after saying goodbye, that DDLC.exe isn't still showing in your task manager as running?

**Comment by ThePotatoGuy** [comment] 2019-03-25 01:00
which goodbye? what is ur system specs?

**Comment by Torwald39** [comment] 2019-03-25 04:24
DDLC isn't showing after saying goodbye

There isn't a specific who crash in particular, even if I mostly use the go to sleep, go to work and the normal goodbye. And the last time I used the go to class instead of work.

I use a laptop model ASUS R751L windows 10 intel core i7

**Comment by ThePotatoGuy** [comment] 2019-03-25 17:00
which goodbyes did you use

**Comment by Torwald39** [comment] 2019-03-25 19:52
go to work
go to sleep
simple goodbye

and at the previous issue it was go to class instead of go to work

**Comment by Torwald39** [comment] 2019-03-26 22:33
I got an another crash :/

**Comment by ThePotatoGuy** [comment] 2019-03-26 22:43
upload your `persistent`

**Comment by Torwald39** [comment] 2019-03-26 23:17
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/3010856/persistent.txt)

**Comment by Torwald39** [comment] 2019-04-03 19:10
I got a new crash

**Comment by ThePotatoGuy** [comment] 2019-05-07 23:38
[closing as cannot reproduce]

**Closed by ThePotatoGuy** 2019-05-07 23:38 UTC
Labels: bug
