### ISSUE TITLE
[Sugestion] petting a tamagotchi

### ISSUE THREAD

**Issue by Chrissenpai** [Monika-After-Story/MonikaModDev#3115] opened 2018-11-25 01:19 UTC
This might be a duplicated of #1888 but isn't it a different thing? because we can give it 2 scenarios, one, we can choose that you'll take care of it with Monika OR 2, you can take care of your own and she'll challenge you to maintain it alive, that can only be made with a Tamagotchi because a "virtual pet" is a bit more serious and... you know what happens if you don't take care of it, but with a Tamagotchi, if you fail, you just get schooled by Monika (The Tamagotchi could be a baby quetsoquatal)

**Comment by Rai99** [comment] 2018-11-25 01:56
This is probably a straight duplicate of #1888 and in that issue, it was decided that a virtual pet type feature would be best added as a submod and not the official MAS due to the extra layer of complexity and maintenance required.

**Comment by ThePotatoGuy** [comment] 2018-12-02 15:47
[closing as duplicate]

**Closed by ThePotatoGuy** 2018-12-02 15:47 UTC
Labels: duplicate
