### ISSUE TITLE
[Suggestion] Telling Monika you're taking a screenshot/picture of her or selfie with her

### ISSUE THREAD

**Issue by Abc2557** [Monika-After-Story/MonikaModDev#5790] opened 2020-05-16 17:34 UTC
(You could use https://github.com/Monika-After-Story/MonikaModDev/issues/5768 for this)
I mean, it seems kinda weird for the player to just randomly take a picture of Moni without her knowing, right?

**Comment by Rai99** [comment] 2020-05-19 03:10
What are you imagining would happen when you tell her? Do you think she would strike a pose for the screenshot?

**Comment by lunulae** [comment] 2020-05-21 22:24
I'm imagining it'd prompt something similar to the "I love you too" button, there could be a few expressions she might want to hold for a few seconds. Afterward she might have a small quip like "Did it come out alright?" or "How do I look?"
The first time it's prompted, maybe she could have some extra dialogue about how she feels about having her picture taken.

I'm not sure if it would be Monika's sort of humor, but perhaps there could be a rare chance for her to do a somewhat silly-looking expression for fun.

**Comment by ThePotatoGuy** [comment] 2020-05-25 19:13
marking as duplicate of the #2056 and related

**Closed by ThePotatoGuy** 2020-05-25 19:13 UTC
Labels: duplicate
