### ISSUE TITLE
Just a typo issue

### ISSUE THREAD

**Issue by Tychoke** [Monika-After-Story/MonikaModDev#7633] opened 2021-08-15 23:40 UTC
Well, some days ago I entered in the game and Monika said a dialog that I don't remember (she was surprised), and suddenly she said this;

![E-Wha](https://user-images.githubusercontent.com/88991144/129495931-0d40c9b1-e544-4aa8-b9be-9b244bbb541b.png)

Just a little mistake but I thought that report this was for the best.

**Comment by ashyashton** [comment] 2021-08-16 19:56
I think that's probably intentional. Sometimes, in actual verbal conversations, people will say "wha" instead of "what" because they cut themselves off out of surprise, or they trail off, or that's just what naturally comes out of their mouth. So if I had to guess, this was intentional.

Also, there's a pinned threat specifically for typos. #7271 is the one for the current version I believe.

**Comment by Tychoke** [comment] 2021-08-16 22:26
Oh, I didn't know that, maybe that's the reason, huh? 

and thanks for letting me know about this #7271 (also for you publicating it there).

**Comment by ThePotatoGuy** [comment] 2021-08-28 19:54
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-08-28 19:54 UTC
Labels: not a bug
