### ISSUE TITLE
[Suggestion] - Setting times for when awake;

### ISSUE THREAD

**Issue by Storylover-Vodhr** [Monika-After-Story/MonikaModDev#2804] opened 2018-10-21 11:23 UTC
It's awesome that Monika cares for us and our sleep schedules and all, but it's rather difficult to please her when you work a night shift, and literally go to bed at noon. 

It'd be cool if we could get an option to set when we're typically awake, to avoid comments on us taking a nap, or condemnations of being up so late when we don't really have the option to sleep as she'd prefer. Maybe even an option to tell her why, such as work, or even simply being a night owl. 

(Still trying to figure the rules of this forum and this whole GitHub system out, so I apologize for any mistakes I have made in the process.)

**Comment by Storylover** [comment] 2018-10-21 11:31
> it's not a good one,because a lot of people wake up at random times

I'm sorry, I don't follow.

**Comment by SaiPrithvi123** [comment] 2018-10-21 11:35
I think there already is such a topic in the game, but this too, like some other important topics, is random for some reason I don't know of.

**Comment by Storylover-Vodhr** [comment] 2018-10-21 11:40
> I think there already is such a topic in the game, but this too, like some other important topics, is random for some reason I don't know of.

So I might've just gotten unlucky in encountering it?

**Comment by SaiPrithvi123** [comment] 2018-10-21 11:42
>So I might've just gotten unlucky in encountering it?

I can't say "unlucky." If your Monika talks more than usual stuff to you, then I'd say you're lucky.

**Comment by SaiPrithvi123** [comment] 2018-10-21 11:43
Oh wait

**Comment by SaiPrithvi123** [comment] 2018-10-21 11:43
I misunderstood you lol

**Comment by SaiPrithvi123** [comment] 2018-10-21 11:44
I haven't gotten that one too. IDK why they put it in random. I think they didn't mean to make it random, and they just did it by accident.

**Comment by Storylover-Vodhr** [comment] 2018-10-21 11:44
> I misunderstood you lol

That's fine. XD

So, I'll just continue on, and hopefully come across it before I get in too much trouble for being up so early.

**Comment by multimokia** [comment] 2018-10-21 15:10
The time concern topic does in fact account for those who work night shift, however it seems she asks once it's between 1 am and 2 am in the morning. Which is probably when you're out...

**Comment by Storylover-Vodhr** [comment] 2018-10-21 15:12
> The time concern topic does in fact account for those who work night shift, however it seems she asks once it's between 1 am and 2 am in the morning. Which is probably when you're out...

Aye. I got to work at 10 Pm, and get home around 7.

**Comment by ThePotatoGuy** [comment] 2018-10-26 01:20
marking as duplicate of #1669

**Closed** 2018-10-26 03:38 UTC
Labels: duplicate
