### ISSUE TITLE
[Bug] - Texts turn cryptic

### ISSUE THREAD

**Issue by Mykesss** [Monika-After-Story/MonikaModDev#7408] opened 2021-07-01 00:24 UTC
![DDLC_goDUgVBCcB](https://user-images.githubusercontent.com/50587061/124046025-99077980-da43-11eb-9527-738d02a55511.png)
If you try to sleep in the morning Monika scolds you for staying up all night (which I do all the time xD)
and this message appears
![DDLC_RguZVaV353](https://user-images.githubusercontent.com/50587061/124046473-a96c2400-da44-11eb-8743-3a7c8a5d2673.png)
Last message is supposed to be "I bet you can't even keep your eyes open right now" or something can't remember exactly since it changed to cryptic as soon as the message appeared xD
Cryptic texts seems to change it's characters every 2 to 3 seconds

I'm fairly new so happened 4 out of 4 times I tried. Idk if it's really a bug but yeah.. xD

**Comment by xXMidnight** [comment] 2021-07-01 00:36
Huh.

Pickle language lol-

uh anyway-

It's not **exactly** a bug, since- uh- I've done it before, no matter what you answer, she will always interpret it as a yes. So uh, it's because she's worried. It's not a bug since my Monika is completely healthy ^w^

**Comment by xXMidnight** [comment] 2021-07-01 00:37
I also suggest you download the Gen Scroll submod as it doesn't cover Monika's face when the select menu opens.

**Comment by Mykesss** [comment] 2021-07-01 01:20
yeah both choices gave the same answers
I'm not really bothered but just wanted to know what she was saying xD
Can you elaborate further on the Gen Scroll submod? I couldn't find anything on it

**Comment by xXMidnight** [comment] 2021-07-02 01:46
Oh- uh- qnq I already installed it- uh hold on lemme find it- uhhhh- Found it! :D https://github.com/Monika-After-Story/MonikaModDev/wiki/External-Content#submods It's multimokia's last submod on the list, the All Scrollable Menus. It moves Monika to the left and displays the menu on the right, therefore you can see Monika's face :D

**Comment by ThePotatoGuy** [comment] 2021-07-11 03:07
not a bug. see #5302 and #3391

The point is that you are too tired to actually read the text.

**Comment by ThePotatoGuy** [comment] 2021-08-07 22:41
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-08-07 22:41 UTC
Labels: not a bug
