### ISSUE TITLE
[Suggestion] Being able to watch a movie with Monika / Read to her + Shuffle option to songs

### ISSUE THREAD

**Issue by charliethecookie** [Monika-After-Story/MonikaModDev#8357] opened 2021-12-06 19:35 UTC
I think it would be great to have an option where you can ask Monika to watch a movie / series with you. Upon clicking the option, she would become excited, and when the dialogue ends, she would be silent and the "Play" button would not be available as if you clicked a "I'll be right back" option. After that, she'd say something along the lines of "That was very nice, [player]. You can always ask me to watch something with you, okay?"

Another similar version of this option would be "Can I read you a story?". Monika would say yes, the "Play" option would not be available and she would again be silent. When you clicked on "Talk" after finishing, she would say something like "All done? Thanks for reading that story to me, [player]. You're so sweet~"

Last thing. It's small but it would be really useful. Maybe adding a shuffle option to the songs so you don't have to manually pick another one when the one that is currently playing is over? I often read or even sleep with the game open, so it would be nice if the songs changed without me having to get up and select another one.

**Comment by ThePotatoGuy** [comment] 2021-12-07 03:50
> watching movies

see #628 and [here](https://github.com/Monika-After-Story/MonikaModDev/issues/5484#issuecomment-612543995)

> reading

duplicate of #5632

> shuffling songs

duplicate of #2088

**Comment by ThePotatoGuy** [comment] 2021-12-12 02:55
[closing as duplicate]

**Closed by ThePotatoGuy** 2021-12-12 02:55 UTC
Labels: duplicate
