### ISSUE TITLE
Monika stopped letting me know she's run out of topics

### ISSUE THREAD

**Issue by Snowgies** [Monika-After-Story/MonikaModDev#6296] opened 2020-09-08 07:06 UTC
As per the title, Monika has stopped telling me that she'll "hopefully think of something fun to talk about soon" as she usually does when I start the game and there are no new topics to be presented. Now, when I start the game she just does her usual greeting and that's it. I tried to change the random chatter setting from never to very often but still, no response whatsoever. 

Perhaps this is because I am running on unstable? This became present in 11.3 unstable and I was hoping it would fix itself after a few restarts or take her out and back into the space room or even after updating to 11.4 unstable but that did not seem to work and I don't know what else I can do to try and fix it. 

on a side note: thank you, devs and contributors, for your hard work and dedication to this mod especially during these trying times. I hope all of you are staying safe out there!

**Comment by Snowgies** [comment] 2020-09-08 07:07
ah hold on i messed up and accidentally pressed enter, trying to figure out how to delete this and start a new one

**Comment by Snowgies** [comment] 2020-09-08 07:24
sorry for the confusion with closing and reopening, I accidentally hit return after typing in the title and it ended up submitting the issue without me adding a description to it. I was hoping that closing the issue would delete it but that didn't work. I don't really know how to delete issues.

**Comment by Freshairkaboom** [comment] 2020-09-08 07:30
Hey, yeah we changed it, she now doesn't repeat the lines about running out of topics unless it's been 2 weeks, or a new topic has been discussed since. It was a bit too intrusive to get for people who wanted to just spend some silent time with Monika after depleting the topics.

And thank you, I am staying safe. :) Hope you are too.

**Comment by Snowgies** [comment] 2020-09-08 07:37
Oh gotcha! That makes a lot of sense, that's quite nice of you guys to do that. Thank you for letting me know! 

stay awesome :D

**Comment by ThePotatoGuy** [comment] 2020-09-19 18:11
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-09-19 18:11 UTC
Labels: not a bug
