### ISSUE TITLE
Visual bug at the table when monika gets more coffee

### ISSUE THREAD

**Issue by Jose190** [Monika-After-Story/MonikaModDev#3819] opened 2019-02-21 15:41 UTC
![screenshot0054](https://user-images.githubusercontent.com/47601477/53181241-95d76580-35cd-11e9-92d0-1ba10be5a193.png)

**Comment by ThePotatoGuy** [comment] 2019-02-21 15:57
going to mark as duplicate of #3820 as this is a result of not having functionality in linked issue

**Comment by ThePotatoGuy** [comment] 2019-03-02 18:18
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-03-02 18:18 UTC
Labels: duplicate
