### ISSUE TITLE
Potato Here is the issue you ordered  from me to make it 

### ISSUE THREAD

**Issue by Glitch2545** [Monika-After-Story/MonikaModDev#9937] opened 2023-03-11 12:01 UTC
Here is my pc information 
![image](https://user-images.githubusercontent.com/105886636/224483148-61c521ff-a668-4858-bb92-733d2ac77396.png)
[DxDiag.txt](https://github.com/Monika-After-Story/MonikaModDev/files/10948428/DxDiag.txt)
![image](https://user-images.githubusercontent.com/105886636/224483344-3a3cc19f-95c5-4664-849e-cfbf1ede73e8.png)

**Comment by ThePotatoGuy** [comment] 2023-06-15 00:47
[closing as not a bug]

**Closed by ThePotatoGuy** 2023-06-15 00:47 UTC
Labels: not a bug
