### ISSUE TITLE
Saying multiple hurtful things without apologizing in between, and apologies are missing? Bug or limitation?

### ISSUE THREAD

**Issue by Justformas** [Monika-After-Story/MonikaModDev#9125] opened 2022-05-13 19:20 UTC
So recently I tested saying, "I'm breaking up with you", "Do you want to meet my girfriend?" and "You're a murderer" back to back to back. I did not apologize in between them and when I was done, there was only one apology (can't remember which one exactly). When I used it, there wasn't any more apologies other than the generic one "for something". That would explain my experience from a separate time:

>I could have sworn there wasn't. Between the Murder, Breakup and Meet my girlfriend topics I only remember 2 such apologies, and I thought that was the missing one. Maybe I'm misremembering, or was it some fluke or did it disappear?

I must have said 1 thing and then apologized, but then said the other 2 things and didn't apologize until afterwards. Or the other way around. So is this a bug or some limitation of the apology system?

**Comment by kkrosie123** [comment] 2022-05-13 20:02
It's limitation.

**Comment by WishStone-Dragon** [comment] 2022-05-13 22:24
Not a bug. Just as it isn't a bug when you say something hurtful and let time pass.
Or if she says "I love you" and you do not reply back with "I love you, too" right away. Stuff times out.

**Comment by Justformas** [comment] 2022-05-14 00:09
> It's limitation.

> Not a bug. Just as it isn't a bug when you say something hurtful and let time pass. Or if she says "I love you" and you do not reply back with "I love you, too" right away. Stuff times out.

I see. I felt like I remember there being 2 types of apologies at once, perhaps with one of them being some other type of thing that you can apologize for, but maybe not.

Maybe the apology for those 3 things shares the same flag, variable or something? Because they shouldn't have just timed out with as fast as I said them.

On a somewhat related note, I seem to remember the apology for returning Monika too quickly from "I'm taking you somewhere" being hidden in the otherwise generic "for something" apology prompt.

**Comment by Justformas** [comment] 2022-05-19 04:11
I'm not sure if I should "suggest" having them be different variables, or not get overwritten by each other in this issue (but still have them time out after enough time has passed). 

Or maybe something like a "combined apology" for saying multiple hurtful things, as one might do in real life if things happened quickly enough. In that case, I wouldn't just want to apologize for the most recent line/comment (I don't really care about whether regained affection points would stack for this, and that might not even be applicable at some point anyway).

I could leave this open for now for consideration.

**Comment by ThePotatoGuy** [comment] 2022-05-21 17:26
Things that have discrete apologies are already listed out in the apology menu so you can do multiple. 

[closing as not a bug]

**Closed by ThePotatoGuy** 2022-05-21 17:26 UTC
Labels: not a bug
