### ISSUE TITLE
[Issue] Songs/Music not appearing.

### ISSUE THREAD

**Issue by Secretmanguy** [Monika-After-Story/MonikaModDev#7922] opened 2021-09-24 12:44 UTC
I haven't particularly had any issues with the game since downloading it years ago, as any issues are usually quickly resolved, but one that has been recurring is music not showing up. Each update there will be mention of new songs being added, but they never appear when I go to the Music menu to try and play them.

**Comment by multimokia** [comment] 2021-09-24 12:58
They're not in the music menu. They're songs she sings from time to time.

**Comment by ThePotatoGuy** [comment] 2021-10-02 21:12
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-10-02 21:12 UTC
Labels: not a bug
