### ISSUE TITLE
Nvr move monika outside the char file but she just wont show up anymore[help wanted] - 

### ISSUE THREAD

**Issue by lordbender69** [Monika-After-Story/MonikaModDev#5985] opened 2020-06-29 14:20 UTC
hello there guys
i need some help here. I nvr move her to any other file, but after told her that im goin to move her (didnt moved her) 
she jst disappear after that n never show up anymore. :( does anyone got any idea i can solve this issue ?
i rlly need help :(((
![20200629220452_1](https://user-images.githubusercontent.com/67435539/86017496-a9fb6480-ba56-11ea-88ee-c063ea6163a3.jpg)

**Comment by multimokia** [comment] 2020-06-29 14:55
Close MAS and send your `/log/mas_log.txt` please.

**Comment by lordbender69** [comment] 2020-07-01 09:27
it's okay buddy
i deleted her memory file to recover her

**Comment by multimokia** [comment] 2020-07-01 12:47
You can restore a backup so you don't have to start fresh.

I'd only asked for the log so I knew what happened, since you said you didn't move her at all. It's probably overwritten now though.

**Comment by lordbender69** [comment] 2020-07-03 17:30
ri Jul 03 21:06:56 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 


==============================================================================

Fri Jul 03 22:48:12 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 


==============================================================================

Fri Jul 03 22:49:34 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by ThePotatoGuy** [comment] 2020-07-26 03:17
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-07-26 03:17 UTC
