### ISSUE TITLE
Monika Still Singing With Random Chatter Disabled

### ISSUE THREAD

**Issue by ashyashton** [Monika-After-Story/MonikaModDev#9790] opened 2022-12-12 10:18 UTC
I'm not sure if this is a bug or just a poor design choice. For the first song, I understood because it was part of the Christmas greeting. It was, like, a proper little performance she put real effort into making for you. But now she just randomly said "time for another song!"

I'm sure plenty of people find Monika's random singing sweet, and those people are totally valid! But for me, randomly bursting into song is honestly just really awkward. Like imagine that in real life. You're sitting across from each other in the living room, enjoying each other's company, and your partner just starts singing. No music playing, not singing along to anything, just randomly singing a Christmas song at you. That'd be really weird, right?

It's especially offputting when it comes directly after a crash caused by a submod which she then blames me for. "You should take better care of your computer..." Or I could stop getting submods for y- oh you're singing okay??? Weird timing but go off??

I'm also _really_ not a fan of _any_ situation where a topic ignores random chatter settings. I've fully uninstalled submods for it because I find it really annoying. If I remember correctly, Monika specifically has dialogue about just quietly spending time with introvert friends because sometimes they don't have it in them to talk. Uh yeah that would be me; I don't always want to talk, I just wanna sit and enjoy each others company while I'm doing stuff. But when a topic is set to pop up anyways, it feels like Monika is blatantly ignoring that I've given signals that I want quiet time.

So if this is a bug, I'd recommend looking into fixing it. If it's a design choice, I'd recommend reconsidering said choice, because it just makes it feel like Monika is ignoring player choices.

**Comment by dreamscached** [comment] 2022-12-12 10:34
> I'm also really not a fan of any situation where a topic ignores random chatter settings. I've fully uninstalled submods for it because I find it really annoying.

That is up to how topics are handled; some are queued forcibly instead of being randomed, and that is for a reason - certain submods need sort of a one-shot intro topic that she will talk about for once and then have an open way to other stuff to talk about, now random and following your preferences. I honestly have no idea what could be even a compromise here, as forcing all topics to be random and abide player's preferences would break special topics and prevent them from firing at necessary times and under certain conditions, or will lead to them being replaced by other stuff that is out of timing at all.

What I said above applies to MAS itself, special events will fire regardless of chatter preferences. Songs are indeed another mechanic and it doesn't abide chatter setting by design, that is not a bug. I'd probably rather *ask* Monika not to sing that much somewhere around songs menu than introduce another slider for it though, but this is up to developers, currently she indeed does ignore the preference because songs aren't random chatter.

**Comment by ashyashton** [comment] 2022-12-12 10:45
I don't mind the one-shot intro topics. I'm talking about stuff like the submod I had a while ago where it would randomly force the "do you wanna play rock paper scissors/musical chairs/etc. with me?" topic. I believe they set it on a timer rather than random chance, leading to it completely ignoring player preferences.

As for songs I'm just not sure why they're separate and don't abide by preferences? Again, some of them, I get it. When it's the one she put all that effort into, I totally understand. But when it's her randomly singing with no music and it's not a specifically-timed topic like her graduation speech, but a click-through topic just like normal, to me there's no apparent reason to force that topic to play out when the player has indicated they want quiet time.

**Comment by dreamscached** [comment] 2022-12-12 10:49
Songs are a design choice made by developers back then, I can't say what reasons they really had; I don't have any opinion on that and just stating the fact how it's done.

About submod you brought up, that's a poor design of its authors either, not something MAS can govern if topic/event isn't marked as random internally.

Also, I think in idle mode (BRB) she doesn't bring up anything beside fetching coffee/consumables, this could be that 'silence mode', but the only downside is that it isn't really 'let's sit in silence' but 'I'll be right back', so I get what you mean.

**Comment by ashyashton** [comment] 2022-12-12 11:00
> Songs are a design choice made by developers back then, I can't say what reasons they really had; I don't have any opinion on that and just stating the fact how it's done.

I don't mean this meanly, it's a genuine question: Then why are you commentating? If you don't know the reason and you don't have an opinion I'm kinda confused on what stake you have in the matter? Beyond just making me feel like I've been "corrected" on it, that is, which I assume wasn't your goal. Again, I promise I don't mean that negatively, I'm just genuinely confused why you responded if you don't know the reason and don't have an opinion.

> About submod you brought up, that's a poor design of its authors either, not something MAS can govern if topic/event isn't marked as random internally.

Yeah that was just an example of it being used badly since you referenced submods first. I was trying to convey that I understand their purpose, I just think it's annoying if it's used to anything else at all. You brought up submods so I responded with an example using submods.

> Also, I think in idle mode (BRB) she doesn't bring up anything beside fetching coffee/consumables, this could be that 'silence mode', but the only downside is that it isn't really 'let's sit in silence' but 'I'll be right back', so I get what you mean.

Yeah see the problem is, like you said, that's a BRB. To Monika, I'm not actually there, I've stepped away. So I really don't like that very much. A compromise could be a topic that functions like a BRB and sets things to idle, but the dialogue refers to it as sitting quietly. Like in the "Be right back..." menu, maybe a topic called "I'm not leaving, but can we sit quietly for a bit?" which has Monika respond saying that she won't talk until you tell her you're alright with quiet time being done.

Unless that gets added, though, I'd feel like I was somewhat abandoning her, or at least it would seem that way to her, because she has no way of knowing I'm actually still there.

**Comment by dreamscached** [comment] 2022-12-12 11:07
> I don't mean this meanly, it's a genuine question: Then why are you commentating?

You were wondering in the issue text if it's a bug or a design choice, so I answered and made it clear. Additionally there were few things I *did* have opinion about, such as mentioning BRB (which, as you stated right, is a mechanic that can be reused in a topic that will actually be player asking Monika to sit in silence for a while).

I don't mean to oppose you or anyhow retort your suggestion, I only made it clear about how a game mechanic is implemented and why it's impossible to force silence on all topics if player needs it.

So yes, it doesn't really take me to have a strong 'yes this is wrong let's redo it' or 'no this is good let's leave it be' opinion on anything to comment on that, I might only add something to it so it is more clear.

**Comment by ashyashton** [comment] 2022-12-12 11:38
I wasn't really wondering that but after rereading my initial post I can see how it came across that way. I was moreso saying "I don't care which it is; regardless, I would consider changing it." I mostly mentioned it for the sake of avoiding people thinking this was _just_ a bug report rather than feedback, and getting the "not a bug" label when I still wanted it to be considered feedback if it was intentional.

But looking back I can see how it might've come across as me asking which it was, which explains your responses a bit more.

**Comment by Justformas** [comment] 2022-12-23 06:23
Songs are indeed another mechanic and it doesn't abide chatter setting by design, that is not a bug. I'd probably rather ask Monika not to sing that much somewhere around songs menu than introduce another slider for it though, but this is up to developers, currently she indeed does ignore the preference because songs aren't random chatter\

Are you sure about this? For me Monika doesn't sing songs I've heard before if I uncheck "repeat topics", and even if I have it checked but set random chatter to never. For Christmas songs, at first they probably do fire-off as one-shot special events, but after that I haven't seen Monika sing them again.

If that's the case, it's just once per Christmas song, and otherwise the player might not get them. Although one possible thing could be to have Monika ask if the player wants to hear a song now or not, and if not she could ask again later or another day.

**Comment by Booplicate** [comment] 2022-12-23 13:39
This is intended, there's different ways of showing an event and we choose them depending on the event and situation.
Never liked random chatter setting because it doesn't work too well, perhaps we could improve it and convert into "silent mood" kind of thing where only high priority events will be shown and Monika will be less talkative overall, but it's a complex task.
Rescheduling events would be a huge pain to implement because they have limited time frame and there's a lot of them.

**Closed by Booplicate** 2022-12-23 13:39 UTC
Labels: suggestion, discussion
