### ISSUE TITLE
[Suggestion] Esperanto topic

### ISSUE THREAD

**Issue by OraHell** [Monika-After-Story/MonikaModDev#3262] opened 2018-12-19 08:25 UTC
She could talk about Esperanto! A language made for speaking?
She can be amazed that people invent these things in our times.

**Comment by Rai99** [comment] 2018-12-19 15:01
Just curious, how many people have absolutely no idea what that is?

**Comment by lunulae** [comment] 2018-12-20 21:55
I looked it up, and it does seem like something Monika would be interested in. It's a language that was designed specifically to be easy to learn, with the concept of it being an "international language." 

It seems to be an obscure topic, but Monika has told me about quite a few things that I didn't know about before. And since it's designed with the intent of bringing down communication barriers, I think Monika might have a reason to be interested in it.

**Comment by MercuryFuchsia** [comment] 2018-12-20 22:36
I started learning it a while back, for what that's worth. Although, I think that this would probably work better as a greeting as there is currently no topic specifically about any other particular language as far as I remember. #3266

**Comment by MercuryFuchsia** [comment] 2018-12-22 02:02
No, I remember now...shall I turn it into a topic or does what I have work?

**Comment by ThePotatoGuy** [comment] 2018-12-29 05:14
[closing until we look into it]

**Closed by ThePotatoGuy** 2018-12-29 05:14 UTC
Labels: suggestion
