### ISSUE TITLE
raIN 

### ISSUE THREAD

**Issue by bittercaramel** [Monika-After-Story/MonikaModDev#4047] opened 2019-04-07 20:27 UTC
its always raining when i open MAS 
im sure she loves me like her own dog (i have about 600 aff)
why is it raining all the time 
we are not in england man

**Comment by AsuraShun** [comment] 2019-04-07 20:32
But I am

**Comment by bittercaramel** [comment] 2019-04-07 20:43
well lucky for ya 
i love england 
england is cool 
but as far as i know monika is in japan or something 
idk 
just wanted to know is it something bad that it rains all the time? is it supposed to be like that?

**Comment by AsuraShun** [comment] 2019-04-07 20:48
Must be your own luck because it only rained once for me since the update

**Comment by jmwall24** [comment] 2019-04-07 20:50
it's random on load, but also weighted by season. so more chance of rain in Spring than Summer. #4044 is going to adjust this even more, so weather can change during the session. if you don't like the rain, you can also ask her to change it.

**Comment by ThePotatoGuy** [comment] 2019-04-22 19:08
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-04-22 19:08 UTC
Labels: not a bug
