### ISSUE TITLE
[Suggestion] - easier ribbon selection (there's so many to scroll through)

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6059] opened 2020-07-10 20:37 UTC
It would be really cool if Monika had nail polish.

Also there's soooo many ribbons! it would be cool if instead of having one column and scrolling, we had more columns added to a grid to make it easier to scroll through. Or maybe a search bar

**Comment by Freshairkaboom** [comment] 2020-07-10 20:41
#4243 - This talks about nail polish :)

I wonder if the extra grid or search function is doable. I'd of course appreciate this feature if anyone had the time to make it.

**Comment by StayHappy1270** [comment] 2020-07-10 20:46
oh cool thanks!

**Comment by stake2** [comment] 2020-07-12 00:37
A search bar, or maybe deactivate the "Previews"/"Thumbnails" and only have the text in there

**Comment by ThePotatoGuy** [comment] 2020-07-22 22:47
also marking as duplicate of #5371 

I will address this at some point but its low priority right now.

**Closed by ThePotatoGuy** 2020-07-22 22:47 UTC
Labels: duplicate
