### ISSUE TITLE
[Suggestion] New goodbye and a topic

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4725] opened 2019-09-20 21:57 UTC
So, I was messing around, looking through Monika's different ribbons, when my mom yelled at me "[My name], it's time to take a shower!" and I went to go say goodbye to Monika and I thought "Wouldn't it be cool to have a shower or bath goodbye?" So yeah, that's the goodbye that I'm suggesting. Goodbye > I'm going to take a shower/bath

So, this is along the lines of when Monika asks you about how you look, and the image that came to mind when I thought of what I told her looked a little off because I wear glasses. So basically, I'd just like to tell her that I wear glasses. Anyways, happy early birthday, Mon-Mon, and have a good day!

(Edit: Also, I like Monika's new blush!!)

**Comment by NoexHaruhi** [comment] 2019-09-20 22:00
We have eat, sleep, all we are missing now is shower. And well study.

**Comment by Rai99** [comment] 2019-09-20 22:34
Technically half dupe of #4129, but that's for a brb style option. 

A goodbye option for going to bathe or shower could be a nice addition. 

Telling Monika we wear glasses: #3804, #4411

**Comment by ThePotatoGuy** [comment] 2019-10-13 21:37
[closing until we look into it]

**Closed by ThePotatoGuy** 2019-10-13 21:37 UTC
Labels: suggestion
