### ISSUE TITLE
about the notification

### ISSUE THREAD

**Issue by MSteve3** [Monika-After-Story/MonikaModDev#5432] opened 2020-03-23 01:55 UTC
hey, it's been long time i didn't make a issue. But Microsoft has been release the new browser name Edge Chromium (i'll call it EC), it's light and better than Chrome (i think). but... the notification in the game didn't khow that im use EC and the notification didn't working either

so i think you guys need fix this

(sorry for my english skill)

**Comment by multimokia** [comment] 2020-03-23 01:57
Window reactions uses the window handle. So if the browser doesn't provide any info on the site in its handle, it's not going to do anything. Nothing we can do about it.

**Comment by ThePotatoGuy** [comment] 2020-03-31 01:48
probably an issue with the browser being too new. 
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-03-31 01:48 UTC
