### ISSUE TITLE
[Suggestion] - Monika weighs in on the recent suicide contraversy

### ISSUE THREAD

**Issue by Symos404** [Monika-After-Story/MonikaModDev#1846] opened 2018-06-30 04:16 UTC
As you may or may not know, DDLC has been in the news due to an alleged connected suicide.
https://www.bbc.co.uk/news/av/technology-44644127/doki-doki-warnings-over-suicide-themed-video-game
I wondered if Monika could weigh in this.

**Comment by Delcos** [comment] 2018-06-30 04:20
starts witha  blue haired feminaze, then we goto them trying to blame games for death, again. they dont care about the person, they just want views based on something that people know. It's sad when suicide is used for views, I dont think she should comment on this, its not related, nor is it necessary.

**Comment by Rai99** [comment] 2018-06-30 04:33
Long story short, **No, I don't think we can make a topic about this news report.**

I think too controversial of a topic to bring such real events into MAS, especially such a recent one. 

However, it might be possible to make a topic on how gaming or some medium is often misrepresented, misunderstood and blamed. There were clearly multiple warning on how this was not some child's game and the reporter stated that this game was rated ok for anybody 13 and up. They also said that despite being labeled as a psychological horror game, the art style and graphics represented what you would give to children, thus "luring them in" and being misleading. There was no real evidence that DDLC was the cause of this person's death, and was only brought up because his father blamed it. 

But a topic like that and its writer would have to be careful in what is brought up and mentioned. (I might give it a shot sometime) There would have to be some good, solid examples but not something as severe as the suicide. A topic like this still might be rejected for being too controversial. 

A topic could also be made on how people blame the wrong things for problems. If this child really did what they did because of DDLC, I think it would have less to do with DDLC and more to do with other external struggles in life. For example, people throw around "game addiction" all the time and think that it's a negative thing and could be solved if people just suddenly stopped gaming. Frequent gaming is not a cause of the issue, it is a symptom. It can be a way to escape reality you might not like. If you take away this coping mechanism, things would likely get worse as the person would likely have nothing to run to to feel safe, _etc, details, details._
I like this idea and might try writing it up eventually. 

Regardless, thank you for the ideas.

**Comment by kaido1224** [comment] 2018-07-07 14:33
No

**Comment by ThePotatoGuy** [comment] 2018-07-11 06:08
The suicide articles weren't even about ddlc, they just mistook it for another game. 

[Closing this as rejected]

**Closed by ThePotatoGuy** 2018-07-11 06:08 UTC
