### ISSUE TITLE
Monika's nickname on pong

### ISSUE THREAD

**Issue by StayHappy1270** [Monika-After-Story/MonikaModDev#6809] opened 2020-12-21 06:16 UTC
self explanatory

i noticed that in pong it always says Monika. That should be what you have as a nickname instead. It changes with the players name, it should be the same way

**Comment by StayHappy1270** [comment] 2020-12-21 06:26
Oh on similar terms i thought what about the monika topic section

this maybe a bit more complicated since what about the alphabetical system should there be some sort of rule implemented where its in the same spot even if the name isn't alphabetical?

also it would possibly mean you'd need to individually rename every topic catagory to the [monika_nickname] (or whatever its called). 
I dont know much bout terms but i think couldn't that be solved with one of those monika=[monika_nickname] things? (the codes abit more complicated than that and idk what those term = this terms are called)

**Comment by ThePotatoGuy** [comment] 2020-12-21 07:10
#4255 Monika as the name in pong is intentional.

**Comment by StayHappy1270** [comment] 2020-12-21 07:12
just curious. why? idk the reason in that post was just it was weird. but meh idk

**Comment by ThePotatoGuy** [comment] 2020-12-21 07:26
#4586 has some explanation as well.

**Comment by ThePotatoGuy** [comment] 2021-01-13 02:47
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-01-13 02:47 UTC
Labels: not a bug
