### ISSUE TITLE
coffee zoom change?

### ISSUE THREAD

**Issue by cordwill** [Monika-After-Story/MonikaModDev#5090] opened 2019-12-10 15:05 UTC
I just really noticed this today. Monika is wearing the new navy dress with the blue rabbit ear bow so I have it zoomed out all the way so I can see more the bow as well but when the coffee finished and she went to get it the desk and she auto zoomed in, the same thing happened when she went to get another cup after finishing her first one. Don't know if this is a known thing or not

**Comment by multimokia** [comment] 2019-12-10 15:42
This is known, also not a bug. Auto zoom back to default and then back is intentional.

**Comment by ThePotatoGuy** [comment] 2020-01-03 03:48
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-01-03 03:48 UTC
Labels: not a bug
