### ISSUE TITLE
Some MAS conversations not showing up in the 'repeat conversation' tab?(maybe bug?)

### ISSUE THREAD

**Issue by Mononucleosis59** [Monika-After-Story/MonikaModDev#5530] opened 2020-04-13 04:27 UTC
While I was checking out the 0.11.0 update and seeing all of the new stuff I noticed that some of the conversations you have with Monika are not in the 'repeat conversation' tab.
examples include:
-COVID-19 Topic
-Our first kiss Topic
Not sure of any others yet.
Is this a bug or was it intended?
If it was intended, I recommend putting those as options in the 'repeat conversation' tab for those including myself who want to see all of the outcomes for the different options given.

**Comment by multimokia** [comment] 2020-04-13 04:45
These are intentional. Additionally, these topics aren't about completionism. They are for your answer and actual thoughts on the matter (or in the case of COVID, your actions)

The `thinking about our first kiss` topic shouldn't allow you to change your answer realistically.

**Comment by Mononucleosis59** [comment] 2020-04-14 15:16
@multimokia 
I can see what your trying to go for here.
However...I still don't see why you wouldn't put these topics into the "repeat conversation" tab, since that is the whole purpose of it.
I mean you might as well get rid of the tab, since there are plenty of topics here that I can never see Monika repeating again.
Examples include:
-player's family
-player's appearance
-vocaloids
And if you want to make it a one time use thing, than make the player know more that the topic will not be repeatable.
The problem here is that it is blended in with all topics that ARE repeatable. Many people will get confused with this and assume it's like everything else, and as soon as the player realizes that those topics aren't repeatable if he/she made a mistake, well then that just sucks and is unnecessary.

**Comment by multimokia** [comment] 2020-04-14 15:21
Player's family I can see being repeated depending on what you answered the first time. It's possible for things to change situationally and therefore, changing your answer is a valid thing to do.

Player's appearance can change as well. If I said I had long hair originally and then decided to cut my hair as my new normal style, have I not changed my appearance?

Music related topics can change too, as they deal with *personal tastes*, which naturally change over time.

All of these examples there are things which *can* change in the future.

Regarding the answer of "Do you still think about our first kiss?", imagine if you said you didn't in real life, you can't just change your answer at all. I get what you're saying the case of a mistake, but letting people know that a topic is one-time only really breaks immersion. That doesn't happen in real life and since this intends to mimic a normal relationship, it really shouldn't happen here either.

**Comment by Mononucleosis59** [comment] 2020-04-14 15:21
If your wanting to make these topics more special, then maybe get more creative with it.
-Maybe make the "thinking about our first kiss topic" to be something she says on a holiday or special event after having your first kiss with Monika.
-And maybe put a date on the calendar that talks about COVID-19 on a specific day of a specific year.


Now you can argue that each of the compliments you can give Monika have a one time use option dialogue thing, but the thing here is that the player is more aware of it, since he/she knows that every compliment has a one time use dialogue option.
To put it in simply, "it's structured"

**Comment by Mononucleosis59** [comment] 2020-04-14 15:25
I believe the problem here is I dont think a lot of people will suspect these topics to be one time use, since just about everything else in that same categorie is repeatable in some way.

**Comment by ThePotatoGuy** [comment] 2020-04-14 15:44
>I dont think a lot of people will suspect these topics to be one time use

We like to keep people on their toes.

>Maybe make the "thinking about our first kiss topic" to be something she says on a holiday or special event after having your first kiss with Monika.

Actually, maybe we can use this on a first kiss anniversary. Still wouldn't be in Repeat Conversation, but would trigger once a year.

**Comment by Mononucleosis59** [comment] 2020-04-14 15:53
Alrighty, that answered most of what I was concerned about.

**Comment by jmwall24** [comment] 2020-04-14 16:18
So it seems to me you're the type that wants to see every possible answer, and here likely answered negatively the first time and want to be able to change that. I disagree with that playstyle but to each their own, not my place to judge. Regardless, some of our menus should and do have consequences, so if this is how some want to play, I'd suggest not answering the negative way first if that's not what you want your actual answer to be. That way, if the topic is not repeatable, you're fine, and if it is, then you can go back and mess around with the answers.

**Comment by Mononucleosis59** [comment] 2020-04-14 16:39
I answered fine,
It's was just something that didn't really make much sense to me haha.

**Comment by SamanthaLind** [comment] 2020-04-14 20:33
I would like to repeat covid. When she asked me about it there it wasn't in my region, now it is and I would like to tell her about it. Also in few days quarantine will start and I would like to tell her how it changed.

**Comment by ThePotatoGuy** [comment] 2020-04-23 04:03
we'll reconsider current events topics at a later date.

[closing as not a bug]

**Closed by ThePotatoGuy** 2020-04-23 04:03 UTC
Labels: not a bug
