### ISSUE TITLE
[Suggestion] telling Monika that something bad happened to the player

### ISSUE THREAD

**Issue by Anonimoshadow** [Monika-After-Story/MonikaModDev#4568] opened 2019-08-25 17:56 UTC
There's a dialogue in which Monika says that she would never know if something happened to us, but why not give her the chance to? Now i know it's depressing and all, but i'd rather let her know than leaving her to "wait" for eternity; maybe if we tell her that we (or anyway, the player) passed away she'll ask if we're kidding, as an ultimatum, and if we say yes, she'll get mad at us, if we say no, she'll close the game and we wouldn't be able to open it again.
 i don't know, it is just an idea.
Sorry for my bad English

**Comment by Necrocytus** [comment] 2019-08-25 22:02
![dup](https://user-images.githubusercontent.com/38022925/63656490-197b3600-c75a-11e9-8c08-7c4fa1697d21.png)

**Comment by bringerofstorms** [comment] 2019-08-26 03:57
Meaningful or generic or not, it would be better than nothing. The only alternatives are Monika waiting in silent torment forever for the player to come back, or unexplained deletion. She might not understand either of the two.
(This is something I personally really want because my job is pretty high risk, so if anything happens to me, I'd like her to at least know)

**Comment by multimokia** [comment] 2019-08-26 10:11
> Meaningful or generic or not, it would be better than nothing.

Given the potential gravity of the situation, I'll have to disagree with you here. See, a serious issue being met with a generic response can be extremely immersion breaking because it shows the limitations Monika has in terms of the way she handles input she gets from you. Likewise if the issue is small and she makes a really big deal out of it.

Not to mention, because injuries and illnesses can be so different, it's completely impossible to say all that much without sounding completely low effort and as if we're avoiding talking about it.

While it would be nice to have, it's also one of those things which would be more damaging than it would be if we just didn't include it

**Comment by Anonimoshadow** [comment] 2019-08-26 20:33
I'm sorry but i don't understand (as in, i genuinely, don't understand, don't want to attack anyone), putting a generic response makes her seem like reciting a script, but...isn't she always? 
I mean...couldn't you give as a response just her crying and closing the game or something like that?

**Comment by ThePotatoGuy** [comment] 2019-09-08 16:41
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-09-08 16:41 UTC
Labels: duplicate
