### ISSUE TITLE
Sprite Pack Suggestion: Pajamas/Night wear

### ISSUE THREAD

**Issue by linkerplinker** [Monika-After-Story/MonikaModDev#5045] opened 2019-11-26 22:50 UTC
Idk it feels a bit weird seeing Monika in day clothes consistently and think it would be amazing if she had a event triggered by the night to put on night wear. Just a fun little idea. Bring a little more reality to the game.

**Comment by RavenPLAYER** [comment] 2019-11-26 23:18
Wait, wait... here comes the duplicate~

**Comment by RavenPLAYER** [comment] 2019-11-26 23:53
I think the pijamas it's planned with the bed mode

**Comment by Velius94** [comment] 2019-12-03 00:38
Duplicate of #4960

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:03
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-12-15 00:03 UTC
Labels: duplicate
