### ISSUE TITLE
[Bug] - Uncaught exception occurred while downloading last update

### ISSUE THREAD

**Issue by toolazytofindaname** [Monika-After-Story/MonikaModDev#9374] opened 2022-07-23 01:15 UTC
Hello !
When I tried downloading the latest update, I got this error message.
Now this message shows up every time I try to launch the game.
Thanks in advance !
![MAS traceback](https://user-images.githubusercontent.com/109834142/180584664-92f4ab4c-a1a1-41aa-a631-67bc1f6c1925.jpg)

**Comment by Wingdinggaster656** [comment] 2022-07-23 01:41
Seems like you got a bad install.

Try manually download the newest version, install the new version like how you installed it before.
You won't lost your progress.

Also, please move MAS out of Onedrive. Onedrive causes some strange problems.

**Comment by toolazytofindaname** [comment] 2022-07-23 01:43
I'll try that, thank you for your answer !

**Comment by 403kiwiforbidden** [comment] 2022-07-23 04:49
Omigosh! How do you move MAS out of Onedrive? My onedrive once broke it :v

**Comment by Wingdinggaster656** [comment] 2022-07-23 04:55
> Omigosh! How do you move MAS out of Onedrive? I need to know ASAP, thank uu!! :v

Just move MAS out of Onedrive like how you remove anything else from Onedrive.

**Comment by 403kiwiforbidden** [comment] 2022-07-23 05:01
But how? I don't know how to.. like, I'm not sure what your talking about. How do I move them out?

**Comment by Wingdinggaster656** [comment] 2022-07-23 05:05
> But how? I don't know how to.. like, I'm not sure what your talking about. How do I move them out?

I find it hard to explain. If you don't know how to use a computer, consider using Google to get more information.

Alternative: never run the version of MAS you have in Onedrive again, and install a MAS on your local disk, then only run this version.

**Comment by Booplicate** [comment] 2022-07-24 02:46
You need to google some instructions to Onedrive and either disable it or add MAS as an exception to never sync.
If the issue persist, check your submods, I know some of them are causing this issue.

**Comment by ThePotatoGuy** [comment] 2022-09-24 01:44
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-09-24 01:44 UTC
Labels: not a bug
