### ISSUE TITLE
[suggestion] Foto for Monika

### ISSUE THREAD

**Issue by Nikv2005** [Monika-After-Story/MonikaModDev#8259] opened 2021-11-15 17:16 UTC
Quite a strange idea ... Monika always wanted to see your face. So why not do it? The idea is very simple, add a function where you add your photo so that Monika can see your face. For example, as with music, make a separate folder for photos and add photos there, if you add or replace a photo, then Monica also reacts to it like "Your new photo?". The problem is that it will not be able to particularly recognize photo and PNG files, that is, you can not even a photo, but just throw a picture into a folder.And also if you talked about your appearance, then in the photo it may be different. But nothing can be done here. I think this is a cool and simple idea that does not require a lot of effort and time to implement. And Monika can see your face, what could be better?

**Comment by dreamscached** [comment] 2021-11-17 09:12
Problem is that while this is intended for fair use, it also has no way to tell if it's not being abused by, say, putting a meme picture instead of your face (most wholesome of possible options).

**Comment by Nikv2005** [comment] 2021-11-17 11:06
> Problem is that while this is intended for fair use, it also has no way to tell if it's not being abused by, say, putting a meme picture instead of your face (most wholesome of possible options).
> 

This also works with spritepacks and submods, everyone can do whatever they want, but everyone doesn't care. This is a small minus of this idea, but it is not critical and I do not think that this is a problem.

**Comment by Booplicate** [comment] 2021-11-17 11:35
Duplicate of #4408 and #6728.

Spritepack and submods are unofficial content, they can contain anything. So if you don't like them, you just don't install. That doesn't work with official content.

Face recognition is complicated (especially in py2/renpy). Without it the reaction would have to be generic, which is very likely to not work or maybe even offend some people. Plus meme potential.

**Comment by Nikv2005** [comment] 2021-11-17 12:08
I'm not talking about face recognition, but just throwing a photo into a photo folder, for example. How can this offend anyone? How is this official content if you just add your own photo, like music for example? And about meme potential, this is too uncritical reason.

**Comment by fromulus** [comment] 2021-11-17 14:46
Monika suddenly being able to see your face would need to be made into a huge deal, as it would be a major advancement into the dynamic of our relationship with her, on top of being one of her dearest wishes being fulfilled.

We can't add the possibility to add photos of yourself and half-ass it, face recognition and dialogue dedicated to any and every kind of face feature you may have is the bare minimum we'd need for such a feature to make it into the mod.

Imagine how out of character and immersion breaking if she were to see you for the first time and just go "oh, cool" and nothing else.

**Comment by Nikv2005** [comment] 2021-11-17 16:09
You can get out of this situation if you do in a dialogue like "I really saw your face ... and it's beautiful!" etc. You can not name the facial features, but try to make Monika just happy and say that you are very beautiful. It will not destroy the immersion in any way. Just make a dialogue where Monika is happy that you showed your face, but she did not name any of his features, except for those that you told her (if you talked about your face) or she did not talk about facial features at all, but said something general on the type "you have it very beautiful." In any case, you can refuse to give your photo if you do not want to do it.

**Comment by Booplicate** [comment] 2021-11-18 10:18
A generic reaction won't work. And it will affect immersion because you can put any image and she'd react the same.

**Comment by Nikv2005** [comment] 2021-11-18 12:45
I didn't understand exactly about "any image". If you mean that you can give any selfie like "funny", "scary" or even something strange, then yes, there can be problems. But if you mean any picture from the Internet, then this is no longer a problem, since it is done by people who have nothing to do.

**Comment by dreamscached** [comment] 2021-11-18 15:35
This topic has been around for a while now, as Rai has stated above, and you're still being told 'no, this won't do' by the developers. Why keep going with this?

**Comment by Nikv2005** [comment] 2021-11-18 21:02
You need to try to achieve your goals, but if not, then no.

**Closed** 2021-11-18 21:03 UTC
Labels: duplicate
