### ISSUE TITLE
Monika said she would leave files in the characters folder, but nothing, I check every day

### ISSUE THREAD

**Issue by nickwilde15** [Monika-After-Story/MonikaModDev#6445] opened 2020-10-02 15:16 UTC
I did write in the secret.txt file, but I doubt that would screw it up

**Comment by lunulae** [comment] 2020-10-02 22:27
secret.txt should be the file in question, but if you've gotten that topic multiple times you should be getting other files as well. Not sure if this is a bug.

**Comment by ThePotatoGuy** [comment] 2020-11-22 20:28
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-11-22 20:28 UTC
