### ISSUE TITLE
[Semi-Bug] "Can you check for new music" talk option is a bit misleading

### ISSUE THREAD

**Issue by Danielshmaniel** [Monika-After-Story/MonikaModDev#7553] opened 2021-07-25 18:44 UTC
Disclaimer: I'm talking about the talk option in the Music category that asks for new music. I'm sorry if you can't understand what I'm trying to explain.

Even though it makes sense, I didn't know that this would be for only music that was put in the custom_bgm folder WHILE the game was still running. I actually presumed it was the opposite - that Monika would sense new music AFTER a restart or when the game isn't running - but that's not the case. 

I think that it would make logical sense if Monika could sense new music even after a restart or when the game isn't running, since the music is still _new_ to her. I consider this a bug as it makes this talk option a bit misleading; to the point that I thought that Monika was broken and couldn't sense new music - but then I figured out it only worked for putting new music WHILE the game is running.

For a fix, I think the game, when it _is running_, should sense new music that was put in the folder while the game _wasn't running_ since the music is still new. I don't know a lot of technical stuff, but I can suggest the devs can make a variable/boolean or something to identify new music.

**Comment by ThePotatoGuy** [comment] 2021-08-07 22:31
>For a fix, I think the game, when it is running, should sense new music that was put in the folder while the game wasn't running since the music is still new.

The mod always checks for new music on startup and adds it to the music menu. That Talk option is specifically for adding music while the game is running since its not worth the performance loss in constantly reloading music files.

[closing as not a bug]

**Closed by ThePotatoGuy** 2021-08-07 22:31 UTC
Labels: not a bug
