### ISSUE TITLE
[Suggestion] - Monika Pose Animations

### ISSUE THREAD

**Issue by myseriousaiyan64** [Monika-After-Story/MonikaModDev#2061] opened 2018-08-12 19:44 UTC
When you leave Monika on the menu for too long, it would be cool if there was an opition on the settings that could allow her to do something cool or a affection pose based on how she is feeling i.e. (smiling, in love, gaze somewhere else.)
_Kind of like in many games where the character you're playing will sometimes do an action because of in-active play activity._

**Comment by multimokia** [comment] 2018-08-12 20:08
#2055

**Comment by ThePotatoGuy** [comment] 2018-08-13 13:59
Closing as a duplicate of linked issue

**Closed by ThePotatoGuy** 2018-08-13 13:59 UTC
Labels: duplicate
