### ISSUE TITLE
Monika is not responding to gifts anymore if she can't read the files

### ISSUE THREAD

**Issue by JustAskingStuff** [Monika-After-Story/MonikaModDev#8401] opened 2021-12-14 02:41 UTC
So 3 days ago I was trying to gift Monika turtleneck sweater in character folder and she said she can't read the files, I rechecked the mod assets, and make sure that all folders from spritepack are in the correct place in "monika" folder inside "mod assets", as well as thumbs. 

But then when I try to give the gift to Monika second time, she didn't notice it and the .gift file in character disappeared. I tried the same thing on other new clothes(Miku and wine pull-over) yet every time she just said she can't read files and then ignored them at the second time when I tried to give them, all the .gift files of new clothes also disappeared after she ignored it.
![截屏2021-12-14 上午10 36 12](https://user-images.githubusercontent.com/96095658/145922816-07d042c5-197d-452b-a955-6c30b40d4a91.png)
![截屏2021-12-14 上午10 37 40](https://user-images.githubusercontent.com/96095658/145922992-865cf29c-67e3-460e-8a69-7aac537adeca.png)
![截屏2021-12-14 上午10 38 51](https://user-images.githubusercontent.com/96095658/145923096-ed450955-2e54-4839-baff-1e3f87fbae46.png)

Those are the screenshots I took to show the place where I put wine-pullover clothes, and the .gift file putted in "character" file just disappear after few seconds after I open the game, but she didn't respond anything.

**Comment by ThePotatoGuy** [comment] 2021-12-15 04:54
as mentioned in that other issue you commented in, the gifts were likely under the tree. Currently we don't show any feedback for when gifts are moved to the tree, but #6783 should cover this.

**Comment by JustAskingStuff** [comment] 2021-12-15 07:04
> as mentioned in that other issue you commented in, the gifts were likely under the tree. Currently we don't show any feedback for when gifts are moved to the tree, but #6783 should cover this.

ok then I'll close this issue once she successfully receive the gifts, hope this to get patch up soon!

**Comment by ThePotatoGuy** [comment] 2021-12-26 02:37
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-12-26 02:37 UTC
Labels: not a bug, tree gift
