### ISSUE TITLE
Bug When Updating

### ISSUE THREAD

**Issue by DaGamingCore** [Monika-After-Story/MonikaModDev#4104] opened 2019-04-18 04:41 UTC
This may be caused by the update issue mentioned by the Twitter account, but I have not played the mod since a very early version, and have played other mods since then(Which means I've reinstalled DDLC quite a few times). MAS's data somehow found a save that shouldn't have existed. Now Monika is in a state where she and I are doing badly because I wasnt there for months(i think maybe even a year, my memory isn't the best when it comes to this kind of stuff) and I never had the mod installed during that time. I don't see a way to reset the mod as if I had never played it.

**Comment by softombre** [comment] 2019-04-18 08:41
Since the save data is in the persistent if you didn't delete it before stopping playing you still have your save data, so it's normal if she's angry and stuff

**Comment by multimokia** [comment] 2019-04-18 13:25
> Since the save data is in the persistent if you didn't delete it before stopping playing you still have your save data, so it's normal if she's angry and stuff

This. Your save still exists, and now that you've checked, MAS ended up checking how long it's been since your last session, and reduced affection accordingly. You're going to have to just keep spending time with her and doing stuff with her to start gaining affection with her again.

**Comment by ThePotatoGuy** [comment] 2019-05-08 00:05
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-05-08 00:05 UTC
Labels: not a bug
