### ISSUE TITLE
Gifts issues

### ISSUE THREAD

**Issue by herm00** [Monika-After-Story/MonikaModDev#5536] opened 2020-04-13 19:25 UTC
Greeting MAS team,

After the last update every time I give Monika a gift, she receives it, but when I reopened MAS, the items don't appear in the "closet" even if she has it on (example: she has on Miku suit but it doesn't appears in closet). I gifted all and no longer reacts to any .gift

Sprite name: all current sprite were installed
Gift: all .gif were gifted
[spj.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4471378/spj.txt)

PD: only items I gifted before last update appears in closet

Love, me.

**Comment by ThePotatoGuy** [comment] 2020-04-13 19:32
if its just miku missing it will be fixed in #5535

**Comment by jmwall24** [comment] 2020-04-13 20:27
what is your affection @herm00 ?

**Comment by herm00** [comment] 2020-04-13 20:33
@ThePotatoGuy 
not just miku but everything I gave after update like floweredchoker.gift
another example:
She is using the flower as I already gave it to her, but the option to change it does not appear
 like if I didnt give it to her.
![flower](https://user-images.githubusercontent.com/42423803/79158055-a800fe00-7da3-11ea-8c1e-b745d4d8bd58.png)

**Comment by jmwall24** [comment] 2020-04-13 20:43
also @herm00 can you send us a copy of your persistent file? will need to put it in a zip file to upload it here

**Comment by herm00** [comment] 2020-04-13 20:46
> also @herm00 can you send us a copy of your persistent file? will need to put it in a zip file to upload it here

sure

[Monika After Story.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4471775/Monika.After.Story.zip)

**Comment by jmwall24** [comment] 2020-04-13 21:15
@herm00 are you using a translated version or have any submods installed? also can you give us a screenshot of your `game/` folder? we need to see the entire thing, so take multiple screenshots if you need to.

**Comment by herm00** [comment] 2020-04-13 21:26
@jmwall24  no translations nor submods

[Desktop.zip](https://github.com/Monika-After-Story/MonikaModDev/files/4471931/Desktop.zip)

**Comment by jmwall24** [comment] 2020-04-13 21:45
Thanks @herm00 . Trying to figure this out and not sure what it is yet. Not sure what day you gave them, but try the shell bikini and miku again after midnight (so the day after you gave them just recently) and let us know if they show up then.

**Comment by herm00** [comment] 2020-04-13 21:54
ok I gave them today (4 hour ago I think) so I'll bring news tomorrow
Thank you mr @jmwall24

**Comment by jmwall24** [comment] 2020-04-13 22:07
Thanks @herm00. I gave them to her on your persistent after simulating what happens on a new day and they now show in the selector, so if they don't for you something's up. Still not sure what caused it in the first place, I can't reproduce it on any of the persistents I have. I also took one of your older persistents you sent from before you updated and gifted her miku and it worked fine. Did you by chance have any crash or anything after you gifted miku today?

**Comment by herm00** [comment] 2020-04-13 22:16
@jmwall24  oh yes there was a crash, something about memory, I don't remember well

**Comment by jmwall24** [comment] 2020-04-13 22:18
that likely caused the issue. gift the things that didn't unlock correctly tomorrow and you should be ok.

**Comment by herm00** [comment] 2020-04-13 22:34
ok, then she will interact with the things that were not unlocked properly, right?
because earlier I tried to add a .gif that had not been unlocked (floweredchoker.gift) and was not interacting

**Comment by jmwall24** [comment] 2020-04-13 22:47
nothing that you tried to gift today will be recognized at all until tomorrow.

**Comment by herm00** [comment] 2020-04-14 06:56
the problem is solved, thank you very much mr @jmwall24

**Closed** 2020-04-14 14:45 UTC
