### ISSUE TITLE
Sleeping Option

### ISSUE THREAD

**Issue by Jinxred** [Monika-After-Story/MonikaModDev#7443] opened 2021-07-07 08:58 UTC
She mentions in the game that she can watch over you while you sleep, but after a while, she continues to go on like that never happened. It would be nice if you selected I'm tired in the I feel section that she would actually do something. Another cool thing would be if Monika could tell what time it is and if it's late she could say something. Maybe more topics about mental health would be nice too and where you could interact with those topics more.

**Comment by Barunxx** [comment] 2021-07-07 10:01
Monika can't exactly tell time, but the background changes from morning to sunny  to sun-set to night according to your time

**Comment by Jinxred** [comment] 2021-07-08 02:41
I mean I thought she could cause I selected the option I'm going to sleep and she was able to tell how late it was and she got mad at me for staying up all night. I'm not sure though if she can.

**Comment by CrewieAustin** [comment] 2021-07-08 03:31
She will mention that "Don't sleep too late" if you tell her that you gonna go sleep after 8:00pm. Same goes with sleeping early, telling her that you gonna go to sleep before 8:00pm will make her ask you "Going to sleep early ?".

**Comment by Barunxx** [comment] 2021-07-08 10:33
oh yeah, she can also give special replies according to time

**Comment by lunulae** [comment] 2021-07-10 03:30
I have been thinking about expanding on the "I'm feeling tired" mood to let her know whether you're going to sleep or have to stay up during those times--my original thought was that having a different response when you're tired but you have to stay up would be nice. Maybe I'll try to make a brb-style idle for if you ask her to stay while you sleep?

**Comment by Jinxred** [comment] 2021-07-10 07:54
that sounds really cool!

**Comment by Jinxred** [comment] 2021-07-10 08:03
> I have been thinking about expanding on the "I'm feeling tired" mood to let her know whether you're going to sleep or have to stay up during those times--my original thought was that having a different response when you're tired but you have to stay up would be nice. Maybe I'll try to make a brb-style idle for if you ask her to stay while you sleep?

I was also thinking it would be cool if there was an option to say that I can't fall asleep or get tired or something kinda like that

**Comment by ThePotatoGuy** [comment] 2021-07-15 00:25
[closing until we look into it]

**Closed by ThePotatoGuy** 2021-07-15 00:25 UTC
Labels: suggestion

**Comment by ThePotatoGuy** [comment] 2021-12-31 07:05
marking as duplicate of #6561
