### ISSUE TITLE
A bug in the History option

### ISSUE THREAD

**Issue by Tychoke** [Monika-After-Story/MonikaModDev#7994] opened 2021-10-04 21:52 UTC
I don't think those two last texts should be there.

![screenshot0029](https://user-images.githubusercontent.com/88991144/135929610-bacd9628-d223-4504-9878-0285814905af.png)
![screenshot0030](https://user-images.githubusercontent.com/88991144/135929616-d726efa5-5419-466b-9cd5-9c01cee64ff8.png)

**Comment by Booplicate** [comment] 2021-10-05 09:52
There seem to be no mistake in our code. I'm not sure what caused that for you.

**Comment by ThePotatoGuy** [comment] 2021-10-10 20:51
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2021-10-10 20:51 UTC
