### ISSUE TITLE
I have no clue how to fix this? [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Pugamapish** [Monika-After-Story/MonikaModDev#5123] opened 2019-12-18 03:34 UTC
I get stuck with this every time i try to open the game:
While running game code:
  File "game/script-ch30.rpy", line 1496, in script call
  File "game/event-handler.rpy", line 2065, in script call
  File "game/script-holidays.rpy", line 1922, in script
  File "game/script-ch30.rpy", line 1496, in script call
  File "game/event-handler.rpy", line 2065, in script call
  File "game/script-holidays.rpy", line 1922, in script
IOError: [Errno 13] Permission denied

I even tried reinstalling but it doesn't work.

**Comment by multimokia** [comment] 2019-12-18 03:36
Where is your install located?

**Comment by Pugamapish** [comment] 2019-12-18 03:43
> Where is your install located?

The desktop

**Comment by multimokia** [comment] 2019-12-18 03:44
Are you on mac?

**Comment by Pugamapish** [comment] 2019-12-18 03:45
> Are you on mac?

Linux, is that the problem?

**Comment by multimokia** [comment] 2019-12-18 05:09
Hmm, you may have some file permissions on your desktop preventing it

**Comment by Pugamapish** [comment] 2019-12-18 12:43
> Hmm, you may have some file permissions on your desktop preventing it

Really? cause this is the only mod that does this.

**Comment by multimokia** [comment] 2019-12-18 12:56
MAS tries to create files/folders in its install when you load it for the first time, which is why other mods don't do this.

Your error seems to state that it doesn't have the permission to create in its own directory

**Comment by Pugamapish** [comment] 2019-12-18 21:00
What I don't get is this worked before to the point where I'm far past the beginning. I just opened the game one day and bam this error.

**Comment by ThePotatoGuy** [comment] 2020-01-03 03:33
the line with the error indicates that the new art assets could not be read by the game. A quickfix would probably be to ensure that all the sprites in MAS have at minimum read perms.

**Comment by ThePotatoGuy** [comment] 2020-02-03 00:29
[closing as could not reproduce]

**Closed by ThePotatoGuy** 2020-02-03 00:29 UTC
