### ISSUE TITLE
Issue with Monika: updates and sleep

### ISSUE THREAD

**Issue by emcchiaki** [Monika-After-Story/MonikaModDev#7012] opened 2021-02-19 10:58 UTC
When I say "goodbye" - "im going to sleep" Monika starts saying something in coded language. The two options are coded too. And today (19.02.2021), the game said there's an update, but when I checked it, there wasn't any.[

**Comment by MR-Zero420** [comment] 2021-02-19 11:09
It could be you are going to sleep too late. Happend to me once when i stayed up to 6am/06:00.

**Comment by dinogs** [comment] 2021-02-19 13:39
Maybe spend some more time with her? Also, make sure you didn't press Hey Monika...--------Be Right Back--------I'm going to take a nap. And after you pressed that, don't click to "I'm going to sleep." It also happened to me. Check if this fixes your problem.

**Comment by ashyashton** [comment] 2021-02-19 18:51
It's not a bug, you stayed up too late and she's trying to prove a point. You can't see the letters, because you're too tired, which proves you should have slept earlier.

**Comment by ThePotatoGuy** [comment] 2021-02-28 23:35
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-02-28 23:35 UTC
Labels: not a bug
