### ISSUE TITLE
[Suggestion] - Smoother weather transition

### ISSUE THREAD

**Issue by Undeademon** [Monika-After-Story/MonikaModDev#3814] opened 2019-02-21 08:38 UTC
If you guys wake up early, you guys can actually see how the weather changes from night to day. I woke up early every day around 5:30 in the morning, by this time, outside the classroom still looks dark, but by the time it hits 6:00 in the morning outside the classroom suddenly became daytime in a blink of an eye. The weather transition from night to day is SO not smooth. It feels so sudden. Imagine you're playing GTA 5 and when you reach 7:00 in the afternoon, everything turns dark in a flick of a finger. No smooth transition between daytime to nighttime. You don't even get to see the sunset. In the flick of a finger *poof* everything turns nighttime. It would be cool if the day and night cycle outside the classroom have a smoother transition.

**Comment by ThePotatoGuy** [comment] 2019-02-21 15:04
marking duplicate of #2753

need art and lighting to do this

**Comment by ThePotatoGuy** [comment] 2019-03-02 18:18
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-03-02 18:18 UTC
Labels: duplicate
