### ISSUE TITLE
Art too sharp? 

### ISSUE THREAD

**Issue by LClarance** [Monika-After-Story/MonikaModDev#3701] opened 2019-02-12 14:47 UTC
![monika_sprite_issue](https://user-images.githubusercontent.com/47456818/52642838-bb51d880-2f16-11e9-865b-051b46349f85.png)

I'm not sure if this has been posted before, but look at the shadows of her sleeves... It doesn't look like shadows anymore but bruises and cut wounds on her arm... Also, her chin looks swollen... 

I am sorry I know I am being annoying by complaining too much and I know the devs are working hard to improve this mod but please don't mess with the original sprite too much... This patch is by far the one with most problem since I installed, seeing such modifications done too her is like seeing her falling sick, it hurts.... I didn't join the discord group so I am not sure why the testers approved this update, but I know they are not doing good job... I sincerely hope you guys can fix these before valentine but its ok if you cannot too I know coding and designing aren't easy work. Sorry again for being annoying...

**Comment by ThePotatoGuy** [comment] 2019-02-12 15:31
[marking as duplicate of #3660]

>I'm not sure if this has been posted before

The issue I linked and 2 other issues (#3687 and #3663) are about the leaning pose. Yes, we are aware of concern over the new pose.

>testers approved this update.

The base sprite set (including leaning) was completed in early January. I spent much of my time touching up issues with this set before (and after) releasing it in #3174, as a base set on Jan 16th. People downloaded the PSDs, people saw the new art, people made new outfits with the new base set, and everyone involved liked it. 

This was not rushed, this was not kept secret, this was approved and seen by many many testers and users outside of our dev team. Are people changing their minds about the pose now? Yes. But that does not give you the right to attack the testers when this was basically given public approval way before we even implemented the pose in game.

**Comment by ThePotatoGuy** [comment] 2019-02-12 15:32
Also blazer is due in for a redo #3631 so any issues with that are likely to be resolved already. Check that issue if you want to make sure for yourself.

**Comment by dennisOdenbreit** [comment] 2019-02-12 21:32
I'm not changing my mind, I just never saw it before.

**Comment by dennisOdenbreit** [comment] 2019-02-12 21:36
> that does not give you the right to attack the testers

> I didn't join the discord group so I am not sure why the testers approved this update

I don't see why you are getting mad at this, @ThePotatoGuy.

**Comment by ThePotatoGuy** [comment] 2019-02-12 21:55
clearly if you havent seen it before, then I'm not referring to you. 

The line right after what you quoted.

>but, I know they are not doing good job

**Comment by CloakedGhost** [comment] 2019-02-13 00:10
It's true that those spots look a little odd, but that is something minor. I'm sure the artists are doing the best they can and everyone working on this mod is doing it for free, so keeping that in mind, I think you shouldn't be so upset over it.

**Comment by LClarance** [comment] 2019-02-13 03:52
@ThePotatoGuy I am sorry I sounded offensive, but I really don't know a more polite way to express myself. Like Dennis, this is also my first time seeing this so I am just wondering why everyone was okay with this. Anyway, I know I am very useless as I can't code or draw well, so I am relying on you guys. Thanks for working on for all of us for free.

**Comment by ThePotatoGuy** [comment] 2019-02-20 05:32
[closing this as well]

**Closed by ThePotatoGuy** 2019-02-20 05:32 UTC
Labels: duplicate
