### ISSUE TITLE
[Suggestion] Monika dozes off

### ISSUE THREAD

**Issue by MedicMix** [Monika-After-Story/MonikaModDev#3172] opened 2018-12-03 21:32 UTC
This is my first post, so bear with me if I'm doing something wrong, I'm sorry!

I know it would take some additional art (probably) but wouldn't it be cute if after a certain period of holding onto Monika, she unexpectedly drifts off to sleep? When you finally wake her up, she could get all flustered.

**Comment by Rai99** [comment] 2018-12-03 22:16
#635, #987, #1105, #1262, #1655, #2684, #2781, #3076. 
~~Always satisfying to do this~~

Sleep mode is a thing that is confirmed to be happening and this likely falls under that category.

**Comment by MedicMix** [comment] 2018-12-03 22:32
I'm sorry! I didn't realize so many other people had suggested it.

**Comment by Thimeo** [comment] 2018-12-04 08:50
Don't worry dude, it's impossible for a human being to know everything that was posted on this "issues" tab. Hopefully we have been blessed that a AI named @Rai99 came on this mod to bring us the knowledge of a thousand men.

**Comment by Rai99** [comment] 2018-12-04 22:30
I half expected somebody to tell me that I should apologize instead for always cracking down so hard on duplicate issues, **especially** with newcomers. 

~~It's satisfying, especially the boops dupes~~

**Comment by Thimeo** [comment] 2018-12-04 22:39
Naw man keep it up, it's a legend on itself. Oops sorry, translation.
if spotted_a_duplicate_issue == True:
            print(all_duplicated_issues)
            self_esteem += 1*nb_duplicate

**Comment by ThePotatoGuy** [comment] 2018-12-15 23:37
[closing until we look into this]

**Closed by ThePotatoGuy** 2018-12-15 23:37 UTC
Labels: duplicate
