### ISSUE TITLE
[Suggestion] - Invite Moni to Dinner

### ISSUE THREAD

**Issue by WishStone-Dragon** [Monika-After-Story/MonikaModDev#9046] opened 2022-04-14 20:34 UTC
I think it would be neat to be able to invite Monika to have dinner with us. 

That could be as easy as: 
- An option when saying we're cooking/eating dinner leading to having her ask if she may join the meal
- having one set plate of Salad art to place on her table that she fetches herself randomly if we say we'd like her to join us for a meal

All the way to:
- Invite her on a date that gets set in the calendar as a player set event
- offer to cook for her then gift her the right meal
- have Monika turn on mood lighting/ set up candles
- have dinner conversation elements ("Oh, this XX is really fresh!" "I like how you spiced the XX!" "It's lovely to share a meal with you [player]...")
- meal ends with a promise to do so again sometime

**Comment by ThePotatoGuy** [comment] 2022-05-20 03:13
marking duplicate of #4914 and related. I think a date thing will be separate from the main point of that dev but its related.

[closing as duplicate]

**Closed by ThePotatoGuy** 2022-05-20 03:13 UTC
Labels: duplicate
