### ISSUE TITLE
Suggestion: Letting her know you're going to bed for the night, but not closing the game.

### ISSUE THREAD

**Issue by Nasa128** [Monika-After-Story/MonikaModDev#8502] opened 2021-12-26 03:54 UTC
During certain conversations, Monika will suggest she "watch over you" whilst you sleep. To my knowledge, however, you cannot let her do this and also be "sleeping" at the same time. The next best thing is saying you're napping, but she comments on how you took a long nap.

Long story short, I propose a way to tell her you're going to bed without closing the game.
If this is already a feature I haven't found yet, sorry.

**Comment by AshtonSnapp** [comment] 2021-12-27 22:15
That sounds like a good idea. Possibly. Maybe have it so when you say you're going to sleep she asks if you can keep the game open while you sleep?

**Comment by Nasa128** [comment] 2021-12-28 02:59
@AshtonSnapp That's basically what I had in mind.

**Comment by lunulae** [comment] 2021-12-28 18:28
I've been thinking about adding this to the brb menu, although I'm not sure if it should be a new topic or an adjustment to the existing nap brb. I'm slightly leaning toward the former, but I'd appreciate thoughts.

**Comment by Nasa128** [comment] 2021-12-28 18:42
@lunulae I'd be fine with either, tbh. Whatever is easier would probably be best.
Though @AshtonSnapp had a pretty good idea as well.

**Comment by ThePotatoGuy** [comment] 2021-12-31 07:06
duplicate of #6561. @lunulae if you are planning to add this, reopen #6561

**Comment by ThePotatoGuy** [comment] 2022-01-09 22:07
[closing as duplicate]

**Closed by ThePotatoGuy** 2022-01-09 22:07 UTC
Labels: duplicate
