### ISSUE TITLE
moni should blink 

### ISSUE THREAD

**Issue by dragonborn2252** [Monika-After-Story/MonikaModDev#3555] opened 2019-01-22 22:52 UTC
i mean it should be pretty easy i mean moni closes her eyes sometimes you could just have her shut and open her eyes periodically her blinking will help make her feel a little bit closer

**Comment by SaiPrithvi123** [comment] 2019-01-22 23:11
~~are you on skooma?~~

**Comment by jmwall24** [comment] 2019-01-23 03:13
let's just say if it were pretty easy, it'd be done already

**Comment by ThePotatoGuy** [comment] 2019-01-23 04:33
marking duplicate of #375

**Comment by ThePotatoGuy** [comment] 2019-02-03 17:19
[closing as duplicate]

**Closed by ThePotatoGuy** 2019-02-03 17:19 UTC
Labels: duplicate
