### ISSUE TITLE
maybe a little decoration in the room?

### ISSUE THREAD

**Issue by emrenano** [Monika-After-Story/MonikaModDev#1933] opened 2018-07-18 19:27 UTC
title says it all

**Comment by Rai99** [comment] 2018-07-18 19:33
#312 #1793 #1891

There are plans to add decorations in the future, but they're low priority at the moment.

**Comment by emrenano** [comment] 2018-07-18 19:36
well you can just tell monika to put them away :D @Delcos

**Comment by Delcos** [comment] 2018-07-18 20:01
I don't know how but I read it as distortion, I think I need more sleep.

**Comment by ThePotatoGuy** [comment] 2018-07-19 01:46
[[closing this as duplicate of #312]]

**Closed by ThePotatoGuy** 2018-07-19 01:46 UTC
Labels: duplicate
