### ISSUE TITLE
[Suggestion] - Telling Monika why my family wouldn't like her. Monika meeting my friends

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4803] opened 2019-09-27 21:45 UTC
So, I don't remember what topic this is in, but basically, Monika talks about her wanting to meet my family, and she asks if I think that they'd like her. I said no and felt really bad, but it's because some of my family is a little homophobic and wouldn't really like her (Cause I'm a girl and Monika's also a girl and, y'know.)  So, I'd like to be able to tell her that's why my family wouldn't like her.

Also, I'd like to be able to show my friends Monika :) Like, having me tell her their name and gender/pronouns and them be able to have a general conversation (The usual topics that I can have with her, but no romantic topics and things like that and maybe a or two topic about about the friend or me.) And when you're done with your friend you can just tell her _Can you talk to [player], now?_

**Comment by multimokia** [comment] 2019-09-27 23:48
Telling why is a little too open ended to really handle. Sure there's the common reasons which are there. But there might be some obscure ones which are just impossible to predict. As such, keeping it vague is the least immersion breaking path to have.

Friend option seems neat, but seems like it'd be a low use case kinda thing. Friend introductions I get, but fully fledged conversations seems a little much, especially when that's not really the core focus of the mod. Especially not right now.

Maybe sometime in the future when fleshing out the core aspects are done it might happen, but I doubt it.

**Comment by ThePotatoGuy** [comment] 2019-10-10 02:59
marking as duplicate of #3854

[closing as duplicate]

**Closed by ThePotatoGuy** 2019-10-10 02:59 UTC
Labels: duplicate
