### ISSUE TITLE
[Question?] - Weird and unreadable symbols appear.

### ISSUE THREAD

**Issue by Ulti70895** [Monika-After-Story/MonikaModDev#7669] opened 2021-08-26 04:59 UTC
I crashed my game and when I reopened it, I got a letter from the devs I guess, and then there are 2 options, which I didn't screenshot, appear. One is normal and one consists of unreadable symbols. I have noticed that sometimes options or Monika's dialog contain them, so is that a glitch or intentional stuff?

**Comment by ThePotatoGuy** [comment] 2021-09-04 18:49
[closing as not a bug]

**Closed by ThePotatoGuy** 2021-09-04 18:49 UTC
