### ISSUE TITLE
Bugs when holding Monika

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#4517] opened 2019-08-02 16:20 UTC
I've found a few bugs when holding Monika:
1) The music stops (And you can't change the music)
2) You can't go to the pause menu
3) You can't take a screenshot

**Comment by multimokia** [comment] 2019-08-02 16:21
All of these are fully intended.

**Comment by PollenTheCat** [comment] 2019-08-02 16:23
Okay, thanks

**Comment by ThePotatoGuy** [comment] 2019-08-24 16:19
[closing as not a bug]

**Closed by ThePotatoGuy** 2019-08-24 16:19 UTC
Labels: not a bug
