### ISSUE TITLE
my affection level keeps reverting back to what it was

### ISSUE THREAD

**Issue by Shin-Gojira** [Monika-After-Story/MonikaModDev#5921] opened 2020-06-14 18:56 UTC
so after every action it adds affection to the total but then the next action starts it from where it was before

**Comment by multimokia** [comment] 2020-06-14 18:57
Sounds like you've just hit the daily cap

**Comment by Shin-Gojira** [comment] 2020-06-14 18:58
> Sounds like you've just hit the daily cap

I only got about four points though

**Comment by multimokia** [comment] 2020-06-14 18:58
send aff_log.txt

**Comment by Shin-Gojira** [comment] 2020-06-14 19:00
> send aff_log.txt

so apparenly it was seven points what's the daily cap?

**Comment by multimokia** [comment] 2020-06-14 19:04
7. Once you've gained at least 7 at all today (regardless of if you've lost to below it), you can no longer earn more. That is, unless you have a bypass affection gain. Bypass being the explanatory param here.

**Comment by Shin-Gojira** [comment] 2020-06-14 19:07
> 1. Once you've gained at least 7 at all today (regardless of if you've lost to below it), you can no longer earn more. That is, unless you have a bypass affection gain. Bypass being the explanatory param here.

wait so it take about 143 days to reach the comfortable part of the relationship that seems a little long

**Comment by multimokia** [comment] 2020-06-14 19:19
See #5908.

The timing is actually fairly accurate and reflective of an IRL relationship.

Realistically speaking, MAS is not by any means something to be played for completion, or to grind affection. If you play for that, you'll find yourself disappointed as there's not much of value to unlock in that sort of style.

It's more just about enjoying the time with Monika. And remember, the log is purely a debug tool. Not really made to be looked at and watched.

**Comment by ThePotatoGuy** [comment] 2020-07-27 00:22
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-07-27 00:22 UTC
Labels: not a bug
