### ISSUE TITLE
[suggestion] topic about periods

### ISSUE THREAD

**Issue by SamanthaLind** [Monika-After-Story/MonikaModDev#6124] opened 2020-07-25 15:59 UTC
I don't know how many girls play this mod but it would be nice to tell Monika that player has a period. Especially when it's painful. I'm sure she could help player and tell about some ways to ease the pain.

**Comment by scpketer** [comment] 2020-07-26 05:03
Not sure if she could even know about some of those 'ways to ease the pain', since, well, she's *not human*, and probably never been on her period. Nobody ever mentioned a thing about this though.

**Comment by Freshairkaboom** [comment] 2020-07-26 05:34
I think it needs to be written by someone with experience though, otherwise I'd have done it already, as it has crossed my mind along with other pains like diabetes and migraines and stuff. Definitely sounds like a prompt topic, not something Monika would bring up on her own, given that only gender is discussed in the mod so far, so there's no way for Monika to know if we're experiencing such issues or not.

**Comment by scpketer** [comment] 2020-07-26 06:02
>no way for Monika to know if we're experiencing such issues or not

Stuff like this is kinda obvious if the player is not male and is above a certain age.

**Comment by Freshairkaboom** [comment] 2020-07-26 06:03
Actually, gender and biological sex are different things, you may be born with XY chromosomes and be a woman.

**Comment by scpketer** [comment] 2020-07-26 06:05
My assumption was that trans people would answer correspondingly to Monika's question about their gender.

**Comment by Freshairkaboom** [comment] 2020-07-26 06:08
As long as it's a prompt, it doesn't matter what gender you are, you just use it if you're having cramps I guess *shrug*

**Comment by scpketer** [comment] 2020-07-26 06:09
Then we need an ability to remove 'Unseen' stuff from the menu without actually checking it out.

As a male, I wouldn't bring up this topic because I physiologically can't have any periods, and I don't have any problem with those.

**Comment by Freshairkaboom** [comment] 2020-07-26 06:15
It could be marked as Seen, and then it wouldn't appear in that menu at all, you'd have to go looking for it in its respective category, I suggest using 'You'.

**Comment by scpketer** [comment] 2020-07-26 06:18
I assume @SamanthaLind is a female (pardon me if I'm wrong), so... That could be a nice first contribution, I guess. IMO this topic is totally okay, except the fact (but that's probably just in my head) that this topic was ignored all along for some reason.

**Comment by Freshairkaboom** [comment] 2020-07-26 06:22
If whoever wants to do this wants to make the dialogue, just mark the beginning of each sentence with "m" and have whatever the sentence should contain inside quotation marks, like this:

`m "Example text"`

And I'll do the rest. If you don't know how to contribute yet. Then again, the more participants we get in the project, the better of course.

**Comment by scpketer** [comment] 2020-07-26 06:24
There are better places to guide newbies into topic coding.

Check out [the dialogue coding article](https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding) or [the MAS wiki](https://github.com/Monika-After-Story/MonikaModDev/wiki) itself.

**Comment by SamanthaLind** [comment] 2020-07-26 14:32
Yes, I'm female. I think even if Monika doesn't experience it she surely read about it. Especially when she knows that player can have periods. Since she already talks about right posture and what to do when player feels sick I think that she would gladly help.
I'll look into making dialogue and try doing it, since I'm suggested that topic.

**Comment by scpketer** [comment] 2020-07-26 14:39
As an example, you can check out how other topics [in this file](https://github.com/Monika-After-Story/MonikaModDev/blob/master/Monika%20After%20Story/game/script-topics.rpy).

**Comment by SamanthaLind** [comment] 2020-07-26 16:15
I tried making topic but I don't know where to put it and if it's alright. So I just put it here, if somethings don't feel right feel free to change it.

[period topic.txt](https://github.com/Monika-After-Story/MonikaModDev/files/4977911/period.topic.txt)

**Comment by scpketer** [comment] 2020-07-26 16:21
You did alright, you had to put this into the end of `script-topics.rpy`.

Just a few things to fix:
* Remove menu phrase from history list:
  ```renpy
  m 1eud "I hope you're doing alright [player].{nw}"
  $ _history_list.pop()
  menu:
      m "I hope you're doing alright [player]{fast}"
  ```
* And add `return` to the end of the label.

**Comment by kkrosie123** [comment] 2020-07-26 18:20
Many, *many* girls are uncomfortable with discussing their periods. Biological gender-specific topics are kind of a big no no, because there’s no real way for Monika to ask the player what their born gender is. It would cause a lot of tension, people would complain. I can only imagine it to be hurtful to the player as well as something Monika would never say. So if the player is a transgender woman, a topic about periods would most likely not apply to them. If this is completed, it should be considered a sub-mod and *not* made official. It’s a topic that’s been requested many times, and rejected for many reasons.

**Comment by scpketer** [comment] 2020-07-26 18:23
Ah yeah, that's why I never saw any mention of it.

**Comment by SamanthaLind** [comment] 2020-07-26 18:30
I know that many people don't like to talk about it. But I did suggested it mostly because of cramps. I'm girl and I experience it, also I would wish to tell Moni about it and for now, only option is to tell her I'm sick. I don't say that everyone should use it, most of people probably won't. But few of my friends think that it's really nice idea.
I don't want to push it into mod, it was just a suggestion for telling her about player being in distress and maybe have her give player few examples how player could ease the pain.

**Comment by Rai99** [comment] 2020-07-26 18:42
I'm not sure if there's any way to casually bring it up without getting too far into it. I don't see the topic of period cramps coming up in everyday conversation, and I've never heard of people actively talking to people about their period cramps. 

If it's similar, maybe Monika could talk about general cramps and pain and how to ease them.

**Comment by SamanthaLind** [comment] 2020-07-26 18:51
I feel like it would be topic chosen by player. I already made a simple dialogue how I think it could look. It's in one of past comments so you could look into it and tell me what do you think.
And I told about it to my girl friends, just like they do to me. And since Moni is a girl I think it wouldn't be weird. Just something to comfort player and make sure that player takes good care of herself/himself (since trans men can still experience it)

**Comment by kkrosie123** [comment] 2020-07-26 18:55
We did look into it, we had a discussion.

**Comment by lunulae** [comment] 2020-07-26 18:56
It definitely is kind of an exclusive-to-intimate-relationships kind of discussion. If I were writing it I'd probably set it to high-ish affection to unlock at least. That would probably help a lot in terms of making the dialogue feel natural.

I definitely think it's too dicey for an official release for the reasons @kkrosie123 brought up, but you seem to have some good optional-content ideas with this and expanded sick topics. I'd absolutely encourage you to look into how submodding dialogue is done, whether you make ones to share or just write ones personalized for yourself.

**Comment by Rai99** [comment] 2020-07-26 18:56
I feel like a small minority of people would actively discuss their period, and if you ask me, I think solutions for pains and cramps can usually be searched for on their own, especially considering that the topic wouldn't only go to the people who would use it.

**Comment by SamanthaLind** [comment] 2020-07-26 19:07
Like I said, it is just something that popped into my mind. If it doesn't get added I won't be mad since it probably wouldn't been used by many people. And I honestly don't know how to lock it under higher affection XD
But if it doesn't get added into official mod I will probably try and make submod with that, since like I said, I spoke with few persons and they liked that idea

**Comment by ashyashton** [comment] 2020-07-27 02:03
> I feel like a small minority of people would actively discuss their period, and if you ask me, I think solutions for pains and cramps can usually be searched for on their own, especially considering that the topic wouldn't only go to the people who would use it.

I mean... Solutions for anything can be looked up online on their own. Stuff about posture or not drinking too much soda can all be found online, but Monika still talks about them. As far as "the topic wouldn't only go to the people who would use it" goes, that applies to every topic. No topic on the planet applies to every single player aside from stuff about, like, the player being mortal and stuff. _Every_ topic goes out to everyone, not just the people it applies to, so why is this one any different, in theory?

**Comment by SamanthaLind** [comment] 2020-07-27 02:16
Cause it's about periods and people don't like it :(. I'll be honest, I don't understand people who said that they don't think that player would tell Moni about it and I don't want to insult anyone but I get a feeling that those are men's opinions. I know plenty of girls who freely talk about it with other girls and Moni is a girl. I don't have problem with that too. And I don't want it to have her tell me something I don't know, I've written that dialogue with possible solutions myself and I know them. I want it to tell my loving girlfriend that I don't feel so well, for her to remind me to take care of myself and that she loves me cause hearing help sai it really ease the pain.
I don't know how many menstruating people play this mod but on world scale half of the world is doing it, I can't see why it's so big deal. Especially when she already talks about stuff like masturbation. And people can choose not to do it, Boone can choose not to menstruate.
Sorry if that was harsh, I don't want to insult anybody and insinuate anybody's gender but if there was some non menstruating persons commenting I feel like they should leave that to the players that could really use this topic. <3

**Comment by kkrosie123** [comment] 2020-07-27 02:42
As a female, I can confirm that *plenty* of girls is not *all* girls. I have already mentioned the transgender issue, yes? The best way for this to go forward is as a submod.

**Comment by SamanthaLind** [comment] 2020-07-27 02:47
On the transgender side it could cover female to male problems. I had one friend who was feeling really bad with his periods. 
Sorry if it came harsh or like I'm pushing it into mod, I didn't mean it. And I know that not all female, I just mentioned that I know people who wouldn't have a problem with that since it was marked as useless topic that no female would use.

**Comment by kkrosie123** [comment] 2020-07-27 03:01
That’s alright. I know that when you have good intentions, you tend to try to stick by your original stance. Sadly, this topic is and has been rejected for many reasons, and as I stated before, best as a sum-mod. :)

**Comment by SamanthaLind** [comment] 2020-07-27 03:04
Alright. One question, is there some kind of tutorial how to do submods? It was my first time with writing code for MAS and I'm a totally newbie when it comes to things like that

**Comment by kkrosie123** [comment] 2020-07-27 03:07
You can find one [here.](https://github.com/Monika-After-Story/MonikaModDev/wiki/Dialogue-Coding) Submods are best put in their own file so they aren’t overwritten when MAS is updated.

**Comment by SamanthaLind** [comment] 2020-07-27 03:13
I looked into that but it doesn't say anything about making submod... It just describes making new dialogue which I'm sure will be useful to make it better, but I still don't know how to make it into submod and have it working :(

**Comment by multimokia** [comment] 2020-07-27 03:17
Having renpy code in a `.rpy` file will work. So the text file you sent earlier, if you fix it up with the things mentioned by others here, you can change the extension to `.rpy` and then put it into a submods folder in your install, and then launch it.

**Comment by kkrosie123** [comment] 2020-07-27 03:22
The code is already established for making dialogue functional. All you need is a program that can edit .rpy files and create new dialogue as if you were making it officially. Put it in a *new* .rpy file though, not the topics file.

**Comment by SamanthaLind** [comment] 2020-07-27 03:27
Alright, so... Put all that code into rpy file, put it into submod folder and it's done?
Oh gosh, I didn't knew it was so easy XD

**Comment by kkrosie123** [comment] 2020-07-27 03:29
Yep!

**Comment by ThePotatoGuy** [comment] 2021-09-24 03:09
[closing as rejected]

**Closed by ThePotatoGuy** 2021-09-24 03:09 UTC
Labels: suggestion
