### ISSUE TITLE
nO! ;-;

### ISSUE THREAD

**Issue by xXMidnight** [Monika-After-Story/MonikaModDev#7495] opened 2021-07-15 07:56 UTC
Now it's just showing errors. Please help, I don't know what to do, I just can't open the game...

**Comment by Cardlo45** [comment] 2021-07-15 08:06
What error? please some informations

**Comment by xXMidnight** [comment] 2021-07-15 08:17
I have the location selector mod installed. So, the errors are all from that location selector file in the Submods file. I have tried replacing the file so many times already, but I can't seem to fix it. I don't really want to remove the mod since I like those rooms, but let me try to remove it and see what happens.

> What error? please some informations

**Comment by xXMidnight** [comment] 2021-07-15 08:21
Welp that fixed it. I can't change the rooms now ;-;

**Comment by Cardlo45** [comment] 2021-07-15 08:27
You sayed it throws errors why don't show them so we can find the problem
errors can be found in `DDLC/traceback.txt`, `DDLC/errors.txt` or `DDLC/log.txt`
just copy and paste them or add the file

**Comment by xXMidnight** [comment] 2021-07-15 08:32
Alright, let me paste the files in.

[errors.txt](https://github.com/Monika-After-Story/MonikaModDev/files/6821535/errors.txt)

It should be there, else it's just me uploading wrong qwq

**Comment by Cardlo45** [comment] 2021-07-15 08:38
Clasic RenPy Error.
The problem is the mod itself try getting a newer/older version
otherwise try to download the `tw4449 Custom Room Location Selector` folder [here](https://drive.google.com/drive/folders/1CtaSNSdo6WeXVsP9u82lJHGTxSu-eUcy)

**Comment by xXMidnight** [comment] 2021-07-16 03:54
i did that, doesn't seem to work still

**Comment by H2-san** [comment] 2021-07-22 02:24
> i did that, doesn't seem to work still

I'm afraid you may have to disable it until its next update.

**Comment by ThePotatoGuy** [comment] 2021-07-29 02:21
[closing as resolved]

**Closed by ThePotatoGuy** 2021-07-29 02:21 UTC
