### ISSUE TITLE
[Suggestion] Pictures on the wall

### ISSUE THREAD

**Issue by EntonyEscX** [Monika-After-Story/MonikaModDev#1793] opened 2018-06-22 18:50 UTC
Looking at the calendar on the back wall, it made me have the idea that we could add other things there as well, such as pictures, drawings or photos, maybe not just that, but also other things like a piano or a computer, clicking on them, Monika could have a dialog, as well as the first time we clicked on the calendar.

**Comment by jmwall24** [comment] 2018-06-22 20:14
The piano could even replace the play piano button by having clicking on the piano open the piano game.

**Comment by Rai99** [comment] 2018-06-22 20:42
I don't think there's much space to put things in the room other than on the 2 protruding walls next to the windows. If anything covers the window, we would need new sprites accounting for the shadows of the object. 

I'm not sure what images would be suitable to put on the wall. If they're built into the mod, some people might not like what's pre-placed on the wall and if it's just some generic picture, there wouldn't be much to say about it. 

What I'm thinking is if we had some empty picture frames on the wall and the player could somehow put their own by having a folder to put images in and give them a certain name. The only issues this might have is that dialogue can't be written for these since they could be literally anything, unless we write 
 generic dialogue for the empty frame (ie. Monika telling you that you can put anything in the frame ). There would have to be a way to make sure the image would fit in the frame, but the dimensions could be given and left up to the player to make it fit. This might also take a bit of work to implement but these are my thoughts. 

Also personally, if a piano is added somewhere in the room, I'm not sure where it would fit best. Probably on front of one of the windows but I personally don't think a piano would look nice there. I think this idea would fit in with room customization when or if it becomes a thing.

**Comment by ThePotatoGuy** [comment] 2018-06-24 05:48
Going to close this as a duplicate of #312.

Adding room decorations is something we are going to do, and with calendar, we know how to do it now.

**Closed by ThePotatoGuy** 2018-06-24 05:48 UTC
