### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CreepFort** [Monika-After-Story/MonikaModDev#3911] opened 2019-03-05 14:48 UTC
![screenshot0638](https://user-images.githubusercontent.com/44503785/53813378-cfa95400-3f5d-11e9-8b7e-10796d59b625.png)

**Comment by ThePotatoGuy** [comment] 2019-03-05 16:49
marking as duplicate of #3694

**Closed** 2019-03-05 18:17 UTC
Labels: duplicate
