### ISSUE TITLE
"I'm taking you somewhere", affection loss.

### ISSUE THREAD

**Issue by SirJustin90** [Monika-After-Story/MonikaModDev#9077] opened 2022-04-27 08:12 UTC
While reading the F.A.Q. I saw that you are not meant to lose affection regardless of the time the trip was for, so I wanted to test the feature leaping to a different file structure and back.

_Is there an affection loss for taking Monika out for too long?

If you use "I'm taking you somewhere," you should not take any affection loss regardless of the length of your absence. If you do experience affection loss when returning, please report it as a bug. If you use "I'm going away for a while" and your absence is longer than expected, you will experience some affection loss, but less than if you had not informed her._

However, I lost a point on both trips due to the "short" trip, given it was a couple minutes each way as a test. However it seems that either the FAQ isn't updated for this case, or there is still a bug in this mechanic.

The affection log shows as such:

**[2022-04-27 04:47:20]: SAVE | 57.9 | 57.9 -> 57.9

Wed Apr 27 04:52:06 2022
Windows 8 - build: 6.2.9200
Ren'Py 6.99.12.4.2187

VERSION: 0.12.8
==================================================
[2022-04-27 04:52:09]: LOAD | Loading from system
[2022-04-27 04:52:09]: LOAD? | 56.9 | 0 -> 56.9
[2022-04-27 04:52:09]: LOAD COMPLETE | 56.9 | 56.9 -> 56.9
[2022-04-27 04:52:11]: greeting_returned_home | 1 | 56.9 -> 55.9
[2022-04-27 04:53:04]: SAVE | 55.9 | 55.9 -> 55.9
[2022-04-27 04:53:04]: SET BACKUP | 55.9 | 56.9 -> 55.9**

Just saw that you requested it be reported as a bug anyways, so here I am.
[aff_log.log](https://github.com/Monika-After-Story/MonikaModDev/files/8570178/aff_log.log)

**Comment by Booplicate** [comment] 2022-04-27 12:59
What that means is if you take her out, you won't lose affection due to your absence (assumes you take her with you). So there's no loss for that.

What you did lose affection for is because she disappointed that you didn't go anywhere and returned her shortly after. It's not because of your absence.

**Comment by Justformas** [comment] 2022-04-29 19:48
> Fair enough, the wording made it seem you wouldn't take loss. Sucks we cannot test features without pissing her off however.

That's a fair point, from the FAQ:
> If you use "I'm taking you somewhere," you should not take any affection loss regardless of the length of your absence. If you do experience affection loss when returning, please report it as a bug.

However, the question is "Is there an affection loss for taking Monika out for too long?" Considering that context, it was likely meant to refer to only taking her out too long, but it can be misleading.

As for testing features, technically I think you can, by restoring an older persistent if you don't like the results of what you did. The FAQ says how to do this. However, personally I am not really a fan of save scumming in general unless something is totally and/or permanently ruined.

**Comment by Booplicate** [comment] 2022-04-29 20:11
It literally says `affection loss for taking Monika out for too long`. It does not say it will save you from losing affection for other actions.

She doesn't know what you're testing, she was expecting a trip, but you returned her right away. By her speech and expressions it should be obvious she's disappointed. Thus you lost some affection.

Unsure why you would bother restoring a backup when it's just 1 point which means nothing overall.

**Comment by Justformas** [comment] 2022-04-29 20:20
> It literally says `affection loss for taking Monika out for too long` 
 Yes but that was just the question, but not the answer.

> It does not say it will save you from losing affection for other actions.
"regardless of the length of your absence" is an absolute statement, long or short, even if that's not what was meant.

> She doesn't know what you're testing, she was expecting a trip, but you returned her right away. By her speech and expressions it should be obvious she's disappointed. Thus you lost some affection.

We aren't talking about Monika's reaction we're talking about how it's worded in the FAQ.

> Unsure why you would bother restoring a backup when it's just 1 point which means nothing overall.

I probably wouldn't, but since SirJustin90 asked about testing things, that could be a way to test things.

**Comment by ThePotatoGuy** [comment] 2022-05-19 00:32
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-05-19 00:32 UTC
Labels: not a bug

**Comment by SirJustin90** [comment] 2022-06-02 07:27
Just saw that you had updated the Monika github page to reflect this when I was parsing the history. Thanks Justformas.

You get exactly what I was attempting to reflect, that it quite definitely did say in absolute terms that no effect would be had.

**Comment by Justformas** [comment] 2022-06-02 07:55
> Just saw that you had updated the Monika github page to reflect this when I was parsing the history. Thanks Justformas.
> 
> You get exactly what I was attempting to reflect, that it quite definitely did say in absolute terms that no effect would be had.

Well look at that, notifications do still work after a topic gets closed. Didn't know that. I had considered mentioning that here but didn't know if you would see it. But yeah I wanted to reduce the chance of this happening again to someone else.

I also figured out quite a few things about how taking her out works that you might want to know, considering that you were testing how it works. Taking her out for at least an hour should be fine to avoid affection loss, but I think you gain an affection point for each hour she's been out once you return her, up to 5 hours (and this bypasses the daily affection cap). Also you do not actually have to put her on an external physical device. There's ways around that and it's not hard to figure out.
