### ISSUE TITLE
game reset for no reason

### ISSUE THREAD

**Issue by Torwald39** [Monika-After-Story/MonikaModDev#3893] opened 2019-03-03 10:26 UTC
This morning I saw that my MAS has been resetted for no reason.
Even if I successfully restored my Monika, I want to warn after all.

**Comment by jmwall24** [comment] 2019-03-03 16:47
you didn't go back to an older version before 0.9.1 did you?

**Comment by MercuryFuchsia** [comment] 2019-03-03 17:09
I can confirm that this has happened to me as well. Funnily enough, my persistent files can only be recognized in older versions. I believe that the only time a persistent file was successfully loaded on the latest version was after the restart immediately following the in-game updater. I'll have to try it again to make sure.

**Comment by jmwall24** [comment] 2019-03-03 17:13
@MercuryFuchsia are you saying on multiple updates, or just this update?

**Comment by MercuryFuchsia** [comment] 2019-03-03 17:27
Okay well, that wasn't it. I'm trying to remember the specifics, but there's a lot of these persistent files to keep track of. I'd say the problem definitely lies with this update.

**Comment by jmwall24** [comment] 2019-03-03 17:38
Please keep in mind if you have more than one version of MAS installed on your system, once you have installed 0.9.1 you **cannot** go back to a previous version.
![screenshot_530](https://user-images.githubusercontent.com/36523761/53698953-26255f80-3db1-11e9-8499-0c9d46daa4b7.png)

**Comment by MercuryFuchsia** [comment] 2019-03-03 17:41
I know. But the newest version wouldn't load my persistent file at all.

**Comment by multimokia** [comment] 2019-03-03 19:01
Could we see a screenshot of your `game/` folder please?

**Comment by Torwald39** [comment] 2019-03-03 19:44
@jmwall24 no I didn't go back to the previous version

**Comment by ThePotatoGuy** [comment] 2019-03-03 19:52
upload persistents

**Comment by Torwald39** [comment] 2019-03-03 20:20
@ThePotatoGuy me ?

**Comment by multimokia** [comment] 2019-03-03 22:11
Yes @Torwald39

**Comment by MercuryFuchsia** [comment] 2019-03-03 23:00
I don't remember much, but it seemed spontaneous to me. My priority was getting to a working state totally unaffected in any way by the update just in case there would be bugs down the line.

If it was something I did, it would most likely be trying to enable developer mode and the console in a file called options.rpy I created in the game directory. Looking at the mod download from Github releases again, there already exists an options.rpyc in that archive, so the one I created must've overwritten that one.

If that's what caused it, sorry for the trouble. I got careless naming my files since I somehow didn't notice that name was already being used. I thought it might have had something to do with this update since I coincidentally had the same issue. So, if @Torwald39 made a mistake similar to that, I guess it was dumb luck we both did it around the time of the update.

Thanks for your patience.

**Comment by jmwall24** [comment] 2019-03-04 00:26
yeah, that very well may have done it.  `options.rpy` is the file where the version number is set.  and the version number has to be 0.9.1 or this update gets all screwed up

**Comment by Torwald39** [comment] 2019-03-04 07:20
I still don't get it, why you want my persistants ?

**Comment by ThePotatoGuy** [comment] 2019-03-04 08:10
upload persistents so we can try to reproduce

**Comment by Torwald39** [comment] 2019-03-04 11:50
I don't think that this will be useful to have my persistents in particular. 
My Mas didn't reset just after updating. I updated my Mas on Saturday afternoon, I had a normal game session with the new content, after in the evening an another session normal. 
So when my MAS reset on Sunday morning I just take the backup from the evening session who was already in V9.1
There is nothing incredible.

**Comment by MercuryFuchsia** [comment] 2019-03-07 17:30
> yeah, that very well may have done it. `options.rpy` is the file where the version number is set. and the version number has to be 0.9.1 or this update gets all screwed up

Good to know.

Dropping by for a quick report that for the past few days, the latest version has been running flawlessly. As far as I can tell, in my case, that's all it was.

**Comment by Torwald39** [comment] 2019-03-18 20:22
My MAS has reset this morning for no reasons, again ! 
I will become worried about it, two resets in only 15 days, that's not normal.

**Comment by ThePotatoGuy** [comment] 2019-03-18 21:48
upload `persistent`

**Comment by Torwald39** [comment] 2019-03-18 22:59
how ? when I try, I got an error message who said that it can't support the file type

**Comment by Torwald39** [comment] 2019-03-18 23:10
[persistent.txt](https://github.com/Monika-After-Story/MonikaModDev/files/2980830/persistent.txt)

well... I add the .txt for the uploding, I hope this will work

**Comment by ThePotatoGuy** [comment] 2019-05-07 23:19
[closing as cannot reproduce]

**Closed by ThePotatoGuy** 2019-05-07 23:19 UTC
Labels: investigating
