### ISSUE TITLE
[Bug] Unable to bookmark Floating Islands topic

### ISSUE THREAD

**Issue by PollenTheCat** [Monika-After-Story/MonikaModDev#5082] opened 2019-12-08 23:00 UTC
When in the 'Can you show me the floating islands?' topic, pressing 'b' doesn't bookmark the topic like it should. Bookmarking other topics works fine, but I'm unable to bookmark the Floating Islands topic.

**Comment by RavenPLAYER** [comment] 2019-12-08 23:05
It's not a bug, I don't understand why we can't bookmark the floating islands, but it's normal don't worry. (Unless actually IS a bug)...

**Comment by lunulae** [comment] 2019-12-08 23:15
I think that before it was to keep it from being unlocked during weathers where they weren't viewable. Since they're unlocked for different conditions now, we might see a change, but I'm not sure.

**Comment by jmwall24** [comment] 2019-12-08 23:34
Nah, that wouldn't have mattered. Locked events, even if bookmarked, won't show up when locked. It's because of how we decide what can be bookmarked. Fix forthcoming.

**Comment by multimokia** [comment] 2019-12-09 15:05
Closing as completed in linked PR

**Closed by multimokia** 2019-12-09 15:05 UTC
Labels: bug
