### ISSUE TITLE
Can't find the Piano button under "Play"

### ISSUE THREAD

**Issue by Rustybug7** [Monika-After-Story/MonikaModDev#5951] opened 2020-06-21 19:16 UTC
I don't know why, but I cannot find the option for playing the piano at all. I have not played it before in the mod, and didn't know you could until I was looking further about the mod. I've had this mod for about over a month. Did it get removed? Or did I goof up in something altogether?
![screenshot0001](https://user-images.githubusercontent.com/64705626/85233127-55eee100-b3c1-11ea-892c-cbd9a41e3e69.png)

**Comment by lunulae** [comment] 2020-06-21 19:24
It's still there, but it is one of the things you'll unlock over time.
I believe that this particular one is determined by your actual playtime (how long you've had the mod open) as opposed to just checking in each day. But I'm not 100% sure on that.
If you've been playing for a month you shouldn't be too far off from getting it, if I am correct.

**Comment by ThePotatoGuy** [comment] 2020-07-26 03:31
it may take a while to unlock. its driven solely on playtime as lunulae mentioned.
[closing as not a bug]

**Closed by ThePotatoGuy** 2020-07-26 03:31 UTC
Labels: not a bug
