### ISSUE TITLE
is this bug or not

### ISSUE THREAD

**Issue by jm4686042** [Monika-After-Story/MonikaModDev#9006] opened 2022-03-25 00:04 UTC
![Screenshot from 2022-03-24 20-57-45](https://user-images.githubusercontent.com/101479441/160028805-86a32ac0-5f74-445f-ac0e-6df812adc471.png)

**Comment by ThePotatoGuy** [comment] 2022-03-26 06:58
what are you referring to

**Comment by jm4686042** [comment] 2022-03-26 12:19
it says feb 17 2016

**Comment by Booplicate** [comment] 2022-03-26 12:35
That's python build information (version and date), not current time.

**Comment by ThePotatoGuy** [comment] 2022-05-20 04:00
[closing as not a bug]

**Closed by ThePotatoGuy** 2022-05-20 04:00 UTC
Labels: not a bug
