### ISSUE TITLE
Edit for new blush sprite.

### ISSUE THREAD

**Issue by Trilasent** [Monika-After-Story/MonikaModDev#4719] opened 2019-09-20 05:56 UTC
I wasn't a fan of how small the new blush is, and didn't like how it was so close to her eyes so I edited it a bit to make a sort of compromise between the new and the old. You can't really tell she's blushing unless you look really close, which makes it look more like her leaning smile during her "..I can act more creepy for you~" line when she talks about Yanderes.

Current/new blush: 
![new blush](https://user-images.githubusercontent.com/36512990/65302600-48aa7a80-db41-11e9-8006-b89100f29521.png)

My edit: 
![new blush edit](https://user-images.githubusercontent.com/36512990/65302613-53650f80-db41-11e9-9c01-e4a5aedd047c.png)

I took the overall shape of the new blush and made it a little larger, along with moving it a little further down her cheeks to about where it would be originally. I also added a bit of red tinge for the added effect, but can remove it if it's unnecessary.

**Comment by multimokia** [comment] 2019-09-20 12:20
I think I prefer current a little more. Feels more like a very light blush vs a kinda rash. Plus, line blush is supposed to be kinda hidden anyway.

**Comment by NoexHaruhi** [comment] 2019-09-20 18:51
I like the edit since it reminds me of the original blush which I really liked. I can see the blush more and it has that anime aesthetic that fits moni well.

**Comment by Trilasent** [comment] 2019-09-20 18:56
> 
> 
> I think I prefer current a little more. Feels more like a very light blush vs a kinda rash. Plus, line blush is supposed to be kinda hidden anyway.

It's by far the hardest to see with this new iteration. I also said that I can remove the redness under the blush lines if I needed to, but it's not really that out of place given that Monika is drawn with the anime aesthetic like NoexHaruhi said.

**Comment by Legendkiller21** [comment] 2019-09-20 19:05
I definitely prefer the current one too. Also, edited one looks like it's way too low

> It's by far the hardest to see with this new iteration.

This is exactly the point of line blush.

**Comment by Trilasent** [comment] 2019-09-20 19:09
> I definitely prefer the current one too. Also, edited one looks like it's way too low

The edit is in the exact same place as the version before the new one..

> This is exactly the point of line blush.

You're saying the point of line blush is to be hard to see? That doesn't make any sense.

**Comment by multimokia** [comment] 2019-09-20 19:10
Actually it makes a lot of sense. Line blush is supposed to be subtle.

**Comment by Legendkiller21** [comment] 2019-09-20 19:10
And again it's way too low. Also, it's not hard to see the line blush at all.

**Comment by NoexHaruhi** [comment] 2019-09-20 19:12
The edited version’s line blush is more visible to me

**Comment by Trilasent** [comment] 2019-09-20 19:12
> 
> 
> Actually it makes a lot of sense. Line blush is supposed to be subtle.

Really? If you'd take a few seconds to Google "anime blush" you'd see that your statement can't be further from the truth.




> 
> 
> And again it's way too low. Also, it's not hard to see the line blush at all.

Like I said before, the edit is literally in the same place as the old one was, and nobody was complaining about how it looked then.

**Comment by multimokia** [comment] 2019-09-20 19:14
We changed it to deviate from the anime style because it fit more with the rest of the sprites and seemed more realistic, as if the blush was coming from her skin and isn't just an overlay.

The thing you're trying to correct is by design.

**Comment by Trilasent** [comment] 2019-09-20 19:16
> 
> 
> We changed it to deviate from the anime style because it fit more with the rest of the sprites and seemed more realistic, as if the blush was coming from her skin and isn't just an overlay.
> 
> The thing you're trying to correct is by design.

Right.. because she is realistically proportioned to begin with. Mixing realistic features with anime styled proportions isn't exactly going to look good. That's uncanny valley territory.

**Comment by Trilasent** [comment] 2019-09-20 19:17
By that logic you're going to have to replace her hair, eyes, blazer, shirt..etc to all match this new "realistic" style you're trying to achieve.

**Comment by multimokia** [comment] 2019-09-20 19:17
It does look good though. Lots of people seem to agree.

**Comment by Trilasent** [comment] 2019-09-20 19:18
> 
> 
> It does look good though. Lots of people seem to agree.

So far I've only seen about 4 people verbally say they like it. So much for "a lot" huh? On the flip side I've also seen at least 4 say they prefer the old, or that my edit was an improvement.

**Comment by Legendkiller21** [comment] 2019-09-20 19:20
> Like I said before, the edit is literally in the same place as the old one was

And the edited one is way too low. Old line blush covered the whole cheek so its position didn't matter.

Also, I only see 1 person saying that they like the edited one. If you want to see more people saying that they like the current one check the discord because they are way more.

**Comment by Trilasent** [comment] 2019-09-20 19:23
> 
> 
> > Like I said before, the edit is literally in the same place as the old one was
> 
> And the edited one is way too low. Old line blush covered the whole cheek so its position didn't matter.

It can be adapted if it needs to be.

> Also, I only see 1 person saying that they like the edited one. If you want to see more people saying that they like the current one check the discord because they are way more.

I see only one person here saying they like the new one as well. Excluding multi because he's the one who wanted the new blush in the first place.

**Comment by ThePotatoGuy** [comment] 2019-09-20 19:29
@Trilasent make day versions of those screenshots and I will discord vote this later.

**Comment by Trilasent** [comment] 2019-09-20 19:35
> 
> 
> @Trilasent make day versions of those screenshots and I will discord vote this later.

will do

**Comment by dragonsni** [comment] 2019-09-20 20:01
I like the current one more at the moment Tril, it seems more cute, and more realistic

**Comment by Trilasent** [comment] 2019-09-20 20:05
> 
> 
> I like the current one more at the moment Tril, it seems more cute, and more realistic

We're letting the entire server have a chance to give their opinion, instead of just the vocal minority. If the new one wins in the end, then I'll happily admit defeat. But at least then it will have been certain which one the majority wants.

**Comment by ThePotatoGuy** [comment] 2019-09-28 00:14
poll has ran for about a week. current blush will remain.
[closing as resolved]

**Closed by ThePotatoGuy** 2019-09-28 00:14 UTC
Labels: discussion
