### ISSUE TITLE
Telling Monika I have important job assigment / homework / exam etc., when she tells you to go rest

### ISSUE THREAD

**Issue by WGSpacetime** [Monika-After-Story/MonikaModDev#4996] opened 2019-11-12 22:07 UTC
When you tell Monika, that you're feeling tired, her response usually goes along the "go rest" lines... but a lot of times when I'm tired, I actually still have a lot of important work to do and won't be able to rest for at least few hours, and the "go rest" just makes me angry, as I know I can't go rest... to the point I actually almost never tell Monika that I'm tired... it is especially annoying late, when she actually tells me to go to sleep, and I know I will be probably staying to like 2am to get everything done... I think it would be really nice to have an option to tell her "Sadly, I have important job / school work and I can't go rest" and Monika would reply, that maybe a short 20-30min rest would be ok, suggest to f.ex. drink coffee and maybe add some encouraging words

**Comment by TriniTDM** [comment] 2019-11-12 22:15
Well, in the sleep concern topic if you're up particularly late, she DOES ask if you're working on an important project.

**Comment by WGSpacetime** [comment] 2019-11-12 22:46
Oh, never had that happen to me... that's good, but I'm talking about "I'm feeling tired"...

**Comment by ThePotatoGuy** [comment] 2019-12-15 00:07
should be addressed in  #4914 

closing as duplicate of that issue as well

**Closed by ThePotatoGuy** 2019-12-15 00:07 UTC
Labels: duplicate
